/**
 * Photograph Hoot's menu bar icons from `.harness/tray-icon.html` and write
 * `src/main/hoot-tray-icons.ts`.
 *
 *   npx vite --config .harness/vite.config.ts --port 5296 &
 *   node .harness/tray-icons.mjs [playwright module path]
 *
 * The orange owl as drawn, at 18 and 36 pixels (1x and 2x of an 18-point
 * icon), eyes open and the blink frame.
 *
 * Colour, not a template image. Both were made and put side by side on a light
 * bar, a dark bar and a wallpaper-tinted bar (2026-10-03): the orange owl read
 * on all three — glasses, eyes and all — while the template version, an alpha
 * mask with the pale parts cut out, read as a dark blob with two holes in it.
 * And the orange is what was asked for.
 */
import { writeFileSync } from 'node:fs'

const playwright = process.argv[2] ?? '/Users/imatch/scrape-tools/node_modules/playwright/index.mjs'
const { chromium } = await import(playwright)
const browser = await chromium.launch({ headless: true })
const shots = {}
for (const scale of [1, 2]) {
  const page = await browser.newPage({ viewport: { width: 120, height: 60 }, deviceScaleFactor: scale })
  await page.goto('http://localhost:5296/tray-icon.html', { waitUntil: 'networkidle' })
  await page.waitForTimeout(300)
  for (const id of ['open', 'closed']) {
    shots[`${id}@${scale}`] = await page.locator(`#${id}`).screenshot({ omitBackground: true })
  }
  await page.close()
}
await browser.close()

const b64 = (buffer) => buffer.toString('base64')
const lines = []
for (const id of ['open', 'closed']) {
  lines.push(`  ${id}: {`)
  lines.push(`    colour1x: '${b64(shots[`${id}@1`])}',`)
  lines.push(`    colour2x: '${b64(shots[`${id}@2`])}',`)
  lines.push('  },')
}
const source = `/**
 * Hoot's menu bar icon, as PNG bytes. GENERATED by \`.harness/tray-icons.mjs\`
 * from \`HootMark\` itself — rerun it after the owl is redrawn, never edit by hand.
 *
 * Bytes rather than a file, for the reason \`resident.ts\` gives for its own tray
 * icon: a packaged build ships \`out/**\` and nothing else, so an icon read off
 * disk would be a blank square in the menu bar of every installed copy.
 *
 * \`open\` is the owl at rest; \`closed\` is the blink frame, at 1x and 2x of an
 * 18-point icon. In colour on purpose — the script says why.
 */
export const HOOT_TRAY_ICONS = {
${lines.join('\n')}
} as const
`
writeFileSync(new URL('../src/main/hoot-tray-icons.ts', import.meta.url), source)
console.log('wrote src/main/hoot-tray-icons.ts', Object.keys(shots).map((k) => `${k}:${shots[k].length}`).join(' '))
