import Foundation
import WebKit
import TerminalDeckNativeCore

/// The in-page half of the browser, in WebKit: a port of browser-preload.ts (element picker, Esc to cancel,
/// pick-at-a-point, "this page has a sign-in form"), browser-seed-preload.ts (storage seed) and the host
/// side of browser-record-preload.ts (recording steps), under the SAME message names the Electron guest
/// preloads used. The page side is a WKUserScript in its own content world; the host side is a
/// WKScriptMessageHandler that applies the same checks as browser-tab.ts / browser-annotate.ts /
/// browser-workers-ipc.ts: the page address always comes from the web view and never from the message,
/// only the main frame may answer a pick, and a seed is answered to a frame rather than to a claim.
/// Existing native owners keep their jobs: sign-in autofill decisions stay in BackendBrowserPasswords
/// (the `login-ready` hook feeds it), recording steps are parsed by BrowserFlow, session-lift seeds are
/// still issued by NativeSafariSessionLift. Nothing here reads or stores a secret.
public enum BackendS4BrowserGuest {
    public static let element = "terminaldeck-browser:element"
    public static let setInspect = "terminaldeck-browser:set-inspect"
    public static let inspectCancelled = "terminaldeck-browser:inspect-cancelled"
    public static let pickAt = "terminaldeck-browser:pick-at"
    public static let picked = "terminaldeck-browser:picked"
    public static let loginReady = "terminaldeck-browser:login-ready"
    public static let seed = "terminaldeck-browser:seed"
    public static let step = "terminaldeck-browser:step"
    /// Messages a page may post to the host (the host-bound halves of the seven channels).
    public static let hostBound = [element, inspectCancelled, picked, loginReady, step]
    public static let worldName = "TerminalDeckGuest"
    /// browser-annotate.ts ANSWER_MS: one elementFromPoint; a page that takes longer is busy.
    public static let pickAnswerMilliseconds = 2_000

    /// browser-preload.ts GUEST_PRELOAD_SOURCE minus its Electron plumbing and minus sign-in fill/offer (the
    /// native password feature owns those): the inspector, the point picker and the sign-in-form announcement.
    public static let guestScript = #"""
'use strict'
/* Generated by Deck from src/main/browser-preload.ts. Do not edit — it is overwritten on launch. */
;(function () {
  var guestHandlers = {}
  var ipc = {
    send: function (channel) {
      var args = Array.prototype.slice.call(arguments, 1)
      try {
        window.webkit.messageHandlers[channel].postMessage(args.length > 1 ? args : args.length === 1 ? args[0] : null)
      } catch (err) {
      }
    },
    on: function (channel, fn) { guestHandlers[channel] = fn }
  }
  /* The native side calls in through here, with the channel name the Electron preload listened on. */
  Object.defineProperty(window, '__terminalDeckGuest', {
    value: function (channel, args) {
      var fn = guestHandlers[channel]
      if (typeof fn === 'function') fn.apply(null, [null].concat(args || []))
    },
    enumerable: false
  })

  var CH_ELEMENT = "terminaldeck-browser:element"
  var CH_INSPECT = "terminaldeck-browser:set-inspect"
  var CH_CANCEL = "terminaldeck-browser:inspect-cancelled"
  var CH_PICK_AT = "terminaldeck-browser:pick-at"
  var CH_PICKED = "terminaldeck-browser:picked"
  var CH_LOGIN_READY = "terminaldeck-browser:login-ready"
  var TEST_ATTRS = ["data-testid", "data-test-id", "data-test", "data-qa", "data-cy", "data-automation-id"]
  var ATTR_KEYS = ["aria-label", "alt", "placeholder", "title", "role", "type", "name", "href"]

  var MAX_DEPTH = 64
  var MAX_TEXT = 300
  var MAX_ATTR = 300
  var MAX_IDENT = 200

  var BASE_STYLE =
    'position:fixed;top:0;left:0;width:0;height:0;margin:0;padding:0;' +
    'box-sizing:border-box;pointer-events:none;display:none;' +
    'z-index:2147483647;border:1px solid #3b8fee;border-radius:2px;' +
    'background:transparent;'
  var RING_CAPTURED = "0 0 0 3px rgba(59, 143, 238, 0.35)"

  var active = false
  var overlay = null
  var hovered = null
  var savedCursor = null

  function flatten(value, max) {
    if (typeof value !== 'string') return ''
    // Cut first, collapse second. textContent on a big page is megabytes — and
    // clicking <body> while inspecting asks for exactly that — so an unbounded
    // collapse would hang the page on the click it is meant to capture.
    var raw = value.length > max * 8 ? value.slice(0, max * 8) : value
    var flat = raw.replace(/\s+/g, ' ').trim()
    return flat.length > max ? flat.slice(0, max) : flat
  }

  function printable(value) {
    return !/[\u0000-\u001f\u007f]/.test(value)
  }

  /**
   * The text a person can actually read on this element.
   *
   * Kept in step with \`terminaldeckVisibleText\` in browser-guest-dom.ts, which
   * documents it at length. The short version, because it is the fault he saw:
   * \`textContent\` runs every descendant together with no separator and includes
   * the ones the page has hidden, so a wrapper around a collapsed country picker
   * reported its whole list as one unbroken word. \`innerText\` is what is
   * rendered.
   *
   * Form controls report no text. A \`<select>\`'s is its options; a
   * \`<textarea>\`'s is its seed content. Neither names the field, and both are
   * already covered by the naming attributes.
   */
  function visibleText(el) {
    var tag = typeof el.localName === 'string' ? el.localName : ''
    if (tag === 'select' || tag === 'textarea' || tag === 'input' || tag === 'option') return ''
    var raw = typeof el.textContent === 'string' ? el.textContent : ''
    // innerText forces a layout and builds the whole rendered string before
    // anything can be sliced. Clicking <body> asks for exactly that.
    if (raw.length <= 20000) {
      try {
        if (typeof el.innerText === 'string' && el.innerText !== '') raw = el.innerText
      } catch (err) {
        // Already have textContent, which is a true if uglier answer.
      }
    }
    return flatten(raw, MAX_TEXT)
  }

  function ensureOverlay() {
    // isConnected, not a null check: a single-page app can wipe the DOM out
    // from under us, and a detached box would silently stop appearing.
    if (overlay && overlay.isConnected) return overlay
    var box = document.createElement('div')
    box.setAttribute('data-terminaldeck-inspector', '')
    box.style.cssText = BASE_STYLE
    document.documentElement.appendChild(box)
    overlay = box
    return box
  }

  function place(el, captured) {
    var box = ensureOverlay()
    var rect = el.getBoundingClientRect()
    box.style.transform = 'translate(' + Math.round(rect.left) + 'px,' + Math.round(rect.top) + 'px)'
    box.style.width = Math.max(0, Math.round(rect.width)) + 'px'
    box.style.height = Math.max(0, Math.round(rect.height)) + 'px'
    // Outside the element, never over it: the point of the highlight is that
    // you can still read what it is around.
    box.style.boxShadow = captured ? RING_CAPTURED : 'none'
    box.style.display = 'block'
  }

  function hideOverlay() {
    if (overlay) overlay.style.display = 'none'
  }

  function removeOverlay() {
    if (overlay && overlay.parentNode) overlay.parentNode.removeChild(overlay)
    overlay = null
  }

  function isUnique(selector) {
    try {
      return document.querySelectorAll(selector).length === 1
    } catch (err) {
      return false
    }
  }

  function cssStringOf(value) {
    return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
  }

  function describe(el) {
    var d = { tag: typeof el.localName === 'string' ? el.localName : '' }

    var id = el.getAttribute('id')
    if (typeof id === 'string' && id !== '' && id.length <= MAX_IDENT && printable(id)) {
      d.id = id
      d.idUnique = isUnique('#' + CSS.escape(id))
    }

    for (var i = 0; i < TEST_ATTRS.length; i++) {
      var name = TEST_ATTRS[i]
      var value = el.getAttribute(name)
      if (typeof value === 'string' && value !== '' && value.length <= MAX_IDENT && printable(value)) {
        d.testAttr = name
        d.testValue = value
        d.testUnique = isUnique('[' + name + '=' + cssStringOf(value) + ']')
        break
      }
    }

    var count = 1
    var index = 1
    var parent = el.parentElement
    if (parent) {
      var kids = parent.children
      count = 0
      for (var j = 0; j < kids.length; j++) {
        var kid = kids[j]
        // :nth-of-type counts by element type, which is local name plus
        // namespace — an <a> in SVG is not the same type as an <a> in HTML.
        if (kid.localName === el.localName && kid.namespaceURI === el.namespaceURI) {
          count++
          if (kid === el) index = count
        }
      }
      if (count < 1) count = 1
    }
    d.ofTypeCount = count
    d.nthOfType = index
    return d
  }

  function pathFrom(el) {
    var path = []
    var node = el
    var depth = 0
    while (node && node.nodeType === 1 && depth < MAX_DEPTH) {
      path.push(describe(node))
      node = node.parentElement
      depth++
    }
    return path
  }

  function isSecretField(el) {
    // The property wins where it exists — a page can set input.type without
    // touching the attribute — and the attribute covers the fake-DOM case.
    var type = typeof el.type === 'string' && el.type !== '' ? el.type : el.getAttribute('type')
    return typeof type === 'string' && type.toLowerCase() === 'password'
  }

  function attributesOf(el) {
    var out = {}
    for (var i = 0; i < ATTR_KEYS.length; i++) {
      var name = ATTR_KEYS[i]
      var value = el.getAttribute(name)
      if (typeof value === 'string' && value !== '') out[name] = flatten(value, MAX_ATTR)
    }
    // What a form control currently holds, which its attribute does not track.
    // Never for a password field: that value would be shown in the capture
    // panel and pasted into the agent's prompt, which is written to disk.
    if (typeof el.value === 'string' && el.value !== '' && !isSecretField(el)) {
      out.value = flatten(el.value, MAX_ATTR)
    }
    return out
  }

  function elementFrom(event) {
    var target = event.target
    if (!target || target.nodeType !== 1) return null
    if (overlay !== null && target === overlay) return null
    return target
  }

  function onOver(event) {
    var el = elementFrom(event)
    if (!el) return
    hovered = el
    place(el, false)
  }

  function onOut() {
    hovered = null
    hideOverlay()
  }

  function reposition() {
    if (hovered && hovered.isConnected) place(hovered, false)
    else hideOverlay()
  }

  function swallow(event) {
    // Inspecting must not also drive the page: a click on a nav link would
    // navigate away from the thing being inspected.
    event.preventDefault()
    event.stopPropagation()
    if (typeof event.stopImmediatePropagation === 'function') event.stopImmediatePropagation()
  }

  function onClick(event) {
    var el = elementFrom(event)
    swallow(event)
    if (!el) return
    place(el, true)
    var rect = el.getBoundingClientRect()
    ipc.send(CH_ELEMENT, {
      v: 1,
      path: pathFrom(el),
      text: visibleText(el),
      attributes: attributesOf(el),
      // Where the element is inside the view, in CSS pixels. The renderer
      // anchors the capture popup here — one that opened in a corner would make
      // you look away from the thing you had just pointed at.
      rect: {
        x: Math.round(rect.left),
        y: Math.round(rect.top),
        width: Math.round(rect.width),
        height: Math.round(rect.height)
      }
    })
  }

  function onKeyDown(event) {
    if (event.key !== 'Escape') return
    event.preventDefault()
    event.stopPropagation()
    disable()
    ipc.send(CH_CANCEL)
  }

  // Capture phase everywhere, so page handlers never see these first.
  var DOC_EVENTS = [
    ['mouseover', onOver],
    ['mouseout', onOut],
    ['click', onClick],
    ['mousedown', swallow],
    ['mouseup', swallow],
    ['dblclick', swallow],
    ['contextmenu', swallow],
    ['keydown', onKeyDown]
  ]
  var WIN_EVENTS = [
    ['scroll', reposition],
    ['resize', reposition]
  ]

  function enable() {
    if (active) return
    active = true
    for (var i = 0; i < DOC_EVENTS.length; i++) {
      document.addEventListener(DOC_EVENTS[i][0], DOC_EVENTS[i][1], true)
    }
    for (var j = 0; j < WIN_EVENTS.length; j++) {
      window.addEventListener(WIN_EVENTS[j][0], WIN_EVENTS[j][1], true)
    }
    var root = document.documentElement
    // Remember what the page had rather than blanking it, so turning
    // inspection off cannot destroy a cursor the page set itself.
    savedCursor = root.style.cursor
    root.style.cursor = 'crosshair'
    ensureOverlay()
  }

  function disable() {
    if (!active) return
    active = false
    hovered = null
    for (var i = 0; i < DOC_EVENTS.length; i++) {
      document.removeEventListener(DOC_EVENTS[i][0], DOC_EVENTS[i][1], true)
    }
    for (var j = 0; j < WIN_EVENTS.length; j++) {
      window.removeEventListener(WIN_EVENTS[j][0], WIN_EVENTS[j][1], true)
    }
    if (savedCursor !== null) {
      document.documentElement.style.cursor = savedCursor
      savedCursor = null
    }
    removeOverlay()
  }

  ipc.on(CH_INSPECT, function (event, enabled) {
    if (enabled === true) enable()
    else disable()
  })

  /*
   * Annotate's second and later picks: "what is at this point?"
   *
   * The first element of an Annotate round is a click on the live page, exactly
   * as Inspect always was. After that the page is frozen under a photograph and
   * the person points at the photograph, so the main process asks here, with
   * the point in this page's own CSS pixels, and the answer is described by the
   * same functions a click is — one description of an element, not two that
   * could disagree about its selector.
   *
   * The nonce is echoed so a late answer to an old question is recognisable as
   * one. Nothing is highlighted and no event is dispatched: the page is not
   * being shown, and pointing at a photograph must not click the real thing.
   */
  ipc.on(CH_PICK_AT, function (event, request) {
    var x = request && typeof request.x === 'number' ? request.x : -1
    var y = request && typeof request.y === 'number' ? request.y : -1
    var nonce = request && typeof request.nonce === 'string' ? request.nonce : ''
    var el = x >= 0 && y >= 0 ? document.elementFromPoint(x, y) : null
    if (el && overlay !== null && el === overlay) el = null
    if (!el || el.nodeType !== 1) {
      ipc.send(CH_PICKED, { v: 1, nonce: nonce, none: true })
      return
    }
    var rect = el.getBoundingClientRect()
    ipc.send(CH_PICKED, {
      v: 1,
      nonce: nonce,
      path: pathFrom(el),
      text: visibleText(el),
      attributes: attributesOf(el),
      rect: {
        x: Math.round(rect.left),
        y: Math.round(rect.top),
        width: Math.round(rect.width),
        height: Math.round(rect.height)
      }
    })
  })

  /* ------------------------------------------------------------ logins -- */


  function shown(el) {
    if (!el || el.disabled || el.readOnly) return false
    var rects = el.getClientRects()
    if (!rects || rects.length === 0) return false
    var box = rects[0]
    if (box.width < 8 || box.height < 8) return false
    var style = window.getComputedStyle(el)
    if (style.visibility === 'hidden' || style.display === 'none') return false
    return parseFloat(style.opacity || '1') > 0.05
  }

  function passwordField() {
    var all = document.querySelectorAll('input[type="password"]')
    for (var i = 0; i < all.length; i++) {
      if (shown(all[i])) return all[i]
    }
    return null
  }

  function announce() {
    if (window.top !== window) return
    if (!passwordField()) return
    ipc.send(CH_LOGIN_READY, location.href)
  }


  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', announce)
  } else {
    announce()
  }
  // Sign-in forms are routinely rendered after the first paint, so one look at
  // DOMContentLoaded misses most single-page apps. Two more, cheaply: a
  // querySelector for one attribute is not something worth debouncing.
  setTimeout(announce, 700)
  setTimeout(announce, 2200)
})()
"""#

    /// browser-seed-preload.ts GUEST_SEED_SOURCE: asks the host once for this frame's seed and writes the pairs.
    public static let seedScript = #"""
'use strict'
/* Generated by Deck from src/main/browser-seed-preload.ts. Do not edit — it is overwritten on launch. */
;(function () {
  var ipc = { invoke: function () { return window.webkit.messageHandlers['terminaldeck-browser:seed'].postMessage(null) } }
  var CH = "terminaldeck-browser:seed"

  function put(store, entries) {
    if (!store || !entries || !entries.length) return
    for (var i = 0; i < entries.length; i++) {
      var pair = entries[i]
      if (!pair || typeof pair[0] !== 'string' || typeof pair[1] !== 'string') continue
      try {
        store.setItem(pair[0], pair[1])
      } catch (e) {
        /* Quota, or storage disabled for this origin. The other keys still go. */
      }
    }
  }

  try {
    ipc.invoke().then(function (seed) {
      if (!seed) return
      try {
        put(window.localStorage, seed.local)
      } catch (e) {
        /* Some origins have no localStorage at all — a sandboxed frame, a
           data: URL. sessionStorage is asked separately for that reason. */
      }
      try {
        put(window.sessionStorage, seed.session)
      } catch (e) {}
    }, function () {})
  } catch (e) {
    /* No host call: nothing to do, and nothing worth breaking a page over. */
  }
})()
"""#
}

public struct BackendS4BrowserRect: Equatable, Sendable { public let x: Double, y: Double, width: Double, height: Double }

/// What the picker clicked: the parsed capture, the agent context sentence and the rectangle.
public struct BackendS4BrowserElement: Equatable, Sendable {
    public let capture: BackendSharedElementCapture
    public let context: String
    public let rect: BackendS4BrowserRect?
}

/// Every check the three TypeScript handlers make, as pure functions.
public enum BackendS4BrowserGuestRules {
    /// browser-tab.ts readCaptureRect: four finite numbers or nothing, clamped.
    public static func rect(_ raw: NativeRPCValue) -> BackendS4BrowserRect? {
        guard raw.fields != nil, let x = raw["x"].number, let y = raw["y"].number, let w = raw["width"].number, let h = raw["height"].number else { return nil }
        func clamp(_ value: Double, _ low: Double) -> Double { max(low, min(100_000, value)) }
        return .init(x: clamp(x, -100_000), y: clamp(y, -100_000), width: clamp(w, 0), height: clamp(h, 0))
    }
    /// browser-tab.ts GUEST_ELEMENT_CHANNEL: only while this tab is inspecting, only with a live view address
    /// (the page's own claim of its URL is never used), and only a payload parseCapture accepts.
    public static func element(_ payload: NativeRPCValue, inspecting: Bool, viewURL: String?) -> BackendS4BrowserElement? {
        guard inspecting, let viewURL, let capture = BackendSharedSelector.parseCapture(payload, url: viewURL) else { return nil }
        return .init(capture: capture, context: BackendSharedSelector.composeAgentContext(capture), rect: rect(payload["rect"]))
    }
    /// browser-annotate.ts GUEST_PICKED_CHANNEL: a string nonce that was asked for, from the asked view, main frame only.
    public static func answeredNonce(_ payload: NativeRPCValue, pending: Set<String>, isMainFrame: Bool, askedView: Bool) -> String? {
        guard let nonce = payload["nonce"].string, pending.contains(nonce), askedView, isMainFrame else { return nil }
        return nonce
    }
    /// browser-annotate.ts after the answer: nothing for none:true, a capture built from the VIEW's address otherwise,
    /// with no page image (the caller photographs).
    public static func pickResult(_ payload: NativeRPCValue?, viewURL: String?) -> NativeRPCValue? {
        guard let payload, payload["none"].bool != true, let viewURL, let element = element(payload, inspecting: true, viewURL: viewURL) else { return nil }
        let c = element.capture
        func line(_ key: String, _ value: String) -> NativeRPCValue.Field { .init(key, .string(value)) }
        var fields: [NativeRPCValue.Field] = [line("selector", c.selector), line("tag", c.tag), line("label", c.label), line("labelSource", c.labelSource), line("url", c.url),
            .init("attributes", .object(c.attributes.keys.sorted().map { .init($0, .string(c.attributes[$0] ?? "")) })), line("context", element.context), line("pageImage", "")]
        fields.append(.init("rect", element.rect.map { .object([.init("x", .number($0.x)), .init("y", .number($0.y)), .init("width", .number($0.width)), .init("height", .number($0.height))]) } ?? .null))
        return .object(fields)
    }
    /// browser-annotate.ts: the request sent to the page, in CSS pixels (the zoom divided out, never negative).
    public static func pickRequest(x: Double, y: Double, zoom: Double, nonce: String) -> NativeRPCValue? {
        guard x.isFinite, y.isFinite else { return nil }
        let z = zoom > 0 ? zoom : 1
        return .object([.init("x", .number(max(0, x / z))), .init("y", .number(max(0, y / z))), .init("nonce", .string(nonce))])
    }
    /// browser-tab.ts GUEST_LOGIN_READY_CHANNEL: the origin comes from the view, a tab with no profile is skipped,
    /// and only the top frame announces. (The matching, ranking and the agent-held autofill gate stay in
    /// BackendBrowserPasswords.)
    public static func loginReadyOrigin(viewURL: String?, isMainFrame: Bool, isolated: Bool) -> String? {
        guard isMainFrame, !isolated, let viewURL else { return nil }
        return BackendBrowserPasswords.origin(viewURL)
    }
    /// browser-seed-preload.ts frameOrigin: http/https only; anything else answers nothing.
    public static func frameOrigin(_ url: String?) -> String {
        guard let url, !url.isEmpty, let parts = URLComponents(string: url), let scheme = parts.scheme?.lowercased(), scheme == "http" || scheme == "https",
              let host = parts.host?.lowercased(), !host.isEmpty else { return "" }
        let defaultPort = scheme == "https" ? 443 : 80
        if let port = parts.port, port != defaultPort { return "\(scheme)://\(host):\(port)" }
        return "\(scheme)://\(host)"
    }
    /// browser-seed-preload.ts put(): only [string, string] pairs are written.
    public static func seedPairs(_ raw: NativeRPCValue) -> [[String]] {
        (raw.elements ?? []).compactMap { pair in
            guard let items = pair.elements, items.count >= 2, let key = items[0].string, let value = items[1].string else { return nil }
            return [key, value]
        }
    }
    /// browser-record-preload.ts step: version 1 and one of the recorded kinds; BrowserFlow does the rest of the parsing.
    public static func step(_ raw: Any, viewURL: String, at: Double) -> BrowserRecordedStep? { BrowserFlow.parse(raw, url: viewURL, at: at) }
}

public struct BackendS4BrowserGuestSeed: Sendable {
    public let local: [[String]], session: [[String]]
    public init(local: [[String]], session: [[String]]) { self.local = local; self.session = session }
}

/// Hooks the app composition supplies; every one is optional so a build can wire only what it has.
public struct BackendS4BrowserGuestHooks: Sendable {
    public var isInspecting: @MainActor @Sendable (WKWebView) -> Bool = { _ in false }
    public var isIsolated: @MainActor @Sendable (WKWebView) -> Bool = { _ in false }
    public var element: @MainActor @Sendable (WKWebView, BackendS4BrowserElement) -> Void = { _, _ in }
    /// Esc inside the picker: the tab is no longer inspecting.
    public var cancelled: @MainActor @Sendable (WKWebView) -> Void = { _ in }
    public var loginReady: @MainActor @Sendable (WKWebView, String) -> Void = { _, _ in }
    public var step: @MainActor @Sendable (WKWebView, BrowserRecordedStep) -> Void = { _, _ in }
    /// The seed for this frame's origin, taken once; the origin is the frame's, never the page's claim.
    public var seed: (@MainActor @Sendable (WKWebView, String) -> BackendS4BrowserGuestSeed?)?
    public init() {}
}

@MainActor
public final class BackendS4BrowserGuestBridge {
    public static let world = WKContentWorld.world(name: BackendS4BrowserGuest.worldName)
    private var hooks: BackendS4BrowserGuestHooks
    private var pending: [String: (view: WKWebView, resume: CheckedContinuation<NativeRPCValue?, Never>)] = [:]
    private let now: @Sendable () -> Double
    public init(hooks: BackendS4BrowserGuestHooks, now: @escaping @Sendable () -> Double = { Date().timeIntervalSince1970 * 1_000 }) { self.hooks = hooks; self.now = now }

    /// Adds the page script and every handler to one configuration's content controller.
    public func install(into configuration: WKWebViewConfiguration) {
        let controller = configuration.userContentController, world = Self.world
        controller.addUserScript(WKUserScript(source: BackendS4BrowserGuest.guestScript, injectionTime: .atDocumentStart, forMainFrameOnly: true, in: world))
        for name in BackendS4BrowserGuest.hostBound { controller.add(Weak(self), contentWorld: world, name: name) }
        if hooks.seed != nil {
            controller.addUserScript(WKUserScript(source: BackendS4BrowserGuest.seedScript, injectionTime: .atDocumentStart, forMainFrameOnly: false, in: world))
            controller.addScriptMessageHandler(WeakReply(self), contentWorld: world, name: BackendS4BrowserGuest.seed)
        }
    }

    /// browser:inspect: turn the hover-and-click picker on or off in the page.
    public func setInspecting(_ view: WKWebView, _ on: Bool) async {
        _ = try? await view.callAsyncJavaScript("window.__terminalDeckGuest && window.__terminalDeckGuest(channel, [on])",
                                                arguments: ["channel": BackendS4BrowserGuest.setInspect, "on": on], in: nil, contentWorld: Self.world)
    }

    /// browser:annotate-pick: ask the page for the element at a point; nil when none, malformed or too slow.
    public func pick(_ view: WKWebView, x: Double, y: Double) async -> NativeRPCValue? {
        let nonce = UUID().uuidString.lowercased()
        guard let request = BackendS4BrowserGuestRules.pickRequest(x: x, y: y, zoom: view.pageZoom, nonce: nonce) else { return nil }
        let payload: NativeRPCValue? = await withCheckedContinuation { (continuation: CheckedContinuation<NativeRPCValue?, Never>) in
            pending[nonce] = (view, continuation)
            let timeout = BackendS4BrowserGuest.pickAnswerMilliseconds
            Task { @MainActor [weak self] in
                try? await Task.sleep(nanoseconds: UInt64(timeout) * 1_000_000)
                self?.finish(nonce, nil)
            }
            Task { @MainActor in
                _ = try? await view.callAsyncJavaScript("window.__terminalDeckGuest && window.__terminalDeckGuest(channel, [request])",
                    arguments: ["channel": BackendS4BrowserGuest.pickAt, "request": request.foundation ?? [:]], in: nil, contentWorld: Self.world)
            }
        }
        return BackendS4BrowserGuestRules.pickResult(payload, viewURL: view.url?.absoluteString)
    }

    private func finish(_ nonce: String, _ value: NativeRPCValue?) {
        guard let entry = pending.removeValue(forKey: nonce) else { return }
        entry.resume.resume(returning: value)
    }

    func receive(_ message: WKScriptMessage) {
        guard let view = message.webView, let body = try? NativeRPCValue.fromFoundation(message.body) else { return }
        let main = message.frameInfo.isMainFrame, viewURL = view.url?.absoluteString
        switch message.name {
        case BackendS4BrowserGuest.element:
            guard let element = BackendS4BrowserGuestRules.element(body, inspecting: hooks.isInspecting(view), viewURL: viewURL) else { return }
            hooks.element(view, element)
        case BackendS4BrowserGuest.inspectCancelled:
            hooks.cancelled(view)
        case BackendS4BrowserGuest.picked:
            let asked = Set(pending.keys)
            guard let nonce = BackendS4BrowserGuestRules.answeredNonce(body, pending: asked, isMainFrame: main, askedView: pending[body["nonce"].string ?? ""]?.view === view) else { return }
            finish(nonce, body)
        case BackendS4BrowserGuest.loginReady:
            guard let origin = BackendS4BrowserGuestRules.loginReadyOrigin(viewURL: viewURL, isMainFrame: main, isolated: hooks.isIsolated(view)) else { return }
            hooks.loginReady(view, origin)
        case BackendS4BrowserGuest.step:
            guard let url = viewURL, let step = BackendS4BrowserGuestRules.step(message.body, viewURL: url, at: now()) else { return }
            hooks.step(view, step)
        default: break
        }
    }

    func reply(_ message: WKScriptMessage) async -> (Any?, String?) {
        guard message.name == BackendS4BrowserGuest.seed, let view = message.webView, let seed = hooks.seed else { return (nil, nil) }
        let origin = BackendS4BrowserGuestRules.frameOrigin(message.frameInfo.request.url?.absoluteString)
        if origin.isEmpty { return (nil, nil) }
        guard let found = seed(view, origin) else { return (nil, nil) }
        return (["local": found.local, "session": found.session], nil)
    }

    /// WebKit keeps its handlers alive for the life of the controller; these hold the bridge weakly.
    private final class Weak: NSObject, WKScriptMessageHandler {
        weak var target: BackendS4BrowserGuestBridge?
        init(_ target: BackendS4BrowserGuestBridge) { self.target = target }
        @MainActor func userContentController(_ controller: WKUserContentController, didReceive message: WKScriptMessage) { target?.receive(message) }
    }
    private final class WeakReply: NSObject, WKScriptMessageHandlerWithReply {
        weak var target: BackendS4BrowserGuestBridge?
        init(_ target: BackendS4BrowserGuestBridge) { self.target = target }
        @MainActor func userContentController(_ controller: WKUserContentController, didReceive message: WKScriptMessage) async -> (Any?, String?) {
            guard let target else { return (nil, nil) }
            return await target.reply(message)
        }
    }
}
