import Foundation

/// The six independent page readers from browser-store-catalogue.ts, retaining
/// their exact recipe bytes and pinned digests. No Chrome extension entries.
public enum BackendBrowserRecipeCatalogue {
    public static let entries: [BackendBrowserRecipes.Entry] = [
        .init(id: "page-images", name: "Full-size images", summary: "Every image URL a page offers, widest first, with nothing chosen for you.",
              homepage: "https://developer.mozilla.org/docs/Web/HTML/Element/img", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "7e5f266ec50bf32931cd23f893074be0702f531152eb4ebe6f3ba752499d8186", bundled: Data("{\n  \"id\": \"page-images\",\n  \"name\": \"Full-size images\",\n  \"summary\": \"Every image URL a page offers, widest first, with nothing chosen for you.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"images\",\n      \"selector\": \"img\",\n      \"op\": \"image\",\n      \"all\": true\n    },\n    {\n      \"name\": \"picture_sources\",\n      \"selector\": \"picture source\",\n      \"op\": \"image\",\n      \"all\": true\n    },\n    {\n      \"name\": \"open_graph_image\",\n      \"selector\": \"meta[property='og:image']\",\n      \"op\": \"attribute\",\n      \"attribute\": \"content\"\n    }\n  ],\n  \"stated\": {\n    \"name\": \"images_on_page\",\n    \"selector\": \"img\",\n    \"op\": \"count\"\n  }\n}\n".utf8)),
        .init(id: "page-data", name: "Structured data", summary: "The JSON-LD, OpenGraph and microdata a page publishes about itself.",
              homepage: "https://json-ld.org", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "12b4c6d8be05c234b529592348b193be3fd32f46fa1d92408a3f72915b347b76", bundled: Data("{\n  \"id\": \"page-data\",\n  \"name\": \"Structured data\",\n  \"summary\": \"The JSON-LD, OpenGraph and microdata a page publishes about itself.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"structured\",\n      \"selector\": \"\",\n      \"op\": \"data\"\n    },\n    {\n      \"name\": \"canonical\",\n      \"selector\": \"link[rel='canonical']\",\n      \"op\": \"attribute\",\n      \"attribute\": \"href\"\n    },\n    {\n      \"name\": \"headline\",\n      \"selector\": \"h1\",\n      \"op\": \"text\"\n    }\n  ]\n}\n".utf8)),
        .init(id: "page-links", name: "Links and pagination", summary: "Every link on the page, made absolute, and the link to the next page.",
              homepage: "https://developer.mozilla.org/docs/Web/HTML/Attributes/rel", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "6785089e8e6b8a56f5595dc8d1e0f8dff35d5b3d7f487a97743acdf068c80999", bundled: Data("{\n  \"id\": \"page-links\",\n  \"name\": \"Links and pagination\",\n  \"summary\": \"Every link on the page, made absolute, and the link to the next page.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"links\",\n      \"selector\": \"a[href]\",\n      \"op\": \"link\",\n      \"all\": true\n    },\n    {\n      \"name\": \"link_text\",\n      \"selector\": \"a[href]\",\n      \"op\": \"text\",\n      \"all\": true\n    }\n  ],\n  \"stated\": {\n    \"name\": \"links_on_page\",\n    \"selector\": \"a[href]\",\n    \"op\": \"count\"\n  },\n  \"next\": \"a[rel='next'], link[rel='next'], [aria-label='Next'], .pagination a.next\"\n}\n".utf8)),
        .init(id: "page-tables", name: "Tables as rows", summary: "Every table row on the page, cell by cell, ready to be written out as a sheet.",
              homepage: "https://developer.mozilla.org/docs/Web/HTML/Element/table", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "9b5f55208be6504d0b11029f05554c46dd1ddd19f182d2dca77c7a904e89e7f9", bundled: Data("{\n  \"id\": \"page-tables\",\n  \"name\": \"Tables as rows\",\n  \"summary\": \"Every table row on the page, cell by cell, ready to be written out as a sheet.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"headings\",\n      \"selector\": \"table th\",\n      \"op\": \"text\",\n      \"all\": true\n    }\n  ],\n  \"rows\": {\n    \"selector\": \"table tr\",\n    \"fields\": [\n      {\n        \"name\": \"cells\",\n        \"selector\": \"th, td\",\n        \"op\": \"text\",\n        \"all\": true\n      }\n    ]\n  },\n  \"stated\": {\n    \"name\": \"rows_on_page\",\n    \"selector\": \"table tr\",\n    \"op\": \"count\"\n  }\n}\n".utf8)),
        .init(id: "page-article", name: "Article text", summary: "The headline, byline, date and readable body of an article page.",
              homepage: "https://developer.mozilla.org/docs/Web/HTML/Element/article", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "7baf383d93c89f7266bfd6ff23118babc15b8420b98610d3439e1f274dda7ba8", bundled: Data("{\n  \"id\": \"page-article\",\n  \"name\": \"Article text\",\n  \"summary\": \"The headline, byline, date and readable body of an article page.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"headline\",\n      \"selector\": \"h1\",\n      \"op\": \"text\"\n    },\n    {\n      \"name\": \"byline\",\n      \"selector\": \"[rel='author'], [itemprop='author'], .byline\",\n      \"op\": \"text\"\n    },\n    {\n      \"name\": \"published\",\n      \"selector\": \"time[datetime]\",\n      \"op\": \"attribute\",\n      \"attribute\": \"datetime\"\n    },\n    {\n      \"name\": \"body\",\n      \"selector\": \"article, main, [role='main']\",\n      \"op\": \"text\"\n    },\n    {\n      \"name\": \"paragraphs\",\n      \"selector\": \"article p, main p\",\n      \"op\": \"text\",\n      \"all\": true\n    }\n  ]\n}\n".utf8)),
        .init(id: "page-feeds", name: "Feeds and sitemaps", summary: "The feeds, canonical address and paging links a page declares in its head.",
              homepage: "https://www.rfc-editor.org/rfc/rfc5005", licence: "Public domain", version: "1.0.0", origins: ["*"],
              digest: "e5f16e40f950038a1a50815fb7ea20b0830d25c83d57acfd565afb69c3b7467f", bundled: Data("{\n  \"id\": \"page-feeds\",\n  \"name\": \"Feeds and sitemaps\",\n  \"summary\": \"The feeds, canonical address and paging links a page declares in its head.\",\n  \"version\": \"1.0.0\",\n  \"grants\": [\n    \"page-read\"\n  ],\n  \"origins\": [\n    \"*\"\n  ],\n  \"fields\": [\n    {\n      \"name\": \"feeds\",\n      \"selector\": \"link[rel='alternate'][type*='xml']\",\n      \"op\": \"link\",\n      \"all\": true\n    },\n    {\n      \"name\": \"canonical\",\n      \"selector\": \"link[rel='canonical']\",\n      \"op\": \"link\"\n    },\n    {\n      \"name\": \"previous_page\",\n      \"selector\": \"link[rel='prev']\",\n      \"op\": \"link\"\n    },\n    {\n      \"name\": \"next_page\",\n      \"selector\": \"link[rel='next']\",\n      \"op\": \"link\"\n    }\n  ],\n  \"next\": \"link[rel='next']\"\n}\n".utf8))
    ]
}
