/**
 * scrypt (RFC 7914), because a six-digit pairing code needs it and Apple does not ship one.
 *
 * ## Why this exists at all
 *
 * A pairing code is six digits. Six digits is 10^6, and the rendezvous slot the
 * code names — see `Rendezvous.swift`, and `src/main/remote/machines/rendezvous.ts`
 * for the long version — is derived from it. If that derivation were a hash,
 * anybody could sweep the million slots in seconds, learn which code is live, and
 * spend the five guesses the desktop allows on a single certain one. The whole
 * five-in-a-million argument would be worth nothing.
 *
 * So the derivation is memory-hard, at N=16384, r=8, p=1 — 16 MiB and tens of
 * milliseconds per attempt, ten CPU-hours for the space. Every client has to
 * compute the *same* bytes or a code typed correctly finds nothing, so the
 * parameters are not this file's to choose.
 *
 * CryptoKit has SHA-2, HKDF and PBKDF2 is reachable through CommonCrypto — but
 * neither framework has scrypt at any deployment target this app supports. There
 * is no Apple API to call.
 *
 * ## Why it is written out rather than installed
 *
 * A Swift Package for this would be a third-party licence permanently in
 * `THIRD-PARTY-LICENSES.md` and a dependency in the pairing path, for four
 * hundred lines of published algorithm. RFC 7914 is a specification, not
 * somebody's expression, and `ScryptTests` pins this against **the RFC's own
 * test vectors** plus vectors generated by running the desktop's `node:crypto`
 * scrypt. That is two independent implementations disagreeing-or-not with this
 * one, which is the only kind of confidence worth having here.
 *
 * ## The two places this is easy to get subtly wrong
 *
 * **Endianness.** Salsa20 words are little-endian, and `Integerify` reads the
 * *last* 64-byte block as a little-endian integer. Getting either backwards
 * produces a function that runs, costs the same, and derives different bytes
 * from every other client — which shows up as "the code was typed right and
 * found nothing", not as a crash.
 *
 * **The BlockMix shuffle.** The output is `Y[0], Y[2], … Y[2r-2], Y[1], Y[3], …
 * Y[2r-1]`, not `Y` in order. With r=1 the two are identical, so a test that only
 * covers the RFC's first vector (r=1) passes against a broken shuffle. The
 * vectors below deliberately include r=8.
 */

import CryptoKit
import Foundation

enum Scrypt {

    /// Refusals, all of which are programming errors rather than input problems.
    enum Failure: Error, Equatable {
        case badParameters
    }

    /**
     * Derive `length` bytes from `password` and `salt`.
     *
     * `n` must be a power of two greater than one, which is not politeness: the
     * `mod N` in ROMix is done as a mask, and a non-power-of-two would silently
     * produce a different function rather than a slower one.
     */
    static func derive(
        password: Data,
        salt: Data,
        n: Int,
        r: Int,
        p: Int,
        length: Int
    ) throws -> Data {
        guard n > 1, n & (n - 1) == 0, r >= 1, p >= 1, length >= 1 else { throw Failure.badParameters }
        // 128 * r * p bytes of state, and 128 * r * N bytes of scratch. Bounded
        // here so that a parameter typo is an error rather than an allocation
        // the phone is killed for.
        guard r <= 32, p <= 16, n <= 1 << 20 else { throw Failure.badParameters }

        let blockBytes = 128 * r
        var b = [UInt8](pbkdf2(password: password, salt: salt, length: blockBytes * p))

        var v = [UInt32](repeating: 0, count: 32 * r * n)
        var xy = [UInt32](repeating: 0, count: 64 * r)

        for lane in 0..<p {
            romix(&b, offset: lane * blockBytes, r: r, n: n, v: &v, xy: &xy)
        }

        return pbkdf2(password: password, salt: Data(b), length: length)
    }

    // MARK: - PBKDF2-HMAC-SHA256, with the one iteration scrypt asks for

    /**
     * PBKDF2-HMAC-SHA256 with `c = 1`, which is all scrypt ever uses.
     *
     * Written out rather than reached for through CommonCrypto because at one
     * iteration PBKDF2 collapses to `T_i = HMAC(P, S ‖ INT_32_BE(i))` — four
     * lines, no work factor, and nothing whose cost matters. The strength here is
     * entirely in the ROMix below; this is a variable-length expansion and the
     * RFC vectors cover it end to end.
     */
    private static func pbkdf2(password: Data, salt: Data, length: Int) -> Data {
        let key = SymmetricKey(data: password)
        var out = Data(capacity: length)
        var block: UInt32 = 1
        while out.count < length {
            var message = salt
            // Big-endian, per PBKDF2. The rest of scrypt is little-endian, which
            // is exactly why this one is worth a comment.
            message.append(contentsOf: [
                UInt8((block >> 24) & 0xff),
                UInt8((block >> 16) & 0xff),
                UInt8((block >> 8) & 0xff),
                UInt8(block & 0xff),
            ])
            out.append(contentsOf: HMAC<SHA256>.authenticationCode(for: message, using: key))
            block &+= 1
        }
        return out.prefix(length)
    }

    // MARK: - ROMix, BlockMix, Salsa

    /**
     * ROMix over one 128*r-byte lane of `b`, in place.
     *
     * `v` and `xy` are passed in rather than allocated here so that `p > 1` does
     * not allocate 16 MiB per lane. Everything is held as `UInt32` words rather
     * than bytes: Salsa works on words, and converting at every call was most of
     * the runtime in the first version of this.
     *
     * ## Why the whole body is inside `withUnsafeMutableBufferPointer`
     *
     * Measured, not assumed. At N=16384, r=8 this runs 524,288 Salsa cores over
     * about 67 million word operations, every one of them an `Array` subscript
     * — which in a **debug** build is a bounds check and a uniqueness check
     * apiece. Written with plain subscripts the derivation took **7.2 seconds**
     * unoptimised against 89 milliseconds optimised, an eighty-fold gap, and the
     * unoptimised number is what somebody running this app from Xcode gets. A
     * pairing code lives sixty seconds; seven of them spent on the derivation is
     * a feature that appears broken to every developer who touches it, and a
     * test suite nobody wants to run.
     *
     * The buffers are the same length for the whole call and every index below
     * is derived from `words`, `n` and a mask of `n - 1`, so there is nothing
     * here for a bounds check to have caught.
     */
    private static func romix(
        _ b: inout [UInt8],
        offset: Int,
        r: Int,
        n: Int,
        v: inout [UInt32],
        xy: inout [UInt32]
    ) {
        let words = 32 * r
        for i in 0..<words {
            xy[i] = leWord(b, offset + i * 4)
        }

        var scratch = [UInt32](repeating: 0, count: words)
        v.withUnsafeMutableBufferPointer { vp in
            xy.withUnsafeMutableBufferPointer { xp in
                scratch.withUnsafeMutableBufferPointer { yp in
                    for i in 0..<n {
                        let at = i * words
                        for j in 0..<words { vp[at + j] = xp[j] }
                        blockMix(xp, yp, r)
                    }

                    // `n` is a power of two, so `mod n` is a mask. `Integerify` is
                    // the last 64-byte block read little-endian, and the low word
                    // is enough for any n below 2^32.
                    let mask = UInt32(n - 1)
                    for _ in 0..<n {
                        let at = Int(xp[words - 16] & mask) * words
                        for k in 0..<words { xp[k] ^= vp[at + k] }
                        blockMix(xp, yp, r)
                    }
                }
            }
        }

        for i in 0..<words {
            putLeWord(&b, offset + i * 4, xy[i])
        }
    }

    /**
     * BlockMix, in place over `x` (2r blocks of sixteen words), using `y` as
     * scratch.
     *
     * The shuffle at the end is the part worth reading twice: the even-indexed
     * outputs come first and the odd-indexed ones after. With r = 1 that is the
     * identity, which is how a broken shuffle passes the RFC's first vector.
     */
    private static func blockMix(
        _ x: UnsafeMutableBufferPointer<UInt32>,
        _ y: UnsafeMutableBufferPointer<UInt32>,
        _ r: Int
    ) {
        // X = B[2r-1], carried in registers rather than in a scratch array: a
        // sixteen-word buffer allocated 32,768 times per derivation was the
        // second-largest cost after the subscripting.
        var t0 = x[(2 * r - 1) * 16 + 0], t1 = x[(2 * r - 1) * 16 + 1]
        var t2 = x[(2 * r - 1) * 16 + 2], t3 = x[(2 * r - 1) * 16 + 3]
        var t4 = x[(2 * r - 1) * 16 + 4], t5 = x[(2 * r - 1) * 16 + 5]
        var t6 = x[(2 * r - 1) * 16 + 6], t7 = x[(2 * r - 1) * 16 + 7]
        var t8 = x[(2 * r - 1) * 16 + 8], t9 = x[(2 * r - 1) * 16 + 9]
        var t10 = x[(2 * r - 1) * 16 + 10], t11 = x[(2 * r - 1) * 16 + 11]
        var t12 = x[(2 * r - 1) * 16 + 12], t13 = x[(2 * r - 1) * 16 + 13]
        var t14 = x[(2 * r - 1) * 16 + 14], t15 = x[(2 * r - 1) * 16 + 15]

        for i in 0..<(2 * r) {
            let at = i * 16
            t0 ^= x[at + 0]; t1 ^= x[at + 1]; t2 ^= x[at + 2]; t3 ^= x[at + 3]
            t4 ^= x[at + 4]; t5 ^= x[at + 5]; t6 ^= x[at + 6]; t7 ^= x[at + 7]
            t8 ^= x[at + 8]; t9 ^= x[at + 9]; t10 ^= x[at + 10]; t11 ^= x[at + 11]
            t12 ^= x[at + 12]; t13 ^= x[at + 13]; t14 ^= x[at + 14]; t15 ^= x[at + 15]

            salsa20_8(&t0, &t1, &t2, &t3, &t4, &t5, &t6, &t7,
                      &t8, &t9, &t10, &t11, &t12, &t13, &t14, &t15)

            // Interleave on the way out rather than in a second pass: the even
            // blocks land in the first half and the odd ones in the second.
            let to = (i % 2 == 0 ? i / 2 : r + i / 2) * 16
            y[to + 0] = t0; y[to + 1] = t1; y[to + 2] = t2; y[to + 3] = t3
            y[to + 4] = t4; y[to + 5] = t5; y[to + 6] = t6; y[to + 7] = t7
            y[to + 8] = t8; y[to + 9] = t9; y[to + 10] = t10; y[to + 11] = t11
            y[to + 12] = t12; y[to + 13] = t13; y[to + 14] = t14; y[to + 15] = t15
        }

        for i in 0..<(32 * r) { x[i] = y[i] }
    }

    /**
     * The Salsa20/8 core: eight rounds, then add the input back.
     *
     * Sixteen `inout` words rather than an array, and the ugliness is the point:
     * this is called half a million times per derivation, and an array here is
     * half a million bounds-checked subscript pairs plus a retain/release on
     * every call in an unoptimised build. See `romix` for the measurement.
     */
    // swiftlint:disable:next function_parameter_count
    private static func salsa20_8(
        _ b0: inout UInt32, _ b1: inout UInt32, _ b2: inout UInt32, _ b3: inout UInt32,
        _ b4: inout UInt32, _ b5: inout UInt32, _ b6: inout UInt32, _ b7: inout UInt32,
        _ b8: inout UInt32, _ b9: inout UInt32, _ b10: inout UInt32, _ b11: inout UInt32,
        _ b12: inout UInt32, _ b13: inout UInt32, _ b14: inout UInt32, _ b15: inout UInt32
    ) {
        var x0 = b0, x1 = b1, x2 = b2, x3 = b3
        var x4 = b4, x5 = b5, x6 = b6, x7 = b7
        var x8 = b8, x9 = b9, x10 = b10, x11 = b11
        var x12 = b12, x13 = b13, x14 = b14, x15 = b15

        for _ in 0..<4 {
            // Column round.
            x4 ^= rotl(x0 &+ x12, 7)
            x8 ^= rotl(x4 &+ x0, 9)
            x12 ^= rotl(x8 &+ x4, 13)
            x0 ^= rotl(x12 &+ x8, 18)
            x9 ^= rotl(x5 &+ x1, 7)
            x13 ^= rotl(x9 &+ x5, 9)
            x1 ^= rotl(x13 &+ x9, 13)
            x5 ^= rotl(x1 &+ x13, 18)
            x14 ^= rotl(x10 &+ x6, 7)
            x2 ^= rotl(x14 &+ x10, 9)
            x6 ^= rotl(x2 &+ x14, 13)
            x10 ^= rotl(x6 &+ x2, 18)
            x3 ^= rotl(x15 &+ x11, 7)
            x7 ^= rotl(x3 &+ x15, 9)
            x11 ^= rotl(x7 &+ x3, 13)
            x15 ^= rotl(x11 &+ x7, 18)
            // Row round.
            x1 ^= rotl(x0 &+ x3, 7)
            x2 ^= rotl(x1 &+ x0, 9)
            x3 ^= rotl(x2 &+ x1, 13)
            x0 ^= rotl(x3 &+ x2, 18)
            x6 ^= rotl(x5 &+ x4, 7)
            x7 ^= rotl(x6 &+ x5, 9)
            x4 ^= rotl(x7 &+ x6, 13)
            x5 ^= rotl(x4 &+ x7, 18)
            x11 ^= rotl(x10 &+ x9, 7)
            x8 ^= rotl(x11 &+ x10, 9)
            x9 ^= rotl(x8 &+ x11, 13)
            x10 ^= rotl(x9 &+ x8, 18)
            x12 ^= rotl(x15 &+ x14, 7)
            x13 ^= rotl(x12 &+ x15, 9)
            x14 ^= rotl(x13 &+ x12, 13)
            x15 ^= rotl(x14 &+ x13, 18)
        }

        b0 = b0 &+ x0; b1 = b1 &+ x1; b2 = b2 &+ x2; b3 = b3 &+ x3
        b4 = b4 &+ x4; b5 = b5 &+ x5; b6 = b6 &+ x6; b7 = b7 &+ x7
        b8 = b8 &+ x8; b9 = b9 &+ x9; b10 = b10 &+ x10; b11 = b11 &+ x11
        b12 = b12 &+ x12; b13 = b13 &+ x13; b14 = b14 &+ x14; b15 = b15 &+ x15
    }

    private static func rotl(_ value: UInt32, _ by: UInt32) -> UInt32 {
        (value << by) | (value >> (32 - by))
    }

    /// Salsa words are little-endian. Assembled by hand rather than through
    /// `withUnsafeBytes` + `load`, which would inherit the host's byte order.
    private static func leWord(_ bytes: [UInt8], _ at: Int) -> UInt32 {
        UInt32(bytes[at])
            | (UInt32(bytes[at + 1]) << 8)
            | (UInt32(bytes[at + 2]) << 16)
            | (UInt32(bytes[at + 3]) << 24)
    }

    private static func putLeWord(_ bytes: inout [UInt8], _ at: Int, _ value: UInt32) {
        bytes[at] = UInt8(value & 0xff)
        bytes[at + 1] = UInt8((value >> 8) & 0xff)
        bytes[at + 2] = UInt8((value >> 16) & 0xff)
        bytes[at + 3] = UInt8((value >> 24) & 0xff)
    }
}
