/**
 * The relay's sealed-handshake framing, in Swift. A port of the second half of
 * `src/shared/relay-wire.ts`.
 *
 * ## Why this is a separate file from `Sealed`
 *
 * Because it is a separate layer on the Mac, and the split is the whole reason
 * this app spent a week talking to nobody.
 *
 * `sealed.ts` produces a bare 80-byte Noise IK message and consumes a bare
 * 48-byte reply. `relay-wire.ts` — a file the phone clients had no counterpart
 * for — wraps each of those in a one-byte version. What actually crosses a relay
 * is therefore **81 bytes out and 49 bytes back**, and a client that ports only
 * `sealed.ts` produces a handshake that is byte-perfect and one byte short.
 *
 * That failure is silent by design: the desktop refuses a first payload of the
 * wrong length by closing the channel with nothing on the wire, because saying
 * *which* check failed would hand a hostile relay an oracle. From the phone it
 * looks exactly like a Mac that is asleep.
 *
 * So the framing lives here, named after the file it comes from, and
 * `Sealed`'s own constants are named for the Noise sizes they actually are.
 * `Tests/RelayWireTests` pins every number below against bytes generated by
 * running the real `relay-wire.ts`.
 *
 * ## Why the version byte is outside the seal, and why that is safe
 *
 * It has to be readable before any key exists, so it cannot be inside. A hostile
 * relay can therefore flip it and cause a refusal — but it can already drop the
 * connection outright, so that is not a new power. What it cannot do is
 * downgrade anything: the byte selects no primitive and enables no fallback,
 * there is exactly one accepted value, and every parameter of the handshake is
 * pinned by `noiseName` inside the transcript hash. A mismatch is a build that
 * needs updating, told apart from a cryptographic failure so the phone can say
 * which.
 */

import Foundation

enum RelayWire {

    /// The only version this build speaks. Matches `RELAY_SEALED_VERSION`, which
    /// is `SEALED_VERSION` — bumped with any change to the framing or the key
    /// schedule.
    static let sealedVersion: UInt8 = UInt8(Sealed.version)

    /// What a phone's first payload on a fresh channel must measure: the version
    /// byte and the Noise IK message under it.
    static let handshakeOpenBytes = 1 + Sealed.noiseMessageBytes

    /// What the Mac answers with.
    static let handshakeReplyBytes = 1 + Sealed.noiseReplyBytes

    /// Put the version in front of a handshake message.
    static func withSealedVersion(_ message: Data) -> Data {
        var framed = Data([sealedVersion])
        framed.append(message)
        return framed
    }

    /**
     * Why a handshake payload could not be read.
     *
     * `wrongVersion` is separated from `malformed` for the log and for what the
     * user is told — one of them is fixed by updating an app and the other is
     * not. Neither is described to the far end: both end the channel the same
     * way, silently.
     */
    enum Refusal: Equatable {
        case wrongVersion(UInt8)
        case malformed(count: Int, expected: Int)

        /// A sentence for the connection banner. Says what to do, never which
        /// cryptographic check failed.
        var sentence: String {
            switch self {
            case let .wrongVersion(saw):
                return "That Mac answered with sealed-channel version \(saw); this app speaks "
                    + "\(RelayWire.sealedVersion). Update whichever is older."
            case .malformed:
                return "That Mac's first answer was not a sealed handshake."
            }
        }
    }

    enum SealedOpen: Equatable {
        case ok(Data)
        case refused(Refusal)
    }

    /// Strip the version byte, or say why not.
    static func readSealedHandshake(_ payload: Data, expected: Int) -> SealedOpen {
        guard payload.count == expected else {
            return .refused(.malformed(count: payload.count, expected: expected))
        }
        // `Data` slices keep their parent's indices, so the first byte is at
        // `startIndex` and not necessarily at 0.
        let version = payload[payload.startIndex]
        guard version == sealedVersion else { return .refused(.wrongVersion(version)) }
        return .ok(Data(payload.dropFirst()))
    }
}
