/**
 * Agents, accounts, MCP servers, hooks, routines, settings, voice, updates and logs: every action a person can take, and the tool that takes it.
 *
 * See `./types.ts` for what an entry means. `null` is "not decided yet" and
 * fails `actions.test.ts` on purpose.
 */

import type { CoverageMap } from './types'

export const agentsCoverage: CoverageMap = {
  'accounts:history-share': null,
  'accounts:history-state': null,
  'accounts:history-unshare': null,
  'agent:controls:apply': null,
  'agent:controls:models': null,
  'agent:controls:read': null,
  'agents:add': null,
  'agents:list': null,
  'agents:remove': null,
  'brand:get': null,
  'cost:project': null,
  'cost:session': null,
  'cost:sessions': null,
  'cost:unwatch': null,
  'cost:watch': null,
  'debug:diagnostics': null,
  'debug:diagnostics-text': null,
  'debug:ipc-clear': null,
  'debug:ipc-log': null,
  'debug:subscribe': null,
  'debug:unsubscribe': null,
  'hooks:install': null,
  'hooks:offer': null,
  'hooks:offer-accept': null,
  'hooks:offer-decline': null,
  'hooks:remove': null,
  'hooks:server': null,
  'hooks:status': null,
  'hooks:sync': null,
  'log:clear': null,
  'log:open-folder': null,
  'log:recent': null,
  'log:status': null,
  'mcp:add': null,
  'mcp:call': null,
  'mcp:connect': null,
  'mcp:disconnect': null,
  'mcp:edit': null,
  'mcp:export': null,
  'mcp:import': null,
  'mcp:inventory': null,
  'mcp:list': null,
  'mcp:remove': null,
  'mcp:store': null,
  'mcp:store-install': null,
  'nspeech:hush': null,
  'nspeech:probe': null,
  'nspeech:speak': null,
  'nspeech:start': null,
  'nspeech:stop': null,
  'nspeech:voices': null,
  'prefs:get': null,
  'prefs:set': null,
  'prereq:check': null,
  'profiles:account-providers': null,
  'profiles:create': null,
  'profiles:delete': null,
  'profiles:list': null,
  'profiles:rename': null,
  'profiles:resolve': null,
  'profiles:set-default': null,
  'profiles:set-project-default': null,
  'profiles:signin': null,
  'profiles:signout': null,
  'profiles:status': null,
  'providers:detect': null,
  'readiness:fix': null,
  'readiness:scan': null,
  'routines:delete': null,
  'routines:get': null,
  'routines:list': null,
  'routines:pause': null,
  'routines:resume': null,
  'routines:run': null,
  'routines:save-text': null,
  'routines:text': null,
  'settings:about': null,
  'settings:clear-browser-data': null,
  'settings:get': null,
  'settings:open-path': null,
  'settings:paths': null,
  'settings:reset': null,
  'settings:set': null,
  'setup:status': null,
  'update:check': null,
  'update:download': null,
  'update:get': null,
  'update:install': null,
  'usage:context': null,
  'usage:read': null,
  'usage:refresh': null,
  'usage:unwatch': null,
  'usage:watch': null,
  'voice:forget': null,
  'voice:providers': null,
  'voice:save': null,
  'voice:status': null,
  'voice:transcribe': null,
}
