/**
 * Machines, servers, paired devices, GitHub and the remote layer: every action a person can take, and the tool that takes it.
 *
 * See `./types.ts` for what an entry means. `null` is "not decided yet" and
 * fails `actions.test.ts` on purpose.
 *
 * The tools live in `../machine-tools.ts` (other paired computers),
 * `../server-room-tools.ts` beside `../../servers/tools.ts` (the server room),
 * `../remote-tools.ts` (devices that reach this computer) and
 * `../github-tools.ts`. Every one is a closed list of verbs over the same
 * channels the window calls — `../channel-tap.ts` says why that is the design —
 * and `machine-area.test.ts` fails if an id named here is not one of them.
 *
 * Ten skips, each for a reason in the short list `./types.ts` allows: three are
 * window plumbing (two resizes and a pane letting go), one hands back a private key,
 * one is the copilot's own permission switch, one is a call no screen makes, and
 * four only do anything on Windows, which this release does not ship for.
 */

import type { CoverageMap } from './types'

export const machinesCoverage: CoverageMap = {
  'confine:grant': {
    skip: 'Windows only: it lets the Windows sandbox reach the coding tools\' folders, and a Mac holds a session to its folder with no grant at all. It is also the confinement boundary itself, which no tool may move.',
  },
  'confine:state': { tool: 'remote.status' },
  'confine:withdraw': {
    skip: 'Windows only, the undo of confine:grant; a Mac has no such grant. It is also the confinement boundary itself, which no tool may move.',
  },
  'github:auth-await': { tool: 'github.connect' },
  'github:auth-cancel': { tool: 'github.connect' },
  'github:auth-connect': { tool: 'github.connect' },
  'github:auth-disconnect': { tool: 'github.connect' },
  'github:auth-status': { tool: 'github.look' },
  'github:clear-cache': { tool: 'github.look' },
  'github:overview': { tool: 'github.look' },
  'github:refresh': { tool: 'github.look' },
  'github:repo': { tool: 'github.look' },
  'machines:account:read': { tool: 'machines.look' },
  'machines:account:switch': { tool: 'machines.session' },
  'machines:attach': { tool: 'machines.session' },
  'machines:close': { tool: 'machines.session' },
  'machines:code': { tool: 'machines.manage' },
  'machines:code:cancel': { tool: 'machines.manage' },
  'machines:connect': { tool: 'machines.manage' },
  'machines:controls:apply': { tool: 'machines.session' },
  'machines:controls:read': { tool: 'machines.look' },
  'machines:copilot:attach': { tool: 'machines.copilot' },
  'machines:copilot:refresh': { tool: 'machines.copilot' },
  'machines:copilot:say': { tool: 'machines.copilot' },
  'machines:copilot:start': { tool: 'machines.copilot' },
  'machines:create': { tool: 'machines.session' },
  'machines:detach': {
    skip: 'Stops this window receiving a remote session\'s output when its pane closes. A link holds one subscription per session, so a tool letting go would cut off the pane that is drawing it; machines.look reads the screen without needing to.',
  },
  'machines:disconnect': { tool: 'machines.manage' },
  'machines:drive-windows': { tool: 'machines.manage' },
  'machines:forget': { tool: 'machines.manage' },
  'machines:github:cancel': { tool: 'machines.manage' },
  'machines:github:connect': { tool: 'machines.manage' },
  'machines:github:disconnect': { tool: 'machines.manage' },
  'machines:github:read': { tool: 'machines.look' },
  'machines:host:read': { tool: 'machines.look' },
  'machines:host:restart': { tool: 'machines.manage' },
  'machines:host:stop': { tool: 'machines.manage' },
  'machines:input': { tool: 'machines.session' },
  'machines:list': { tool: 'machines.look' },
  'machines:logins:read': { tool: 'machines.look' },
  'machines:logins:signin': { tool: 'machines.manage' },
  'machines:logins:signout': { tool: 'machines.manage' },
  'machines:open': { tool: 'machines.ports' },
  'machines:pair': { tool: 'machines.manage' },
  'machines:ports': { tool: 'machines.ports' },
  'machines:reach': { tool: 'machines.ports' },
  'machines:reach:close': { tool: 'machines.ports' },
  'machines:rename': { tool: 'machines.manage' },
  'machines:resize': {
    skip: 'Tells the far terminal the pane\'s size as the window is resized: plumbing, with no effect a person chooses. A session a tool watches is sized once, by machines.session\'s watch.',
  },
  'machines:send': { tool: 'machines.session' },
  'machines:session:rename': { tool: 'machines.session' },
  'machines:upload': { tool: 'machines.upload' },
  'machines:upload:cancel': { tool: 'machines.upload' },
  'machines:usage:read': { tool: 'machines.look' },
  'power:lid-awake:get': { tool: 'remote.status' },
  'power:lid-awake:set': { tool: 'remote.manage' },
  'remote:accounts': { tool: 'remote.status' },
  'remote:accounts:set': { tool: 'remote.manage' },
  'remote:connection:disconnect': { tool: 'remote.manage' },
  'remote:device:approve': { tool: 'remote.manage' },
  'remote:device:revoke': { tool: 'remote.manage' },
  'remote:devices': { tool: 'remote.status' },
  'remote:folders': { tool: 'remote.status' },
  'remote:folders:set': { tool: 'remote.manage' },
  'remote:kinds': { tool: 'remote.status' },
  'remote:pair': { tool: 'remote.manage' },
  'remote:pair:cancel': { tool: 'remote.manage' },
  'remote:sessions': { tool: 'remote.status' },
  'remote:sessions:running': { tool: 'remote.status' },
  'remote:sessions:set': { tool: 'remote.manage' },
  'remote:start': { tool: 'remote.manage' },
  'remote:status': { tool: 'remote.status' },
  'remote:stop': { tool: 'remote.manage' },
  'remote:tunnel:stop': { tool: 'remote.manage' },
  'remote:windows': { tool: 'remote.status' },
  'remote:windows:set': { tool: 'remote.manage' },
  'servers:act': { tool: 'servers.control' },
  'servers:add': { tool: 'servers.manage' },
  'servers:close': { tool: 'servers.ports' },
  'servers:controls:apply': { tool: 'servers.shell' },
  'servers:controls:read': { tool: 'servers.details' },
  'servers:drive-windows': { tool: 'servers.manage' },
  'servers:folder': { tool: 'servers.details' },
  'servers:forget': { tool: 'servers.manage' },
  'servers:grant': {
    skip: 'It is the switch that lets servers.control act without asking a person first. The design keeps it on the server\'s own page, in a person\'s hands: a tool that could flip it would make the question it skips decorative.',
  },
  'servers:grant-state': { tool: 'servers.details' },
  'servers:host:cancel': { tool: 'servers.ports' },
  'servers:host:install': { tool: 'servers.manage' },
  'servers:host:link': { tool: 'servers.manage' },
  'servers:host:look': { tool: 'servers.details' },
  'servers:host:pair': { tool: 'servers.manage' },
  'servers:host:remove': { tool: 'servers.manage' },
  'servers:host:state': { tool: 'servers.details' },
  'servers:key-pick': { tool: 'servers.manage' },
  'servers:key-read': {
    skip: 'Hands back a private key\'s text. servers.manage reads the key in place to add a server and never returns it.',
  },
  'servers:keys': { tool: 'servers.details' },
  'servers:list': { tool: 'servers.look' },
  'servers:logs': { tool: 'servers.logs' },
  'servers:look': { tool: 'servers.look' },
  'servers:ports': { tool: 'servers.details' },
  'servers:preview': { tool: 'servers.details' },
  'servers:reach': { tool: 'servers.ports' },
  'servers:reach:close': { tool: 'servers.ports' },
  'servers:rename': { tool: 'servers.manage' },
  'servers:revoke': { tool: 'servers.manage' },
  'servers:setup:cancel': { tool: 'servers.ports' },
  'servers:setup:install': { tool: 'servers.manage' },
  'servers:setup:look': { tool: 'servers.details' },
  'servers:setup:remove': { tool: 'servers.manage' },
  'servers:setup:signin': { tool: 'servers.manage' },
  'servers:setup:signout': { tool: 'servers.manage' },
  'servers:setup:state': { tool: 'servers.details' },
  'servers:shell:account': { tool: 'servers.details' },
  'servers:shell:close': { tool: 'servers.shell' },
  'servers:shell:open': { tool: 'servers.shell' },
  'servers:shell:resize': {
    skip: 'Tells a server terminal the pane\'s size as the window is resized: plumbing, with no effect a person chooses. A terminal a tool opens is given its size when it opens.',
  },
  'servers:shell:write': { tool: 'servers.shell' },
  'servers:start-in': { tool: 'servers.details' },
  'servers:start-in:set': { tool: 'servers.manage' },
  'servers:upload': { tool: 'servers.manage' },
  'tailnet:cert': {
    skip: 'No screen in the app calls it: the remote server fetches its own certificate for the optional Tailscale route when it starts. Tailscale is never something this product needs; remote.status reports its status when asked.',
  },
  'tailnet:status': { tool: 'remote.status' },
  'wsl:choose': {
    skip: 'Windows only: it picks which Linux distribution sessions run in on a Windows PC, and this release ships for the Mac.',
  },
  'wsl:status': {
    skip: 'Windows only: it reports the Linux subsystem on a Windows PC, and this release ships for the Mac.',
  },
}
