/**
 * Sessions, projects, files, git, the copilot and the window itself: every action a person can take, and the tool that takes it.
 *
 * See `./types.ts` for what an entry means. `null` is "not decided yet" and
 * fails `actions.test.ts` on purpose.
 */

import type { CoverageMap } from './types'

export const sessionsCoverage: CoverageMap = {
  'alerts:project': null,
  'artifacts:changes': null,
  'artifacts:list': null,
  'attach:boundary': null,
  'attach:bring-in': null,
  'attach:browse': null,
  'attach:inspect': null,
  'attach:paste': null,
  'chat:close': null,
  'chat:load': null,
  'chat:tail': null,
  'copilot:actions': null,
  'copilot:ensure': null,
  'copilot:files': null,
  'copilot:folder': null,
  'copilot:folder:clear': null,
  'copilot:folder:pick': null,
  'copilot:memory': null,
  'copilot:memory-delete': null,
  'copilot:memory-read': null,
  'copilot:memory-write': null,
  'copilot:read-composed': null,
  'copilot:read-contract': null,
  'copilot:read-folder-instructions': null,
  'copilot:read-instructions': null,
  'copilot:reset-instructions': null,
  'copilot:reveal': null,
  'copilot:scaffold': null,
  'copilot:signin': null,
  'copilot:state': null,
  'copilot:stop': null,
  'copilot:write-folder-instructions': null,
  'copilot:write-instructions': null,
  'dashboard:clear': null,
  'dashboard:load': null,
  'dashboard:save': null,
  'deck-control:activity': null,
  'deck-control:consent-attach': null,
  'deck-control:consent-respond': null,
  'deck-control:status': null,
  'deck-control:tour-report': null,
  'deck-control:tours': null,
  'deckignore:explain': null,
  'deckignore:filter': null,
  'deckignore:invalidate': null,
  'deckignore:overview': null,
  'dev:ports': null,
  'dev:server:list': null,
  'dev:server:start': null,
  'fs:list': null,
  'fs:read': null,
  'git:diff': null,
  'git:init': null,
  'git:status': null,
  'git:unwatch': null,
  'git:watch': null,
  'insights:latest': null,
  'insights:list': null,
  'insights:session': null,
  'link:menu': null,
  'link:open': null,
  'link:opened': null,
  'link:system': null,
  'menu:hidden-commands': null,
  'notifications:delivery': null,
  'notifications:open-settings': null,
  'notifications:support': null,
  'plan:unwatch': null,
  'plan:watch': null,
  'project:home': null,
  'project:pick': null,
  'projects:add': null,
  'projects:list': null,
  'projects:remove': null,
  'search:cancel': null,
  'search:files': null,
  'search:invalidate': null,
  'session-search:cancel': null,
  'session-search:run': null,
  'session:account': null,
  'session:create': null,
  'session:held-forget': null,
  'session:held-retry': null,
  'session:kill': null,
  'session:list': null,
  'session:rename': null,
  'session:resize': null,
  'session:row-menu': null,
  'session:scrollback': null,
  'session:switch-account': null,
  'session:switch-armed': null,
  'session:switch-cancel': null,
  'session:switch-later': null,
  'session:switch-plan': null,
  'session:write': null,
  'sessions:held': null,
  'transfer:stage': null,
  'window:dimmed': null,
}
