package dev.terminaldeck.android.protocol

import dev.terminaldeck.android.crypto.Sealed

/**
 * The relay's sealed-handshake framing, in Kotlin. A port of the second half of
 * `src/shared/relay-wire.ts`.
 *
 * ## Why this is a separate file from `Sealed`
 *
 * Because it is a separate layer on the desktop, and the split is the whole reason this app spent a
 * week talking to nobody.
 *
 * `sealed.ts` produces a bare 80-byte Noise IK message and consumes a bare 48-byte reply.
 * `relay-wire.ts` — a file the phone clients had no counterpart for — wraps each of those in a
 * one-byte version. What actually crosses a relay is therefore **81 bytes out and 49 bytes back**,
 * and a client that ports only `sealed.ts` produces a handshake that is byte-perfect and one byte
 * short.
 *
 * That failure is silent by design: the desktop refuses a first payload of the wrong length by
 * closing the channel with nothing on the wire, because saying *which* check failed would hand a
 * hostile relay an oracle. From the phone it looks exactly like a machine that is asleep.
 *
 * So the framing lives here, named after the file it comes from, and `Sealed`'s own constants are
 * named for the Noise sizes they actually are. `RelayWireTest` pins every number below against
 * bytes generated by running the real `relay-wire.ts`.
 *
 * ## Why the version byte is outside the seal, and why that is safe
 *
 * It has to be readable before any key exists, so it cannot be inside. A hostile relay can
 * therefore flip it and cause a refusal — but it can already drop the connection outright, so that
 * is not a new power. What it cannot do is downgrade anything: the byte selects no primitive and
 * enables no fallback, there is exactly one accepted value, and every parameter of the handshake is
 * pinned by `NOISE_NAME` inside the transcript hash. A mismatch is a build that needs updating,
 * told apart from a cryptographic failure so the phone can say which.
 */
object RelayWire {

    /**
     * The only version this build speaks. Matches `RELAY_SEALED_VERSION`, which is
     * `SEALED_VERSION` — bumped with any change to the framing or the key schedule.
     */
    const val SEALED_VERSION: Byte = Sealed.VERSION.toByte()

    /**
     * What a phone's first payload on a fresh channel must measure: the version byte and the Noise
     * IK message under it.
     */
    const val HANDSHAKE_OPEN_BYTES = 1 + Sealed.NOISE_MESSAGE_BYTES

    /** What the desktop answers with. */
    const val HANDSHAKE_REPLY_BYTES = 1 + Sealed.NOISE_REPLY_BYTES

    /** Put the version in front of a handshake message. */
    fun withSealedVersion(message: ByteArray): ByteArray {
        val framed = ByteArray(message.size + 1)
        framed[0] = SEALED_VERSION
        message.copyInto(framed, 1)
        return framed
    }

    /**
     * Why a handshake payload could not be read.
     *
     * [WrongVersion] is separated from [Malformed] for the log and for what the user is told — one
     * of them is fixed by updating an app and the other is not. Neither is described to the far
     * end: both end the channel the same way, silently.
     */
    sealed interface Refusal {
        /** A sentence for the connection banner. Says what to do, never which check failed. */
        val sentence: String

        /*
         * Both sentences say "desktop" and neither takes a noun, unlike the ones in
         * `WebSocketDeckTransport`.
         *
         * That is not an oversight and not a shortcut. These two refusals can only ever happen
         * *before* the sealed channel is open — they are what a failed handshake produces — and
         * `welcome.hostPlatform` arrives on the first frame *inside* that channel. So at the moment
         * either of these is composed, what kind of machine is at the far end is genuinely unknown,
         * and the neutral word is the only honest one. Threading a noun in here would produce a
         * parameter that is always "desktop" and would invite someone to pass something else.
         */
        data class WrongVersion(val saw: Int) : Refusal {
            override val sentence: String
                get() = "That desktop answered with sealed-channel version $saw; this app speaks " +
                    "${SEALED_VERSION.toInt()}. Update whichever is older."
        }

        data class Malformed(val count: Int, val expected: Int) : Refusal {
            override val sentence: String
                get() = "That desktop's first answer was not a sealed handshake."
        }
    }

    sealed interface SealedOpen {
        data class Ok(val message: ByteArray) : SealedOpen {
            override fun equals(other: Any?): Boolean =
                this === other || (other is Ok && message.contentEquals(other.message))

            override fun hashCode(): Int = message.contentHashCode()
        }

        data class Refused(val reason: Refusal) : SealedOpen
    }

    /** Strip the version byte, or say why not. */
    fun readSealedHandshake(payload: ByteArray, expected: Int): SealedOpen {
        if (payload.size != expected) {
            return SealedOpen.Refused(Refusal.Malformed(payload.size, expected))
        }
        val version = payload[0]
        if (version != SEALED_VERSION) {
            return SealedOpen.Refused(Refusal.WrongVersion(version.toInt() and 0xff))
        }
        return SealedOpen.Ok(payload.copyOfRange(1, payload.size))
    }
}
