import Foundation
import CryptoKit
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

actor BackendOSTestPortStoreCalls {
    var ran: [(String, [String])] = [], claude: [(String, NativeRPCValue)] = []
    let fails: String?
    init(fails: String? = nil) { self.fails = fails }
    func run(_ agent: String, _ argv: [String]) -> NativeRPCValue { ran.append((agent, argv)); return .object([.init("ok", .bool(agent != fails)), .init("message", .string(agent == fails ? agent + " said no" : ""))]) }
    func add(_ request: NativeRPCValue) -> NativeRPCValue { claude.append(("add", request)); return .object([.init("ok", .bool(fails != "claude")), .init("message", .string(fails == "claude" ? "claude said no" : ""))]) }
    func remove(_ request: NativeRPCValue) -> NativeRPCValue { claude.append(("remove", request)); return .object([.init("ok", .bool(true)), .init("message", .string(""))]) }
    func commands() -> [(String, [String])] { ran }; func requests() -> [(String, NativeRPCValue)] { claude }
}

final class BackendOSTestPortStoreInstall: BackendOSTestPortFixture {
    struct Rig { let root: URL, data: URL, home: URL, archive: Data, row: NativeRPCValue, store: BackendOSStoreInstaller, calls: BackendOSTestPortStoreCalls }
    let skill = "---\nname: a-thing\ndescription: A thing.\n---\n\nDo the thing.\n"
    func rig(kind: String = "skill", install: NativeRPCValue = .object([.init("dir", .string("skill"))]), extra: [BackendOSStoreArchiveFixture.Entry]? = nil,
             tier: Int = 1, rowPatch: NativeRPCValue = .object([]), served: Data? = nil, revoked: [NativeRPCValue] = [], fails: String? = nil) throws -> Rig {
        let root = try scratch("store"), data = root.appendingPathComponent("data"), home = root.appendingPathComponent("home"), fixture = try BackendOSStoreInstallFixture.item(kind: kind, install: install, extra: extra ?? [.init("skill/SKILL.md", skill)], tier: tier), row = fixture.row.merging(rowPatch), archive = served ?? fixture.archive, calls = BackendOSTestPortStoreCalls(fails: fails)
        let operations = BackendOSStoreInstaller.ClaudeOperations(add: { await calls.add($0) }, remove: { await calls.remove($0) })
        let store = try BackendOSStoreInstaller(userData: data, environment: [:], home: home.path, writable: true, loadIndex: { BackendOSStoreInstallFixture.loaded([row], revoked: revoked) }, fetchArtifact: { _, _ in .init(ok: true, bytes: archive) }, runAgent: { await calls.run($0, $1) }, claudeOperations: operations, now: { Date(timeIntervalSince1970: 1_788_048_000) })
        return Rig(root: root, data: data, home: home, archive: fixture.archive, row: row, store: store, calls: calls)
    }
    func agents(_ values: [String]) -> NativeRPCValue { .object([.init("agents", .array(values.map(NativeRPCValue.string)))]) }
    var mcp: NativeRPCValue { .object([.init("runtime", .string("node")), .init("package", .string("@pub/thing-server")), .init("args", .array([.string("--root"), .string("${input:ROOT}")])), .init("inputs", .array([
        .object([.init("key", .string("ROOT")), .init("label", .string("Folder")), .init("hint", .string("Which folder to read")), .init("kind", .string("path")), .init("into", .string("arg")), .init("required", .bool(true))]),
        .object([.init("key", .string("THING_KEY")), .init("label", .string("API key")), .init("hint", .string("From the dashboard")), .init("kind", .string("secret")), .init("into", .string("env")), .init("required", .bool(false))])])), .init("token", .string("@pub/thing-server"))]) }
    var noInputsMcp: NativeRPCValue { .object([.init("runtime", .string("node")), .init("package", .string("thing-server")), .init("args", .array([])), .init("inputs", .array([])), .init("token", .string("thing-server"))]) }
    var routine: String { "# Nightly sweep\n\nwhen: schedule 09:00\nin: /somewhere/else\n\n---\n\nSweep the folder.\n" }
    func testStoreInstall220ExplicitAgentDirectories() { XCTAssertEqual(BackendOSStoreInstaller.agentHome("claude", environment: ["CLAUDE_CONFIG_DIR": "/x/claude"], home: "/home"), "/x/claude"); XCTAssertEqual(BackendOSStoreInstaller.agentHome("codex", environment: ["CODEX_HOME": "/x/codex"], home: "/home"), "/x/codex") }
    func testStoreInstall225GeminiVariableNamesParent() { XCTAssertEqual(BackendOSStoreInstaller.agentHome("gemini", environment: ["GEMINI_CLI_HOME": "/x/g"], home: "/home"), "/x/g/.gemini"); XCTAssertEqual(BackendOSStoreInstaller.agentHome("gemini", environment: [:], home: "/home"), "/home/.gemini") }
    func testStoreInstall232AgentDefaultHomes() { XCTAssertEqual(BackendOSStoreInstaller.agentHomes(environment: [:], home: "/home"), .object([.init("claude", .string("/home/.claude")), .init("codex", .string("/home/.codex")), .init("gemini", .string("/home/.gemini"))])) }
    func testStoreInstall242SkillsForClaudeAndGemini() async throws { let r = try rig(), result = try await r.store.install(id: "pub/thing", choice: agents(["claude", "gemini"])); XCTAssertEqual(result["ok"].bool, true); for dir in [".claude", ".gemini"] { let file = r.home.appendingPathComponent(dir + "/skills/pub.thing/SKILL.md"); XCTAssertTrue(FileManager.default.fileExists(atPath: file.path)); XCTAssertEqual(try text(file), skill) } }
    func testStoreInstall256CodexSkillNamedInMemory() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["codex"])); let body = try text(r.home.appendingPathComponent(".codex/AGENTS.md")); XCTAssertTrue(body.contains("terminaldeck-store pub.thing")); XCTAssertTrue(body.contains(r.home.appendingPathComponent(".codex/skills/pub.thing/SKILL.md").path)) }
    func testStoreInstall266RetainedCopyAndLedgerEveryFile() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); let record = try XCTUnwrap(BackendOSStoreInstaller.readLedger(r.data).first); XCTAssertEqual(record["id"].string, "pub/thing"); XCTAssertEqual(record["root"].string, BackendOSStoreInstaller.itemsDirectory(r.data).appendingPathComponent("pub.thing").path); XCTAssertTrue(record["writes"].elements?.contains { $0["path"].string == r.home.appendingPathComponent(".claude/skills/pub.thing/SKILL.md").path } == true); XCTAssertTrue(FileManager.default.fileExists(atPath: r.data.appendingPathComponent("community/items/pub.thing/skill/SKILL.md").path)) }
    func testStoreInstall280MissingSkillRefusesEmptyFolder() async throws { let r = try rig(extra: [.init("skill/notes.md", "nothing useful")]), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("SKILL.md") == true); XCTAssertFalse(FileManager.default.fileExists(atPath: r.home.appendingPathComponent(".claude/skills/pub.thing").path)) }
    func testStoreInstall293ExistingSkillFolderNotOverwritten() async throws { let r = try rig(), file = r.home.appendingPathComponent(".claude/skills/pub.thing/SKILL.md"); try put(file, "mine, not yours"); let result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertEqual(try text(file), "mine, not yours") }
    func testStoreInstall307RemoveOnlyRecordedWrites() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude", "gemini"])); let mine = r.home.appendingPathComponent(".claude/skills/mine-by-hand/SKILL.md"); try put(mine, "hand written"); let removed = try await r.store.remove(id: "pub/thing"); XCTAssertEqual(removed["ok"].bool, true); for path in [r.home.appendingPathComponent(".claude/skills/pub.thing"), r.home.appendingPathComponent(".gemini/skills/pub.thing"), r.data.appendingPathComponent("community/items/pub.thing")] { XCTAssertFalse(FileManager.default.fileExists(atPath: path.path)) }; XCTAssertEqual(BackendOSStoreInstaller.readLedger(r.data), []); XCTAssertEqual(try text(mine), "hand written") }
    func testStoreInstall326MemoryOutsideMarkerRestoredExactly() async throws { let r = try rig(), file = r.home.appendingPathComponent(".codex/AGENTS.md"), before = "# My own notes\n\nSomething I wrote.\n"; try put(file, before); _ = try await r.store.install(id: "pub/thing", choice: agents(["codex"])); XCTAssertNotEqual(try text(file), before); _ = try await r.store.remove(id: "pub/thing"); XCTAssertEqual(try text(file), before) }
    func testStoreInstall340FailedRemovalRemainsInLedger() async throws {
        let r = try rig(kind: "mcp", install: noInputsMcp, extra: [], tier: 3); _ = try await r.store.install(id: "pub/thing", choice: agents(["codex"]))
        let stubborn = try BackendOSStoreInstaller(userData: r.data, environment: [:], home: r.home.path, writable: true, loadIndex: { BackendOSStoreInstallFixture.loaded([r.row]) }, runAgent: { _, _ in .object([.init("ok", .bool(false)), .init("message", .string("the tool is not installed"))]) })
        let removed = try await stubborn.remove(id: "pub/thing"); XCTAssertEqual(removed["ok"].bool, false); XCTAssertTrue(removed["message"].string?.contains("not installed") == true); XCTAssertEqual(BackendOSStoreInstaller.readLedger(r.data).count, 1)
    }
    func testStoreInstall383WrongFingerprintRefused() async throws { let other = try BackendOSStoreArchiveFixture.tarGzip([.init("thing-abc/terminaldeck.json", "{}")]), r = try rig(served: other), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("does not match the fingerprint") == true); XCTAssertFalse(FileManager.default.fileExists(atPath: r.data.appendingPathComponent("community/items/pub.thing").path)) }
    func testStoreInstall394LengthCheckedBeforeDigest() async throws { let fixture = try BackendOSStoreInstallFixture.item(extra: [.init("skill/SKILL.md", skill)]), r = try rig(rowPatch: .object([.init("artifact", fixture.row["artifact"].setting("bytes", .number(Double(fixture.archive.count + 10))))])), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false) }
    func testStoreInstall401ManifestVersionMustMatchRow() async throws { let r = try rig(rowPatch: .object([.init("version", .string("2.0.0"))])), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("2.0.0") == true) }
    func testStoreInstall409DerivedTierCannotExceedDisclosure() async throws { let r = try rig(extra: [.init("skill/SKILL.md", skill), .init("skill/do.sh", "#!/bin/sh\necho hi\n")]), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("skill/do.sh") == true); XCTAssertFalse(FileManager.default.fileExists(atPath: r.home.appendingPathComponent(".claude/skills/pub.thing").path)) }
    func testStoreInstall418OverstatedTierStillInstalls() async throws { let r = try rig(tier: 3), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, true) }
    func testStoreInstall424PinnedTraversalArchiveStillRefused() async throws {
        let escaping = try BackendOSStoreArchiveFixture.tarGzip([.init("../../.claude/settings.json", "{}")]), fixture = try BackendOSStoreInstallFixture.item(), hash = SHA256.hash(data: escaping).map { String(format: "%02x", $0) }.joined()
        let r = try rig(rowPatch: .object([.init("artifact", fixture.row["artifact"].setting("sha256", .string(hash)).setting("bytes", .number(Double(escaping.count))))]), served: escaping), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"]))
        XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("will not write") == true)
    }
    func testStoreInstall441SignedWithdrawalRefuses() async throws { let r = try rig(revoked: [.object([.init("id", .string("pub/thing")), .init("version", .string("*")), .init("reason", .string("it was taking screenshots"))])]), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("screenshots") == true) }
    func testStoreInstall451UnsupportedHooksExplained() async throws { let r = try rig(kind: "hooks", install: .object([.init("script", .string("hook.mjs")), .init("events", .array([.string("SessionStart")])), .init("runtime", .string("node"))]), extra: [.init("hook.mjs", "export default 1\n")], tier: 3), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("Hooks") == true) }
    func testStoreInstall465DuplicateInstallRefuses() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); let again = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); XCTAssertEqual(again["ok"].bool, false); XCTAssertTrue(again["message"].string?.contains("already installed") == true) }
    func testStoreInstall474SecondAgentFailureRollsBackFirst() async throws { let r = try rig(kind: "mcp", install: noInputsMcp, extra: [], tier: 3, fails: "gemini"), result = try await r.store.install(id: "pub/thing", choice: agents(["claude", "gemini"])); XCTAssertEqual(result["ok"].bool, false); XCTAssertEqual(BackendOSStoreInstaller.readLedger(r.data), []); XCTAssertFalse(FileManager.default.fileExists(atPath: r.data.appendingPathComponent("community/items/pub.thing").path)); let claude = await r.calls.requests(), ran = await r.calls.commands(); XCTAssertEqual(claude.map(\.0), ["add", "remove"]); XCTAssertEqual(ran.map { $0.1[1] }, ["add"]) }
    func testStoreInstall504OnlyLocallyComposedMcpCommandRuns() async throws {
        let r = try rig(kind: "mcp", install: mcp, extra: [], tier: 3), result = try await r.store.install(id: "pub/thing", choice: agents(["claude", "codex", "gemini"]).setting("values", .object([.init("ROOT", .string("/tmp/here"))])))
        XCTAssertEqual(result["ok"].bool, true); let claude = await r.calls.requests(), ran = await r.calls.commands(), request = claude[0].1
        XCTAssertEqual(request["name"].string, "pub-thing"); XCTAssertEqual(request["scope"].string, "user"); XCTAssertEqual(request["transport"].string, "stdio"); XCTAssertEqual(request["command"].string, "npx -y @pub/thing-server --root \"/tmp/here\"")
        XCTAssertEqual(ran.map { [$0.0] + $0.1 }, [["codex", "mcp", "add", "pub-thing", "--", "npx", "-y", "@pub/thing-server", "--root", "/tmp/here"], ["gemini", "mcp", "add", "-s", "user", "-t", "stdio", "pub-thing", "npx", "-y", "@pub/thing-server", "--root", "/tmp/here"]])
    }
    func testStoreInstall537RequiredInputMustBeFilled() async throws { let r = try rig(kind: "mcp", install: mcp, extra: [], tier: 3), result = try await r.store.install(id: "pub/thing", choice: agents(["claude"]).setting("values", .object([]))); XCTAssertEqual(result["ok"].bool, false); let ran = await r.calls.commands(), claude = await r.calls.requests(); XCTAssertTrue(ran.isEmpty); XCTAssertTrue(claude.isEmpty) }
    func testStoreInstall545RemoveUsesSameMcpNameAndScope() async throws { let r = try rig(kind: "mcp", install: mcp, extra: [], tier: 3); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude", "codex"]).setting("values", .object([.init("ROOT", .string("/tmp/here"))]))); let removed = try await r.store.remove(id: "pub/thing"); XCTAssertEqual(removed["ok"].bool, true); let claude = await r.calls.requests(), ran = await r.calls.commands(); XCTAssertEqual(claude.last?.0, "remove"); XCTAssertEqual(claude.last?.1, .object([.init("name", .string("pub-thing")), .init("scope", .string("user")), .init("projectPath", .null)])); XCTAssertEqual(ran.last?.0, "codex"); XCTAssertEqual(ran.last?.1, ["mcp", "remove", "pub-thing"]) }
    func testStoreInstall556ExactProviderArgv() { XCTAssertEqual(BackendOSStoreInstaller.mcpAddArguments(agent: "codex", name: "n", argv: ["npx", "-y", "p"], extras: ["K=v"]), ["mcp", "add", "n", "--env", "K=v", "--", "npx", "-y", "p"]); XCTAssertEqual(BackendOSStoreInstaller.mcpAddArguments(agent: "gemini", name: "n", argv: ["npx"], extras: []), ["mcp", "add", "-s", "user", "-t", "stdio", "n", "npx"]); XCTAssertEqual(BackendOSStoreInstaller.mcpRemoveArguments(agent: "gemini", name: "n"), ["mcp", "remove", "-s", "user", "n"]); XCTAssertEqual(BackendOSStoreInstaller.mcpRemoveArguments(agent: "codex", name: "n"), ["mcp", "remove", "n"]) }
    func testStoreInstall577InstructionsFileAndOneOwnedBlock() async throws { let r = try rig(kind: "instructions", install: .object([.init("file", .string("rules.md"))]), extra: [.init("rules.md", "# Rules\n\nBe brief.\n")]); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude", "gemini", "codex"])); XCTAssertTrue(try text(r.home.appendingPathComponent(".claude/instructions/pub.thing.md")).contains("Be brief.")); XCTAssertTrue(try text(r.home.appendingPathComponent(".claude/CLAUDE.md")).contains("@instructions/pub.thing.md")); XCTAssertTrue(try text(r.home.appendingPathComponent(".gemini/GEMINI.md")).contains("@instructions/pub.thing.md")); XCTAssertTrue(try text(r.home.appendingPathComponent(".codex/AGENTS.md")).contains(r.home.appendingPathComponent(".codex/instructions/pub.thing.md").path)) }
    func testStoreInstall595RemoveInstructionsAndOwnBlocks() async throws { let r = try rig(kind: "instructions", install: .object([.init("file", .string("rules.md"))]), extra: [.init("rules.md", "# Rules\n")]); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude", "gemini"])); _ = try await r.store.remove(id: "pub/thing"); XCTAssertFalse(FileManager.default.fileExists(atPath: r.home.appendingPathComponent(".claude/instructions/pub.thing.md").path)); XCTAssertFalse(try text(r.home.appendingPathComponent(".claude/CLAUDE.md")).contains("pub.thing")) }
    func testStoreInstall621RoutineNeedsUserFolder() async throws { let r = try rig(kind: "routine", install: .object([.init("file", .string("routine.md"))]), extra: [.init("routine.md", routine)], tier: 2), result = try await r.store.install(id: "pub/thing", choice: .object([])); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["message"].string?.contains("folder") == true) }
    func testStoreInstall634RoutineWrittenDisarmedInChosenFolder() async throws { let r = try rig(kind: "routine", install: .object([.init("file", .string("routine.md"))]), extra: [.init("routine.md", routine)], tier: 2), folder = r.home.appendingPathComponent("work").path, result = try await r.store.install(id: "pub/thing", choice: .object([.init("folder", .string(folder))])); XCTAssertEqual(result["ok"].bool, true); let written = try text(r.data.appendingPathComponent("routines/pub-thing.md")); XCTAssertTrue(written.contains("enabled: no")); XCTAssertTrue(written.contains("in: " + folder)); XCTAssertFalse(written.contains("/somewhere/else")) }
    func testStoreInstall651PublishedRoutineFolderReplaced() { let rewritten = BackendOSStoreInstaller.setRoutineFolder(routine, folder: "/chosen"); XCTAssertTrue(rewritten.contains("in: /chosen")); XCTAssertFalse(rewritten.contains("/somewhere/else")); XCTAssertTrue(rewritten.contains("Sweep the folder.")) }
    func testStoreInstall660ViewDetectsEditedCopy() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); let first = try await r.store.view(); XCTAssertEqual(first["items"].elements?.first?["state"].string, "installed"); try put(r.data.appendingPathComponent("community/items/pub.thing/skill/SKILL.md"), "edited behind our back"); let second = try await r.store.view(); XCTAssertEqual(second["items"].elements?.first?["state"].string, "damaged"); XCTAssertTrue(second["items"].elements?.first?["note"].string?.contains("no longer matches") == true) }
    func testStoreInstall674NewerVersionOutdated() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); let row = r.row.setting("version", .string("2.0.0")), later = try BackendOSStoreInstaller(userData: r.data, environment: [:], home: r.home.path, loadIndex: { BackendOSStoreInstallFixture.loaded([row]) }), view = try await later.view(); XCTAssertEqual(view["items"].elements?.first?["state"].string, "outdated"); XCTAssertTrue(view["items"].elements?.first?["note"].string?.contains("2.0.0") == true) }
    func testStoreInstall685DelistedInstalledRowRemainsRemovable() async throws { let r = try rig(); _ = try await r.store.install(id: "pub/thing", choice: agents(["claude"])); let empty = try BackendOSStoreInstaller(userData: r.data, environment: [:], home: r.home.path, loadIndex: { BackendOSStoreInstallFixture.loaded([]) }), view = try await empty.view(); XCTAssertEqual(view["items"].elements?.count, 1); XCTAssertEqual(view["items"].elements?.first?["state"].string, "withdrawn"); XCTAssertEqual(view["items"].elements?.first?["row"]["name"].string, "A Thing") }
    func testStoreInstall719NoCatalogueHasReasonNotBlankShelf() async throws { let root = try scratch(), store = try BackendOSStoreInstaller(userData: root, environment: [:], home: root.path, loadIndex: { .object([.init("ok", .bool(false)), .init("why", .string("the store could not be reached"))]) }), view = try await store.view(); XCTAssertEqual(view["ok"].bool, false); XCTAssertTrue(view["why"].string?.contains("could not be reached") == true); XCTAssertEqual(view["items"], .array([])) }
    func testStoreInstall735DisplayedSkillTargetsExact() { let row: NativeRPCValue = .object([.init("kind", .string("skill")), .init("publisher", .string("pub")), .init("id", .string("pub/thing"))]), targets = BackendOSStoreInstaller.plannedTargets(row: row, agents: ["claude", "codex"], homes: BackendOSStoreInstaller.agentHomes(environment: [:], home: "/home"), userData: "/data"); XCTAssertTrue(targets.contains("/home/.claude/skills/pub.thing")); XCTAssertTrue(targets.contains("/home/.codex/skills/pub.thing")); XCTAssertTrue(targets.contains("/home/.codex/AGENTS.md")); XCTAssertEqual(targets[0], "/data/community/items/pub.thing") }
    func testStoreInstall744McpPlanNamesServer() { let targets = BackendOSStoreInstaller.plannedTargets(row: .object([.init("kind", .string("mcp")), .init("publisher", .string("pub")), .init("id", .string("pub/thing"))]), agents: ["claude"], homes: BackendOSStoreInstaller.agentHomes(environment: [:], home: "/home"), userData: "/data"); XCTAssertTrue(targets.contains { $0.contains("pub-thing") }) }
    func testStoreInstall751UnownedTextUnchanged() { XCTAssertEqual(BackendOSStoreInstaller.stripBlock("# Mine\n\nText.\n", marker: "pub.thing"), "# Mine\n\nText.\n") }
    func testStoreInstall755FolderAndLedgerNamesStable() { XCTAssertEqual(BackendOSStoreInstaller.folderName(publisher: "pub", item: "thing"), "pub.thing"); XCTAssertTrue(BackendOSStoreInstaller.ledgerFile(URL(fileURLWithPath: "/data")).path.contains("installed.json")) }
}
