import Foundation
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendMacAppSetupContextTests: XCTestCase {
    actor IO: BackendMacAppSetupContextIO {
        var files: [String: String] = [:]
        func ensureDirectory(_ directory: String) async throws {}
        func writeAtomically(_ file: String, text: String) async throws { files[file] = text }
        func texts() -> [String: String] { files }
    }
    static let reasons = ["this app can only add its browser verbs to a Claude session", "this app’s endpoint is on the Windows side and this session could not reach it from inside WSL", "the device that started this session cannot show a browser window", "this app’s control endpoint is not running here", "this session started before this app’s control endpoint did, and the flag that carries them is read once at launch"]
    private func input(_ opens: Bool = true, name: String = "OFFICE-PC") -> BackendMacAppSetupContextInput { .init(version: "9.9.9", machineName: name, opensInApp: opens) }
    private func paths() -> NativePlatformPaths { .init(platform: .darwin, userData: "/test/state", home: "/test/home", downloads: "/test/downloads", appRoot: "/test/app") }
    private func local(_ opens: Bool = true, name: String = "OFFICE-PC") -> [String: String] { Dictionary(uniqueKeysWithValues: BackendMacAppSetupContextPages.compose(input(opens, name: name), directory: "/test/state/context", noVerbsReasons: Self.reasons).map { ($0.name, $0.text) }) }
    private func remote(_ opens: Bool = true) -> [String: String] { Dictionary(uniqueKeysWithValues: BackendMacAppSetupContextPages.compose(input(opens, name: "Office PC"), directory: nil, remoteAppMachine: "Asad’s MacBook", noVerbsReasons: Self.reasons).map { ($0.name, $0.text) }) }
    private func written() async throws -> BackendMacAppSetupContext { let ctx = BackendMacAppSetupContext(io: IO(), noVerbsReasons: { Self.reasons }); _ = try await ctx.write(paths: paths(), input: input()); return ctx }
    func testMapNamesFileReallyWritten() async throws { let io = IO(), ctx = BackendMacAppSetupContext(io: io, noVerbsReasons: { Self.reasons }); let result = try await ctx.write(paths: paths(), input: input()); let files = await io.texts(); XCTAssertTrue(result.map.contains(result.index)); XCTAssertTrue(files[result.index]!.contains("# Terminal Deck")) }
    func testMapStaysShortAndNamesOneIndex() { let prose = BackendMacAppSetupContextPages.mapText(version: "9.9.9", machine: "OFFICE-PC", directory: "/d"); XCTAssertLessThan(prose.utf16.count, 300); XCTAssertEqual(prose.components(separatedBy: "/d/INDEX.md").count - 1, 1); XCTAssertTrue(prose.contains("OFFICE-PC")); XCTAssertTrue(prose.contains("9.9.9")) }
    func testMapDoesNotRepeatAppName() { let prose = BackendMacAppSetupContextPages.mapText(version: "1.0.0", machine: "M", directory: "/d"); XCTAssertFalse(prose.contains("Terminal Deck")); XCTAssertTrue(prose.hasPrefix("It is version")) }
    func testWritesExactlyPromisedFiles() async throws { let io = IO(), ctx = BackendMacAppSetupContext(io: io, noVerbsReasons: { Self.reasons }); _ = try await ctx.write(paths: paths(), input: input()); let files = await io.texts(); XCTAssertEqual(files.keys.map { URL(fileURLWithPath: $0).lastPathComponent }.sorted(), ["INDEX.md", "browser-windows.md", "sessions-and-machines.md"]); let index = files["/test/state/context/INDEX.md"]!; XCTAssertTrue(index.contains("sessions-and-machines.md")); XCTAssertTrue(index.contains("browser-windows.md")) }
    func testEveryPageNamesItsRegeneration() { for body in local().values { XCTAssertTrue(body.components(separatedBy: "\n")[0].contains("at every start")); XCTAssertTrue(body.contains("Do not edit")) } }
    func testBrowserExplainsConnectionAndBNames() { let page = local()["browser-windows.md"]!; XCTAssertTrue(page.contains("Connect browser")); XCTAssertTrue(page.contains("`B1`, `B2`")); XCTAssertTrue(page.contains("cannot attach a window")) }
    func testNoUninstalledOpenerIsClaimedOnMac() { let shimmed = local()["browser-windows.md"]!, bare = local(false)["browser-windows.md"]!; XCTAssertTrue(shimmed.contains("is on this session's PATH ahead of the machine's own opener")); XCTAssertFalse(bare.contains("ahead of the machine's own opener")); XCTAssertTrue(bare.contains("does not put an opener on a session")) }
    func testDocumentsNameAvailableToolsWithoutOldDenial() { let page = local()["browser-windows.md"]!; XCTAssertFalse(page.contains("a session has no tool for any of that")); XCTAssertFalse(page.contains("Driving a page belongs to the copilot")); for verb in ["browser_open", "browser_read", "browser_step", "browser_close"] { XCTAssertTrue(page.contains(verb)) }; XCTAssertTrue(page.contains("`window: \"B2\"`")) }
    func testReasonsComeFromSuppliedSingleList() { let page = local()["browser-windows.md"]!; XCTAssertFalse(Self.reasons.isEmpty); for clause in Self.reasons { XCTAssertTrue(page.contains(String(clause.prefix(1)).uppercased() + String(clause.dropFirst()) + ".")) } }
    func testNamesActualSessionMachine() { XCTAssertTrue(local(name: "DESKTOP-DDGMNCV")["sessions-and-machines.md"]!.contains("This session is running on DESKTOP-DDGMNCV.")) }
    func testEverySessionStartReturnsMap() async throws { let ctx = try await written(); let first = await ctx.bootMapFor(event: "SessionStart", sessionID: "s1"), second = await ctx.bootMapFor(event: "SessionStart", sessionID: "s1"); XCTAssertNotNil(first); XCTAssertEqual(first, second) }
    func testGeminiFirstTurnLatchIsPerSession() async throws { let ctx = try await written(); let first = await ctx.bootMapFor(event: "BeforeAgent", sessionID: "s1"), second = await ctx.bootMapFor(event: "BeforeAgent", sessionID: "s1"), third = await ctx.bootMapFor(event: "BeforeAgent", sessionID: "s1"), other = await ctx.bootMapFor(event: "BeforeAgent", sessionID: "s2"); XCTAssertNotNil(first); XCTAssertNil(second); XCTAssertNil(third); XCTAssertNotNil(other) }
    func testOtherEventsNeverRepayMap() async throws { let ctx = try await written(); for event in ["UserPromptSubmit", "PostToolUse", "AfterTool", "Stop"] { let map = await ctx.bootMapFor(event: event, sessionID: "s1"); XCTAssertNil(map) } }
    func testNoIDOrUnwrittenDocumentsGiveNoMap() async { let ctx = BackendMacAppSetupContext(io: IO(), noVerbsReasons: { Self.reasons }); let missingID = await ctx.bootMapFor(event: "SessionStart", sessionID: nil), unwritten = await ctx.bootMapFor(event: "SessionStart", sessionID: "s1"); XCTAssertNil(missingID); XCTAssertNil(unwritten) }
    func testRemoteMapNamesOnlyRemoteDirectory() async throws { let ctx = try await written(), here = await ctx.currentAppContext(); let map = BackendMacAppSetupContextPages.mapText(version: "9.9.9", machine: "Office PC", directory: "/tmp/td-drive-abc123/context"); XCTAssertTrue(map.contains("/tmp/td-drive-abc123/context/INDEX.md")); XCTAssertFalse(map.contains(here!.dir)); XCTAssertNotEqual(map, here!.map) }
    func testCallerMapOverrideAndLocalFallback() async throws { let ctx = try await written(), map = BackendMacAppSetupContextPages.mapText(version: "9.9.9", machine: "Office PC", directory: "/tmp/td-drive-abc123/context"); let there = await ctx.bootMapFor(event: "SessionStart", sessionID: "server-1 shell-9", machineID: "server-1", override: map), here = await ctx.bootMapFor(event: "SessionStart", sessionID: "s1"), current = await ctx.currentAppContext(); XCTAssertEqual(there, map); XCTAssertEqual(here, current!.map) }
    func testRemotePagesDescribeActualTransport() { let page = remote()["sessions-and-machines.md"]!; XCTAssertTrue(page.contains("Nothing was written into this account's home directory.")); XCTAssertTrue(page.contains("# terminaldeck-hook")); XCTAssertFalse(page.contains("~/.codex/hooks.json")); XCTAssertFalse(page.contains("TERMINALDECK_SESSION")); XCTAssertTrue(page.contains("There is no session id in this shell's environment")) }
    func testRemotePagesKeepMachineRolesSeparate() { let pages = remote(); XCTAssertTrue(pages["INDEX.md"]!.contains("Office PC")); XCTAssertTrue(pages["INDEX.md"]!.contains("Asad’s MacBook")); XCTAssertTrue(pages["sessions-and-machines.md"]!.contains("This session is running on Office PC, and the app")); XCTAssertTrue(pages["browser-windows.md"]!.contains("on Asad’s MacBook")) }
    func testRemoteNoOpenerClaimWhenNotInstalled() { XCTAssertTrue(remote()["browser-windows.md"]!.contains("ahead of this server's own opener")); XCTAssertTrue(remote(false)["browser-windows.md"]!.contains("opens **on this server** rather than in the")); XCTAssertTrue(remote(false)["INDEX.md"]!.contains("this server's own opener")) }
    func testRemoteDocumentsDoNotOfferLocalRefusalReasons() { let page = remote()["browser-windows.md"]!; XCTAssertTrue(page.contains("browser verbs, and that is not a hope")); XCTAssertTrue(page.contains("browser_read")); for clause in Self.reasons { XCTAssertFalse(page.contains(String(clause.prefix(1)).uppercased() + String(clause.dropFirst()) + ".")) } }
    func testRemoteIndexDoesNotGuessDirectory() { XCTAssertFalse(remote()["INDEX.md"]!.contains("This directory:")) }
    struct HookDependencies: BackendMacAppSetupHookContextDependencies {
        let known: Bool, attached: Bool
        func mayAnswer(provider: String, event: String) async throws -> Bool { ["claude": ["SessionStart", "UserPromptSubmit", "PostToolUse"], "codex": ["SessionStart", "PostToolUse"], "gemini": ["BeforeAgent", "AfterTool"]][provider]?.contains(event) == true }
        func isMidTurn(_ event: String) async throws -> Bool { ["PostToolUse", "AfterTool"].contains(event) }
        func announcement(sessionID: String, machineID: String) async throws -> String? { nil }
        func standingContext(sessionID: String?, machineID: String, map: String?) async throws -> String? { guard known, sessionID != nil else { return nil }; var lines = ["You are running inside Terminal Deck, a terminal app with browser windows of its own."]; if let map { lines.append(map) }; if attached { lines.append("B1 — Stripe — https://stripe.com") }; lines.append("Do not mention any of this unless asked."); return lines.joined(separator: "\n") }
    }
    private func hook(_ known: Bool = true, attached: Bool = false) async throws -> BackendMacAppSetupHookContextAdapter { let ctx = BackendMacAppSetupContext(io: IO(), noVerbsReasons: { Self.reasons }); _ = try await ctx.write(paths: paths(), input: .init(version: "0.8.1", machineName: "OFFICE-PC", opensInApp: true)); return .init(context: ctx, existing: HookDependencies(known: known, attached: attached)) }
    func testBootClaudeCarriesAppVersionAndReadableIndex() async throws { let h = try await hook(), text = try await h.answer(provider: "claude", event: "SessionStart", sessionID: "s1"); for fragment in ["Terminal Deck", "0.8.1", "OFFICE-PC", "/test/state/context/INDEX.md"] { XCTAssertTrue(text!.contains(fragment)) }; XCTAssertEqual(text == nil ? 204 : 200, 200) }
    func testBootCodexUsesOnlyItsContextDoor() async throws { let h = try await hook(), start = try await h.answer(provider: "codex", event: "SessionStart", sessionID: "s1"), prompt = try await h.answer(provider: "codex", event: "UserPromptSubmit", sessionID: "s1"); XCTAssertTrue(start!.contains("0.8.1")); XCTAssertEqual(prompt == nil ? 204 : 200, 204) }
    func testBootGeminiFirstTurnGetsMapOnce() async throws { let h = try await hook(), first = try await h.answer(provider: "gemini", event: "BeforeAgent", sessionID: "s1"), second = try await h.answer(provider: "gemini", event: "BeforeAgent", sessionID: "s1"); XCTAssertTrue(first!.contains("0.8.1")); XCTAssertNotNil(second); XCTAssertFalse(second!.contains("0.8.1")) }
    func testBootPromptStaysShort() async throws { let h = try await hook(); _ = try await h.answer(provider: "claude", event: "SessionStart", sessionID: "s1"); let prompt = try await h.answer(provider: "claude", event: "UserPromptSubmit", sessionID: "s1"); XCTAssertTrue(prompt!.contains("You are running inside Terminal Deck")); XCTAssertFalse(prompt!.contains("0.8.1")); XCTAssertFalse(prompt!.contains("INDEX.md")) }
    func testBootMapPrecedesWindowsAndInstructionIsLast() async throws { let h = try await hook(attached: true), text = try await h.answer(provider: "claude", event: "SessionStart", sessionID: "s1"), lines = text!.components(separatedBy: "\n"); XCTAssertTrue(lines[0].contains("You are running inside Terminal Deck")); XCTAssertTrue(lines[1].contains("INDEX.md")); XCTAssertGreaterThan(lines.firstIndex(of: "B1 — Stripe — https://stripe.com")!, 1); XCTAssertTrue(lines.last!.contains("Do not mention any of this")) }
    func testBootMidTurnCallsSayNothing() async throws { let h = try await hook(); _ = try await h.answer(provider: "claude", event: "SessionStart", sessionID: "s1"); for (provider, event) in [("claude", "PostToolUse"), ("gemini", "AfterTool")] { let text = try await h.answer(provider: provider, event: event, sessionID: "s1"); XCTAssertEqual(text == nil ? 204 : 200, 204) } }
    func testBootUnknownSessionsHearNothing() async throws { let h = try await hook(false); for (provider,event) in [("claude", "SessionStart"), ("gemini", "BeforeAgent")] { let text = try await h.answer(provider: provider, event: event, sessionID: "outside"); XCTAssertEqual(text == nil ? 204 : 200, 204) } }
}
