import Foundation
import Testing
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

@Suite("window-drive.test.ts case parity with fake processes")
struct BackendServersWindowPortDriveTests {
    private var dir: String { BackendServersWindowPortFixtures.dir }
    @Test("reads the flag out of it rather than out of a version number") func d138McpHelp() { let h = BackendServersWindowPortFixtures.help; #expect(BackendServersWindowDriveScripts.honoursMcpConfig(h)); #expect(!BackendServersWindowDriveScripts.honoursMcpConfig(h.replacingOccurrences(of: "--mcp-config <configs...>", with: "--model <model>"))) }
    @Test("takes the subcommands, both spellings of an alias, and nothing else") func d143Commands() { #expect(BackendServersWindowDriveScripts.subcommandsFrom(BackendServersWindowPortFixtures.help) == ["agents", "doctor", "mcp", "plugin", "plugins", "update"]) }
    @Test("answers nothing at all for help with no Commands block") func d154NoCommands() { #expect(BackendServersWindowDriveScripts.subcommandsFrom("Usage: claude\n\nOptions:\n  -p, --print  Print\n") == []) }
    @Test("does not mistake an option line or a wrapped description for a subcommand") func d158NoWrappedCommands() { let words = BackendServersWindowDriveScripts.subcommandsFrom(BackendServersWindowPortFixtures.help); #expect(!words.contains("load") && !words.contains("strings")) }
    @Test("adds the flag to a bare invocation") func d168BareWrapper() throws { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: []) == ["--mcp-config", dir + "/deck-control.json"]) }
    @Test("adds it to a prompt, and keeps the prompt one argument") func d173PromptArgv() throws { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: ["fix the build please"]) == ["--mcp-config", dir + "/deck-control.json", "fix the build please"]) }
    @Test("adds it in front of flags the person passed") func d182OriginalFlags() throws { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: ["-p", "hello"]) == ["--mcp-config", dir + "/deck-control.json", "-p", "hello"]) }
    @Test("leaves every subcommand this server listed completely alone") func d192BypassCommands() throws { for word in ["mcp", "doctor", "update", "plugins"] { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: [word, "list"]) == [word, "list"]) } }
    @Test("treats a word that only looks like a subcommand as a prompt") func d201UnknownCommandIsPrompt() throws { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: ["deploy"]) == ["--mcp-config", dir + "/deck-control.json", "deploy"]) }
    @Test("survives a path with a quote in it, which is what would brick a terminal") func d210QuotedRealBinary() throws { let script = BackendServersWindowPortFixtures.wrapper(real: "/tmp/td-fake-o'clock/claude"); #expect(try BackendServersWindowPortProcess.assignment("REAL", script) == "/tmp/td-fake-o'clock/claude"); #expect(try BackendServersWindowPortProcess.wrapper(script, args: []) == ["--mcp-config", dir + "/deck-control.json"]) }
    @Test("writes the config where the wrapper names it, and only for this account") func d222PrivateManifest() throws { let body = #"{"mcpServers":{"deck-control":{"type":"http"}}}"#, script = try BackendServersWindowDriveScripts.armScript(dir: dir, files: [.init(path: "deck-control.json", body: body), .init(path: "bin/claude", body: BackendServersWindowPortFixtures.wrapper(), executable: true)]); let files = try BackendServersWindowPortProcess.armFiles(script); #expect(dir.hasPrefix(BackendServersWindowDriveScripts.scratchPrefix)); #expect(try NativeRPCValue.parseJSON(Data(try #require(files[dir + "/deck-control.json"]?.body).utf8)) == NativeRPCValue.parseJSON(Data(body.utf8))); #expect(files[dir + "/deck-control.json"]?.mode == 0o600); #expect(script.contains(#"chmod 700 "$d""#) || BackendServersWindowDriveScripts.scoutScript.contains(#"chmod 700 "$d""#)) }
    @Test("answers with this machine’s own programs, absolutely, and never a bare word") func d239ScoutPrograms() { let answer = BackendServersWindowDriveScripts.readScouted(BackendServersWindowPortFixtures.scouted()); #expect(answer.dir.hasPrefix(BackendServersWindowDriveScripts.scratchPrefix) && answer.curl == "/usr/bin/curl"); for path in answer.openers.values { #expect(path.isEmpty || path.hasPrefix("/")) }; #expect(Set(answer.openers.keys) == Set(BackendServersWindowBelong.openerNames)); #expect(BackendServersWindowDriveScripts.scoutScript.contains(#"v=$(command -v "$1""#) && BackendServersWindowDriveScripts.scoutScript.contains(#"case "$v" in /*)"#)) }
    @Test("takes exactly its own folder back, and refuses any other path") func d259ScratchRemovalGuard() throws { for path in [dir, "/tmp"] { let script = BackendServersWindowDriveScripts.disarmScript(path); #expect(try BackendServersWindowPortProcess.assignment("p", script) == path); #expect(script.contains(#"case "$p" in /tmp/td-drive-??????) ;; *) exit 1 ;; esac"#)) }; #expect(BackendServersWindowDriveScripts.disarmScript(dir).contains(#"rm -rf "$p""#)) }
    @Test("says what it is, in the line it types into the terminal") func d268VisiblePathLine() { let line = BackendServersWindowDriveScripts.pathLine("/tmp/td-drive-abc123"); #expect(line.hasPrefix("export PATH='/tmp/td-drive-abc123/bin':$PATH") && line.contains("#") && line.hasSuffix("\n")) }
    @Test("binds the token to the server, not to this computer") func d353ServerBinding() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; #expect(await d.arm("server-1", shellId: "server-1 shell-9") == .armed(line: BackendServersWindowDriveScripts.pathLine(dir))); #expect(f.bound.values == ["server-1/server-1 shell-9"]) }
    @Test("answers with the line to type, naming the folder the server made") func d362ArmPath() async { let f = BackendServersWindowPortDriveBox(); let out = await f.drives.arm("server-1", shellId: "shell-9"); if case .armed(let line) = out { #expect(line.contains(dir + "/bin")) } else { Issue.record("Expected arming") } }
    @Test("refuses before asking the server anything when the switch is off") func d368Disabled() async { var o = BackendServersWindowPortDriveOptions(); o.allowed = false; let f = BackendServersWindowPortDriveBox(o), d = f.drives; #expect(await d.arm("server-1", shellId: "shell-9") == .refused(why: BackendServersWindowDriveReasons.notAllowed)); #expect(f.asked.values.isEmpty); #expect(await d.whyNot("shell-9") == BackendServersWindowDriveReasons.notAllowed) }
    @Test("names the agents it cannot reach when there is no claude") func d377MissingClaude() async { var o = BackendServersWindowPortDriveOptions(); o.claude = false; let f = BackendServersWindowPortDriveBox(o); #expect(await f.drives.arm("server-1", shellId: "shell-9") == .refused(why: BackendServersWindowDriveReasons.agent)); #expect(BackendServersWindowDriveReasons.agent.contains("Codex") && BackendServersWindowDriveReasons.agent.contains("Gemini")) }
    @Test("refuses a claude too old for the flag rather than wrapping it") func d385UnsupportedMcp() async { var o = BackendServersWindowPortDriveOptions(); o.help = "Usage: claude\n"; let f = BackendServersWindowPortDriveBox(o); #expect(await f.drives.arm("server-1", shellId: "shell-9") == .refused(why: BackendServersWindowDriveReasons.flag)) }
    @Test("gives the token back when the port could not be opened") func d390RefusedPort() async { var o = BackendServersWindowPortDriveOptions(); o.controlRefusal = "that server will not forward."; let f = BackendServersWindowPortDriveBox(o); #expect(await f.drives.arm("server-1", shellId: "shell-9") == .refused(why: "that server will not forward.")); #expect(f.dropped.values == ["dropped"] && f.releases.values.isEmpty) }
    @Test("gives the token back and lets go of the port when the files would not land") func d402FailedFiles() async { var o = BackendServersWindowPortDriveOptions(); o.failWrite = true; let f = BackendServersWindowPortDriveBox(o); if case .armed = await f.drives.arm("server-1", shellId: "shell-9") { Issue.record("Armed despite write failure") }; #expect(!f.dropped.values.isEmpty && f.releases.values == ["server-1/control", "server-1/hooks"]) }
    @Test("refuses a folder answer that is not one of ours") func d416UnsafeFolder() async { var o = BackendServersWindowPortDriveOptions(); o.dir = "/etc"; let f = BackendServersWindowPortDriveBox(o); if case .armed = await f.drives.arm("server-1", shellId: "shell-9") { Issue.record("Armed unsafe directory") }; #expect(!f.dropped.values.isEmpty) }
    @Test("says nothing about a shell it never armed") func d424UnknownDrive() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; #expect(await d.whyNot("a shell nobody opened") == nil); _ = await d.arm("server-1", shellId: "shell-9"); #expect(await d.whyNot("shell-9") == nil) }
    @Test("reads the answers past whatever a profile printed, by the mark") func d433ProfileNoise() { let got = BackendServersWindowDriveScripts.readScouted("bash: warning: setlocale\n" + BackendServersWindowPortFixtures.scouted()); #expect(got.dir == dir && got.shell == "/bin/bash" && got.curl == "/usr/bin/curl" && got.openers == ["open": "", "xdg-open": "/usr/bin/xdg-open", "sensible-browser": ""]) }
    @Test("answers with nothing at all when the mark never arrived") func d444MissingMark() { let got = BackendServersWindowDriveScripts.readScouted("permission denied\n"); #expect(got.dir == "" && got.shell == "" && got.curl == "" && got.openers == ["open": "", "xdg-open": "", "sensible-browser": ""]) }
    @Test("takes the Bourne family, by syntax rather than by popularity") func d453BourneShells() { for shell in ["/bin/sh", "/bin/bash", "/usr/bin/zsh", "/bin/dash", "/bin/ash", "/bin/ksh", ""] { #expect(BackendServersWindowDriveScripts.takesAnExportLine(shell)) } }
    @Test("refuses the two where the line would print an error instead") func d461NonBourneShells() { for shell in ["/usr/bin/fish", "/bin/csh", "/bin/tcsh"] { #expect(!BackendServersWindowDriveScripts.takesAnExportLine(shell)) } }
    @Test("gives back the token, the port and the folder when the shell cannot take it") func d470ShellRefusalCleanup() async { var o = BackendServersWindowPortDriveOptions(); o.shell = "/usr/bin/fish"; let f = BackendServersWindowPortDriveBox(o); #expect(await f.drives.arm("server-1", shellId: "shell-9") == .refused(why: BackendServersWindowDriveReasons.shell)); #expect(!f.dropped.values.isEmpty && f.releases.values == ["server-1/control"]) }
    @Test("removes what it had already put on the server") func d485RefusalRemovesScratch() async { var o = BackendServersWindowPortDriveOptions(); o.shell = "/usr/bin/fish"; let f = BackendServersWindowPortDriveBox(o); _ = await f.drives.arm("server-1", shellId: "shell-9"); #expect(f.written.values.contains { $0.contains("rm -rf") }) }
    @Test("drops the token before it tries to remove the folder") func d504DropBeforeRemove() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; _ = await d.arm("server-1", shellId: "shell-9"); await d.disarm("shell-9"); #expect(f.order.values.first == "dropped") }
    @Test("takes every shell on one server down when the switch goes off") func d524ServerRevoke() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; _ = await d.arm("server-1", shellId: "shell-a"); _ = await d.arm("server-1", shellId: "shell-b"); _ = await d.arm("server-2", shellId: "shell-c"); await d.revoke("server-1"); #expect(await d.whyNot("shell-a") == BackendServersWindowDriveReasons.notAllowed); #expect(await d.whyNot("shell-b") == BackendServersWindowDriveReasons.notAllowed); #expect(await d.whyNot("shell-c") == nil); #expect(f.releases.values == ["server-1/control", "server-1/hooks", "server-1/control", "server-1/hooks"]) }
    @Test("is idempotent, because a shell can close twice") func d541IdempotentDisarm() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; _ = await d.arm("server-1", shellId: "shell-9"); await d.disarm("shell-9"); await d.disarm("shell-9"); #expect(f.releases.values == ["server-1/control", "server-1/hooks"]) }
    @Test("adds the settings flag only when there is a settings file") func d561MissingSettings() throws { let bare = try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(), args: []); #expect(bare == ["--mcp-config", dir + "/deck-control.json"]); let missing = try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(settings: "/tmp/td-drive-placeholder/settings.json"), args: [], files: [dir + "/settings.json"]); #expect(missing == bare); #expect(!bare.contains("--settings")) }
    @Test("uses the settings file when it is actually there") func d579PresentSettings() throws { #expect(try BackendServersWindowPortProcess.wrapper(BackendServersWindowPortFixtures.wrapper(settings: dir + "/settings.json"), args: ["-p", "hi"], files: [dir + "/settings.json"]) == ["--mcp-config", dir + "/deck-control.json", "--settings", dir + "/settings.json", "-p", "hi"]) }
    @Test("hands the session a map naming the documents on that server") func d611RemoteMap() async { let f = BackendServersWindowPortDriveBox(), d = f.drives; _ = await d.arm("server-1", shellId: "shell-9"); #expect(await d.belonging("shell-9") == .init(map: "read \(dir)/context/INDEX.md", opensInApp: true)) }
    @Test("says nothing at all about a shell it never armed") func d620UnknownBelonging() async { #expect(await BackendServersWindowPortDriveBox().drives.belonging("shell-9") == nil) }
    @Test("still opens pages here when the claude on that server is too old for hooks") func d625OpenerWithoutHooks() async { var o = BackendServersWindowPortDriveOptions(); o.help = o.help.replacingOccurrences(of: "--settings <file-or-json>", with: "--seatings <file>"); let f = BackendServersWindowPortDriveBox(o), d = f.drives; if case .refused = await d.arm("server-1", shellId: "shell-9") { Issue.record("Opener requires no settings flag") }; #expect(await d.belonging("shell-9") == .init(map: nil, opensInApp: true)); let text = f.written.values.joined(separator: "\n"); for name in BackendServersWindowBelong.openerNames { #expect(text.contains("bin/" + name)) }; #expect(!text.contains("settings.json") && !text.contains("--settings")) }
    @Test("arranges none of it on a server with no curl, and claims none of it") func d641NoCurl() async { var o = BackendServersWindowPortDriveOptions(); o.curl = ""; let f = BackendServersWindowPortDriveBox(o), d = f.drives; if case .refused = await d.arm("server-1", shellId: "shell-9") { Issue.record("Browser verbs do not need curl") }; #expect(await d.belonging("shell-9") == nil); #expect(!f.written.values.joined().contains("bin/open")); await d.disarm("shell-9"); #expect(f.releases.values == ["server-1/control"]) }
    @Test("writes nothing of it when the hook endpoint is not running") func d660NoHookEndpoint() async { var o = BackendServersWindowPortDriveOptions(); o.token = nil; let f = BackendServersWindowPortDriveBox(o), d = f.drives; if case .refused = await d.arm("server-1", shellId: "shell-9") { Issue.record("Control arming should work") }; #expect(await d.belonging("shell-9") == nil); #expect(!f.written.values.joined().contains("bin/xdg-open")) }
    @Test("writes nothing of it when that server will not open a second port") func d667NoSecondPort() async { var o = BackendServersWindowPortDriveOptions(); o.hookRefusal = "no second forward."; let f = BackendServersWindowPortDriveBox(o), d = f.drives; if case .refused = await d.arm("server-1", shellId: "shell-9") { Issue.record("Control arming should work") }; #expect(await d.belonging("shell-9") == nil); #expect(!f.written.values.joined().contains("bin/open")); await d.disarm("shell-9"); #expect(f.releases.values == ["server-1/control"]) }
    @Test("refuses to write a file whose path it cannot vouch for") func d683UnsafeManifest() { #expect(throws: BackendServersSetupFailure.self) { _ = try BackendServersWindowDriveScripts.armScript(dir: dir, files: [.init(path: "bin/$(id)", body: "x")]) }; #expect(throws: BackendServersSetupFailure.self) { _ = try BackendServersWindowDriveScripts.armScript(dir: dir, files: [.init(path: "a", body: "TD_FILE_0")]) } }
}
