import Foundation
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendDeckCoreTestPortSecurityControl: BackendDeckCoreTestPortSecurityCase {
    private var readOnly: BackendDeckCoreSecurityCaller { .init(kind: .remote, tiers: [.read], deviceID: "phone-1") }
    private var acting: BackendDeckCoreSecurityCaller { .init(kind: .remote, tiers: [.read, .act], deviceID: "phone-1") }
    private func start(_ f: BackendDeckCoreTestPortSecurityRig, folder: String = "/work/api", caller: BackendDeckCoreSecurityCaller = .local) async -> BackendDeckCoreSecurityCallResult { await f.call("sessions_start", o([("cwd", .string(folder))]), .init(caller: caller)) }
    private var write: V { o([("scope", .string("settings")), ("patch", o([("appearance.density", .string("compact"))]))]) }
    private func send(_ id: String, text: String = "go") -> V { o([("sessionId", .string(id)), ("text", .string(text))]) }
    func testControlL262() async throws {
        let f = try rig(), result = await f.call("sessions_list"), rows = result.value["sessions"].elements ?? [], byID = Dictionary(uniqueKeysWithValues: rows.map { ($0["id"].string ?? "", $0["status"].string ?? "") })
        XCTAssertTrue(result.ok); XCTAssertEqual(byID.keys.sorted(), ["human-1", "human-2"]); XCTAssertEqual(byID["human-1"], "working"); XCTAssertEqual(byID["human-2"], "idle")
    }
    func testControlL276() async throws {
        let f = try rig(); f.surface.sessions = ["busy", "quiet-one", "blocked"].map { BackendDeckCoreTestPortSecuritySurface.meta($0) }
        f.surface.statuses = ["busy": o([("status", .string("working")), ("at", .number(1))]), "quiet-one": o([("status", .string("waiting")), ("at", .number(1))]), "blocked": o([("status", .string("input")), ("at", .number(1))])]
        let value = await f.call("sessions_list").value, rows = value["sessions"].elements ?? []
        XCTAssertEqual(rows.map { $0["id"].string }, ["blocked", "quiet-one", "busy"]); XCTAssertEqual(value["blocked"], .number(1))
        XCTAssertEqual(rows[1]["attention"], .string("quiet")); XCTAssertEqual(rows[1]["attentionReason"], .string("prompt-ready")); XCTAssertEqual(rows[0]["attention"], .string("blocked")); XCTAssertEqual(rows[0]["attentionReason"], .string("question-unanswered"))
    }
    func testControlL307() async throws {
        let f = try rig(); f.clock.set(1_000_000); f.surface.sessions = [BackendDeckCoreTestPortSecuritySurface.meta("blocked")]; f.surface.statuses = ["blocked": o([("status", .string("input")), ("at", .number(400_000))])]
        let rows = await f.call("sessions_list").value["sessions"].elements ?? []; XCTAssertEqual(rows[0]["attentionForMs"], .number(600_000)); XCTAssertEqual(rows[0]["statusSource"], .string("screen"))
    }
    func testControlL324() async throws { let f = try rig(); f.surface.sessions = [BackendDeckCoreTestPortSecuritySurface.meta("human-1", exitCode: 0)]; f.surface.statuses["human-1"] = o([("status", .string("working")), ("at", .number(5))]); let rows = await f.call("sessions_list").value["sessions"].elements ?? []; XCTAssertEqual(rows[0]["status"], .string("exited")) }
    func testControlL335() async throws { let f = try rig(); f.surface.sessions = [BackendDeckCoreTestPortSecuritySurface.meta("human-1", createdAt: 1, exitCode: 0)]; f.surface.statuses.removeValue(forKey: "human-1"); let rows = await f.call("sessions_list").value["sessions"].elements ?? []; XCTAssertEqual(rows[0]["attention"], .string("done")); XCTAssertEqual(rows[0]["attentionForMs"], .null) }
    func testControlL353() async throws { let f = try rig(), result = await f.call("sessions.list"); XCTAssertTrue(result.ok) }
    func testControlL360() async throws { let f = try rig(); _ = await f.call("projects_list"); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["tool"], .string("projects.list")); assertValue(rows[0]["confirmed"], o([("required", .bool(false)), ("granted", .bool(false)), ("by", .null), ("at", .null), ("reason", .null)])) }
    func testControlL372() async throws { let f = try rig(), result = await f.call("git_status", o([("cwd", .string("/work/api"))])); XCTAssertTrue(result.ok) }
    func testControlL377() async throws { let f = try rig(), result = await f.call("git_status", o([("cwd", .string("/etc"))])); XCTAssertFalse(result.ok); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertTrue(result.error?.contains("projects.list") == true); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["outcome"], .string("refused")) }
    func testControlL387() async throws { let f = try rig(); f.surface.sessions = [BackendDeckCoreTestPortSecuritySurface.meta("x", cwd: "/somewhere/else")]; let result = await f.call("alerts_list", o([("projectPath", .string("/somewhere/else"))])); XCTAssertTrue(result.ok) }
    func testControlL395() async throws {
        let f = try rig(), result = await f.call("sessions_start", o([("cwd", .string("/work/api")), ("provider", .string("claude"))])); XCTAssertTrue(result.ok)
        assertValue(.array(f.surface.starts), .array([o([("cwd", .string("/work/api")), ("cols", .number(120)), ("rows", .number(30)), ("resume", .bool(false)), ("provider", .string("claude")), ("origin", .string("copilot")), ("originRunId", result.row["id"])])]))
        XCTAssertTrue(f.questions.get().isEmpty); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["tier"], .string("act")); XCTAssertEqual(rows[0]["outcome"], .string("ok")); XCTAssertEqual(rows[0]["action"], .string("tool.sessions.start"))
    }
    func testControlL420() async throws {
        let f = try rig(), limits = o([("deniedTools", .array([.string("WebFetch"), .string("WebFetch"), .string("mcp__deck-control")])), ("noSkills", .bool(true))])
        let result = await f.call("sessions_start", o([("cwd", .string("/work/api")), ("provider", .string("claude"))]), .init(sessionLimits: limits)); XCTAssertTrue(result.ok)
        XCTAssertEqual(f.surface.starts[0]["deniedTools"], .array([.string("WebFetch"), .string("mcp__deck-control")])); XCTAssertEqual(f.surface.starts[0]["noSkills"], .bool(true))
        let sent = await f.call("sessions_start", o([("cwd", .string("/work/api")), ("provider", .string("claude")), ("blockTools", .array([.string("Bash")]))])); XCTAssertFalse(sent.ok); XCTAssertEqual(f.surface.starts.count, 1)
        let invalid = await f.call("sessions_start", o([("cwd", .string("/work/api"))]), .init(sessionLimits: o([("deniedTools", .array([.string("Bash(rm *)")]))]))); XCTAssertFalse(invalid.ok); XCTAssertEqual(f.surface.starts.count, 1)
    }
    func testControlL434() async throws { let f = try rig(), result = await start(f, folder: "/tmp/anything"); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertTrue(f.surface.starts.isEmpty) }
    func testControlL442() async throws { let f = try rig(), result = await f.call("sessions_start", o([("cwd", .string("/work/api")), ("provider", .string("gpt"))])); XCTAssertFalse(result.ok); XCTAssertTrue(f.surface.starts.isEmpty) }
    func testControlL448() async throws { let f = try rig(budgets: .init(sessionStarts: .init(limit: 2, windowMilliseconds: 60_000))); _ = await start(f); _ = await start(f, folder: "/work/web"); let third = await start(f, folder: "/work/docs"); XCTAssertEqual(third.refusal, .rateLimited); XCTAssertEqual(f.surface.starts.count, 2) }
    func testControlL465() async throws {
        let f = try rig(), started = await start(f), id = try XCTUnwrap(started.value["session"]["id"].string), result = await f.call("sessions_send", send(id, text: "run the tests"))
        XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.writes.map(\.0), [id, id]); XCTAssertEqual(f.surface.writes.map(\.1), ["run the tests", "\r"]); XCTAssertTrue(f.questions.get().isEmpty)
        let rows = await f.log.tail(); XCTAssertEqual(rows[1]["tier"], .string("act"))
    }
    func testControlL484() async throws {
        let f = try rig(), result = await f.call("sessions_send", send("human-1", text: "rm -rf everything")); XCTAssertFalse(result.ok); XCTAssertEqual(result.refusal, .noApprover); XCTAssertTrue(f.surface.writes.isEmpty)
        let rows = await f.log.tail(); XCTAssertEqual(rows[0]["tier"], .string("alter")); XCTAssertEqual(rows[0]["baseTier"], .string("act")); XCTAssertEqual(rows[0]["confirmed"]["required"], .bool(true)); XCTAssertEqual(rows[0]["confirmed"]["granted"], .bool(false)); XCTAssertEqual(rows[0]["confirmed"]["reason"], .string("no-approver"))
    }
    func testControlL501() async throws { let f = try rig(approval: .allow), result = await f.call("sessions_send", send("human-1", text: "status?")); XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.writes.map(\.0), ["human-1", "human-1"]); XCTAssertEqual(f.surface.writes.map(\.1), ["status?", "\r"]); XCTAssertTrue(f.questions.get()[0].summary.contains("status?")); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["confirmed"]["required"], .bool(true)); XCTAssertEqual(rows[0]["confirmed"]["granted"], .bool(true)); XCTAssertEqual(rows[0]["confirmed"]["by"], .string("window")) }
    func testControlL516() async throws { let f = try rig(approval: .decline), result = await f.call("sessions_send", send("human-1")); XCTAssertEqual(result.refusal, .declined); XCTAssertTrue(f.surface.writes.isEmpty) }
    func testControlL526() async throws { let f = try rig(), started = await start(f), id = try XCTUnwrap(started.value["session"]["id"].string); _ = await f.call("sessions_send", send(id, text: "half a thought").setting("submit", .bool(false))); XCTAssertEqual(f.surface.writes[0].1, "half a thought") }
    func testControlL539() async throws { let f = try rig(), started = await start(f), id = try XCTUnwrap(started.value["session"]["id"].string), result = await f.call("sessions_send", send(id, text: "ok\u{03}")); XCTAssertFalse(result.ok); XCTAssertTrue(f.surface.writes.isEmpty) }
    func testControlL553() async throws { let f = try rig(approval: .allow), result = await f.call("sessions_send", send("human-1", text: "ok\u{1b}]0;pwned\u{07}")); XCTAssertFalse(result.ok); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertTrue(f.surface.writes.isEmpty) }
    func testControlL571() async throws { let f = try rig(approval: .allow); f.surface.sessions = [BackendDeckCoreTestPortSecuritySurface.meta("human-1", exitCode: 1)]; let result = await f.call("sessions_send", send("human-1", text: "hello")); XCTAssertFalse(result.ok); XCTAssertTrue(f.surface.writes.isEmpty) }
    func testControlL580() async throws { let f = try rig(approval: .allow); _ = await f.call("sessions_send", send("human-1", text: "deploy to production")); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["args"]["sessionId"], .string("human-1")); XCTAssertEqual(rows[0]["args"]["text"], .string("deploy to production")); XCTAssertEqual(rows[0]["sessionId"], .string("human-1")); XCTAssertTrue(rows[0]["detail"].string?.contains("allowed by the person") == true) }
    func testControlL593() async throws { let f = try rig(), started = await start(f), id = try XCTUnwrap(started.value["session"]["id"].string); _ = await f.call("sessions_stop", o([("sessionId", .string(id))])); XCTAssertEqual(f.surface.killed, [id]); XCTAssertTrue(f.questions.get().isEmpty) }
    func testControlL604() async throws { let f = try rig(), result = await f.call("sessions_stop", o([("sessionId", .string("human-1"))])); XCTAssertEqual(result.refusal, .noApprover); XCTAssertTrue(f.surface.killed.isEmpty) }
    func testControlL614() async throws {
        let f = try rig(), result = await f.call("settings_write", write); XCTAssertFalse(result.ok); XCTAssertEqual(result.refusal, .noApprover); XCTAssertEqual(f.surface.settings["appearance.density"], .string("comfortable"))
        let rows = await f.log.tail(); XCTAssertEqual(rows[0]["outcome"], .string("refused")); XCTAssertEqual(rows[0]["confirmed"]["required"], .bool(true)); XCTAssertEqual(rows[0]["confirmed"]["granted"], .bool(false)); XCTAssertEqual(rows[0]["confirmed"]["reason"], .string("no-approver"))
    }
    func testControlL640() async throws {
        let f = try BackendDeckCoreTestPortSecurityRig(directory: scratch(), approval: .hold, timeout: 5), args = write, call = Task { await f.call("settings_write", args) }
        await f.clock.scheduled.wait(1); f.clock.advance(5); let result = await call.value; XCTAssertEqual(result.refusal, .timeout); XCTAssertEqual(f.surface.settings["appearance.density"], .string("comfortable"))
    }
    func testControlL657() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", write); XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.settings["appearance.density"], .string("compact")); XCTAssertEqual(f.questions.get()[0].summary, "Change settings: appearance.density to \"compact\"") }
    func testControlL671() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("preferences")), ("patch", o([("theme", .string("light"))]))])); XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.preferences["theme"], .string("light")) }
    func testControlL681() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("preferences")), ("patch", o([("windowBounds", o([("width", .number(1))]))]))])); XCTAssertEqual(result.refusal, .notPermitted) }
    func testControlL703() async throws {
        let f = try rig(approval: .allow), result = await f.call("settings_write", write); XCTAssertTrue(result.ok)
        let trace = f.surface.settingsTrace; XCTAssertLessThan(try XCTUnwrap(trace.firstIndex(of: "snapshot")), try XCTUnwrap(trace.firstIndex(of: "asked"))); XCTAssertLessThan(try XCTUnwrap(trace.firstIndex(of: "asked")), try XCTUnwrap(trace.firstIndex(of: "write"))); XCTAssertEqual(trace.filter { $0 == "write" }.count, 1)
    }
    func testControlL719() async throws { let f = try rig(approval: .allow); _ = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("appearance.terminalFontSize", .number(4000))]))])); XCTAssertEqual(f.questions.get().count, 1); XCTAssertNotNil(f.questions.get()[0].summary.range(of: #"appearance\.terminalFontSize to \d+ \(asked for 4000\)"#, options: .regularExpression)) }
    func testControlL740() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", write); XCTAssertEqual(result.value["snapshot"], .string("/tmp/settings.last-good.json")); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["result"]["snapshot"], .string("/tmp/settings.last-good.json")) }
    func testControlL753() async throws {
        let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("appearance.density", .string("spacious"))]))]))
        XCTAssertFalse(result.ok); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertTrue(f.surface.settingsTrace.isEmpty); XCTAssertTrue(result.error?.contains("comfortable") == true); XCTAssertEqual(f.surface.settings["appearance.density"], .string("comfortable"))
    }
    func testControlL771() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("tools.profile", .string("none"))]))])); XCTAssertFalse(result.ok); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertEqual(f.surface.settings["tools.profile"], .missing) }
    func testControlL783() async throws { let f = try rig(approval: .allow); f.surface.snapshotFails = true; let result = await f.call("settings_write", write); XCTAssertFalse(result.ok); XCTAssertTrue(result.error?.contains("could not save a copy") == true); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertEqual(f.surface.settingsTrace, ["snapshot"]); XCTAssertEqual(f.surface.settings["appearance.density"], .string("comfortable")) }
    func testControlL807() async throws { let f = try rig(approval: .allow); _ = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("remote.enabled", .bool(true))]))])); XCTAssertTrue(f.surface.settingsTrace.isEmpty) }
    func testControlL829() async throws { let f = try rig(), result = await f.call("sessions_list", .object([]), .init(caller: readOnly)); XCTAssertTrue(result.ok) }
    func testControlL835() async throws { let f = try rig(), result = await start(f, caller: readOnly); XCTAssertFalse(result.ok); XCTAssertEqual(result.refusal, .notGranted); XCTAssertTrue(f.surface.starts.isEmpty); XCTAssertTrue(result.error?.contains("do not retry") == true); XCTAssertTrue(result.error?.contains("read access only") == true) }
    func testControlL848() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", write, .init(caller: readOnly)); XCTAssertEqual(result.refusal, .notGranted); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertTrue(f.surface.settingsTrace.isEmpty) }
    func testControlL864() async throws { let f = try rig(), result = await f.call("sessions_list", .object([]), .init(caller: .init(kind: .remote, tiers: [], deviceID: "phone-2"))); XCTAssertEqual(result.refusal, .notGranted); XCTAssertTrue(result.error?.contains("not been given any access to Hoot’s tools") == true) }
    func testControlL883() async throws {
        let f = try rig(approval: .allow), caller = acting, started = await start(f, caller: caller), id = try XCTUnwrap(started.value["session"]["id"].string)
        let own = await f.call("sessions_send", send(id, text: "carry on"), .init(caller: caller)); XCTAssertTrue(own.ok)
        let theirs = await f.call("sessions_send", send("human-1", text: "stop what you are doing"), .init(caller: caller)); XCTAssertEqual(theirs.refusal, .notGranted); XCTAssertEqual(f.surface.writes.map(\.0), [id, id])
    }
    func testControlL909() async throws { let f = try rig(); _ = await f.call("sessions_list", .object([]), .init(caller: readOnly)); _ = await f.call("sessions_list"); let rows = await f.log.tail(); assertValue(rows[0]["caller"], o([("kind", .string("remote")), ("deviceId", .string("phone-1"))])); assertValue(rows[1]["caller"], o([("kind", .string("local"))])) }
    func testControlL921() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", write); XCTAssertTrue(result.ok); XCTAssertEqual(f.questions.get().count, 1); XCTAssertEqual(f.surface.settings["appearance.density"], .string("compact")) }
    func testControlL954() async throws { let f = try rig(), result = await start(f, folder: "/work/web", caller: acting); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertTrue(f.surface.starts.isEmpty); XCTAssertTrue(result.error?.contains("/work/api") == true) }
    func testControlL968() async throws { let f = try rig(), result = await start(f, caller: acting); XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.startedFor.map(\.0), ["phone-1"]); XCTAssertEqual(f.surface.startedFor.map(\.1), ["/work/api"]) }
    func testControlL979() async throws { let f = try rig(), result = await start(f, folder: "/work/web"); XCTAssertTrue(result.ok); XCTAssertEqual(f.surface.startedFor.map(\.0), [nil]); XCTAssertEqual(f.surface.startedFor.map(\.1), ["/work/web"]) }
    func testControlL989() async throws { let f = try rig(), first = await start(f, caller: acting); XCTAssertTrue(first.ok); f.surface.deviceGrants?["phone-1"] = []; let after = await start(f, caller: acting); XCTAssertEqual(after.refusal, .notPermitted); XCTAssertTrue(after.error?.contains("no folders chosen") == true) }
    func testControlL1000() async throws { let f = try rig(); f.surface.deviceGrants = nil; let result = await start(f, caller: acting); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertTrue(f.surface.starts.isEmpty) }
    func testControlL1021() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("remote.enabled", .bool(true))]))])); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertTrue(f.questions.get().isEmpty); XCTAssertEqual(f.surface.settings["remote.enabled"], .missing) }
    func testControlL1044() async throws { let f = try rig(approval: .allow); for key in ["copilot.confirmAlter", "deckControl.token", "security.anything"] { let result = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([(key, .bool(false))]))])); XCTAssertEqual(result.refusal, .notPermitted) }; XCTAssertEqual(f.surface.settings.fields?.map(\.key), ["appearance.density"]) }
    func testControlL1055() async throws { let f = try rig(approval: .allow), result = await f.call("settings_write", o([("scope", .string("settings")), ("patch", o([("appearance.density", .string("compact")), ("advanced.debugMode", .bool(true))]))])); XCTAssertEqual(result.refusal, .notPermitted); XCTAssertEqual(f.surface.settings["appearance.density"], .string("comfortable")) }
    private func conversation(_ count: Int) -> [V] { (0..<count).map { index in o([("id", .string("\(index % 2 == 0 ? "you" : "agent"):m\(index)")), ("role", .string(index % 2 == 0 ? "you" : "agent")), ("at", .number(Double(1000 + index))), ("text", .string("message \(index)")), ("truncated", .bool(false))]) } }
    func testControlL1082() async throws {
        let f = try rig(); f.surface.transcriptSize = Double(154 * 1024 * 1024); f.surface.transcript = conversation(10)
        let value = await f.call("sessions_transcript", o([("sessionId", .string("human-1"))])).value
        XCTAssertEqual(f.surface.transcriptReads[0].1, Double(154 * 1024 * 1024 - 256 * 1024)); XCTAssertGreaterThan(value["fromByte"].number ?? 0, 0); XCTAssertEqual(value["partial"], .bool(true))
    }
    func testControlL1101() async throws { let f = try rig(); f.surface.transcriptSize = 4000; f.surface.transcript = conversation(3); let value = await f.call("sessions_transcript", o([("sessionId", .string("human-1"))])).value; XCTAssertEqual(f.surface.transcriptReads[0].1, 0); XCTAssertEqual(value["partial"], .bool(false)); XCTAssertEqual(value["returned"], .number(3)) }
    func testControlL1115() async throws { let f = try rig(); f.surface.transcriptSize = 10_000; f.surface.transcript = conversation(50); let value = await f.call("sessions_transcript", o([("sessionId", .string("human-1"))])).value; XCTAssertEqual(value["returned"], .number(40)); XCTAssertEqual(value["partial"], .bool(true)); XCTAssertEqual(value["messages"].elements?.last?["text"], .string("message 49")) }
    func testControlL1132() async throws { let f = try rig(); f.surface.transcriptSize = 10_000; f.surface.transcript = (0..<40).map { o([("id", .string("agent:big\($0)")), ("role", .string("agent")), ("at", .number(Double($0))), ("text", .string(String(repeating: "x", count: 50_000))), ("truncated", .bool(false))]) }; let messages = await f.call("sessions_transcript", o([("sessionId", .string("human-1"))])).value["messages"].elements ?? []; XCTAssertLessThanOrEqual(messages.reduce(0) { $0 + ($1["text"].string?.utf16.count ?? 0) }, 65_537); XCTAssertTrue(messages.allSatisfy { $0["truncated"].bool == true }) }
    func testControlL1151() async throws { let f = try rig(); f.surface.transcriptSize = 10_000; f.surface.transcript = conversation(5); _ = await f.call("sessions_transcript", o([("sessionId", .string("human-1"))])); let rows = await f.log.tail(); assertValue(rows[0]["result"], o([("source", .string("chat")), ("fileBytes", .number(10_000)), ("fromByte", .number(0)), ("returned", .number(5)), ("inWindow", .number(5))])); XCTAssertFalse(rows[0].compact.contains("message 0")) }
    func testControlL1170() async throws { let f = try rig(), value = await f.call("sessions_transcript", o([("sessionId", .string("human-2"))])).value; XCTAssertEqual(value["source"], .string("terminal")); XCTAssertTrue(value["screen"].string?.contains("the last screen") == true); XCTAssertEqual(value["messages"], .array([])) }
    func testControlL1187() async throws { let f = try rig(budgets: .init(all: .init(limit: 3, windowMilliseconds: 60_000))); for _ in 0..<3 { _ = await f.call("projects_list") }; let fourth = await f.call("projects_list"), rows = await f.log.tail(); XCTAssertEqual(fourth.refusal, .rateLimited); XCTAssertEqual(rows.count, 4); XCTAssertEqual(rows[3]["outcome"], .string("refused")) }
    func testControlL1201() async throws { let f = try rig(budgets: .init(changes: .init(limit: 1, windowMilliseconds: 60_000))); _ = await start(f); let next = await start(f, folder: "/work/web"), read = await f.call("projects_list"); XCTAssertEqual(next.refusal, .rateLimited); XCTAssertTrue(read.ok) }
    private func tap(_ taps: BackendDeckCoreSecurityTestBox<[String]>) throws -> BackendDeckCoreSecurityToolPolicy {
        .init(tool: try .init(id: "devices.tap", wireName: "devices_tap", description: "Tap a device.", inputSchema: o([("type", .string("object")), ("properties", .object([]))]), tier: .act), spendsDeviceInput: true, summary: { _, _ in "Tap" }, run: { _, _ in taps.edit { $0.append("tap") }; return .init(value: .object([.init("tapped", .bool(true))]), summary: .object([])) })
    }
    func testControlL1231() async throws { let taps = BackendDeckCoreSecurityTestBox<[String]>([]), f = try rig(budgets: .init(changes: .init(limit: 1, windowMilliseconds: 60_000)), extras: [tap(taps)]); for _ in 0..<10 { let result = await f.call("devices_tap"); XCTAssertTrue(result.ok) }; XCTAssertEqual(taps.get().count, 10); let first = await start(f), second = await start(f, folder: "/work/web"); XCTAssertTrue(first.ok); XCTAssertEqual(second.refusal, .rateLimited) }
    func testControlL1244() async throws { let taps = BackendDeckCoreSecurityTestBox<[String]>([]), f = try rig(budgets: .init(deviceInput: .init(limit: 3, windowMilliseconds: 60_000)), extras: [tap(taps)]); for _ in 0..<3 { _ = await f.call("devices_tap") }; let fourth = await f.call("devices_tap"); XCTAssertEqual(fourth.refusal, .rateLimited); XCTAssertTrue(fourth.error?.contains("devices.tree") == true); XCTAssertEqual(taps.get().count, 3); let ordinary = await start(f); XCTAssertTrue(ordinary.ok) }
    func testControlL1259() { let budgets = BackendDeckCoreSecurityBudgets(); XCTAssertEqual(budgets.changes.limit, 30); XCTAssertEqual(budgets.changes.windowMilliseconds, 300_000); XCTAssertEqual(budgets.deviceInput.limit, 300); XCTAssertEqual(budgets.deviceInput.windowMilliseconds, 300_000) }
    func testControlL1266() async throws { let f = try rig(); _ = await f.call("projects_list"); _ = await f.call("git_status", o([("cwd", .string("/etc"))])); _ = await f.call("settings_write", write); _ = await f.call("sessions_get", o([("sessionId", .string("nope"))])); _ = await f.call("not_a_tool"); let rows = await f.log.tail(); XCTAssertEqual(rows.count, 5); XCTAssertEqual(rows.map { $0["outcome"].string }, ["ok", "refused", "refused", "error", "error"]); XCTAssertEqual(rows.map { $0["action"].string }, ["tool.projects.list", "tool.git.status", "tool.settings.write", "tool.sessions.get", "tool.not_a_tool"]) }
    func testControlL1287() async throws { let f = try rig(); _ = await f.call("projects_list"); let rows = await f.log.tail(); XCTAssertNotNil(rows[0]["at"].string?.range(of: #"^\d{4}-\d{2}-\d{2}T"#, options: .regularExpression)); XCTAssertTrue(rows[0]["ms"].number?.isFinite == true) }
    func testControlL1298() async throws { let f = try rig(); _ = await f.call("projects_list"); _ = await f.call("projects_list"); let rows = await f.log.tail(); XCTAssertNotEqual(rows[0]["id"], rows[1]["id"]) }
    func testControlL1318() async throws { let f = try rig(), result = await f.call("log_note", o([("note", .string("session 4 has retried the same migration nine times"))])), rows = await f.log.tail(); XCTAssertTrue(result.ok); XCTAssertEqual(rows.count, 1); XCTAssertTrue(rows[0]["detail"].string?.contains("session 4 has retried the same migration nine times") == true); XCTAssertEqual(rows[0]["outcome"], .string("ok")) }
    func testControlL1331() async throws { let f = try rig(); _ = await f.call("log_note", o([("note", .string("session.started — confinement enforced"))])); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["action"], .string("tool.log.note")); XCTAssertEqual(rows[0]["tool"], .string("log.note")); XCTAssertEqual(rows[0]["tier"], .string("act")); assertValue(rows[0]["caller"], o([("kind", .string("local"))])) }
    func testControlL1353() async throws { let f = try rig(); _ = await f.call("log_note", o([("note", .string("told it to stop")), ("sessionId", .string("human-1"))])); let rows = await f.log.tail(); XCTAssertEqual(rows[0]["sessionId"], .string("human-1")) }
    func testControlL1359() async throws { let f = try rig(), result = await f.call("log_note", o([("note", .string("two\nlines"))])), rows = await f.log.tail(); XCTAssertFalse(result.ok); XCTAssertEqual(rows[0]["action"], .string("tool.log.note")); XCTAssertEqual(rows[0]["outcome"], .string("error")); XCTAssertTrue(rows[0]["error"].string?.contains("single line") == true) }
    func testControlL1373() async throws { let f = try rig(budgets: .init(changes: .init(limit: 2, windowMilliseconds: 60_000))); let one = await f.call("log_note", o([("note", .string("one"))])), two = await f.call("log_note", o([("note", .string("two"))])), three = await f.call("log_note", o([("note", .string("three"))])); XCTAssertTrue(one.ok); XCTAssertTrue(two.ok); XCTAssertFalse(three.ok); XCTAssertEqual(three.refusal, .rateLimited) }
    func testControlL1385() async throws { let f = try rig(), result = await f.call("log_note", o([("note", .string("from somewhere else"))]), .init(caller: readOnly)); XCTAssertFalse(result.ok); XCTAssertEqual(result.refusal, .notGranted) }
    private func renamed(id: String = "hoot.state", aliases: [String] = ["copilot.state", "copilot_state"]) throws -> BackendDeckCoreSecurityToolPolicy {
        .init(tool: try .init(id: id, wireName: id.replacingOccurrences(of: ".", with: "_"), description: "A stand-in for the renamed tool.", inputSchema: o([("type", .string("object")), ("properties", .object([])), ("additionalProperties", .bool(false))]), tier: .read), aliases: aliases, summary: { _, _ in "Read Hoot’s state" }, run: { _, _ in .init(value: .object([.init("running", .bool(true))]), summary: .object([])) })
    }
    func testControlL1418() async throws { let f = try rig(extras: [renamed()]); for old in ["copilot.state", "copilot_state"] { let result = await f.call(old); XCTAssertTrue(result.ok, old); assertValue(result.value, o([("running", .bool(true))])); XCTAssertEqual(result.row["tool"], .string("hoot.state")) } }
    func testControlL1428() async throws { let f = try rig(extras: [renamed()]), names = await f.control.tools().flatMap { [$0.tool.id, $0.tool.wireName] }; XCTAssertTrue(names.contains("hoot_state")); XCTAssertFalse(names.contains("copilot_state")); XCTAssertFalse(names.contains("copilot.state")) }
    func testControlL1436() throws { assertError({ _ = try self.rig(extras: [self.renamed(id: "hoot.other", aliases: ["sessions_list"])]) }, contains: "old name sessions_list is taken") }
}
