import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendDeckToolsMachinesPortDeviceReadTests: XCTestCase {
    typealias V = NativeRPCValue
    private let o = BackendDeckToolsMachinesPortObject
    private let ios = "ios:AAAA-1111"
    private func args(_ fields: [String: V] = [:]) -> V { o(fields).setting("deviceId", .string(ios)) }
    private func metadata() throws -> [V] { try BackendDeckToolsMachinesCatalogue.rows().filter { $0["module"].string == "device-tools" } }
    func testExactlyElevenDeviceToolsKeepSourceTiers() throws {
        let rows = try metadata(), actual = Dictionary(uniqueKeysWithValues: rows.map { ($0["id"].string!, $0["tier"].string!) })
        BackendDeckToolsMachinesPortEqual(actual, ["devices.list": "read", "devices.open": "act", "devices.shutdown": "act", "devices.screenshot": "read", "devices.tap": "act", "devices.swipe": "act", "devices.type": "act", "devices.button": "act", "devices.tree": "read", "devices.find": "read", "devices.annotations": "read"])
    }
    func testOnlyGlassInputSpendsDeviceBudget() async throws {
        let service = BackendDeckToolsMachinesDevices(service: BackendDeckToolsMachinesPortDevices()), context = BackendDeckToolsMachinesPortContext()
        for (id, args) in [("devices.tap", self.args(["x": .number(0.5), "y": .number(0.5)])), ("devices.swipe", self.args(["direction": .string("up")])), ("devices.type", self.args(["text": .string("hello")])), ("devices.button", self.args(["button": .string("home")]))] { let policy = try await service.policy(BackendDeckToolsMachinesPortSpec(id), args, context); BackendDeckToolsMachinesPortEqual(policy.spends, "device-input") }
        for id in ["devices.open", "devices.shutdown"] { let policy = try await service.policy(BackendDeckToolsMachinesPortSpec(id), args(), context); BackendDeckToolsMachinesPortEqual(policy.spends, "changes") }
    }
    func testDeviceWireNamesUseDottedIDWithUnderscores() throws { for row in try metadata() { let id = row["id"].string!, wire = row["wire"].string!; BackendDeckToolsMachinesPortEqual(wire, id.replacingOccurrences(of: ".", with: "_")); XCTAssertNotNil(wire.range(of: #"^[a-zA-Z0-9_-]{1,64}$"#, options: .regularExpression)) } }
    func testEveryDeviceToolStaysBehindDescribeWithUsefulSentence() throws { for row in try metadata() { let index = row["index"].string!; XCTAssertGreaterThan(index.utf16.count, 60); XCTAssertLessThan(index.utf16.count, 200); XCTAssertNotEqual(index, row["title"].string); XCTAssertTrue(index.trimmingCharacters(in: .whitespacesAndNewlines).hasSuffix(".")); XCTAssertFalse(try BackendDeckToolsMachinesPortSpec(row["id"].string!).advertised) } }
    func testCoordinateDescriptionsAllSayFractions() throws { for id in ["devices.list", "devices.tap", "devices.swipe", "devices.tree"] { XCTAssertTrue(try BackendDeckToolsMachinesPortSpec(id).description.contains("fractions of the screen")) } }
    func testDeviceRegistrationDoesNotCollideWithBuiltinCatalogue() async throws {
        let server = BackendNativeMCPServer()
        for entry in try BackendDeckCoreCatalogueLiterals.builtins() { try await server.registerTool(entry.tool) { _, _ in .failure("fixture handler not invoked") } }
        let definitions = try BackendDeckToolsMachinesDevices(service: BackendDeckToolsMachinesPortDevices()).definitions(environment: BackendDeckToolsMachinesPortEnvironment())
        for definition in definitions { try await server.registerTool(definition.spec, handler: definition.handler) }
        let tools = try await server.catalogue(); BackendDeckToolsMachinesPortEqual(tools.filter { $0.id.hasPrefix("devices.") }.count, 11)
    }
    func testDeviceIDRuleEqualsPagePattern() throws {
        let pattern = #"^(ios|android|avd):[A-Za-z0-9._:-]{1,120}$"#, page = try source("src/main/devices/ipc.ts"), native = try source("macos/TerminalDeckNative/Sources/TerminalDeckBackend/BackendDeckToolsMachinesDevices.swift")
        XCTAssertTrue(page.contains("const ID = /" + pattern + "/")); XCTAssertTrue(native.contains(pattern))
    }
    func testButtonsKeysModifiersAgreeWithDevicePage() throws {
        let page = try source("src/main/devices/ipc.ts")
        func values(_ name: String) throws -> [String] {
            let set = try NSRegularExpression(pattern: "const " + name + #" = new Set\(\[([^\]]*)\]"#)
            let found = try XCTUnwrap(set.firstMatch(in: page, range: NSRange(page.startIndex..<page.endIndex, in: page))), range = try XCTUnwrap(Range(found.range(at: 1), in: page)), body = String(page[range]), strings = try NSRegularExpression(pattern: "'([^']+)'")
            return strings.matches(in: body, range: NSRange(body.startIndex..<body.endIndex, in: body)).compactMap { Range($0.range(at: 1), in: body).map { String(body[$0]) } }.sorted()
        }
        BackendDeckToolsMachinesPortEqual(try values("BUTTONS"), BackendDeckToolsMachinesDeviceRules.buttons.sorted()); BackendDeckToolsMachinesPortEqual(try values("KEYS"), BackendDeckToolsMachinesDeviceRules.keys.sorted())
        let modifiers = try BackendDeckToolsMachinesPortSpec("devices.type").inputSchema["properties"]["modifiers"]["items"]["enum"].elements!.compactMap(\.string)
        BackendDeckToolsMachinesPortEqual(try values("MODIFIERS"), modifiers.sorted())
    }
    func testListUsesStateWordsAndCapabilitiesForAllDeviceKinds() async throws {
        let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.list", .object([])), rows = try XCTUnwrap(result.structuredContent?["devices"].elements)
        BackendDeckToolsMachinesPortEqual(rows.map { $0["id"].string! }, [ios, "avd:Pixel_9", "android:R58M123"]); BackendDeckToolsMachinesPortEqual(result.structuredContent?["usable"], .number(1)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(false))
        BackendDeckToolsMachinesPortEqual(rows[0]["name"], .string("iPhone 17 Pro")); BackendDeckToolsMachinesPortEqual(rows[0]["state"], .string("running")); BackendDeckToolsMachinesPortEqual(rows[0]["kind"], .string("simulator")); BackendDeckToolsMachinesPortEqual(rows[0]["text"], .string("unicode")); BackendDeckToolsMachinesPortEqual(rows[1]["state"], .string("off")); BackendDeckToolsMachinesPortEqual(rows[1]["canStart"], .bool(true)); BackendDeckToolsMachinesPortEqual(rows[2]["state"], .string("waiting for you to allow this computer on the phone")); BackendDeckToolsMachinesPortEqual(rows[2]["note"], .string("Unlock the phone and allow this computer when it asks."))
    }
    func testCheckingRowTruthfullySaysItCanStillBeOpened() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(); await fake.inventory([BackendDeckToolsMachinesPortDevices.entry(o(["checking": .bool(true)])), BackendDeckToolsMachinesPortDevices.entry(o(["id": .string("ios:BBBB-2222"), "name": .string("iPhone Air")]))])
        let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.list", .object([])), rows = try XCTUnwrap(result.structuredContent?["devices"].elements)
        BackendDeckToolsMachinesPortEqual(rows[0]["checking"], .bool(true)); BackendDeckToolsMachinesPortEqual(rows[0]["usable"], .bool(true)); XCTAssertTrue(rows[0]["checkingNote"].string?.contains("can still be opened") == true); BackendDeckToolsMachinesPortEqual(rows[1]["checking"], .missing)
    }
    func testEmptyDeviceListNamesWhatToInstall() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.inventory([]); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.list", .object([])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["devices"], .array([])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(true)); XCTAssertTrue(result.structuredContent?["emptyReason"].string?.contains("Xcode") == true); XCTAssertTrue(result.structuredContent?["emptyReason"].string?.contains("Android Studio") == true) }
    func testTreeRowsMatchReadingOrderCompactFieldsAndNoHiddenSubtree() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()), rows = try XCTUnwrap(result.structuredContent?["elements"].elements), calls = await fake.seen("tree")
        BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .string("visible")]]); BackendDeckToolsMachinesPortEqual(result.structuredContent?["source"], .string("accessibility")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["foreground"], o(["app": .string("com.example.Shop"), "screen": .string("")]))
        BackendDeckToolsMachinesPortEqual(rows.count, 6); BackendDeckToolsMachinesPortEqual(rows.map { $0["name"].string }, ["Checkout", "Password", "Pay", "Pay", "Cancel", nil]); BackendDeckToolsMachinesPortEqual(rows.map { $0["depth"].number! }, [0, 0, 0, 1, 0, 0])
        BackendDeckToolsMachinesPortEqual(rows[0]["frame"], o(["x": .number(0.1), "y": .number(0.05), "width": .number(0.8), "height": .number(0.05)])); BackendDeckToolsMachinesPortEqual(rows[0]["centre"], o(["x": .number(0.5), "y": .number(0.075)])); BackendDeckToolsMachinesPortEqual(rows[1]["secret"], .bool(true)); BackendDeckToolsMachinesPortEqual(rows[1]["focused"], .bool(true)); BackendDeckToolsMachinesPortEqual(rows[2]["identifier"], .string("pay-button")); BackendDeckToolsMachinesPortEqual(rows[4]["enabled"], .bool(false)); BackendDeckToolsMachinesPortEqual(rows[5]["centre"], o(["x": .number(0.94), "y": .number(0.075)])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["shown"], .number(6)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["total"], .number(6)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["truncated"], .bool(false)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(false)); XCTAssertFalse(result.structuredContent?.compact.contains("Secret menu") == true); XCTAssertFalse(result.structuredContent?.compact.contains("\"ref\"") == true)
    }
    func testPasswordFieldValueNeverLeavesTree() async throws { let fake = BackendDeckToolsMachinesPortDevices(); var password = DeviceNode(ref: "r", role: "AXTextField", label: "PIN", value: "4821", frame: .init(x: 0.1, y: 0.1, width: 0.5, height: 0.1)); password.valueRedacted = true; await fake.setRoot(password); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()); XCTAssertFalse(result.structuredContent?.compact.contains("4821") == true); BackendDeckToolsMachinesPortEqual(result.structuredContent?["elements"].elements?.first?["secret"], .bool(true)) }
    func testTreeDefaultMaximumAndSmallLimitsReportExactlyWhatWasLeftOut() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(), children = (0..<500).map { DeviceNode(ref: "n\($0)", role: "AXStaticText", label: "Row \($0)", frame: .init(x: 0, y: Double($0) / 500, width: 1, height: 1.0 / 500)) }; await fake.setRoot(DeviceNode(ref: "root", role: "AXApplication", children: children))
        let first = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()), most = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args(["limit": .number(10_000)])), few = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args(["limit": .number(3)]))
        BackendDeckToolsMachinesPortEqual(first.structuredContent?["elements"].elements?.count, 150); BackendDeckToolsMachinesPortEqual(first.structuredContent?["shown"], .number(150)); BackendDeckToolsMachinesPortEqual(first.structuredContent?["total"], .number(500)); BackendDeckToolsMachinesPortEqual(first.structuredContent?["truncated"], .bool(true)); XCTAssertTrue(first.structuredContent?["note"].string?.contains("Showing 150 of 500") == true); BackendDeckToolsMachinesPortEqual(most.structuredContent?["elements"].elements?.count, 400); BackendDeckToolsMachinesPortEqual(few.structuredContent?["elements"].elements?.compactMap { $0["name"].string }, ["Row 0", "Row 1", "Row 2"])
    }
    func testEngineTruncationIsNotHidden() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.treeMeta(truncated: true); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()); BackendDeckToolsMachinesPortEqual(result.structuredContent?["truncated"], .bool(true)); XCTAssertTrue(result.structuredContent?["note"].string?.contains("stopped reading the screen early") == true) }
    func testReactNativeComponentSourceAndRequestedScopeSurvive() async throws { let fake = BackendDeckToolsMachinesPortDevices(); var node = DeviceNode(ref: "r", role: "button", label: "Buy now", testID: "buy", frame: .init(x: 0.1, y: 0.8, width: 0.8, height: 0.1)); node.component = "BuyButton"; node.sourceLocation = .init(file: "src/screens/Product.tsx", line: 42, column: 7); await fake.setRoot(node); await fake.treeMeta(source: "react-native-fiber"); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args(["scope": .string("interactive")])), row = try XCTUnwrap(result.structuredContent?["elements"].elements?.first), calls = await fake.seen("tree"); BackendDeckToolsMachinesPortEqual(result.structuredContent?["source"], .string("react-native-fiber")); BackendDeckToolsMachinesPortEqual(row["name"], .string("Buy now")); BackendDeckToolsMachinesPortEqual(row["identifier"], .string("buy")); BackendDeckToolsMachinesPortEqual(row["component"], .string("BuyButton")); BackendDeckToolsMachinesPortEqual(row["source"], .string("src/screens/Product.tsx:42:7")); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .string("interactive")]]) }
    func testReactNativeFallbackReasonIsPassedThrough() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.treeMeta(fallback: "Metro answered but the app is not connected to it."); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()); XCTAssertTrue(result.structuredContent?["note"].string?.contains("Metro answered but the app is not connected to it.") == true) }
    func testTreeWithNoUsefulRowsSaysWhatToDoInstead() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.setRoot(DeviceNode(ref: "r", role: "AXApplication", frame: .init(x: 0, y: 0, width: 1, height: 1))); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tree", args()); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(true)); XCTAssertTrue(result.structuredContent?["emptyReason"].string?.contains("devices.screenshot") == true) }
    func testFindWholeNameGivesCentreAndDisabledFlag() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.find", args(["name": .string("cancel")])), match = try XCTUnwrap(result.structuredContent?["matches"].elements?.first); BackendDeckToolsMachinesPortEqual(result.structuredContent?["count"], .number(1)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["truncated"], .bool(false)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(false)); BackendDeckToolsMachinesPortEqual(match["role"], .string("button")); BackendDeckToolsMachinesPortEqual(match["name"], .string("Cancel")); BackendDeckToolsMachinesPortEqual(match["enabled"], .bool(false)); BackendDeckToolsMachinesPortEqual(match["centre"], o(["x": .number(0.25), "y": .number(0.93)])) }
    func testFindWholeNamesUnlessPartialRequested() async throws { let fake = BackendDeckToolsMachinesPortDevices(), whole = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.find", args(["name": .string("Check")])), partial = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.find", args(["name": .string("Check"), "partial": .bool(true)])); BackendDeckToolsMachinesPortEqual(whole.structuredContent?["count"], .number(0)); BackendDeckToolsMachinesPortEqual(whole.structuredContent?["empty"], .bool(true)); XCTAssertTrue(whole.structuredContent?["emptyReason"].string?.contains("partial: true") == true); BackendDeckToolsMachinesPortEqual(partial.structuredContent?["count"], .number(1)); BackendDeckToolsMachinesPortEqual(partial.structuredContent?["matches"].elements?.first?["name"], .string("Checkout")) }
    func testPlainRoleFindLeavesHiddenElementsOut() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.find", args(["role": .string("button")])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["matches"].elements?.map { $0["name"].string }, ["Pay", "Cancel", nil]) }
    func testFindWithoutSelectorRefusesBeforeTree() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.find", args()), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("name, an identifier or a role") == true); XCTAssertTrue(calls.isEmpty) }
    func testFindUsesRequestedFullScope() async throws { let fake = BackendDeckToolsMachinesPortDevices(); _ = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.find", args(["name": .string("Pay"), "scope": .string("full")])); let calls = await fake.seen("tree"); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .string("full")]]) }
    func testNoAnnotationRoundsIsHonestlyEmpty() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.annotations", .object([])); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["rounds"], .array([])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["total"], .number(0)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(true)); XCTAssertTrue(result.structuredContent?["emptyReason"].string?.contains("nobody has annotated anything since the app started") == true) }
    func testNewestRoundKeepsOneNotePictureAndEachNumberedMarker() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.store([BackendDeckToolsMachinesPortRound("newest", "device"), BackendDeckToolsMachinesPortRound("older", "browser")]); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.annotations", .object([])), rows = try XCTUnwrap(result.structuredContent?["rounds"].elements), row = try XCTUnwrap(rows.first), markers = try XCTUnwrap(row["markers"].elements); BackendDeckToolsMachinesPortEqual(result.structuredContent?["total"], .number(2)); BackendDeckToolsMachinesPortEqual(rows.count, 1); BackendDeckToolsMachinesPortEqual(row["id"], .string("newest")); BackendDeckToolsMachinesPortEqual(row["where"]["deviceId"], .string(ios)); BackendDeckToolsMachinesPortEqual(row["picture"]["path"], .string("/Users/someone/Pictures/App/newest-annotated.png")); BackendDeckToolsMachinesPortEqual(row["sentTo"], .null); BackendDeckToolsMachinesPortEqual(row["note"], .string("Make #1 green and put #2 on the left.")); BackendDeckToolsMachinesPortEqual(markers[0]["n"], .number(1)); BackendDeckToolsMachinesPortEqual(markers[0]["described"], .string("button \"Pay\" (id pay-button)")); BackendDeckToolsMachinesPortEqual(markers[1]["n"], .number(2)); BackendDeckToolsMachinesPortEqual(markers[1]["described"], .string("blank space")); XCTAssertTrue(markers.allSatisfy { $0["note"] == .missing }) }
    func testAnnotationKindFilterExplainsOtherKindWhenEmpty() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.store([BackendDeckToolsMachinesPortRound("d1", "device"), BackendDeckToolsMachinesPortRound("b1", "browser"), BackendDeckToolsMachinesPortRound("d2", "device")]); let browser = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.annotations", o(["kind": .string("browser"), "count": .number(5)])); BackendDeckToolsMachinesPortEqual(browser.structuredContent?["rounds"].elements?.compactMap { $0["id"].string }, ["b1"]); await fake.store([BackendDeckToolsMachinesPortRound("d1", "device")]); let none = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.annotations", o(["kind": .string("browser")])); BackendDeckToolsMachinesPortEqual(none.structuredContent?["empty"], .bool(true)); XCTAssertTrue(none.structuredContent?["emptyReason"].string?.contains("1 round on device screens") == true) }
    func testAnnotationsNeverReturnMoreThanTen() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.store((0..<15).map { BackendDeckToolsMachinesPortRound("r\($0)", "device") }); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.annotations", o(["count": .number(50)])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["rounds"].elements?.count, 10) }
    private func source(_ relative: String) throws -> String { var root = URL(fileURLWithPath: #filePath); for _ in 0..<5 { root.deleteLastPathComponent() }; return try String(contentsOf: root.appendingPathComponent(relative), encoding: .utf8) }
}
