import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendDeckToolsMachinesPortDeviceInteractionTests: XCTestCase {
    typealias V = NativeRPCValue
    private let o = BackendDeckToolsMachinesPortObject
    private let ios = "ios:AAAA-1111"
    private func args(_ fields: [String: V] = [:]) -> V { o(fields).setting("deviceId", .string(ios)) }
    private func engineCases() -> [(String, V)] { [("devices.open", args()), ("devices.shutdown", args()), ("devices.screenshot", args()), ("devices.tap", args(["x": .number(0.5), "y": .number(0.5)])), ("devices.swipe", args(["direction": .string("up")])), ("devices.type", args(["text": .string("hello")])), ("devices.button", args(["button": .string("home")])), ("devices.tree", args()), ("devices.find", args(["name": .string("Pay")]))] }
    func testAllNineEngineToolsRefuseWithOwnReasonBeforeCalls() async throws {
        for (id, args) in engineCases() { let fake = BackendDeckToolsMachinesPortDevices(); await fake.configure(reason: "Simulators need a Mac with Apple silicon."); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, id, args), calls = await fake.names(); XCTAssertTrue(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["refusal"], .string("not-permitted")); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Simulators need a Mac with Apple silicon.") == true); XCTAssertTrue(result.structuredContent?["error"].string?.contains("do not retry") == true); XCTAssertTrue(calls.isEmpty) }
    }
    func testUnavailableListAnswersEmptyWithWhyInsteadOfRefusing() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(); await fake.configure(reason: "Simulators need a Mac with Apple silicon."); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.list", .object([])), calls = await fake.names()
        XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["available"], .bool(false)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["devices"], .array([])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(true)); XCTAssertTrue(result.structuredContent?["emptyReason"].string?.contains("Simulators need a Mac with Apple silicon.") == true); XCTAssertTrue(calls.isEmpty)
    }
    func testAnnotationsStillReadWithoutEngine() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.configure(reason: "Simulators need a Mac with Apple silicon."); await fake.store([BackendDeckToolsMachinesPortRound("r1", "browser")]); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.annotations", .object([])); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["rounds"].elements?.count, 1) }
    func testAllNineEngineToolsRejectBadIDBeforeEffects() async throws { for (id, args) in engineCases() { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, id, args.setting("deviceId", .string("iPhone 17; rm -rf ~"))), calls = await fake.names(); XCTAssertTrue(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["refusal"], .string("not-permitted")); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Call devices.list first") == true); XCTAssertTrue(calls.isEmpty) } }
    func testMissingIDIsNamedBySchema() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.tap", o(["x": .number(0.5), "y": .number(0.5)])); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("deviceId is required") == true) }
    func testRunningSimulatorOpensWithoutBoot() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.open", args()), calls = await fake.names(); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["id"], .string(ios)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["started"], .bool(false)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["device"]["name"], .string("iPhone 17 Pro")); BackendDeckToolsMachinesPortEqual(calls, ["list", "open"]) }
    func testOffEmulatorBootsAndReturnsNewRunningID() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.open", args().setting("deviceId", .string("avd:Pixel_9"))), names = await fake.names(), boot = await fake.seen("boot"), open = await fake.seen("open")
        XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["id"], .string("android:emulator-5554")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["started"], .bool(true)); XCTAssertTrue(result.structuredContent?["note"].string?.contains("Use that id for every call from here on") == true); BackendDeckToolsMachinesPortEqual(names, ["list", "boot", "open"]); BackendDeckToolsMachinesPortEqual(boot, [[.string("avd:Pixel_9")]]); BackendDeckToolsMachinesPortEqual(open, [[.string("android:emulator-5554")]])
    }
    func testGoneDeviceReportsCurrentIDsWithoutOpening() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.open", args().setting("deviceId", .string("ios:GONE"))), names = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Call devices.list") == true); BackendDeckToolsMachinesPortEqual(names, ["list"]) }
    func testUnauthorizedPhoneSaysHowToAllowComputer() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.open", args().setting("deviceId", .string("android:R58M123"))); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Unlock the phone") == true) }
    func testBootFailureStaysFaultWithPlatformSentence() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.setBoot(o(["ok": .bool(false), "message": .string("The emulator did not start.")])); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.open", args().setting("deviceId", .string("avd:Pixel_9"))), names = await fake.names(); XCTAssertTrue(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["refusal"], .null); BackendDeckToolsMachinesPortEqual(result.structuredContent?["error"], .string("The emulator did not start.")); XCTAssertFalse(names.contains("open")) }
    func testShutdownSimulatorHasRealResultAndOneEffect() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.shutdown", args()), calls = await fake.seen("shutDown"); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["id"], .string(ios)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["shutDown"], .bool(true)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(false)); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios)]]) }
    func testCablePhoneShutdownNeverReachesEngine() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.shutdown", args().setting("deviceId", .string("android:R58M123"))), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("turned off on the phone itself") == true); XCTAssertTrue(calls.isEmpty) }
    func testRunningAndroidEmulatorShutsDownByRunningID() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.shutdown", args().setting("deviceId", .string("android:emulator-5554"))), names = await fake.names(); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(names, ["shutDown"]) }
    func testOffEmulatorShutdownIsHonestlyEmpty() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.shutdown", args().setting("deviceId", .string("avd:Pixel_9"))), names = await fake.names(); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["alreadyOff"], .bool(true)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["empty"], .bool(true)); XCTAssertTrue(names.isEmpty) }
    func testShutdownFailureIsFaultWithOwnSentence() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.setShut(o(["ok": .bool(false), "message": .string("The simulator would not shut down.")])); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.shutdown", args()); XCTAssertTrue(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["error"], .string("The simulator would not shut down.")) }
    func testScreenshotReturnsOnlyPathAndPixelSize() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.screenshot", args()); BackendDeckToolsMachinesPortEqual(result.structuredContent, o(["deviceId": .string(ios), "path": .string("/Users/someone/Pictures/App/iPhone-17-Pro-20261003-142233.png"), "width": .number(1_206), "height": .number(2_622)])) }
    func testElsewhereSessionPictureRefusalPointsToDeviceTree() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.screenshot", args(), context: BackendDeckToolsMachinesPortContext(.session, session: "s1", machine: "server-1")), calls = await fake.names(); XCTAssertTrue(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["refusal"], .string("not-permitted")); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Use devices.tree") == true); XCTAssertFalse(result.structuredContent?["error"].string?.contains("browser.read") == true); XCTAssertTrue(calls.isEmpty) }
    func testRemoteCallerPictureIsSavedWithHonestPathNote() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.screenshot", args(), context: BackendDeckToolsMachinesPortContext(.remote)); XCTAssertFalse(result.isError); XCTAssertTrue(result.structuredContent?["note"].string?.contains("not a file you can open") == true) }
    func testTapAtPointUsesFractionsExactly() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["x": .number(0.25), "y": .number(0.75)])), calls = await fake.seen("tap"); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["tapped"], o(["x": .number(0.25), "y": .number(0.75)])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["longPress"], .bool(false)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"], .null); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .number(0.25), .number(0.75), .missing]]) }
    func testPixelsAreRefusedBeforeTap() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["x": .number(540), "y": .number(0.5)])), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("looks like pixels") == true); XCTAssertTrue(calls.isEmpty) }
    func testHalfPositionIsRefusedBeforeTap() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["x": .number(0.5)])), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("both x and y") == true); XCTAssertTrue(calls.isEmpty) }
    func testPointAndNameTogetherAreRefusedBeforeTap() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["x": .number(0.5), "y": .number(0.5), "name": .string("Pay")])), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("not both") == true); XCTAssertTrue(calls.isEmpty) }
    func testTapWithoutTargetExplainsHowToNameIt() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.tap", args()); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Say where to tap") == true) }
    func testLongPressCapsHoldAndSaysLongPress() async throws { let fake = BackendDeckToolsMachinesPortDevices(), env = BackendDeckToolsMachinesPortEnvironment(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["x": .number(0.5), "y": .number(0.5), "holdMs": .number(60_000)]), environment: env), calls = await fake.seen("tap"), log = await env.log(); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["longPress"], .bool(true)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["holdMs"], .number(5_000)); BackendDeckToolsMachinesPortEqual(calls.first?.last, .number(5_000)); XCTAssertTrue(log.contains("Long-press")) }
    func testNamedTapReadsFreshTreeThenOneCentreAndSecretMarker() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["identifier": .string("password-field")])), names = await fake.names(), calls = await fake.seen("tap"); BackendDeckToolsMachinesPortEqual(names, ["tree", "tap"]); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .number(0.5), .number(0.23), .missing]]); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["role"], .string("text field")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["name"], .string("Password")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["identifier"], .string("password-field")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["secret"], .bool(true)) }
    func testButtonAndInnerLabelAreOnePlaceWithButtonNamed() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.tap", args(["name": .string("pay")])); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(result.structuredContent?["tapped"], o(["x": .number(0.5), "y": .number(0.84)])); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["role"], .string("button")); BackendDeckToolsMachinesPortEqual(result.structuredContent?["element"]["identifier"], .string("pay-button")) }
    func testAmbiguousTapListsOnlyFiveCandidatesAndTapsNothing() async throws {
        let fake = BackendDeckToolsMachinesPortDevices(), buttons = (0..<8).map { DeviceNode(ref: "b\($0)", role: "AXButton", label: "Delete", identifier: "delete-\($0)", frame: .init(x: 0.8, y: 0.1 * Double($0), width: 0.15, height: 0.05)) }; await fake.setRoot(DeviceNode(ref: "root", role: "AXApplication", children: buttons))
        let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["name": .string("Delete")])), message = result.structuredContent?["error"].string ?? "", calls = await fake.names()
        XCTAssertTrue(result.isError); XCTAssertTrue(message.contains("8 different elements")); XCTAssertTrue(message.contains("Nothing was tapped")); XCTAssertTrue(message.contains("delete-0")); XCTAssertTrue(message.contains("delete-4")); XCTAssertFalse(message.contains("delete-5")); XCTAssertTrue(message.contains("at x 0.875, y 0.025")); BackendDeckToolsMachinesPortEqual(calls, ["tree"])
    }
    func testNoMatchOffersNearMissAndTapsNothing() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["name": .string("Canc")])), calls = await fake.names(), message = result.structuredContent?["error"].string ?? ""; XCTAssertTrue(result.isError); XCTAssertTrue(message.contains("Nothing on the screen matches")); XCTAssertTrue(message.contains("Close: button \"Cancel\"")); BackendDeckToolsMachinesPortEqual(calls, ["tree"]) }
    func testHiddenSheetExactNameIsNeverTapped() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.tap", args(["name": .string("Secret menu")])), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("hidden or scrolled away") == true); BackendDeckToolsMachinesPortEqual(calls, ["tree"]) }
    func testDirectionPathsAllFourStayQuarterInsideEdges() {
        let r = BackendDeckToolsMachinesDeviceRules.self
        for (direction, values) in [("up", [0.5, 0.75, 0.5, 0.25]), ("down", [0.5, 0.25, 0.5, 0.75]), ("left", [0.75, 0.5, 0.25, 0.5]), ("right", [0.25, 0.5, 0.75, 0.5])] { let path = r.directionPath(direction); BackendDeckToolsMachinesPortEqual(path.from, o(["x": .number(values[0]), "y": .number(values[1])])); BackendDeckToolsMachinesPortEqual(path.to, o(["x": .number(values[2]), "y": .number(values[3])])) }
    }
    func testSwipeDirectionUsesPathDefaultDurationAndReadableSentence() async throws { let fake = BackendDeckToolsMachinesPortDevices(), env = BackendDeckToolsMachinesPortEnvironment(); _ = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.swipe", args(["direction": .string("up")]), environment: env); let calls = await fake.seen("swipe"), log = await env.log(); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), o(["x": .number(0.5), "y": .number(0.75)]), o(["x": .number(0.5), "y": .number(0.25)]), .number(300)]]); XCTAssertTrue(log.contains("Swipe up")) }
    func testSwipeExplicitPointsClampDurationInsideSourceBounds() async throws { let fake = BackendDeckToolsMachinesPortDevices(), from = o(["x": .number(0.1), "y": .number(0.5)]), to = o(["x": .number(0.9), "y": .number(0.5)]); _ = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.swipe", args(["from": from, "to": to, "durationMs": .number(10)])); let calls = await fake.seen("swipe"); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), from, to, .number(50)]]) }
    func testDirectionAndPointsAreRefusedTogether() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.swipe", args(["direction": .string("up"), "from": o(["x": .number(0.1), "y": .number(0.5)]), "to": o(["x": .number(0.9), "y": .number(0.5)])])), calls = await fake.names(); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("not both") == true); XCTAssertTrue(calls.isEmpty) }
    func testSwipeNeedsBothEndsAndRejectsPixelPoint() async throws { let fake = BackendDeckToolsMachinesPortDevices(), half = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.swipe", args(["from": o(["x": .number(0.1), "y": .number(0.5)])])), pixels = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.swipe", args(["from": o(["x": .number(100), "y": .number(0.5)]), "to": o(["x": .number(0.9), "y": .number(0.5)])])); XCTAssertTrue(half.structuredContent?["error"].string?.contains("Say how to swipe") == true); XCTAssertTrue(pixels.structuredContent?["error"].string?.contains("from.x") == true) }
    func testTextIsTypedBeforeReturnKey() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.type", args(["text": .string("hello"), "key": .string("return")])), names = await fake.names(), typed = await fake.seen("type"), keys = await fake.seen("key"); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(names, ["open", "type", "key"]); BackendDeckToolsMachinesPortEqual(typed, [[.string(ios), .string("hello")]]); BackendDeckToolsMachinesPortEqual(keys, [[.string(ios), .string("return"), .array([])]]); BackendDeckToolsMachinesPortEqual(result.structuredContent?["typedCharacters"], .number(5)); BackendDeckToolsMachinesPortEqual(result.structuredContent?["pressed"], .string("return")) }
    func testPasswordTextIsSentButOnlyLengthReachesActionLog() async throws { let fake = BackendDeckToolsMachinesPortDevices(), env = BackendDeckToolsMachinesPortEnvironment(), sentinel = "correct-horse-battery-staple-7731"; _ = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.type", args(["text": .string(sentinel)]), environment: env); let sent = await fake.seen("type"), log = await env.log(); BackendDeckToolsMachinesPortEqual(sent, [[.string(ios), .string(sentinel)]]); XCTAssertFalse(log.contains(sentinel)); XCTAssertTrue(log.contains("[\(sentinel.utf16.count) characters]")) }
    func testPasswordTextNeverAppearsInSentenceOrResult() async throws { let env = BackendDeckToolsMachinesPortEnvironment(), sentinel = "correct-horse-battery-staple-7731", result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.type", args(["text": .string(sentinel)]), environment: env), log = await env.log(); XCTAssertFalse(result.structuredContent?.compact.contains(sentinel) == true); XCTAssertFalse(log.contains(sentinel)); XCTAssertTrue(log.contains("\(sentinel.utf16.count) characters")) }
    func testModifiersNeedKeyAndEmptyTypingIsRefusedWithoutEffects() async throws { let fake = BackendDeckToolsMachinesPortDevices(), mods = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.type", args(["text": .string("a"), "modifiers": .array([.string("command")])])), nothing = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.type", args()), calls = await fake.names(); XCTAssertTrue(mods.structuredContent?["error"].string?.contains("need a key") == true); XCTAssertTrue(nothing.structuredContent?["error"].string?.contains("text to type, a key to press") == true); XCTAssertTrue(calls.isEmpty) }
    func testUnknownKeyIsRejectedBySchema() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.type", args(["key": .string("f13")])); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("key must be one of") == true) }
    func testTypingOverTwoThousandSaysSendInParts() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.type", args(["text": .string(String(repeating: "x", count: 2_001))])); XCTAssertTrue(result.structuredContent?["error"].string?.contains("Send it in parts") == true) }
    func testASCIIUnsupportedTextAndUnsupportedKeyTypeNothing() async throws {
        let ascii = BackendDeckToolsMachinesPortDevices(); await ascii.detail("text", .string("ascii")); let accented = try await BackendDeckToolsMachinesPortDeviceCall(ascii, "devices.type", args(["text": .string("café")])), asciiCalls = await ascii.names(); XCTAssertTrue(accented.structuredContent?["error"].string?.contains("plain ASCII") == true); BackendDeckToolsMachinesPortEqual(asciiCalls, ["open"])
        let none = BackendDeckToolsMachinesPortDevices(); await none.detail("text", .string("none")); let typed = try await BackendDeckToolsMachinesPortDeviceCall(none, "devices.type", args(["text": .string("hi")])); XCTAssertTrue(typed.structuredContent?["error"].string?.contains("does not accept typed text") == true)
        let keys = BackendDeckToolsMachinesPortDevices(), escape = try await BackendDeckToolsMachinesPortDeviceCall(keys, "devices.type", args(["key": .string("escape")])), keyCalls = await keys.names(); XCTAssertTrue(escape.structuredContent?["error"].string?.contains("It takes: return, delete, tab") == true); BackendDeckToolsMachinesPortEqual(keyCalls, ["open"])
    }
    func testSupportedHardwareButtonIsActuallyPressed() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.button", args(["button": .string("home")])), names = await fake.names(), calls = await fake.seen("button"); BackendDeckToolsMachinesPortEqual(result.structuredContent?["pressed"], .string("home")); BackendDeckToolsMachinesPortEqual(names, ["open", "button"]); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .string("home")]]) }
    func testMissingHardwareButtonRefusesWithoutPress() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.button", args(["button": .string("back")])), calls = await fake.names(); XCTAssertTrue(result.structuredContent?["error"].string?.contains("has no back button") == true); XCTAssertTrue(result.structuredContent?["error"].string?.contains("It has: home, lock") == true); BackendDeckToolsMachinesPortEqual(calls, ["open"]) }
    func testUnknownDeviceButtonCapabilitiesDoNotInventRefusal() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.detail("buttons", .array([])); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.button", args(["button": .string("back")])), calls = await fake.names(); XCTAssertFalse(result.isError); BackendDeckToolsMachinesPortEqual(calls, ["open", "button"]) }
    func testUnknownButtonRejectedBySchema() async throws { let result = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.button", args(["button": .string("power")])); XCTAssertTrue(result.isError); XCTAssertTrue(result.structuredContent?["error"].string?.contains("button must be one of") == true) }
    func testRotationReturnsRequestedOrientation() async throws { let fake = BackendDeckToolsMachinesPortDevices(), result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.button", args(["rotate": .string("landscape-right")])), calls = await fake.seen("rotate"); BackendDeckToolsMachinesPortEqual(result.structuredContent?["orientation"], .string("landscape-right")); BackendDeckToolsMachinesPortEqual(calls, [[.string(ios), .string("landscape-right")]]) }
    func testNonrotatingDeviceIsLeftAsItIs() async throws { let fake = BackendDeckToolsMachinesPortDevices(); await fake.detail("canRotate", .bool(false)); let result = try await BackendDeckToolsMachinesPortDeviceCall(fake, "devices.button", args(["rotate": .string("portrait")])), calls = await fake.names(); XCTAssertTrue(result.structuredContent?["error"].string?.contains("does not turn") == true); BackendDeckToolsMachinesPortEqual(calls, ["open"]) }
    func testButtonAndRotationNeedExactlyOneChoice() async throws { let both = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.button", args(["button": .string("home"), "rotate": .string("portrait")])), neither = try await BackendDeckToolsMachinesPortDeviceCall(.init(), "devices.button", args()); XCTAssertTrue(both.structuredContent?["error"].string?.contains("not both") == true); XCTAssertTrue(neither.structuredContent?["error"].string?.contains("Give a button") == true) }
}
