import Foundation
import Testing
@testable import TerminalDeckBackend

@Suite("host.test.ts individual case parity")
struct BackendServersHostPortTests {
    private var good: BackendServersHostRoom { BackendServersHostPortFixtures.good }
    private var running: BackendServersHostOnServer { BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.running).host }
    @Test("reads a bare rented server the way it actually answered") func h210Bare() { let look = BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.bare), r = look.room; #expect(look.host.command == "" && r.node == "v18.19.1" && r.npm == ""); #expect(r.missingTools == ["make", "gcc", "g++"]); #expect(r.downloader == "curl" && r.canHash && r.canUnpack && r.systemdUser && r.homeFreeKb == 33_209_852) }
    @Test("believes the host when it says it is not running") func h229Stopped() { #expect(BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.stopped).host.running == .no) }
    @Test("believes it when it says it is") func h233Running() { #expect(running.running == .yes && running.version == "0.9.1" && running.unit == "active" && running.linger); #expect(running.status.contains("fingerprint    A3PL-DGAB-3N6W-RK3Y-V4VS-MMHP")) }
    @Test("says it does not know when there is a command and no answer") func h248Unknown() { #expect(BackendServersHostRules.readHostProbe("command\t/home/me/.local/bin/terminaldeck\n").host.running == .unknown) }
    @Test("reports no unit at all rather than an inactive one") func h259NoUnit() { #expect(BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.bare).host.unit == ""); #expect(BackendServersHostScripts.probe.contains(".config/systemd/user/terminaldeck.service")) }
    @Test("refuses a machine with no compiler, and names the packages") func h268Compiler() { let why = BackendServersHostRules.whyNotHost(BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.bare).room); #expect(why != nil && why?.contains("make, gcc, g++") == true && why?.contains("apt-get install -y make gcc g++") == true) }
    @Test("refuses musl, because Node publishes no build for it") func h275Musl() { var r = good; r.libc = "musl"; let why = BackendServersHostRules.whyNotHost(r); #expect(why?.contains("musl") == true && why?.contains("apk add") == true) }
    @Test("refuses a machine with no Node and nothing to fetch one with") func h281NoRuntimeFetcher() { var r = good; r.node = ""; r.npm = ""; r.downloader = ""; #expect(BackendServersHostRules.whyNotHost(r)?.contains("curl or wget") == true) }
    @Test("refuses a machine with no room, and says how much it has") func h286Disk() { var r = good; r.homeFreeKb = 50 * 1024; #expect(BackendServersHostRules.whyNotHost(r)?.contains("50 MB free") == true) }
    @Test("refuses Windows rather than pretending") func h291RemoteUnsupportedOS() { var r = good; r.os = "mingw64_nt"; #expect(BackendServersHostRules.whyNotHost(r)?.contains("Linux and macOS") == true) }
    @Test("allows a machine with no Node that can fetch one") func h301CanFetchRuntime() { var r = good; r.node = "v18.19.1"; r.npm = ""; #expect(BackendServersHostRules.whyNotHost(r) == nil) }
    @Test("allows a machine that already has a good Node") func h305GoodRuntime() { #expect(BackendServersHostRules.whyNotHost(good) == nil) }
    @Test("counts Node and npm as one question") func h309RuntimeAndNpm() { for (node, npm, wanted) in [("v22.23.2", "/usr/bin/npm", true), ("v22.23.2", "", false), ("v18.19.1", "/usr/bin/npm", false), ("", "/usr/bin/npm", false)] { var r = good; r.node = node; r.npm = npm; #expect(BackendServersHostRules.usableNode(r) == wanted) } }
    @Test("says what the install will do about Node, both ways") func h320RuntimeConsequence() { #expect(BackendServersHostRules.hostConsequence("box", room: good).contains("uses the Node v22")); var r = good; r.node = "v18.19.1"; r.npm = ""; #expect(BackendServersHostRules.hostConsequence("box", room: r).contains("checked against the checksum")) }
    @Test("does not tell him nothing can run a session on a server he has been using") func h327ExistingSSH() { var h = running; h.command = ""; let line = BackendServersHostRules.hostLine(h); #expect(!line.contains("Nothing on this server") && line.lowercased().contains("ssh")); let said = BackendServersHostRules.hostConsequence("box", room: good); #expect(said.contains("SSH shell this app holds open") && said.contains("keep running") && said.contains("Hoot is not on it")) }
    @Test("never claims a host is running when it would not say") func h348UnknownLine() { #expect(BackendServersHostRules.hostLine(.init(command: "/home/me/.local/bin/x", version: "0.9.1")).contains("would not say")) }
    @Test("says whether it will still be there tomorrow") func h357RestartPersistence() { var h = running; h.unit = ""; #expect(BackendServersHostRules.reachLine(h)?.contains("will not come back") == true); h = running; h.linger = false; #expect(BackendServersHostRules.reachLine(h)?.contains("enable-linger") == true); #expect(BackendServersHostRules.reachLine(running)?.contains("keeps running when you log out") == true); h.command = ""; #expect(BackendServersHostRules.reachLine(h) == nil) }
    @Test("says what removing it leaves, differently for each answer") func h365DataConsequence() { #expect(BackendServersHostRules.removeConsequence(running, alsoData: false).contains("What it stored stays")); #expect(BackendServersHostRules.removeConsequence(running, alsoData: false).contains(running.dataDir)); #expect(BackendServersHostRules.removeConsequence(running, alsoData: true).contains("will need pairing again")) }
    @Test("starts the daemon and not the command-line tool") func h381ServiceDaemon() { let s = BackendServersHostScripts.service("/home/me/.local/bin/terminaldeck"); for part in ["ExecStart=$host", #"host="$rt/bin/terminaldeck-host""#, #"host="$bin/terminaldeck-host""#, "grep -q terminaldeck-launcher"] { #expect(s.contains(part)) } }
    @Test("asks for lingering without sudo, and reads the answer back") func h389Linger() { let s = BackendServersHostScripts.service("/home/me/.local/bin/terminaldeck"); #expect(!s.contains("sudo")); #expect(s.contains("loginctl enable-linger")); #expect(s.contains(#"printf "linger %s\n""#)) }
    @Test("leaves the data folder alone unless it was asked for") func h396KeepData() { #expect(!BackendServersHostScripts.remove("/home/me/.local/bin/terminaldeck", dataDir: "/home/me/.local/share/terminaldeck", alsoData: false).contains(".local/share/terminaldeck")); #expect(BackendServersHostScripts.remove("/home/me/.local/bin/terminaldeck", dataDir: "/home/me/.local/share/terminaldeck", alsoData: true).contains(#"rm -rf "$dd""#)) }
    @Test("refuses to remove anything outside the account’s own home") func h403HomeGuards() { let s = BackendServersHostScripts.remove("/usr/bin/terminaldeck", dataDir: "/var/lib/terminaldeck", alsoData: true); #expect(s.contains(#"case "$b" in "$HOME"/*) ;; *) echo "not ours to remove" >&2; exit 1 ;; esac"#)); #expect(s.contains(#"case "$dd" in "$HOME"/*)"#)) }
    @Test("quotes a home directory with a space in it") func h409QuotedHome() { #expect(BackendServersHostScripts.remove("/home/my name/.local/bin/terminaldeck", dataDir: "/x", alsoData: false).contains("b='/home/my name/.local/bin/terminaldeck'")) }
    @Test("reports every step, in order, and ends linked to this computer") func h630InstallSteps() async { let f = BackendServersHostPortBox(), h = BackendServersHosts(f.dependencies); let result = await f.install(h); #expect(f.states.values.map(\.step) == [.checking, .uploading, .installing, .service, .pairing, .pairing, .done]); #expect(f.states.values.map(\.line).contains("Approved. Waiting for this computer to reach it.")); #expect(result.line.contains("linked to this computer") && result.done.count == 5); #expect(result.done[1].contains("Copied the package to") && result.done[3].contains("keeps running when you log out") && result.done[4].contains("linked to this computer as office-pc")) }
    @Test("waits for the channel to come up before saying it is linked") func h666ExactMachineWait() async { var o = BackendServersHostPortOptions(); o.reaches = true; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .done && r.line == "It is running, and linked to this computer." && r.detail == ""); #expect(f.waited.values == [BackendServersHostPortFixtures.machine]) }
    @Test("says the channel never came up rather than claiming a link") func h684NoChannel() async { var o = BackendServersHostPortOptions(); o.reaches = false; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .done && r.line.contains("has not reached it yet") && r.detail.contains("Link this computer")); #expect(r.done.contains { $0.contains("approved as your own device") }) }
    @Test("never puts the code it spends on any state a window can read") func h704NoSpentCodeBroadcast() async { let f = BackendServersHostPortBox(); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.code == nil && f.states.values.allSatisfy { $0.code == nil }); #expect(f.redeemed.values == ["904021"]) }
    @Test("refuses the approval when the host shows a fingerprint that is not ours") func h719Mismatch() async { var o = BackendServersHostPortOptions(); o.hostShows = BackendServersHostPortFixtures.other; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && r.line.contains("Something other than this computer") && r.detail.contains(BackendServersHostPortFixtures.other)); #expect(f.shell.writes.contains("n\n") && !f.shell.writes.contains("y\n")) }
    @Test("reports a host that will not approve, rather than claiming it linked") func h729RefusedApproval() async { var o = BackendServersHostPortOptions(); o.approves = false; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && r.line.contains("did not approve")) }
    @Test("says which of the two things went wrong when nothing answered the code") func h742UnansweredPublishedCode() async { var o = BackendServersHostPortOptions(); o.answers = [.refused("Nothing answered for that code at the relay.")]; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && r.detail.contains("Nothing answered for that code") && r.detail.contains("connected to the relay")); #expect(f.shell.writes.contains("\u{03}")) }
    @Test("names the relay when that is what is missing") func h753NoRelay() async { var o = BackendServersHostPortOptions(); o.after = BackendServersHostPortFixtures.offRelay; o.answers = [.refused("Nothing answered for that code at the relay.")]; let f = BackendServersHostPortBox(o); #expect(await f.install(BackendServersHosts(f.dependencies)).detail.contains("nothing at the relay to answer")) }
    @Test("waits for the host to reach the relay before asking it for a code") func h771RelayReadinessEvent() async { let entered = BackendServersSetupPortSignal(), ready = BackendServersSetupPortSignal(); var o = BackendServersHostPortOptions(); o.beforeProbe = { at in if at == 1 { entered.send(); await ready.wait() } }; let f = BackendServersHostPortBox(o); let h = BackendServersHosts(f.dependencies); let operation = Task { await f.install(h) }; await entered.wait(); #expect(f.redeemed.values.isEmpty && !f.shell.writes.contains { $0.contains("pair --kind") }); ready.send(); let r = await operation.value; #expect(r.step == .done && r.line.contains("linked to this computer") && f.redeemed.values == ["904021"]) }
    @Test("asks for a code anyway when the relay never comes up") func h784RelayCourtesyCeiling() async { var o = BackendServersHostPortOptions(); o.after = BackendServersHostPortFixtures.offRelay; o.codes = ["904021", "111111", "222222"]; o.answers = [.refused("Nothing answered for that code at the relay.")]; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(f.redeemed.values == o.codes && r.detail.contains("nothing at the relay to answer")) }
    @Test("mints another code when the first one is not answered, and links on it") func h809FreshRetry() async { var o = BackendServersHostPortOptions(); o.codes = ["904021", "551180"]; o.answers = [.refused("Nothing answered for that code at the relay."), .linked(machineId: BackendServersHostPortFixtures.machine, machineName: "office-pc", deviceFingerprint: BackendServersHostPortFixtures.ours)]; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .done && r.line.contains("linked to this computer")); #expect(f.redeemed.values == o.codes && f.shell.writes.contains("\u{03}")) }
    @Test("gives up after three codes and names the press that tries again") func h834ThreeTries() async { var o = BackendServersHostPortOptions(); o.codes = ["904021", "551180", "773301"]; o.answers = [.refused("Nothing answered for that code at the relay.")]; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && f.redeemed.values == o.codes && r.line.contains("could not be linked to this computer") && r.detail.contains("3 times") && r.detail.contains("Link this computer")); #expect(r.done.contains { $0.contains("Installed") }) }
    @Test("does not retry a host that answered, only one that did not") func h857AnsweredIsFinal() async { var o = BackendServersHostPortOptions(); o.hostShows = BackendServersHostPortFixtures.other; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && f.redeemed.values.count == 1) }
    @Test("shows the code instead when this build cannot redeem one") func h869MissingMachineAdapter() async { var o = BackendServersHostPortOptions(); o.canLink = false; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .done && r.code == "904021" && f.redeemed.values.isEmpty) }
    @Test("copies the installer before the package") func h878UploadOrder() async { let f = BackendServersHostPortBox(); _ = await f.install(BackendServersHosts(f.dependencies)); #expect(f.puts.values.map { $0.components(separatedBy: "|").last! } == ["install.sh", "terminaldeck-0.9.1.tgz"]) }
    @Test("hands the installer the tarball it just copied, and quotes the folder") func h884CopiedReceipt() async { let f = BackendServersHostPortBox(); _ = await f.install(BackendServersHosts(f.dependencies)); let line = f.shell.writes.first { $0.contains("install.sh") } ?? ""; #expect(line.contains("TERMINALDECK_PACKAGE='/home/me/Terminal Deck/terminaldeck-0.9.1.tgz'") && line.contains("sh '/home/me/Terminal Deck/install.sh'")) }
    @Test("refuses a machine that cannot take it, and copies nothing") func h897RefuseBeforeUpload() async { let f = BackendServersHostPortBox(); let r = await f.install(BackendServersHosts(f.dependencies), look: BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.bare)); #expect(r.step == .failed && r.line.contains("make, gcc, g++") && f.puts.values.isEmpty && f.shell.writes.isEmpty) }
    @Test("refuses when this build carries no package, and copies nothing") func h907MissingPackage() async { var o = BackendServersHostPortOptions(); o.carriesPackage = false; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && f.puts.values.isEmpty) }
    @Test("refuses when the install finished and left no command behind") func h914NoInstalledCommand() async { var o = BackendServersHostPortOptions(); o.after = BackendServersHostPortFixtures.bare; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && r.line.contains("no terminaldeck command")) }
    @Test("says the install failed rather than going on to pair with nothing") func h921InstallerFailure() async { var o = BackendServersHostPortOptions(); o.installExit = 1; let f = BackendServersHostPortBox(o); let r = await f.install(BackendServersHosts(f.dependencies)); #expect(r.step == .failed && r.detail.contains("ended with 1") && !f.shell.writes.contains { $0.contains("pair") }) }
    @Test("starts it directly when there is no systemd, and says what that costs") func h934DirectStart() async { let f = BackendServersHostPortBox(); var look = BackendServersHostPortFixtures.goodLook; look.room.systemdUser = false; let r = await f.install(BackendServersHosts(f.dependencies), look: look); #expect(r.done[3].contains("will not come back on its own after a reboot")); #expect(f.scripts.values.contains { $0.contains("nohup") }) }
    @Test("stops what it started with the key the person would press") func h951CtrlCOnly() async { var o = BackendServersHostPortOptions(); o.holdInstall = true; let f = BackendServersHostPortBox(o), h = BackendServersHosts(f.dependencies); let op = Task { await f.install(h) }; await f.shell.writesChanged.wait(); await h.cancel("s1"); _ = await op.value; #expect(f.shell.writes.allSatisfy { $0 == "\u{03}" || $0.hasSuffix("\n") }); #expect(f.shell.writes.contains("\u{03}")) }
    @Test("says it was stopped, rather than sitting on the ceiling") func h968ImmediateStopOutcome() async { var o = BackendServersHostPortOptions(); o.holdInstall = true; let f = BackendServersHostPortBox(o), h = BackendServersHosts(f.dependencies); let op = Task { await f.install(h) }; await f.shell.writesChanged.wait(); await h.cancel("s1"); let r = await op.value; #expect(r.step == .failed && r.line.contains("Stopped before")) }
    @Test("reads the code out of the terminal exactly as it was printed") func h986PhoneCode() async { let f = BackendServersHostPortBox(); let r = await BackendServersHosts(f.dependencies).pairDevice("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck"); #expect(r.code == "904021" && f.shell.writes[0] == "'/home/me/.local/bin/terminaldeck' pair --kind mine\n") }
    @Test("never answers the fingerprint question, and never redeems the code itself") func h1002HumanPhoneApproval() async { let f = BackendServersHostPortBox(); _ = await BackendServersHosts(f.dependencies).pairDevice("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck"); #expect(!f.shell.writes.contains { $0.trimmingCharacters(in: .whitespacesAndNewlines) == "y" } && f.redeemed.values.isEmpty) }
    @Test("spends the code itself and shows nobody anything") func h1018AutomaticCode() async { let f = BackendServersHostPortBox(); let r = await BackendServersHosts(f.dependencies).link("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck"); #expect(r.step == .done && r.code == nil && f.redeemed.values == ["904021"]); #expect(f.shell.writes.first == "'/home/me/.local/bin/terminaldeck' pair --kind mine\n" && f.shell.writes.contains("y\n")) }
    @Test("says it was stopped, rather than blaming the server for going quiet") func h1037CodeWaitCancelled() async { var o = BackendServersHostPortOptions(); o.holdCode = true; let f = BackendServersHostPortBox(o), h = BackendServersHosts(f.dependencies); let op = Task { await h.link("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck") }; await f.shell.writesChanged.wait(); await h.cancel("s1"); let r = await op.value; #expect(r.step == .failed && r.line.contains("Stopped before") && f.redeemed.values.isEmpty) }
    @Test("answers a Stop pressed while the code is being redeemed") func h1058RedeemCancelled() async { let entered = BackendServersSetupPortSignal(), release = BackendServersSetupPortSignal(); var o = BackendServersHostPortOptions(); o.whileRedeeming = { entered.send(); await release.wait() }; let f = BackendServersHostPortBox(o), h = BackendServersHosts(f.dependencies); let op = Task { await h.link("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck") }; await entered.wait(); await h.cancel("s1"); release.send(); let r = await op.value; #expect(r.step == .failed && r.line.contains("Stopped while linking") && r.detail.contains("nothing approved it")) }
    @Test("can only ever act on the terminal it was handed") func h1076OnlyBorrowedShell() async { let f = BackendServersHostPortBox(); _ = await BackendServersHosts(f.dependencies).link("s1", shell: f.shell, command: "/home/me/.local/bin/terminaldeck"); #expect(!f.shell.writes.isEmpty && f.redeemed.values == ["904021"]) }
    private func address() throws -> String { try #require(BackendSharedServerAddresses.format(url: "wss://relay.terminaldeck.dev", hostId: BackendServersHostPortFixtures.machine, hostKey: BackendSharedServerAddresses.toBase64Url(Data(repeating: 7, count: 32)))) }
    private func withAddress(_ address: String) -> String { BackendServersHostPortFixtures.running.replacingOccurrences(of: "  fingerprint    A3PL-DGAB-3N6W-RK3Y-V4VS-MMHP\n", with: "  fingerprint    A3PL-DGAB-3N6W-RK3Y-V4VS-MMHP\n\nServer address\n  \(address)\n") }
    @Test("reads the token a host prints under its own heading") func h1109AddressHeading() throws { let token = try address(), look = BackendServersHostRules.readHostProbe(withAddress(token)); #expect(BackendServersHostRules.serverAddressOf(look.host.status) == token && look.host.address == token) }
    @Test("answers nothing for a host too old to print one") func h1115OldHostAddress() { #expect(BackendServersHostRules.serverAddressOf(running.status) == "" && running.address == "") }
    @Test("answers nothing when the host says it has none") func h1122NoAddress() { #expect(BackendServersHostRules.serverAddressOf("Server address\n  none — This host is not dialling out to a relay.") == "") }
    @Test("refuses a line that is not a usable address rather than passing it on") func h1127TruncatedAddress() throws { let token = try address(), text = withAddress(token).replacingOccurrences(of: token, with: String(token.dropLast(6))); #expect(BackendServersHostRules.serverAddressOf(BackendServersHostRules.readHostProbe(text).host.status) == "") }
    @Test("reads only its own block, never a token loose in the output") func h1134NoLooseAddress() throws { #expect(BackendServersHostRules.serverAddressOf("Some session printed \(try address()) once.") == ""); #expect(BackendServersHostRules.serverAddressOf("") == "") }
    @Test("reads the relay block a host prints, in each of its shapes") func h1141RelayStates() { #expect(BackendServersHostRules.relayState(running.status) == .connected); #expect(BackendServersHostRules.relayState(BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.offRelay).host.status) == .notConnected); #expect(BackendServersHostRules.relayState("Relay\n  off — this host is not dialling out.") == .off); #expect(BackendServersHostRules.relayState("Terminal Deck host 0.9.1 — running, idle") == .unknown) }
    @Test("reads the host id, which is what joins a server to a machine row") func h1150HostID() { #expect(BackendServersHostRules.hostIdOf(running.status) == BackendServersHostPortFixtures.machine); #expect(BackendServersHostRules.hostIdOf(BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.offRelay).host.status) == "") }
    @Test("reads how many clients that host says are connected to it") func h1162ChannelCount() { #expect(BackendServersHostRules.channelsOf(running.status + "\n  channels       0") == 0); #expect(BackendServersHostRules.channelsOf("Relay\n  connected      wss://x\n  channels       3") == 3) }
    @Test("says it does not know rather than zero when there is no channel line") func h1172UnknownChannels() { for text in [BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.offRelay).host.status, "Relay\n  off — this host is not dialling out.", ""] { #expect(BackendServersHostRules.channelsOf(text) == nil) } }
    @Test("says what it left behind, in the answer that was given") func h1180RemovalReceipts() async { let f = BackendServersHostPortBox(), h = BackendServersHosts(f.dependencies); let kept = await h.uninstall("s1", look: running, alsoData: false), wiped = await h.uninstall("s1", look: running, alsoData: true); #expect(kept.step == .idle && kept.done[1].contains("was left alone") && wiped.done[1].contains("will need pairing again")) }
    @Test("refuses when there is nothing of ours there") func h1193NothingToRemove() async { let f = BackendServersHostPortBox(); let r = await BackendServersHosts(f.dependencies).uninstall("s1", look: BackendServersHostRules.readHostProbe(BackendServersHostPortFixtures.bare).host, alsoData: false); #expect(r.step == .failed && !f.scripts.values.contains { $0.contains("rm -rf") }) }
}
