import Foundation
import Testing
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

@Suite("window-belong.test.ts case parity with fake processes")
struct BackendServersWindowPortBelongTests {
    private func input(dir: String = "/tmp/td-drive-abcdef", curl: String = "/fake/curl", port: Int = 40405,
                       session: String = "server-1 shell-9", token: String = "abcdef0123456789", hooks: Bool = true,
                       pages: [String: String]? = nil, openers: [String: String] = [:]) -> BackendServersWindowBelongInput {
        .init(dir: dir, curl: curl, port: port, sessionId: session, token: token, openers: openers, pages: pages, hooks: hooks)
    }
    @Test("reads the flag out of it rather than out of a version number") func b134SettingsHelp() {
        #expect(BackendServersWindowBelong.honoursSettings("  --settings <file-or-json>   Path to a settings JSON file")); #expect(!BackendServersWindowBelong.honoursSettings("Usage: claude\n  --model <model>\n"))
    }
    @Test("is not fooled by the neighbouring flag that is not this one") func b139NeighbourFlag() { #expect(!BackendServersWindowBelong.honoursSettings("  --setting-sources <sources>  user, project, local\n")) }
    @Test("takes the shapes that actually turn up and refuses the rest") func b148SafeInterpolation() { for good in ["/usr/bin/curl", "server-1 shell-9", "/tmp/td-drive-abcdef"] { #expect(BackendServersWindowBelong.plainEnough(good)) }; for bad in ["", "/usr/bin/o'clock", "/usr/bin/$(id)", "/usr/bin/`id`", "/a\\b", "/a\nb"] { #expect(!BackendServersWindowBelong.plainEnough(bad)) } }
    @Test("writes nothing at all rather than something half-quoted") func b157AllOrNothing() { for value in [input(curl: "/usr/bin/o'clock"), input(session: "$(rm -rf /)"), input(token: "not hex"), input(port: 0), input(dir: "relative/path")] { #expect(BackendServersWindowBelong.files(value).isEmpty) } }
    @Test("goes in a curl config and never on a command line") func b173TokenOnlyInConfig() { let files = BackendServersWindowBelong.files(input()); #expect(files.filter { $0.body.contains("abcdef0123456789") }.map(\.path) == [BackendServersWindowBelong.hookConfigFile]); #expect(BackendServersWindowBelong.hookConfig("abcdef0123456789").contains("header = \"x-terminaldeck-token: abcdef0123456789\"")) }
    @Test("installs the three events that are answered, and nothing else") func b187OnlyContextHooks() throws { let parsed = try NativeRPCValue.parseJSON(Data(BackendServersWindowBelong.settingsFile("/tmp/td-drive-abcdef").utf8)); #expect(parsed.fields?.map(\.key) == ["hooks"]); #expect(parsed["hooks"].fields?.map(\.key).sorted() == BackendServersWindowBelong.events.sorted()); for event in BackendServersWindowBelong.events { let entry = try #require(parsed["hooks"][event].elements?.first?["hooks"].elements?.first); #expect(entry["command"].string == "/tmp/td-drive-abcdef/\(BackendServersWindowBelong.posterFile) \(event) \(BackendServersWindowBelong.marker)"); #expect(entry["timeout"].number == 5) } }
    @Test("tags every entry as ours") func b203HookMarkers() { #expect(BackendServersWindowBelong.settingsFile("/tmp/td-drive-abcdef").components(separatedBy: BackendServersWindowBelong.marker).count - 1 == BackendServersWindowBelong.events.count) }
    @Test("is not written at all for a claude that cannot be given it") func b211NoUnsupportedSettings() { let paths = BackendServersWindowBelong.files(input(hooks: false)).map(\.path); #expect(!paths.contains(BackendServersWindowBelong.settingsFileName) && !paths.contains(BackendServersWindowBelong.posterFile)); for name in BackendServersWindowBelong.openerNames { #expect(paths.contains("bin/" + name)) } }
    @Test("posts the event, keeps the answer, and drains the pipe") func b222PosterPreservesBody() throws { let reply = try BackendServersWindowPortProcess.poster(BackendServersWindowBelong.posterScript(input()), event: "SessionStart", body: #"{"session_id":"x"}"#, curlReply: #"{"ok":1}"#); #expect(reply.status == 0 && reply.out == #"{"ok":1}"# && reply.stdin == #"{"session_id":"x"}"#); #expect(reply.argv.contains("http://127.0.0.1:40405/hook/claude/SessionStart")); #expect(reply.argv.contains("x-terminaldeck-session: server-1 shell-9")); #expect(reply.argv.contains("/tmp/td-drive-abcdef/hook.conf")) }
    @Test("is silent and successful when nothing answers") func b242PosterSilence() throws { let reply = try BackendServersWindowPortProcess.poster(BackendServersWindowBelong.posterScript(input()), event: "PostToolUse", body: "{}", curlReply: "", curlStatus: 7); #expect(reply.status == 0 && reply.out == "") }
    @Test("refuses a word it was not given by the settings file") func b254InvalidHookEvent() throws { let reply = try BackendServersWindowPortProcess.poster(BackendServersWindowBelong.posterScript(input()), event: "../../etc/passwd", body: "{}", curlReply: "unsafe"); #expect(reply.status == 0 && reply.argv.isEmpty) }
    @Test("lands a URL in the app and prints which window") func b271TabRoute() throws { let script = BackendServersWindowBelong.openerScript("open", real: "/fake/real-opener", input: input()); let reply = try BackendServersWindowPortProcess.opener(script, name: "open", args: ["https://example.com/a?b=1"], curlReply: "tab\nOpened in B1.\n", realExists: true); #expect(reply.status == 0 && reply.out == "Opened in B1.\n" && !reply.out.contains("REAL")); #expect(reply.stdin == "https://example.com/a?b=1" && reply.argv.contains("http://127.0.0.1:40405/open")) }
    @Test("falls through to this server and says so, rather than dropping the link") func b286RealFallback() throws { let script = BackendServersWindowBelong.openerScript("open", real: "/fake/real-opener", input: input()); let reply = try BackendServersWindowPortProcess.opener(script, name: "open", args: ["https://example.com/"], curlReply: "", curlStatus: 7, realExists: true); #expect(reply.out.contains("opening it on this server instead") && reply.out.contains("REAL") && reply.status == 0) }
    @Test("hands everything that is not one http(s) URL straight to the real opener") func b299RealArgvUntouched() throws { let script = BackendServersWindowBelong.openerScript("open", real: "/fake/real-opener", input: input()); for args in [[], ["."], ["-a", "Xcode", "f.swift"], ["report.pdf"], ["mailto:a@b.c"]] { let reply = try BackendServersWindowPortProcess.opener(script, name: "open", args: args, curlReply: "tab\nOpened in B1.\n", realExists: true); #expect(reply.out.components(separatedBy: "\n").first == "REAL"); #expect(Array(reply.out.components(separatedBy: "\n").dropFirst()).filter { !$0.isEmpty } == args); #expect(reply.argv.isEmpty) } }
    @Test("says what the shell would have said when the name never existed here") func b312MissingRealOpener() throws { let reply = try BackendServersWindowPortProcess.opener(BackendServersWindowBelong.openerScript("open", real: "", input: input()), name: "open", args: ["."], curlReply: "", realExists: false); #expect(reply.err.trimmingCharacters(in: .whitespacesAndNewlines) == "open: not found" && reply.status == 127) }
    @Test("never exits 0 having opened nothing") func b324NoFalseSuccess() throws { let reply = try BackendServersWindowPortProcess.opener(BackendServersWindowBelong.openerScript("open", real: "", input: input()), name: "open", args: ["https://example.com/"], curlReply: "", curlStatus: 7, realExists: false); #expect(reply.status == 127 && reply.out.contains("opening it on this server instead")) }
    @Test("never looks its own opener up on the PATH it is first on") func b336NoRecursiveLookup() { let script = BackendServersWindowBelong.openerScript("open", real: "/usr/bin/xdg-open", input: input()); #expect(script.contains("REAL='/usr/bin/xdg-open'") && !script.contains("command -v")) }
    @Test("is written for every opener name, each falling back to its own") func b347AllOpeners() { let files = BackendServersWindowBelong.files(input(openers: ["open": "", "xdg-open": "/usr/bin/xdg-open"])); for name in BackendServersWindowBelong.openerNames { let file = files.first { $0.path == "bin/" + name }; #expect(file?.executable == true && file?.body.contains(name + ": not found") == true) }; #expect(files.first { $0.path == "bin/xdg-open" }?.body.contains("REAL='/usr/bin/xdg-open'") == true); #expect(files.first { $0.path == "bin/open" }?.body.contains("REAL=''") == true) }
    @Test("rides along when there are hooks to read them, and not otherwise") func b367DocumentsWithHooks() { let pages = ["INDEX.md": "# index", "browser-windows.md": "# windows"]; let with = BackendServersWindowBelong.files(input(pages: pages)).map(\.path); #expect(with.contains("context/INDEX.md") && with.contains("context/browser-windows.md")); #expect(!BackendServersWindowBelong.files(input(hooks: false, pages: pages)).contains { $0.path.hasPrefix("context/") }) }
    @Test("is spelled once") func b383SettingsFlag() { #expect(BackendServersWindowBelong.settingsFlag == "--settings") }
}
