import Foundation
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

actor BackendDeckToolsAppPortCommunityFake: BackendDeckToolsAppCommunityService, BackendDeckToolsAppToolsStoreService {
    private typealias F = BackendDeckCoreTestPortToolsFixture
    private var trace: [NativeRPCValue] = []
    func calls() -> [NativeRPCValue] { trace }
    func view() async throws -> NativeRPCValue {
        let search = try F.json(#"{"id":"acme/search-mcp","publisher":"Acme","handle":"acme","kind":"mcp","name":"Search","summary":"Search the web from your agent","version":"1.0.0","licence":"MIT","tags":["web"],"agents":["claude"],"tier":3,"needs":["node"],"missing":[],"cost":"free","repo":"https://github.com/acme/search","network":["api.acme.test"],"state":"available","installedVersion":"","message":"","lands":["~/.claude.json"],"variables":["ACME_KEY"],"trigger":""}"#)
        let notes = search.setting("id", .string("bob/notes")).setting("kind", .string("skill")).setting("name", .string("Notes")).setting("summary", .string("Keep notes")).setting("tags", .array([])).setting("tier", .number(1)).setting("variables", .array([]))
        return F.object([("from", .string("store")), ("at", .string("")), ("stale", .string("")), ("problem", .string("")), ("items", .array([search, notes])), ("agents", .array([]))])
    }
    func install(_ id: String, choice: NativeRPCValue) async throws -> NativeRPCValue { trace.append(F.object([("op", .string("communityInstall")), ("id", .string(id)), ("choice", choice)])); return try F.json(#"{"ok":true,"message":"Installed."}"#) }
    func remove(_ id: String) async throws -> NativeRPCValue { trace.append(F.object([("op", .string("communityRemove")), ("id", .string(id))])); return try F.json(#"{"ok":true,"message":"Removed."}"#) }
    func list(_ caller: BackendMCPCallContext) async throws -> NativeRPCValue { try F.json(#"{"view":{"tools":[{"id":"listings","name":"Listings","summary":"Reads property listings","licence":"MIT","version":"1","origins":["example.com"],"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","state":"available","installedVersion":"","message":"","reads":[]}]},"orphans":[]}"#) }
    func install(_ id: String, caller: BackendMCPCallContext) async throws -> NativeRPCValue { trace.append(F.object([("op", .string("toolsInstall")), ("id", .string(id))])); return try F.json(#"{"ok":true,"message":"Installed."}"#) }
    func remove(_ id: String, caller: BackendMCPCallContext) async throws -> NativeRPCValue { trace.append(F.object([("op", .string("toolsRemove")), ("id", .string(id))])); return try F.json(#"{"ok":true,"message":"Removed."}"#) }
}
@MainActor
final class BackendDeckToolsAppPortCommunityTests: XCTestCase {
    private typealias F = BackendDeckCoreTestPortToolsFixture
    private func community(_ fake: BackendDeckToolsAppPortCommunityFake, audit: BackendDeckCoreTestPortToolsAudit = .init(), caller: BackendDeckToolsAppCaller = .init(kind: .local)) throws -> [BackendDeckToolsDefinition] { try BackendDeckToolsAppCommunity.definitions(service: fake, access: F.access(audit, identity: caller)) }
    private func store(_ fake: BackendDeckToolsAppPortCommunityFake, audit: BackendDeckCoreTestPortToolsAudit = .init()) throws -> [BackendDeckToolsDefinition] { try BackendDeckToolsAppToolsStore.definitions(service: fake, access: F.access(audit)) }
    func testRowsSayWhatEachItemRunsInPlainWords() async throws { let value = try F.value(await F.call(community(.init()), "store.community")), items = value["items"].elements!; XCTAssertEqual(items.first { $0["item"].string == "acme/search-mcp" }?["whatItRuns"], .string("Runs a program on this machine")); XCTAssertEqual(items.first { $0["item"].string == "bob/notes" }?["whatItRuns"], .string("Text only — nothing runs")) }
    func testDescriptionAndConfirmationNameStrangerWorkAndTier() async throws { let fake = BackendDeckToolsAppPortCommunityFake(), audit = BackendDeckCoreTestPortToolsAudit(), definitions = try community(fake, audit: audit); XCTAssertTrue(definitions[0].spec.description.contains("Installing runs someone else’s work on this Mac")); _ = try await F.call(definitions, "store.community"); _ = try await F.call(definitions, "store.community", #"{"action":"install","item":"acme/search-mcp"}"#); let consent = await audit.consent(), sentence = consent.last!["sentence"].string!; XCTAssertTrue(sentence.contains("runs someone else's work on this Mac")); XCTAssertTrue(sentence.contains("Runs a program on this machine")) }
    func testCommunityListReadAndBothWritesAlter() async throws { let fake = BackendDeckToolsAppPortCommunityFake(), audit = BackendDeckCoreTestPortToolsAudit(), definitions = try community(fake, audit: audit); _ = try await F.call(definitions, "store.community"); _ = try await F.call(definitions, "store.community", #"{"action":"install","item":"x"}"#); _ = try await F.call(definitions, "store.community", #"{"action":"remove","item":"x"}"#); let consent = await audit.consent(); XCTAssertEqual(consent.map { $0["tier"] }, [.string("read"), .string("alter"), .string("alter")]) }
    func testCommunityValuesUseExactLengthRedaction() throws { let args = try F.json(#"{"action":"install","item":"x","values":{"ACME_KEY":"sk-live-1234567890"}}"#), hidden = BackendDeckToolsAppKit.redacted("store.community", args); XCTAssertFalse(hidden.compact.contains("sk-live")); XCTAssertEqual(hidden["values"]["ACME_KEY"], .string("[18 characters]")) }
    func testCommunityInstallerReceivesExactChoices() async throws { let fake = BackendDeckToolsAppPortCommunityFake(); _ = try await F.call(community(fake), "store.community", #"{"action":"install","item":"acme/search-mcp","agents":["claude"],"values":{"ACME_KEY":"k"}}"#); let calls = await fake.calls(), first = calls[0]; XCTAssertEqual(first["id"], .string("acme/search-mcp")); XCTAssertEqual(first["choice"]["agents"], .array([.string("claude")])); XCTAssertEqual(first["choice"]["values"]["ACME_KEY"], .string("k")); XCTAssertEqual(first["choice"].fields!.map(\.key).sorted(), ["agents", "values"]) }
    func testCommunityShelfFiltersKindAndWords() async throws { let definitions = try community(.init()), skills = try F.value(await F.call(definitions, "store.community", #"{"kind":"skill"}"#)), web = try F.value(await F.call(definitions, "store.community", #"{"query":"web"}"#)); XCTAssertEqual(skills["items"].elements!.count, 1); XCTAssertEqual(web["items"].elements!.map { $0["item"] }, [.string("acme/search-mcp")]) }
    func testOrdinarySessionCannotManageCommunityStore() async throws { F.error(try await F.call(community(.init(), caller: .init(kind: .session, sessionID: "s1")), "store.community"), contains: "reaches only the windows attached to it") }
    func testToolsStoreListsHostsAndPinnedDigest() async throws { let value = try F.value(await F.call(store(.init()), "browser.store")), first = value["tools"].elements![0]; XCTAssertEqual(first["tool"], .string("listings")); XCTAssertEqual(first["runsOn"], .array([.string("example.com")])); XCTAssertEqual(first["sha256"], .string(String(repeating: "a", count: 64))) }
    func testToolsStoreWritesAlterAndUnknownToolIsRefused() async throws { let audit = BackendDeckCoreTestPortToolsAudit(), definitions = try store(.init(), audit: audit); _ = try await F.call(definitions, "browser.store", #"{"action":"install","tool":"listings"}"#); _ = try await F.call(definitions, "browser.store", #"{"action":"remove","tool":"listings"}"#); F.error(try await F.call(definitions, "browser.store", #"{"action":"install","tool":"nope"}"#), contains: "has no tool nope"); let consent = await audit.consent(); XCTAssertEqual(consent.map { $0["tier"] }, [.string("alter"), .string("alter")]) }
    func testToolsStoreInstallerAndNextToolMatchPanel() async throws { let fake = BackendDeckToolsAppPortCommunityFake(), value = try F.value(await F.call(store(fake), "browser.store", #"{"action":"install","tool":"listings"}"#)), calls = await fake.calls(); XCTAssertEqual(calls[0]["op"], .string("toolsInstall")); XCTAssertEqual(calls[0]["id"], .string("listings")); XCTAssertTrue(value["next"].string!.contains("browser.extract")) }
}
