import Foundation
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendMacAppSetupRedactionTests: XCTestCase {
    private func gone(_ output: String, _ secret: String) { XCTAssertFalse(output.contains(secret)); XCTAssertTrue(output.contains("[redacted]")) }
    func testRemovesAnthropicLog() { let token = "sk-ant-a" + "pi03-Zx8" + "kQm2LpR7" + "vNw4TgH1" + "sYbF6dJc" + "E0aUiOx9" + "PlKmQnR3" + "tVzWyXs"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesAnthropicJSON() { let token = "sk-ant-a" + "pi03-Zx8" + "kQm2LpR7" + "vNw4TgH1" + "sYbF6dJc" + "E0aUiOx9" + "PlKmQnR3" + "tVzWyXs"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesAnthropicShell() { let token = "sk-ant-a" + "pi03-Zx8" + "kQm2LpR7" + "vNw4TgH1" + "sYbF6dJc" + "E0aUiOx9" + "PlKmQnR3" + "tVzWyXs"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesOpenaiLog() { let token = "sk-proj-" + "7HgTn2Qp" + "LxV8mZcR" + "4yBwK1sD" + "6fJaE9uN" + "oI0PlM3t" + "XvYbCqWr"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesOpenaiJSON() { let token = "sk-proj-" + "7HgTn2Qp" + "LxV8mZcR" + "4yBwK1sD" + "6fJaE9uN" + "oI0PlM3t" + "XvYbCqWr"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesOpenaiShell() { let token = "sk-proj-" + "7HgTn2Qp" + "LxV8mZcR" + "4yBwK1sD" + "6fJaE9uN" + "oI0PlM3t" + "XvYbCqWr"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesOpenaiLegacyLog() { let token = "sk-T3Blb" + "kFJ9mQx2" + "vLpR8nZw" + "K4tYgH6s" + "B1dCeF0a" + "UiOx7Pl"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesOpenaiLegacyJSON() { let token = "sk-T3Blb" + "kFJ9mQx2" + "vLpR8nZw" + "K4tYgH6s" + "B1dCeF0a" + "UiOx7Pl"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesOpenaiLegacyShell() { let token = "sk-T3Blb" + "kFJ9mQx2" + "vLpR8nZw" + "K4tYgH6s" + "B1dCeF0a" + "UiOx7Pl"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGithubClassicLog() { let token = "ghp_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGithubClassicJSON() { let token = "ghp_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGithubClassicShell() { let token = "ghp_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGithubOauthLog() { let token = "gho_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a" + "ZZ"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGithubOauthJSON() { let token = "gho_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a" + "ZZ"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGithubOauthShell() { let token = "gho_16C7" + "e42F292c" + "6912E771" + "0c838347" + "Ae178B4a" + "ZZ"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGithubFineGrainedLog() { let token = "github_p" + "at_11ABC" + "DEFG0aBc" + "DeFgHiJk" + "L_MnOpQr" + "StUvWxYz" + "01234567" + "89AbCdEf"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGithubFineGrainedJSON() { let token = "github_p" + "at_11ABC" + "DEFG0aBc" + "DeFgHiJk" + "L_MnOpQr" + "StUvWxYz" + "01234567" + "89AbCdEf"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGithubFineGrainedShell() { let token = "github_p" + "at_11ABC" + "DEFG0aBc" + "DeFgHiJk" + "L_MnOpQr" + "StUvWxYz" + "01234567" + "89AbCdEf"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGitlabLog() { let token = "glpat-AB" + "CdefGHIj" + "klMNOpqr" + "ST"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGitlabJSON() { let token = "glpat-AB" + "CdefGHIj" + "klMNOpqr" + "ST"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGitlabShell() { let token = "glpat-AB" + "CdefGHIj" + "klMNOpqr" + "ST"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesSlackBotLog() { let token = "xoxb-123" + "45678901" + "2-123456" + "7890123-" + "AbCdEfGh" + "IjKlMnOp" + "QrStUvWx"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesSlackBotJSON() { let token = "xoxb-123" + "45678901" + "2-123456" + "7890123-" + "AbCdEfGh" + "IjKlMnOp" + "QrStUvWx"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesSlackBotShell() { let token = "xoxb-123" + "45678901" + "2-123456" + "7890123-" + "AbCdEfGh" + "IjKlMnOp" + "QrStUvWx"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesSlackAppLog() { let token = "xapp-1-A" + "012BCDEF" + "GH-12345" + "67890123" + "-abcdef0" + "12345678" + "9"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesSlackAppJSON() { let token = "xapp-1-A" + "012BCDEF" + "GH-12345" + "67890123" + "-abcdef0" + "12345678" + "9"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesSlackAppShell() { let token = "xapp-1-A" + "012BCDEF" + "GH-12345" + "67890123" + "-abcdef0" + "12345678" + "9"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesAwsAccessKeyLog() { let token = "AKIAIOSF" + "ODNN7EXA" + "MPLE"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesAwsAccessKeyJSON() { let token = "AKIAIOSF" + "ODNN7EXA" + "MPLE"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesAwsAccessKeyShell() { let token = "AKIAIOSF" + "ODNN7EXA" + "MPLE"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGoogleApiLog() { let token = "AIzaSyD-" + "9tSrke72" + "PouQMnMX" + "-a7eZSW0" + "jkFMBWY"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGoogleApiJSON() { let token = "AIzaSyD-" + "9tSrke72" + "PouQMnMX" + "-a7eZSW0" + "jkFMBWY"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGoogleApiShell() { let token = "AIzaSyD-" + "9tSrke72" + "PouQMnMX" + "-a7eZSW0" + "jkFMBWY"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesGoogleOauthLog() { let token = "ya29.a0A" + "fH6SMBx7" + "Yq2LpR8n" + "ZwK4tYgH" + "6sB1dCeF" + "0aUiOx7P" + "l"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesGoogleOauthJSON() { let token = "ya29.a0A" + "fH6SMBx7" + "Yq2LpR8n" + "ZwK4tYgH" + "6sB1dCeF" + "0aUiOx7P" + "l"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesGoogleOauthShell() { let token = "ya29.a0A" + "fH6SMBx7" + "Yq2LpR8n" + "ZwK4tYgH" + "6sB1dCeF" + "0aUiOx7P" + "l"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesStripeLog() { let token = "sk_live_" + "51H8xQ2L" + "pR7vNw4T" + "gH1sYbF6" + "d"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesStripeJSON() { let token = "sk_live_" + "51H8xQ2L" + "pR7vNw4T" + "gH1sYbF6" + "d"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesStripeShell() { let token = "sk_live_" + "51H8xQ2L" + "pR7vNw4T" + "gH1sYbF6" + "d"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesNpmLog() { let token = "npm_aBcD" + "eFgHiJkL" + "mNoPqRsT" + "uVwXyZ01" + "23456789"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesNpmJSON() { let token = "npm_aBcD" + "eFgHiJkL" + "mNoPqRsT" + "uVwXyZ01" + "23456789"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesNpmShell() { let token = "npm_aBcD" + "eFgHiJkL" + "mNoPqRsT" + "uVwXyZ01" + "23456789"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesHuggingfaceLog() { let token = "hf_ABCde" + "fGHIjklM" + "NOpqrSTu" + "vwxYZ012" + "3"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesHuggingfaceJSON() { let token = "hf_ABCde" + "fGHIjklM" + "NOpqrSTu" + "vwxYZ012" + "3"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesHuggingfaceShell() { let token = "hf_ABCde" + "fGHIjklM" + "NOpqrSTu" + "vwxYZ012" + "3"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesSupabaseLog() { let token = "sbp_0123" + "456789ab" + "cdef0123" + "456789ab" + "cdef0123" + "4567"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesSupabaseJSON() { let token = "sbp_0123" + "456789ab" + "cdef0123" + "456789ab" + "cdef0123" + "4567"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesSupabaseShell() { let token = "sbp_0123" + "456789ab" + "cdef0123" + "456789ab" + "cdef0123" + "4567"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesSendgridLog() { let token = "SG.aBcDe" + "FgHiJkLm" + "NoPqRsT." + "uVwXyZ01" + "23456789" + "AbCdEfGh" + "IjKl"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesSendgridJSON() { let token = "SG.aBcDe" + "FgHiJkLm" + "NoPqRsT." + "uVwXyZ01" + "23456789" + "AbCdEfGh" + "IjKl"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesSendgridShell() { let token = "SG.aBcDe" + "FgHiJkLm" + "NoPqRsT." + "uVwXyZ01" + "23456789" + "AbCdEfGh" + "IjKl"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesJwtLog() { let token = "eyJhbGci" + "OiJIUzI1" + "NiIsInR5" + "cCI6IkpX" + "VCJ9.eyJ" + "zdWIiOiI" + "xMjM0NTY" + "3ODkwIiw" + "ibmFtZSI" + "6IkpvaG4" + "ifQ.dozj" + "gNryP4J3" + "jVmNHl0w" + "5N_XgL0n" + "3I9PlFUP" + "0THsR8U"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesJwtJSON() { let token = "eyJhbGci" + "OiJIUzI1" + "NiIsInR5" + "cCI6IkpX" + "VCJ9.eyJ" + "zdWIiOiI" + "xMjM0NTY" + "3ODkwIiw" + "ibmFtZSI" + "6IkpvaG4" + "ifQ.dozj" + "gNryP4J3" + "jVmNHl0w" + "5N_XgL0n" + "3I9PlFUP" + "0THsR8U"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesJwtShell() { let token = "eyJhbGci" + "OiJIUzI1" + "NiIsInR5" + "cCI6IkpX" + "VCJ9.eyJ" + "zdWIiOiI" + "xMjM0NTY" + "3ODkwIiw" + "ibmFtZSI" + "6IkpvaG4" + "ifQ.dozj" + "gNryP4J3" + "jVmNHl0w" + "5N_XgL0n" + "3I9PlFUP" + "0THsR8U"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesBareHex32Log() { let token = "d41d8cd9" + "8f00b204" + "e9800998" + "ecf8427e" + "1a2b3c4d"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesBareHex32JSON() { let token = "d41d8cd9" + "8f00b204" + "e9800998" + "ecf8427e" + "1a2b3c4d"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesBareHex32Shell() { let token = "d41d8cd9" + "8f00b204" + "e9800998" + "ecf8427e" + "1a2b3c4d"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
    func testRemovesBareBase64Log() { let token = "aGVsbG8g" + "d29ybGQg" + "dGhpcyBp" + "cyBhIGxv" + "bmcgc2Vj" + "cmV0Cg12" + "34"; gone(BackendSharedRedact.redact("2026-08-12 INFO [net] calling api with " + token + " now"), token) }
    func testRemovesBareBase64JSON() { let token = "aGVsbG8g" + "d29ybGQg" + "dGhpcyBp" + "cyBhIGxv" + "bmcgc2Vj" + "cmV0Cg12" + "34"; gone(BackendSharedRedact.redact(NativeRPCValue.object([.init("nested", .object([.init("value", .string(token))]))]).compact), token) }
    func testRemovesBareBase64Shell() { let token = "aGVsbG8g" + "d29ybGQg" + "dGhpcyBp" + "cyBhIGxv" + "bmcgc2Vj" + "cmV0Cg12" + "34"; gone(BackendSharedRedact.redact("curl -H 'Authorization: Bearer " + token + "' https://api.example.com"), token) }
}

extension BackendMacAppSetupRedactionTests {
    func testSeveralSecretsOnOneLineAllDisappear() { let a = "ghp_16C7" + "e42F292c6912E7710c838347Ae178B4a", b = "sk-ant-api03-" + "Zx8kQm2LpR7vNw4TgH1sYbF6dJcE0aUiOx9PlKmQnR3tVzWyXs"; let out = BackendSharedRedact.redact("GH=\(a) ANTHROPIC=\(b) done"); XCTAssertFalse(out.contains(a)); XCTAssertFalse(out.contains(b)) }
    func testAuthorizationWithoutKnownTokenShape() { gone(BackendSharedRedact.redact("Authorization: Bearer correcthorsebatterystaple"), "correcthorsebatterystaple") }
    func testAuthorizationJSONHeaderBag() { gone(BackendSharedRedact.redact("{\"headers\":{\"Authorization\":\"Basic YWxhZGRpbjpvcGVuc2VzYW1l\"}}"), "YWxhZGRpbjpvcGVuc2VzYW1l") }
    func testCookieHeader() { gone(BackendSharedRedact.redact("Cookie: session=abc; theme=dark"), "session=abc") }
    func testWeakPasswordHasSecretKeyBoundary() { gone(BackendSharedRedact.redact("password=hunter2"), "hunter2") }
    func testSecretKeyAssignmentsAllRedact() { for line in ["ANTHROPIC_API_KEY=letmein-please", "api_key: letmein-please", "\"apiKey\": \"letmein-please\"", "GITHUB_TOKEN='letmein-please'", "client_secret = letmein-please", "MY_APP_ACCESS_KEY:letmein-please", "private_key=letmein-please"] { gone(BackendSharedRedact.redact(line), "letmein-please") } }
    func testURLCredentialGoneAndHostSurvives() { let out = BackendSharedRedact.redact("https://asad:hunter2@github.com/asadev/terminaldeck.git"); XCTAssertFalse(out.contains("hunter2")); XCTAssertTrue(out.contains("github.com/asadev/terminaldeck.git")) }
    func testWholePrivateKeyBlockGone() { let pem = "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAxGZm9v0aB1cD2eF3gH4iJ5kL6mN7oP8qR9sT0uV1wX2yZ3aB\nc4dE5fG6hI7jK8lM9nO0pQ1rS2tU3vW4xY5zA6bC7dE8fG9hI0jK1lM2nO3pQ4rS\n-----END RSA PRIVATE KEY-----"; let out = BackendSharedRedact.redact("key follows\n" + pem + "\nend"); XCTAssertFalse(out.contains("MIIEowIBAAKCAQEA")); XCTAssertTrue(out.contains("end")) }
    func testSlackWebhookURLGone() { gone(BackendSharedRedact.redact("posting to https://hooks.slack.com/services/T00000000/B00000000/" + String(repeating: "X", count: 24)), String(repeating: "X", count: 24)) }
    func testVersionStringsSurvive() { let value = "Claude Code 2.4.17 (Electron 41.10.5, node 22.9.0)"; XCTAssertEqual(BackendSharedRedact.redact(value), value) }
    func testGitAuthorIsNotAuthentication() { XCTAssertTrue(BackendSharedRedact.redact("author: Ada Lovelace <ada@example.com>").contains("Ada Lovelace")) }
    func testSessionUUIDSurvives() { let id = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"; XCTAssertTrue(BackendSharedRedact.redact("session " + id + " started").contains(id)) }
    func testOrdinaryProseAndShortIDsSurvive() { let value = "git status found 3 modified files in src/main and 1 in src/renderer"; XCTAssertEqual(BackendSharedRedact.redact(value), value) }
    func testSystemPathsNamingNobodySurvive() { let value = "/opt/homebrew/bin:/usr/local/bin:/usr/bin"; XCTAssertEqual(BackendSharedRedact.redact(value), value) }
    func testLongHyphenatedFontNameSurvives() { let value = "hanken-grotesk-v4-latin-regular-400.woff2"; XCTAssertEqual(BackendSharedRedact.redact(value), value) }
    func testOrdinaryPathsNeverBecomeEntropyBlobs() { for value in ["/usr/local/lib/node_modules/terminaldeck/dist/index2", "/Users/<user>/Projects/terminaldeck/src/renderer/components/DebugPanel2", "src/renderer/components/DebugPanel2/index", "/opt/homebrew/Cellar/node/22.9.0/lib/node_modules"] { XCTAssertEqual(BackendSharedRedact.redact(value, options: .init(home: "/Users/nobody", username: "nobody")), value) } }
    func testBareBase64WithSlashStillRedacts() { let value = "YmF6cXV4abc123DEF456ghi789JKL012mno345PQR678/Zm9vYmFyabc123DEF456ghi789JKL012"; XCTAssertFalse(BackendSharedRedact.redact("blob " + value + " end").contains("Zm9vYmFyabc123DEF456ghi789JKL012")) }
    func testEntropyRejectsUnder32Characters() { XCTAssertFalse(BackendSharedRedact.looksSecret("abc123abc123abc123abc123abc12")) }
    func testEntropyRejectsNoDigits() { XCTAssertFalse(BackendSharedRedact.looksSecret("abcdefghijklmnopqrstuvwxyzabcdefghij")) }
    func testEntropyRejectsCanonicalUUID() { XCTAssertFalse(BackendSharedRedact.looksSecret("3f2504e0-4f89-11d3-9a0c-0305e82c3301")) }
    func testEntropyAcceptsLegacyPATLengthHex() { XCTAssertTrue(BackendSharedRedact.looksSecret("1a2b3c4d5e6f708192a3b4c5d6e7f80918273645")) }
    func testEntropyRejectsRepetitionEvenWhenLong() { XCTAssertFalse(BackendSharedRedact.looksSecret(String(repeating: "a", count: 40) + "1")) }
    func testHomeDirectoryFoldsToTilde() { XCTAssertEqual(BackendSharedRedact.redact("/Users/testuser/Projects/terminaldeck", options: .init(home: "/Users/testuser", username: "testuser")), "~/Projects/terminaldeck") }
    func testOtherHomeDirectoriesFoldToo() { let options = BackendSharedRedactOptions(home: "/Users/testuser", username: "testuser"); XCTAssertEqual(BackendSharedRedact.redact("/Users/someoneelse/Library/Logs", options: options), "/Users/<user>/Library/Logs"); XCTAssertEqual(BackendSharedRedact.redact("/home/deploy/app", options: options), "/home/<user>/app") }
    func testPastedWindowsIdentityIsRedactedOnMac() { XCTAssertEqual(BackendSharedRedact.redact("C:\\Users\\Asad\\AppData", options: .init(home: "/Users/testuser", username: "testuser")), "C:\\Users\\<user>\\AppData") }
    func testShellPromptIdentityFolds() { XCTAssertEqual(BackendSharedRedact.redact("testuser@Mac-mini ~ %", options: .init(home: "/Users/testuser", username: "testuser")), "<user>@Mac-mini ~ %") }
    func testUsernameAsOrdinaryWordSurvives() { XCTAssertEqual(BackendSharedRedact.redact("apple pie recipe", options: .init(home: "/Users/apple", username: "apple")), "apple pie recipe") }
    func testUserAssignmentsFold() { XCTAssertTrue(BackendSharedRedact.redact("USER=testuser", options: .init(home: "/Users/testuser", username: "testuser")).contains("<user>")) }
    func testCallerLiteralSecretWithNoShapeRemoved() { XCTAssertFalse(BackendSharedRedact.redact("the hook token is swordfish99 today", options: .init(extraSecrets: ["swordfish99"])).contains("swordfish99")) }
    func testSecretEnvironmentValuesPickedUp() { XCTAssertEqual(BackendSharedRedact.secretsFromEnv(["MY_API_TOKEN": "swordfish99xyz", "PATH": "/usr/bin"]), ["swordfish99xyz"]) }
    func testTooShortEnvironmentValuesIgnored() { XCTAssertEqual(BackendSharedRedact.secretsFromEnv(["DEBUG_TOKEN": "1", "API_KEY": "yes"]), []) }
    func testOnlySecretEnvironmentNamesReported() { XCTAssertEqual(BackendSharedRedact.secretEnvNames(["GITHUB_TOKEN": "ghp_" + String(repeating: "x", count: 24), "PATH": "/usr/bin"]), ["GITHUB_TOKEN"]) }
    private var invariantSample: String { "Authorization: Bearer sk-ant-" + "api03-Zx8kQm2LpR7vNw4TgH1sYbF6dJcE0aUiOx9PlKmQnR3tVzWyXs\nGITHUB_TOKEN=ghp_" + "16C7e42F292c6912E7710c838347Ae178B4a\ndb=postgres://user:hunter2@db.example.com:5432/app\n/Users/testuser/.claude/.credentials.json" }
    func testRedactionIsIdempotent() { let options = BackendSharedRedactOptions(home: "/Users/testuser", username: "testuser"), once = BackendSharedRedact.redact(invariantSample, options: options); XCTAssertEqual(BackendSharedRedact.redact(once, options: options), once) }
    func testSubstitutionsAreCounted() { XCTAssertGreaterThan(BackendSharedRedact.redactWithCount(invariantSample).count, 3) }
    func testEmptyAndWhitespaceRemainIntact() { XCTAssertEqual(BackendSharedRedact.redact(""), ""); XCTAssertEqual(BackendSharedRedact.redact("   "), "   ") }
    func testSecretLookingKeysHideEveryValueType() { let value = BackendSharedRedact.redactValue(.object([.init("token", .number(12345678)), .init("apiKey", .object([.init("nested", .bool(true))])), .init("theme", .string("dark"))])); XCTAssertEqual(value["token"], .string("[redacted]")); XCTAssertEqual(value["apiKey"], .string("[redacted]")); XCTAssertEqual(value["theme"], .string("dark")) }
    func testNestedArraysAndObjectsAreWalked() { let value = BackendSharedRedact.redactValue(.object([.init("items", .array([.object([.init("password", .string("hunter2"))]), .string("ghp_" + "16C7e42F292c6912E7710c838347Ae178B4a")]))])); XCTAssertFalse(value.compact.contains("hunter2")); XCTAssertFalse(value.compact.contains("ghp_16C7")) }
    func testObjectCycleDoesNotThrow() { let object = NSMutableDictionary(); object["name"] = "a"; object["self"] = object; let value = BackendSharedRedact.redactFoundation(object) as! [String: Any]; XCTAssertEqual(value["name"] as? String, "a"); object.removeObject(forKey: "self") }
    func testSharedObjectReferenceIsNotCycle() { let shared: NSDictionary = ["theme": "dark"]; let value = BackendSharedRedact.redactFoundation(["a": shared, "b": shared] as NSDictionary) as! [String: Any]; XCTAssertEqual((value["a"] as? [String: String])?["theme"], "dark"); XCTAssertEqual((value["b"] as? [String: String])?["theme"], "dark") }
    func testSharedArraySurvivesBothBranches() { let shared: NSArray = [1, 2]; let value = BackendSharedRedact.redactFoundation(["a": shared, "b": shared] as NSDictionary) as! [String: Any]; XCTAssertEqual(value["b"] as? [Int], [1,2]) }
    func testGenuineCycleIsMarked() { let object = NSMutableDictionary(); object["name"] = "a"; object["self"] = object; let value = BackendSharedRedact.redactFoundation(object) as! [String: Any]; XCTAssertEqual(value["self"] as? String, "[circular]"); object.removeObject(forKey: "self") }
    func testExistingAppLogLineHasNoEmbeddedNewline() { let value = BackendOSLogRules.line(at: 0, level: "info", scope: "git", message: "a\nb"); XCTAssertFalse(value.contains("\n")); XCTAssertTrue(value.contains("[git]")); XCTAssertTrue(value.contains("INFO")) }
}
