import Foundation
import CryptoKit
import XCTest
import TerminalDeckNativeCore
@testable import TerminalDeckBackend

final class BackendOSTestPortStoreIndex: BackendOSTestPortFixture {
    let now = BackendAppStoreIndex.date("2026-08-28T12:00:00.000Z")!
    var row: NativeRPCValue { .object([
        .init("id", .string("acme/pr-review")), .init("publisher", .string("acme")), .init("listedBy", .string("acme")), .init("kind", .string("skill")), .init("name", .string("Pull request review")), .init("summary", .string("Reads a diff and writes the review you would have written.")),
        .init("version", .string("1.0.0")), .init("licence", .string("MIT")), .init("category", .string("code")), .init("tags", .array([.string("review")])), .init("agents", .array([.string("claude")])), .init("platforms", .array([.string("darwin"), .string("linux")])), .init("tier", .number(1)), .init("needs", .array([])), .init("cost", .string("free")), .init("costNote", .null), .init("delivery", .string("repo")),
        .init("source", .object([.init("repo", .string("https://github.com/acme/pr-review")), .init("commit", .string(String(repeating: "a", count: 40))), .init("path", .string(".")), .init("host", .string("github.com"))])),
        .init("artifact", .object([.init("url", .string("https://codeload.github.com/acme/pr-review/zip/" + String(repeating: "a", count: 40))), .init("sha256", .string(String(repeating: "b", count: 64))), .init("bytes", .number(2048)), .init("files", .number(4)), .init("unpacked", .number(8192))])),
        .init("install", .object([.init("dir", .string("skills/pr-review"))])), .init("network", .array([])), .init("publishedAt", .string("2026-08-01T00:00:00.000Z")), .init("updatedAt", .string("2026-08-20T00:00:00.000Z"))]) }
    func document(_ patch: NativeRPCValue = .object([])) -> NativeRPCValue { NativeRPCValue.object([.init("v", .number(1)), .init("serial", .number(7)), .init("issuedAt", .string("2026-08-27T00:00:00.000Z")), .init("expiresAt", .null), .init("generator", .string("terminaldeck-commons 0.1.0")), .init("truncated", .bool(false)), .init("items", .array([row])), .init("revoked", .array([]))]).merging(patch) }
    func envelope(_ document: NativeRPCValue, stranger: Bool = false) throws -> String {
        let seed = stranger ? Data(repeating: 42, count: 32) : Data(SHA256.hash(data: Data(BackendSharedStoreKeys.developmentPhrase.utf8)))
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed), bytes = try document.encodedJSON(), signature = try key.signature(for: bytes)
        return NativeRPCValue.object([.init("v", .number(1)), .init("keyId", .string("td-store-dev-1")), .init("alg", .string("ed25519")), .init("sig", .string(signature.base64EncodedString())), .init("signed", .string(bytes.base64EncodedString()))]).compact
    }
    func checked(_ document: NativeRPCValue) throws -> NativeRPCValue { BackendAppStoreIndex.check(try envelope(document), keys: [BackendSharedStoreKeys.development], now: now).wire }
    func refused(_ document: NativeRPCValue) throws -> String { let result = try checked(document); XCTAssertEqual(result["ok"].bool, false); return result["why"].string ?? "" }
    func one(_ patch: NativeRPCValue) -> NativeRPCValue { document(.object([.init("items", .array([row.merging(patch)]))])) }
    func cache(_ root: URL, fetch: @escaping BackendAppStoreIndexCache.Fetch = { _, _ in .init(ok: false, message: "the store could not be reached") }) -> BackendAppStoreIndexCache { .init(userData: root, writable: true, keys: [BackendSharedStoreKeys.development], fetch: fetch) }
    func testStoreIndex124GoodSignatureNormalizedInstallAndKey() throws { let result = try checked(document()); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["keyId"].string, "td-store-dev-1"); XCTAssertEqual(result["index"]["items"].elements?.count, 1); XCTAssertEqual(result["index"]["items"].elements?.first?["install"], .object([.init("kind", .string("skill")), .init("dir", .string("skills/pr-review"))])); XCTAssertEqual(result["stale"], .null) }
    func testStoreIndex135OneFlippedSignedBitRefuses() throws { var raw = try NativeRPCValue.parseJSON(Data(envelope(document()).utf8)), bytes = Data(base64Encoded: raw["signed"].string!)!; bytes[20] ^= 1; raw = raw.setting("signed", .string(bytes.base64EncodedString())); XCTAssertEqual(BackendAppStoreIndex.check(raw.compact, keys: [BackendSharedStoreKeys.development], now: now).wire["why"].string, "this catalogue was not signed by Terminal Deck, so it was not used") }
    func testStoreIndex145UnknownSigningKeyRefuses() throws { let result = BackendAppStoreIndex.check(try envelope(document(), stranger: true), keys: [BackendSharedStoreKeys.development], now: now).wire; XCTAssertTrue(result["why"].string?.contains("not signed by Terminal Deck") == true) }
    func testStoreIndex150SecondSlotRotationAccepted() throws { let older = BackendSharedStoreKey(id: "td-store-old", hex: String(repeating: "c", count: 64), because: "a retired key, in tests"), result = BackendAppStoreIndex.check(try envelope(document()), keys: [older, BackendSharedStoreKeys.development], now: now).wire; XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["keyId"].string, "td-store-dev-1") }
    func testStoreIndex157NoTrustedKeyRefuses() throws { XCTAssertEqual(BackendAppStoreIndex.check(try envelope(document()), keys: [], now: now).wire["why"].string, "this build carries no key to check a catalogue with") }
    func testStoreIndex168DevelopmentKeyRequiresUnpackagedOptIn() throws {
        let text = try envelope(document()), byDefault = BackendAppStoreIndex.check(text, now: now).wire; XCTAssertEqual(byDefault["ok"].bool, false); XCTAssertTrue(byDefault["why"].string?.contains("not signed by Terminal Deck") == true)
        let asked = [BackendSharedStoreKeys.environmentKey: "1"], packaged = BackendAppStoreIndex.check(text, keys: BackendSharedStoreKeys.keys(environment: asked, packaged: true), now: now).wire, local = BackendAppStoreIndex.check(text, keys: BackendSharedStoreKeys.keys(environment: asked, packaged: false), now: now).wire
        XCTAssertEqual(packaged["ok"].bool, false); XCTAssertEqual(local["ok"].bool, true); XCTAssertEqual(local["keyId"].string, "td-store-dev-1")
    }
    func testStoreIndex180UnknownAlgorithmRefuses() throws { let raw = try NativeRPCValue.parseJSON(Data(envelope(document()).utf8)).setting("alg", .string("rsa")); XCTAssertEqual(BackendAppStoreIndex.check(raw.compact, keys: [BackendSharedStoreKeys.development], now: now).wire["why"].string, "this catalogue is signed with rsa, which this app does not check") }
    func testStoreIndex185ShortSignatureRefusesBeforeCrypto() { XCTAssertNil(BackendAppStoreIndex.verify(signed: Data("x".utf8), signature: Data(repeating: 0, count: 10), keys: [BackendSharedStoreKeys.development]).key) }
    func testStoreIndex191OldSerialRefuses() throws { let result = BackendAppStoreIndex.check(try envelope(document(.object([.init("serial", .number(6))]))), keys: [BackendSharedStoreKeys.development], highWater: 7, now: now).wire; XCTAssertTrue(result["why"].string?.contains("older list than one this machine has already seen") == true) }
    func testStoreIndex195ReplayNamesWithdrawalRisk() throws { let result = BackendAppStoreIndex.check(try envelope(document(.object([.init("serial", .number(1))]))), keys: [BackendSharedStoreKeys.development], highWater: 7, now: now).wire; XCTAssertTrue(result["why"].string?.contains("put back something that was withdrawn") == true) }
    func testStoreIndex199SameSerialAccepted() throws { XCTAssertEqual(BackendAppStoreIndex.check(try envelope(document()), keys: [BackendSharedStoreKeys.development], highWater: 7, now: now).wire["ok"].bool, true) }
    func testStoreIndex205FortyDayAgeIsReported() throws { let result = try checked(document(.object([.init("issuedAt", .string(BackendAppSettingsStore.iso(now - 40 * 86_400_000)))]))); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["stale"].string, "This list is 40 days old.") }
    func testStoreIndex211FutureDateIsReported() throws { let result = try checked(document(.object([.init("issuedAt", .string(BackendAppSettingsStore.iso(now + 86_400_000)))]))); XCTAssertEqual(result["ok"].bool, true); XCTAssertTrue(result["stale"].string?.contains("dated in the future") == true) }
    func testStoreIndex217ExpiredDateIsReported() throws { let result = try checked(document(.object([.init("expiresAt", .string(BackendAppSettingsStore.iso(now - 60_000)))]))); XCTAssertEqual(result["ok"].bool, true); XCTAssertTrue(result["stale"].string?.contains("passed the date it was good until") == true) }
    func testStoreIndex223ThisMorningNotStale() { XCTAssertNil(BackendAppStoreIndex.staleness(.object([.init("issuedAt", .string(BackendAppSettingsStore.iso(now - 3_600_000))), .init("expiresAt", .null)]), now: now)) }
    func testStoreIndex229UnknownTopLevelKeyNamed() throws { XCTAssertEqual(try refused(document(.object([.init("hydrate", .string("https://example.com/more.json"))]))), "the catalogue has a key this app does not know about: hydrate") }
    func testStoreIndex235UnknownFormatNamed() throws { XCTAssertEqual(try refused(document(.object([.init("v", .number(2))]))), "this catalogue is written for format 2, and this app reads format 1") }
    func testStoreIndex239UnknownRowKeyNamed() throws { XCTAssertEqual(try refused(one(.object([.init("sponsored", .bool(true))]))), "item 1 has a key this app does not know about: sponsored") }
    func testStoreIndex245PublisherNamespaceRefuses() throws { XCTAssertTrue(try refused(one(.object([.init("id", .string("someone-else/pr-review"))]))).contains("must be written acme/<id>")) }
    func testStoreIndex251TagIsNotCommit() throws { XCTAssertTrue(try refused(one(.object([.init("source", row["source"].setting("commit", .string("v1.0.0")))]))).contains("never a tag")) }
    func testStoreIndex257TierFloorRefuses() throws {
        let hooks = row.setting("kind", .string("hooks")).setting("tier", .number(1)).setting("needs", .array([.string("runs-scripts")])).setting("install", .object([.init("script", .string("hooks/notify.mjs")), .init("events", .array([.string("SessionStart")])), .init("runtime", .string("node"))]))
        XCTAssertEqual(try refused(document(.object([.init("items", .array([hooks]))]))), "item 1 calls itself tier 1, and a hooks can never be less than 3")
    }
    func testStoreIndex270PaidWithoutDisclosureRefuses() throws { XCTAssertTrue(try refused(one(.object([.init("cost", .string("paid")), .init("costNote", .null)]))).contains("does not say what")) }
    func testStoreIndex274ManifestInstallGrammarApplied() throws { XCTAssertTrue(try refused(one(.object([.init("install", .object([.init("dir", .string("../../etc"))]))]))).contains("must not step outside the item with ..")) }
    func testStoreIndex279DuplicateRowsRefuse() throws { XCTAssertEqual(try refused(document(.object([.init("items", .array([row, row]))]))), "this catalogue lists acme/pr-review twice") }
    func testStoreIndex283DigestShapeRefuses() throws { XCTAssertTrue(try refused(one(.object([.init("artifact", row["artifact"].setting("sha256", .string("nope")))]))).contains("must be 64 hex characters")) }
    func testStoreIndex288ArrivedBytesCap() { let huge: NativeRPCValue = .object([.init("v", .number(1)), .init("keyId", .string("x")), .init("alg", .string("ed25519")), .init("sig", .string("")), .init("signed", .string(String(repeating: "x", count: BackendAppStoreIndex.maxBytes)))]); XCTAssertEqual(BackendAppStoreIndex.check(huge.compact, keys: [BackendSharedStoreKeys.development], now: now).wire["why"].string, "this catalogue is larger than this app will read") }
    func testStoreIndex293JunkNeverThrows() { for bytes in ["", "{", "null", "[]", #"{"v":1}"#] { XCTAssertEqual(BackendAppStoreIndex.check(bytes, keys: [BackendSharedStoreKeys.development], now: now).wire["ok"].bool, false) } }
    func testStoreIndex299SignedWithdrawalAndAbsentWithdrawal() throws {
        let result = try checked(document(.object([.init("revoked", .array([.object([.init("id", .string("acme/pr-review")), .init("version", .string("*")), .init("reason", .string("The publisher asked for it to come down."))])]))]))); XCTAssertEqual(result["ok"].bool, true)
        XCTAssertTrue(BackendAppStoreIndex.revocation(result["index"], id: "acme/pr-review", version: "1.0.0")?["reason"].string?.contains("asked for it") == true); XCTAssertNil(BackendAppStoreIndex.revocation(result["index"], id: "acme/other", version: "1.0.0"))
    }
    var archive: Data { Data("the archive".utf8) }
    var digest: String { SHA256.hash(data: archive).map { String(format: "%02x", $0) }.joined() }
    func testStoreIndex316CorrectBytesCaseInsensitiveDigest() { XCTAssertTrue(BackendAppStoreIndex.artifactMatches(archive, expectedHex: digest)); XCTAssertTrue(BackendAppStoreIndex.artifactMatches(archive, expectedHex: digest.uppercased())) }
    func testStoreIndex321OneChangedByteRefuses() { XCTAssertFalse(BackendAppStoreIndex.artifactMatches(Data("the archivf".utf8), expectedHex: digest)) }
    func testStoreIndex325MalformedDigestDoesNotThrow() { for bad in [String(digest.prefix(32)), "zz", ""] { XCTAssertFalse(BackendAppStoreIndex.artifactMatches(archive, expectedHex: bad)) } }
    func testStoreIndex345CacheRoundTripAndFetchTime() async throws {
        let root = try scratch(), cache = self.cache(root); let absent = await cache.hasCache(); XCTAssertFalse(absent); try await cache.write(envelope: envelope(document()), serial: 7, at: now)
        let present = await cache.hasCache(), kept = await cache.read(now: now), high = await cache.highWater(); XCTAssertTrue(present); XCTAssertNotNil(kept); XCTAssertEqual(kept?["savedAt"].string, BackendAppSettingsStore.iso(now)); XCTAssertEqual(kept?["index"]["serial"].number, 7); XCTAssertEqual(high, 7)
    }
    func testStoreIndex357HighWaterNeverDecreases() async throws { let root = try scratch(), cache = self.cache(root); try await cache.write(envelope: envelope(document(.object([.init("serial", .number(9))]))), serial: 9, at: now); try await cache.write(envelope: envelope(document(.object([.init("serial", .number(2))]))), serial: 2, at: now); let high = await cache.highWater(); XCTAssertEqual(high, 9) }
    func testStoreIndex364CacheTamperRefuses() async throws {
        let root = try scratch(), cache = self.cache(root); try await cache.write(envelope: envelope(document()), serial: 7, at: now); let file = await cache.file
        var raw = try disk(file), env = try NativeRPCValue.parseJSON(Data(raw["envelope"].string!.utf8)), bytes = Data(base64Encoded: env["signed"].string!)!; bytes[15] ^= 2; env = env.setting("signed", .string(bytes.base64EncodedString())); raw = raw.setting("envelope", .string(env.compact)); try raw.encodedJSON().write(to: file)
        let kept = await cache.read(now: now); XCTAssertNil(kept)
    }
    func testStoreIndex378NoCacheNoHighWater() async throws { let cache = self.cache(try scratch()), kept = await cache.read(now: now), high = await cache.highWater(); XCTAssertNil(kept); XCTAssertEqual(high, 0) }
    func serving(_ root: URL, text: String) -> BackendAppStoreIndexCache { cache(root) { url, _ in XCTAssertEqual(url, "http://127.0.0.1:8931/store/index.json"); return .init(ok: true, text: text) } }
    func testStoreIndex415FetchCheckKeep() async throws { let root = try scratch(), cache = serving(root, text: try envelope(document())), result = await cache.load(base: "http://127.0.0.1:8931", now: now), high = await cache.highWater(); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["from"].string, "store"); XCTAssertEqual(result["because"], .null); XCTAssertEqual(high, 7) }
    func testStoreIndex426OfflineKeptHasOriginalFetchTime() async throws { let root = try scratch(), online = serving(root, text: try envelope(document())); _ = await online.load(base: "http://127.0.0.1:8931", now: now); let offline = self.cache(root), result = await offline.load(base: "http://127.0.0.1:8931", now: now); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["from"].string, "kept"); XCTAssertEqual(result["at"].string, BackendAppSettingsStore.iso(now)); XCTAssertEqual(result["because"].string, "the store could not be reached") }
    func testStoreIndex438ForgedFetchUsesKeptAndNamesSignatureFailure() async throws { let root = try scratch(), online = serving(root, text: try envelope(document())); _ = await online.load(base: "http://127.0.0.1:8931", now: now); let forged = serving(root, text: try envelope(document(.object([.init("serial", .number(8))])), stranger: true)), result = await forged.load(base: "http://127.0.0.1:8931", now: now); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["from"].string, "kept"); XCTAssertTrue(result["because"].string?.contains("not signed by Terminal Deck") == true); XCTAssertEqual(result["index"]["serial"].number, 7) }
    func testStoreIndex452NothingKeptOrBelievableRefuses() async throws { let root = try scratch(), cache = serving(root, text: try envelope(document(), stranger: true)), result = await cache.load(base: "http://127.0.0.1:8931", now: now); XCTAssertEqual(result["ok"].bool, false); XCTAssertTrue(result["why"].string?.contains("not signed by Terminal Deck") == true) }
    func testStoreIndex460ReplayFromStoreUsesNewerKept() async throws { let root = try scratch(), online = serving(root, text: try envelope(document(.object([.init("serial", .number(9))])))); _ = await online.load(base: "http://127.0.0.1:8931", now: now); let replay = serving(root, text: try envelope(document(.object([.init("serial", .number(3))])))), result = await replay.load(base: "http://127.0.0.1:8931", now: now); XCTAssertEqual(result["ok"].bool, true); XCTAssertEqual(result["from"].string, "kept"); XCTAssertEqual(result["index"]["serial"].number, 9); XCTAssertTrue(result["because"].string?.contains("older list") == true) }
    func acceptedRow(_ patch: NativeRPCValue) throws -> NativeRPCValue { let result = try checked(one(patch)); XCTAssertEqual(result["ok"].bool, true, result["why"].string ?? ""); return result["index"]["items"].elements?.first ?? .missing }
    func testStoreIndex480OwnLogoNameRetained() throws { XCTAssertEqual(try acceptedRow(.object([.init("icon", .string("github"))]))["icon"].string, "github") }
    func testStoreIndex484RemoteLogoRefused() throws { XCTAssertEqual(try refused(one(.object([.init("icon", .string("https://acme.example/logo.png"))]))), "item 1.icon must name one of this app's own logos, never a link") }
    func testStoreIndex490HostStatsAndReadDateRetained() throws { let stats: NativeRPCValue = .object([.init("stars", .number(12)), .init("openIssues", .number(3)), .init("pushedAt", .string("2026-07-01T00:00:00.000Z")), .init("readAt", .string("2026-08-28T00:00:00.000Z"))]); XCTAssertEqual(try acceptedRow(.object([.init("repoStats", stats)]))["repoStats"], stats) }
    func testStoreIndex500UnknownStatsKeyNamed() throws { let stats: NativeRPCValue = .object([.init("stars", .number(1)), .init("openIssues", .number(0)), .init("pushedAt", .string("2026-07-01T00:00:00.000Z")), .init("readAt", .string("2026-07-01T00:00:00.000Z")), .init("forks", .number(4))]); XCTAssertEqual(try refused(one(.object([.init("repoStats", stats)]))), "item 1.repoStats has a key this app does not know about: forks") }
    func testStoreIndex521LogoAndStatsCanBothBeAbsent() throws { let value = try acceptedRow(.object([.init("icon", .null), .init("repoStats", .null)])); XCTAssertEqual(value["icon"], .null); XCTAssertEqual(value["repoStats"], .null) }
    func testStoreIndex527TagsHaveManifestGrammar() throws { XCTAssertEqual(try refused(one(.object([.init("tags", .array([.string("root cause")]))]))), "item 1.tags[0] must be lower-case letters, digits and hyphens") }
    func testStoreIndex543PublisherAIReaderAddressRetained() throws { XCTAssertEqual(try acceptedRow(.object([.init("ai", .string("https://terminaldeck.dev/@acme/pr-review/llms.txt"))]))["ai"].string, "https://terminaldeck.dev/@acme/pr-review/llms.txt") }
    func testStoreIndex549AbsentAIAllowedIncludingLegacyMissingKey() throws { XCTAssertEqual(try acceptedRow(.object([.init("ai", .null)]))["ai"], .null); XCTAssertEqual(try checked(document())["ok"].bool, true) }
    func testStoreIndex555ForeignAIHostRefused() throws { XCTAssertEqual(try refused(one(.object([.init("ai", .string("https://terminaldeck.dev.evil.example/x/llms.txt"))]))), "item 1.ai must be an https address on terminaldeck.dev") }
    func testStoreIndex561HTTPAIRefused() throws { XCTAssertEqual(try refused(one(.object([.init("ai", .string("http://terminaldeck.dev/@acme/x/llms.txt"))]))), "item 1.ai must be an https address on terminaldeck.dev") }
    func testStoreIndex567ScriptAIRefused() throws { XCTAssertEqual(try refused(one(.object([.init("ai", .string("javascript:alert(1)"))]))), "item 1.ai must be an https address on terminaldeck.dev") }
}
