package dev.terminaldeck.android.pairing

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The derivation every client has to agree on.
 *
 * ## Why the vectors are the point of this file
 *
 * [Rendezvous.identity] here and `rendezvousIdentity` in
 * `src/main/remote/machines/rendezvous.ts` must produce the **same** host id and the **same**
 * responder key from the same six digits, or a person types a code correctly and is told no machine
 * is showing it. There is no shared module that could make that true by construction — one is Kotlin
 * and the other imports `node:crypto` — so it is made true by something that fails on the drift
 * instead.
 *
 * The vectors below were generated by running the desktop's function. If somebody changes the salt,
 * a cost parameter, the seed length or the split between the slot secret and the responder key on
 * either side, one of these stops matching. `pwa/src/rendezvous.test.ts` and
 * `ios/Tests/RendezvousTests.swift` hold the same line from their sides.
 *
 * Never regenerate one of these to make a failing test pass. A change to these bytes is a change
 * every already-shipped client disagrees with, which is every pairing failing with "no machine is
 * showing that code".
 */
class RendezvousTest {

    private data class Vector(val code: String, val hostId: String, val publicKey: String)

    private val vectors = listOf(
        Vector("482913", "PNN7FEFPVPEPG8J6JD5LTK22CW", "PluJUUCYOIi9dWOnMK0Sq8NrO635DqyD0yTLIyeLlAU="),
        // The leading-zero case, pinned on purpose. A code is six *digits*, not a number, and
        // anything that parses `000000` as an integer on the way to the derivation lands on `0` and
        // derives a slot nobody else is sitting in.
        Vector("000000", "ESVP7D6GDHN28MLNU5AEGRGGC7", "AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc="),
        Vector("999999", "UAFTGU2WS5MN5GYUKF48KJG5SK", "bleS0Mpc5kqiW5FJ7wNs6uardUbhJgcrjUN583t7Zx4="),
    )

    @Test
    fun `the salt and the parameters are the desktop's`() {
        // One line each, and they are the lines that turn a silent disagreement into a red test.
        assertEquals("terminaldeck-machine-pairing-v1", Rendezvous.SALT)
        assertEquals(16384, Rendezvous.SCRYPT_N)
        assertEquals(8, Rendezvous.SCRYPT_R)
        assertEquals(1, Rendezvous.SCRYPT_P)
        assertEquals(64, Rendezvous.SEED_BYTES)
    }

    @Test
    fun `the cost parameters are not negotiable`() {
        /*
         * Asserted as a value rather than merely used, because this is the whole reason six digits
         * is defensible.
         *
         * There are 10^6 codes and a slot lookup is an unlimited oracle for "is this the live one".
         * At a hash, an attacker sweeps the million in seconds, learns the code exactly, and the
         * five-guess budget the desktop enforces buys nothing. At N = 16384, r = 8 a guess costs
         * 16 MiB and tens of milliseconds — ten CPU-hours for the space, inside a sixty-second
         * window. Lowering N "because phones are slow" is the change this assertion exists to stop.
         */
        assertEquals(16 * 1024 * 1024, 128 * Rendezvous.SCRYPT_R * Rendezvous.SCRYPT_N)
    }

    @Test
    fun `matches the desktop host id and responder key`() {
        for (vector in vectors) {
            val identity = Rendezvous.identity(vector.code)
            assertNotNull("no identity for ${vector.code}", identity)
            assertEquals("slot for ${vector.code}", vector.hostId, identity!!.hostId)
            assertEquals(
                "responder key for ${vector.code}",
                vector.publicKey,
                java.util.Base64.getEncoder().encodeToString(identity.keys.publicKey),
            )
        }
    }

    @Test
    fun `lands on one identity however the code was typed`() {
        // Both ends derive from the *normalised* string, or pairing depends on what somebody's
        // keyboard put between the digits on the way here.
        val canonical = checkNotNull(Rendezvous.identity("482913"))
        for (typed in listOf("482-913", " 482 913 ", "482–913")) {
            assertEquals("\"$typed\" should be the same slot", canonical.hostId, Rendezvous.identity(typed)?.hostId)
        }
    }

    @Test
    fun `refuses a string that is not a code instead of hashing it anyway`() {
        for (typed in listOf("", "48291", "4829131", "O82913", "H4K9-2FQT", "not a code at all")) {
            assertNull("\"$typed\" is not a code and must not derive a slot", Rendezvous.identity(typed))
        }
    }

    @Test
    fun `the slot name is the relay's alphabet`() {
        // `hostIdFor` in `src/shared/relay-wire.ts`: 26 characters of base32 with no `0`/`O` or
        // `1`/`I`, because a host id gets printed on screens.
        val name = Rendezvous.slotName(ByteArray(32) { 4 })
        assertEquals(26, name.length)
        assertTrue(PairingCodes.isHostId(name))
    }

    /* ------------------------------------------------------------------ offers -- */

    private val offer = """
        {"t":"machine","relayUrl":"wss://relay.terminaldeck.dev",
        "hostId":"PNN7FEFPVPEPG8J6JD5LTK22CW",
        "publicKey":"AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=",
        "name":"Asad's MacBook Pro","platform":"darwin"}
    """.trimIndent().replace("\n", "")

    @Test
    fun `reads the three facts that make an endpoint`() {
        val parsed = checkNotNull(Rendezvous.parseOffer(offer))
        assertEquals("wss://relay.terminaldeck.dev", parsed.relayUrl)
        assertEquals("PNN7FEFPVPEPG8J6JD5LTK22CW", parsed.hostId)
        assertEquals(32, parsed.hostKey.size)
    }

    @Test
    fun `accepts a key in standard base64, which is what the desktop sends`() {
        /*
         * The regression this exists for. An offer carries 32 bytes as **standard** base64, because
         * `machines/ipc.ts` re-encodes them that way, and standard base64 of 32 random bytes
         * contains a `+` or a `/` most of the time — the vector above contains a `+`. A validator
         * written for the base64url form the old pairing link carried would refuse most real
         * machines, intermittently, in a way that reads on screen as a code that had expired.
         */
        assertTrue(offer.contains("+"))
        assertNotNull(Rendezvous.parseOffer(offer))
    }

    @Test
    fun `refuses anything that is not an offer`() {
        assertNull(Rendezvous.parseOffer("not json"))
        assertNull(Rendezvous.parseOffer(offer.replace("\"machine\"", "\"other\"")))
        // A host id in the wrong alphabet would otherwise become a relay dial that 404s, described
        // to the user as their machine being offline.
        assertNull(Rendezvous.parseOffer(offer.replace("PNN7FEFPVPEPG8J6JD5LTK22CW", "lower-case-and-short")))
        assertNull(Rendezvous.parseOffer(offer.replace("wss://relay.terminaldeck.dev", "https://relay.terminaldeck.dev")))
        assertNull(Rendezvous.parseOffer(offer.replace("AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=", "AAAA")))
    }

    @Test
    fun `will not hold an unbounded string on a hostile answer`() {
        assertNull(Rendezvous.parseOffer("\"" + "x".repeat(8192) + "\""))
    }
}
