import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { PathRow } from './AdvancedSection'
import { NotificationsSection, soundHelp } from './NotificationsSection'
import { GeneralSection } from './GeneralSection'
import { HelpSection } from './HelpSection'
import { updateNote } from './AboutSection'
import { SettingControl } from '../controls'
import { FeaturesProvider } from '../../features/FeaturesProvider'
import { SETTINGS, type Setting, type SettingValues } from '../settings-schema'
import type { AboutInfo, ConfigPath } from '../settings-bridge'

/**
 * Settings panes that used to argue with themselves.
 *
 * Every case here was the same defect wearing a different coat: two things on
 * one screen, both generated by code that was individually correct, saying
 * things that cannot both be true. A picker offering one option beside prose
 * explaining there is only one. A "Which sound a finished session plays" line
 * under a switch that stops any session playing one. A Reveal button, fully lit,
 * beside a badge reading "not created yet" for a file it cannot reveal.
 *
 * They are gathered in one file rather than scattered through the section tests
 * because they are one rule — a control says what it does, and nothing beside it
 * says otherwise — and a rule with its cases in one place is a rule somebody can
 * read before adding the next pane.
 *
 * `renderToStaticMarkup` runs no effects, so anything a section fetches on mount
 * is absent here. That is fine for all three: what is being read is what the
 * pane says about state it was handed.
 */

const values: SettingValues = Object.fromEntries(
  SETTINGS.map((setting) => [setting.id, setting.default]),
)

function withValues(over: Record<string, unknown>): SettingValues {
  return { ...values, ...over }
}

function render(node: React.ReactElement): string {
  return renderToStaticMarkup(<FeaturesProvider>{node}</FeaturesProvider>)
}

/* ------------------------------------------------------- General → Language -- */

/**
 * The strongest version of this file's rule, and the one that took two passes.
 *
 * The language row was the original case here: an enabled `<select>` holding
 * exactly "English", beside prose saying English is the only one there is. The
 * first fix drew the row as a *value* instead of a control, which removed the
 * contradiction and left the row.
 *
 * That was not enough, and his answer is why this section now asserts an
 * absence:
 *
 *   > "It will be always English and it is English, so there is no selection.
 *   > The option should not be there."
 *
 * A row that can only ever state a constant is still a row. In a window being
 * cut down for people who are not programmers, it costs the same reading as a
 * setting and gives back nothing that can be acted on.
 */
describe('a row that can only state a constant is not a row', () => {
  it('draws no language row at all', () => {
    const html = render(
      <GeneralSection values={values} save={() => {}} bridge={{}} loading={false} goTo={() => {}} reload={() => {}} />,
    )
    expect(html).not.toContain('Language')
    expect(html).not.toContain('English')
    expect(html).not.toContain('<select')
  })

  /**
   * The *rule* the row used to demonstrate outlived it, and is still enforced
   * where it always was: in `SettingControl`, keyed off the option count rather
   * than off any particular id.
   *
   * Exercised against a setting made up here, because the real table now has no
   * one-option select. A rule that can only be tested through whichever row
   * happens to use it is a rule that quietly stops being tested the day that row
   * changes — which is exactly what just happened.
   */
  it('still draws a one-option select as a value, whatever row has one next', () => {
    const only: Setting = {
      id: 'general.example',
      section: 'general',
      label: 'Example',
      help: 'One option, on purpose.',
      store: 'extra',
      kind: 'select',
      default: 'a',
      options: [{ value: 'a', label: 'Only choice' }],
    }
    const html = render(
      <SettingControl setting={only} values={{ 'general.example': 'a' }} save={() => {}} />,
    )
    expect(html).toContain('Only choice')
    expect(html).not.toContain('<select')

    // And a second option brings the picker straight back, with nobody having
    // to remember that a section file was hiding it.
    const two: Setting = { ...only, options: [...only.options, { value: 'b', label: 'Second' }] }
    expect(
      render(<SettingControl setting={two} values={{ 'general.example': 'a' }} save={() => {}} />),
    ).toContain('<select')
  })
})

/* ------------------------------------------------- Notifications → the sound -- */

describe('the sound row says what is true of it right now', () => {
  it('claims nothing plays it while the switch above is off', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': false })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('Nothing plays this while the switch above is off')
    // The schema sentence, which is false in this state, is gone rather than
    // sitting beside its own correction.
    expect(html).not.toContain('Which sound a finished session plays')
  })

  it('goes back to the schema’s sentence once something does play it', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': true })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('Which sound a finished session plays')
    expect(html).not.toContain('Nothing plays this while')
  })

  /**
   * The recorded decision this fix had to work around, restated where it can
   * fail: Test is a preview and is never disabled, so the *picker* was the
   * thing to resolve. `finish.test.ts` pins the button; this pins that neither
   * it nor the picker was quietly greyed on the way past.
   */
  it('leaves both the picker and Test pressable', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': false })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('>Test</button>')
    expect(html).not.toMatch(/<select[^>]*disabled/)
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Test</)
  })

  it('reads the same off the pure helper', () => {
    expect(soundHelp(true)).toBeUndefined()
    expect(soundHelp(false)).toMatch(/switch above is off/)
    expect(soundHelp(false)).toMatch(/Test still previews it/)
  })
})

/* -------------------------------------------------- Advanced → the path rows -- */

describe('a path row offers only the actions that can work', () => {
  const missingFile = {
    key: 'ipcTrace',
    label: 'Debug trace',
    purpose: 'Every IPC call, recorded while Debug mode is on. Off by default.',
    path: '/x/ipc-trace.log',
    kind: 'file' as const,
    exists: false,
  }
  const realFile = { ...missingFile, key: 'settings', label: 'Settings', path: '/x/settings.json', exists: true }
  const folder = { ...missingFile, key: 'profilesDir', label: 'Profile folders', kind: 'folder' as const }

  function row(entry: ConfigPath): string {
    return render(<PathRow entry={entry} canOpen onCopy={() => {}} onOpen={() => {}} />)
  }

  it('greys Reveal for a file that has not been written, and keeps Copy', () => {
    const html = row(missingFile)
    // A pane that says "not created yet" and then offers to reveal it is the
    // contradiction; the badge is the reason the button is grey.
    expect(html).toContain('not created yet')
    expect(html).toMatch(/<button[^>]*disabled[^>]*>Reveal<\/button>/)
    // Copy acts on the path, which exists as a string either way, so it stays
    // live — a control that looks pressable and answers.
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Copy<\/button>/)
  })

  it('keeps Reveal live for a file that is really there', () => {
    const html = row(realFile)
    expect(html).not.toContain('not created yet')
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Reveal<\/button>/)
    expect(html).toContain('Show this file in your file manager')
  })

  /**
   * Open and Reveal are two verbs because they are two behaviours —
   * `openConfigPath` sends a folder to `shell.openPath` and a file to
   * `shell.showItemInFolder`, deliberately, so a JSON config is never handed to
   * whatever the OS thinks edits .json. The titles are what makes that legible
   * rather than looking like one action with two names.
   */
  it('says which of the two things each verb does', () => {
    expect(row(folder)).toContain('Open this folder in your file manager')
    expect(row(realFile)).toContain('Copy this path to the clipboard')
  })

  /**
   * A folder that does not exist yet still opens, because `openConfigPath`
   * creates it on the way — so greying this one would be inventing a limit the
   * main process does not have.
   */
  it('leaves Open live for a folder the app will create on the way', () => {
    expect(row(folder)).not.toMatch(/<button[^>]*disabled[^>]*>Open<\/button>/)
  })
})

/* --------------------------------------------------- Help → check for updates -- */

/**
 * The last contradiction in this window, and the most direct one: a lit button
 * with **"Press the button to check."** under it, on the one build where
 * pressing it could answer nothing at all.
 *
 * The guard read `about !== null && !checkable`, so a build with no `app:about`
 * channel — `about === null` — fell through it and stayed pressable, while the
 * `??` chain beside it ran out of alternatives and printed the instruction. Two
 * pieces of individually reasonable code, one sentence that could not be true.
 *
 * `updateNote` has a case per state now, which is why it is a function rather
 * than a chain: only one of the three is reachable on any given machine, so the
 * other two are only ever exercised here.
 */
describe('“press this” is only printed beside a button that can be pressed', () => {
  const packaged: AboutInfo = {
    name: 'Deck',
    tagline: '',
    version: '1.0.0',
    electron: '',
    chromium: '',
    node: '',
    platform: '',
    arch: '',
    license: null,
    repository: null,
    homepage: null,
    updates: { packaged: true, feedPresent: true, checkable: true, detail: '' },
  }

  it('says why, rather than "press it", when the build details cannot be read', () => {
    expect(updateNote(null, false)).toBe('Not while the build details cannot be read.')
  })

  it('prefers the main process’s own sentence wherever it has one', () => {
    const fromSource = {
      ...packaged,
      updates: { packaged: false, feedPresent: false, checkable: false, detail: 'Run from source — updates are not checked.' },
    }
    expect(updateNote(fromSource, false)).toBe('Run from source — updates are not checked.')
  })

  it('says the build cannot tell, when it cannot and has not said why', () => {
    expect(updateNote({ ...packaged, updates: null }, false)).toBe(
      'This build cannot tell whether an update exists.',
    )
  })

  it('invites the press only where the press does something', () => {
    expect(updateNote(packaged, true)).toBe('Press the button to check.')
  })

  it('greys the button in every state that cannot check, and says so on hover', () => {
    // Rendered through the pane it now lives on, because the button and the
    // sentence are two elements and the bug was that they disagreed.
    const html = render(
      <HelpSection values={values} save={() => {}} bridge={{}} loading={false} goTo={() => {}} reload={() => {}} />,
    )
    expect(html).toMatch(/<button[^>]*disabled[^>]*>Check for updates<\/button>/)
    expect(html).toContain('Not while the build details cannot be read.')
    expect(html).not.toContain('Press the button to check.')
  })
})
