import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { PathRow } from './AdvancedSection'
import { NotificationsSection, soundHelp } from './NotificationsSection'
import { GeneralSection } from './GeneralSection'
import { FeaturesProvider } from '../../features/FeaturesProvider'
import { getSetting, SETTINGS, type SettingValues } from '../settings-schema'
import type { ConfigPath } from '../settings-bridge'

/**
 * Settings panes that used to argue with themselves.
 *
 * Every case here was the same defect wearing a different coat: two things on
 * one screen, both generated by code that was individually correct, saying
 * things that cannot both be true. A picker offering one option beside prose
 * explaining there is only one. A "Which sound a finished session plays" line
 * under a switch that stops any session playing one. A Reveal button, fully lit,
 * beside a badge reading "not created yet" for a file it cannot reveal.
 *
 * They are gathered in one file rather than scattered through the section tests
 * because they are one rule — a control says what it does, and nothing beside it
 * says otherwise — and a rule with its cases in one place is a rule somebody can
 * read before adding the next pane.
 *
 * `renderToStaticMarkup` runs no effects, so anything a section fetches on mount
 * is absent here. That is fine for all three: what is being read is what the
 * pane says about state it was handed.
 */

const values: SettingValues = Object.fromEntries(
  SETTINGS.map((setting) => [setting.id, setting.default]),
)

function withValues(over: Record<string, unknown>): SettingValues {
  return { ...values, ...over }
}

function render(node: React.ReactElement): string {
  return renderToStaticMarkup(<FeaturesProvider>{node}</FeaturesProvider>)
}

/* ------------------------------------------------------- General → Language -- */

describe('a control with one choice is not drawn as a control', () => {
  it('states the language instead of offering a dropdown that cannot choose', () => {
    const html = render(
      <GeneralSection values={values} save={() => {}} bridge={{}} loading={false} goTo={() => {}} reload={() => {}} />,
    )
    // The answer is still on screen — the row exists to answer the question.
    expect(html).toContain('English')
    // But there is no picker to open. This is the whole complaint: an enabled
    // <select> holding exactly one option, beside a line saying English is the
    // only one there is.
    expect(html).not.toContain('<select')
  })

  /**
   * And it must come back by itself.
   *
   * The rule lives in `SettingControl`, keyed off the option count, rather than
   * in `GeneralSection` keyed off the id — so a second translation restores the
   * picker without anybody remembering that a section file was hiding it.
   */
  it('is a rule about option counts, not a special case for the language row', () => {
    const language = getSetting('general.language')
    expect(language?.kind).toBe('select')
    const theme = getSetting('appearance.theme')
    const html = render(
      <GeneralSection values={values} save={() => {}} bridge={{}} loading={false} goTo={() => {}} reload={() => {}} />,
    )
    expect(html).not.toContain('<select')
    // Theme has three, and is drawn as a picker on its own pane.
    expect(theme?.kind === 'select' && theme.options.length).toBeGreaterThan(1)
  })
})

/* ------------------------------------------------- Notifications → the sound -- */

describe('the sound row says what is true of it right now', () => {
  it('claims nothing plays it while the switch above is off', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': false })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('Nothing plays this while the switch above is off')
    // The schema sentence, which is false in this state, is gone rather than
    // sitting beside its own correction.
    expect(html).not.toContain('Which sound a finished session plays')
  })

  it('goes back to the schema’s sentence once something does play it', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': true })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('Which sound a finished session plays')
    expect(html).not.toContain('Nothing plays this while')
  })

  /**
   * The recorded decision this fix had to work around, restated where it can
   * fail: Test is a preview and is never disabled, so the *picker* was the
   * thing to resolve. `finish.test.ts` pins the button; this pins that neither
   * it nor the picker was quietly greyed on the way past.
   */
  it('leaves both the picker and Test pressable', () => {
    const html = render(
      <NotificationsSection
        values={withValues({ 'notifications.onFinishSound': false })}
        save={() => {}}
        bridge={{}}
        loading={false}
        goTo={() => {}}
        reload={() => {}}
      />,
    )
    expect(html).toContain('>Test</button>')
    expect(html).not.toMatch(/<select[^>]*disabled/)
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Test</)
  })

  it('reads the same off the pure helper', () => {
    expect(soundHelp(true)).toBeUndefined()
    expect(soundHelp(false)).toMatch(/switch above is off/)
    expect(soundHelp(false)).toMatch(/Test still previews it/)
  })
})

/* -------------------------------------------------- Advanced → the path rows -- */

describe('a path row offers only the actions that can work', () => {
  const missingFile = {
    key: 'ipcTrace',
    label: 'Debug trace',
    purpose: 'Every IPC call, recorded while Debug mode is on. Off by default.',
    path: '/x/ipc-trace.log',
    kind: 'file' as const,
    exists: false,
  }
  const realFile = { ...missingFile, key: 'settings', label: 'Settings', path: '/x/settings.json', exists: true }
  const folder = { ...missingFile, key: 'profilesDir', label: 'Profile folders', kind: 'folder' as const }

  function row(entry: ConfigPath): string {
    return render(<PathRow entry={entry} canOpen onCopy={() => {}} onOpen={() => {}} />)
  }

  it('greys Reveal for a file that has not been written, and keeps Copy', () => {
    const html = row(missingFile)
    // A pane that says "not created yet" and then offers to reveal it is the
    // contradiction; the badge is the reason the button is grey.
    expect(html).toContain('not created yet')
    expect(html).toMatch(/<button[^>]*disabled[^>]*>Reveal<\/button>/)
    // Copy acts on the path, which exists as a string either way, so it stays
    // live — a control that looks pressable and answers.
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Copy<\/button>/)
  })

  it('keeps Reveal live for a file that is really there', () => {
    const html = row(realFile)
    expect(html).not.toContain('not created yet')
    expect(html).not.toMatch(/<button[^>]*disabled[^>]*>Reveal<\/button>/)
    expect(html).toContain('Show this file in your file manager')
  })

  /**
   * Open and Reveal are two verbs because they are two behaviours —
   * `openConfigPath` sends a folder to `shell.openPath` and a file to
   * `shell.showItemInFolder`, deliberately, so a JSON config is never handed to
   * whatever the OS thinks edits .json. The titles are what makes that legible
   * rather than looking like one action with two names.
   */
  it('says which of the two things each verb does', () => {
    expect(row(folder)).toContain('Open this folder in your file manager')
    expect(row(realFile)).toContain('Copy this path to the clipboard')
  })

  /**
   * A folder that does not exist yet still opens, because `openConfigPath`
   * creates it on the way — so greying this one would be inventing a limit the
   * main process does not have.
   */
  it('leaves Open live for a folder the app will create on the way', () => {
    expect(row(folder)).not.toMatch(/<button[^>]*disabled[^>]*>Open<\/button>/)
  })
})
