/**
 * Six typed digits, and the machine they have to name.
 *
 * ## The vectors, and why they are the point of this file
 *
 * `rendezvousIdentity` here and `rendezvousIdentity` in
 * `src/main/remote/machines/rendezvous.ts` must produce the *same* host id and
 * the *same* responder key from the same code, or a person types a code
 * correctly and is told no machine is showing it. There is no shared module to
 * make that true by construction — the desktop's copy imports `node:scrypt` and
 * the desktop's own relay client, neither of which can be in a browser bundle —
 * so it is made true by something that fails on the drift instead.
 *
 * The two vectors below were generated by running the desktop's function. If
 * somebody changes the salt, the parameters or the seed layout on either side,
 * one of these stops matching. `shared/pairing-link.ts` restates the host-id
 * alphabet for the same reason and `relay-client.test.ts` cross-checks the
 * relay's own copy of the wire the same way: two implementations of one thing
 * are safe when something breaks on the difference, not when nobody edits either.
 *
 * `pwa/tests/node-crypto.test.ts` holds the other half — that the browser's
 * scrypt is byte-identical to Node's, at these parameters.
 */

import { describe, expect, it } from 'vitest'
import { HOST_SECRET_BYTES } from '../../src/shared/relay-wire'
import {
  generateStatic,
  respondToHandshake,
  type StaticKeyPair,
} from '../../src/shared/sealed'
import {
  HANDSHAKE_OPEN_BYTES,
  readSealedHandshake,
  withSealedVersion,
} from '../../src/shared/relay-wire'
import { hostKeyBytes } from './endpoint'
import { lookupMachine, parseOffer, rendezvousIdentity, RENDEZVOUS_SALT } from './rendezvous'
import type { BinarySocketLike } from './relay-socket'

/**
 * Generated by `rendezvousIdentity` in `src/main/remote/machines/rendezvous.ts`.
 *
 * To regenerate: call that function with the code and print `hostId` and
 * `keys.publicKey.toString('base64')`. Do not regenerate to make a failing test
 * pass — a change to these values is a change every already-shipped client
 * disagrees with.
 */
const VECTORS = [
  {
    code: '482913',
    hostId: 'PNN7FEFPVPEPG8J6JD5LTK22CW',
    publicKey: 'PluJUUCYOIi9dWOnMK0Sq8NrO635DqyD0yTLIyeLlAU=',
  },
  {
    // The leading-zero case, pinned on purpose. A code is six *digits*, not a
    // number: anything that parses `000000` as an integer on the way to the
    // derivation lands on `0`, derives a different slot from every other client,
    // and reads on screen as a code that was typed correctly and found nothing.
    code: '000000',
    hostId: 'ESVP7D6GDHN28MLNU5AEGRGGC7',
    publicKey: 'AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=',
  },
  {
    code: '999999',
    hostId: 'UAFTGU2WS5MN5GYUKF48KJG5SK',
    publicKey: 'bleS0Mpc5kqiW5FJ7wNs6uardUbhJgcrjUN583t7Zx4=',
  },
] as const

describe('the identity a code derives', () => {
  it('is pinned to the salt the desktop uses', () => {
    // Pinned to the literal in two places — here and in
    // `pwa/tests/node-crypto.test.ts` — because the desktop's own constant lives
    // in a module a browser build cannot import.
    expect(RENDEZVOUS_SALT).toBe('terminaldeck-machine-pairing-v1')
  })

  it('matches the desktop, host id and responder key', async () => {
    for (const vector of VECTORS) {
      const identity = await rendezvousIdentity(vector.code)
      expect(identity).not.toBeNull()
      expect(identity?.hostId).toBe(vector.hostId)
      expect(identity?.keys.publicKey.toString('base64')).toBe(vector.publicKey)
    }
  }, 20_000)

  it('lands on one identity however the code was typed', async () => {
    // The two ends derive from the *normalised* string, or pairing depends on
    // what somebody's keyboard put between the digits on the way here.
    const canonical = await rendezvousIdentity('482913')
    for (const typed of ['482-913', ' 482 913 ', '482–913']) {
      expect((await rendezvousIdentity(typed))?.hostId).toBe(canonical?.hostId)
    }
  }, 30_000)

  it('refuses a string that is not a code, instead of hashing it anyway', async () => {
    // Five digits, seven digits, a letter, and the eight-character shape this
    // format replaced — all refused rather than derived into a slot nobody else
    // lands on.
    for (const typed of ['', '48291', '4829131', 'O82913', 'H4K9-2FQT', 'not a code at all']) {
      expect(await rendezvousIdentity(typed)).toBeNull()
    }
  })

  it('spends the first 32 bytes on the slot and the rest on the key', () => {
    // Stated as an assertion because the split is a wire fact: the desktop reads
    // the same seed the same way round, and swapping the halves would produce two
    // machines that both derive valid identities and never meet.
    expect(HOST_SECRET_BYTES).toBe(32)
  })
})

describe('the offer a machine answers with', () => {
  const offer = {
    t: 'machine',
    relayUrl: 'wss://relay.terminaldeck.dev',
    hostId: 'PNN7FEFPVPEPG8J6JD5LTK22CW',
    publicKey: 'AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=',
    name: 'Asad’s MacBook Pro',
    platform: 'darwin',
  }

  it('reads the three facts that make an endpoint', () => {
    expect(parseOffer(JSON.stringify(offer))).toEqual({
      kind: 'relay',
      url: offer.relayUrl,
      hostId: offer.hostId,
      hostKey: offer.publicKey,
    })
  })

  it('accepts a key in standard base64, which is what the desktop sends', () => {
    // The regression this exists for: the offer's key is **standard** base64,
    // because `machines/ipc.ts` re-encodes it that way, and standard base64 of
    // 32 random bytes contains a `+` or a `/` most of the time. A validator
    // written for the base64url form a link used to carry would refuse most real
    // machines at random — the vector above contains a `+` — and read on screen
    // as a code that had expired.
    expect(offer.publicKey).toContain('+')
    expect(hostKeyBytes(offer.publicKey)?.length).toBe(32)
    expect(parseOffer(JSON.stringify(offer))).not.toBeNull()
  })

  it('refuses anything that is not one', () => {
    expect(parseOffer('not json')).toBeNull()
    expect(parseOffer(JSON.stringify({ ...offer, t: 'something-else' }))).toBeNull()
    expect(parseOffer(JSON.stringify({ ...offer, hostId: 'lower-case-and-short' }))).toBeNull()
    expect(parseOffer(JSON.stringify({ ...offer, relayUrl: 'https://relay.example' }))).toBeNull()
    expect(parseOffer(JSON.stringify({ ...offer, publicKey: 'AAAA' }))).toBeNull()
    expect(parseOffer(JSON.stringify([offer]))).toBeNull()
  })

  it('will not hold an unbounded string on a hostile answer', () => {
    expect(parseOffer(`"${'x'.repeat(8192)}"`)).toBeNull()
  })
})

/* ----------------------------------------------------------------- lookup -- */

/**
 * A beacon, as the desktop runs one: a responder keyed by the code that answers
 * with its address and says nothing else.
 *
 * The crypto is the real `respondToHandshake`, so this proves the browser's
 * lookup completes a genuine Noise IK handshake against an identity derived from
 * the code — not that it can parse a JSON string somebody handed it.
 */
function beacon(keys: StaticKeyPair, payload: string | null): { open: (url: string) => BinarySocketLike; urls: string[] } {
  const urls: string[] = []
  return {
    urls,
    open: (url) => {
      urls.push(url)
      const socket: BinarySocketLike = {
        send(data) {
          const opened = readSealedHandshake(Buffer.from(data), HANDSHAKE_OPEN_BYTES)
          if (!opened.ok) return
          const result = respondToHandshake(keys, opened.message, () => true)
          socket.onmessage?.({ data: withSealedVersion(result.reply) })
          if (payload === null) {
            socket.onclose?.({ code: 1000, reason: '' })
            return
          }
          socket.onmessage?.({ data: result.transport.send(Buffer.from(payload, 'utf8')) })
        },
        close: () => {},
        onopen: null,
        onmessage: null,
        onclose: null,
        onerror: null,
      }
      // The relay reaches the machine on the next turn, not on this one.
      setTimeout(() => socket.onopen?.(), 0)
      return socket
    },
  }
}

describe('looking a code up', () => {
  const CODE = '482913'
  const offer = JSON.stringify({
    t: 'machine',
    relayUrl: 'wss://relay.terminaldeck.dev',
    hostId: 'UAFTGU2WS5MN5GYUKF48KJG5SK',
    publicKey: 'bleS0Mpc5kqiW5FJ7wNs6uardUbhJgcrjUN583t7Zx4=',
  })

  it('reaches the machine showing that code and reads its address', async () => {
    const identity = await rendezvousIdentity(CODE)
    if (identity === null) throw new Error('the vector code did not derive an identity')
    const relay = beacon(identity.keys, offer)

    const found = await lookupMachine({ code: CODE, relayUrl: 'wss://relay.example', open: relay.open })
    expect(found?.hostId).toBe('UAFTGU2WS5MN5GYUKF48KJG5SK')
    expect(relay.urls).toEqual(['wss://relay.example/v1/join?host=' + identity.hostId])
  }, 30_000)

  it('finds nothing when the answering machine does not hold the code', async () => {
    // A relay that claimed the slot and answered for itself. Its handshake reply
    // cannot authenticate against a responder key derived from the code, so the
    // channel ends before the offer is ever parsed — which is the whole reason
    // the rendezvous is a sealed channel rather than a lookup table.
    const relay = beacon(generateStatic(), offer)
    expect(await lookupMachine({ code: CODE, relayUrl: 'wss://relay.example', open: relay.open })).toBeNull()
  }, 30_000)

  it('finds nothing when nobody is showing that code', async () => {
    const identity = await rendezvousIdentity(CODE)
    if (identity === null) throw new Error('the vector code did not derive an identity')
    const relay = beacon(identity.keys, null)
    expect(await lookupMachine({ code: CODE, relayUrl: 'wss://relay.example', open: relay.open })).toBeNull()
  }, 30_000)

  it('gives up rather than waiting forever on a relay that never answers', async () => {
    const open = (): BinarySocketLike => ({
      send: () => {},
      close: () => {},
      onopen: null,
      onmessage: null,
      onclose: null,
      onerror: null,
    })
    expect(
      await lookupMachine({ code: CODE, relayUrl: 'wss://relay.example', open, timeoutMs: 50 }),
    ).toBeNull()
  }, 30_000)
})
