import { chmodSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * The preload that runs inside the *guest* page of an embedded browser tab.
 *
 * ## Why the script lives here as a string
 *
 * electron-vite builds exactly one preload entry (`src/preload/index.ts`), and
 * this repo's parallel-agent rule forbids touching the build config. A preload,
 * unlike everything else in `src/main`, has to exist as its own file on disk at
 * runtime because Electron loads it by path. So this module owns the source and
 * writes it out on first use. That also keeps the guest script honest: it is
 * plain ES5-ish JavaScript with no imports, which is all a sandboxed preload
 * can be anyway.
 *
 * ## Why it is so small
 *
 * The guest page is untrusted. This script only *reports facts* — tag names,
 * ids, whether an id is unique in its document, sibling positions. Every
 * decision (which selector wins, what is safe to show, what may reach a
 * terminal) happens in `selector.ts` in the main process, where it is tested.
 *
 * It runs in an isolated world with `contextIsolation` on and `sandbox` on, so
 * the page cannot see or poison it: the DOM is shared, but the JavaScript
 * globals and prototypes are not. Nothing is exposed via `contextBridge`, so
 * page code has no route to the IPC channels either.
 */

/** Guest → main: an element was clicked while inspecting. */
export const GUEST_ELEMENT_CHANNEL = 'terminaldeck-browser:element'
/** Main → guest: turn inspection on or off. */
export const GUEST_INSPECT_CHANNEL = 'terminaldeck-browser:set-inspect'
/** Guest → main: the user pressed Escape inside the page. */
export const GUEST_CANCEL_CHANNEL = 'terminaldeck-browser:inspect-cancelled'

export const GUEST_PRELOAD_FILENAME = 'browser-guest-preload.js'

/**
 * Test-hook attributes the guest looks for, most standard first.
 * Mirrors `TEST_ID_ATTRS` in selector.ts; the main process re-checks the name
 * against its own list, so a tampered payload cannot widen this.
 */
const TEST_ATTRS = ['data-testid', 'data-test-id', 'data-test', 'data-qa', 'data-cy', 'data-automation-id']

/** Attributes carried across for the capture panel. Closed list, by design. */
const ATTR_KEYS = ['aria-label', 'alt', 'placeholder', 'title', 'role', 'type', 'name', 'href']

/*
 * The highlight colours are the app's accent written out literally, because the
 * guest is a different document and cannot read `tokens.css`. If the accent in
 * tokens.css changes, change it here too — there is no way to share it.
 *
 * That instruction had already been ignored once: these stayed the purple-blue
 * #8588f2 through two accent changes, so the picker outlined elements in a
 * colour that appeared nowhere else in the product and read as a rendering bug
 * rather than a selection. This is the dark theme's --accent (#3b8fee, itself
 * the app icon's blue) and its --accent-soft alpha, plus a heavier fill for an
 * element that has actually been captured.
 */
const HIGHLIGHT_BORDER = '#3b8fee'
const HIGHLIGHT_FILL = 'rgba(59, 143, 238, 0.16)'
const CAPTURED_FILL = 'rgba(59, 143, 238, 0.38)'

/**
 * The guest script.
 *
 * Written with doubled backslashes because it is a template literal: `\\s` here
 * becomes `\s` in the generated file. It uses no template literals of its own
 * for the same reason.
 */
export const GUEST_PRELOAD_SOURCE = `'use strict'
/* Generated by Deck from src/main/browser-preload.ts. Do not edit — it is overwritten on launch. */
;(function () {
  var ipc = require('electron').ipcRenderer

  var CH_ELEMENT = ${JSON.stringify(GUEST_ELEMENT_CHANNEL)}
  var CH_INSPECT = ${JSON.stringify(GUEST_INSPECT_CHANNEL)}
  var CH_CANCEL = ${JSON.stringify(GUEST_CANCEL_CHANNEL)}
  var TEST_ATTRS = ${JSON.stringify(TEST_ATTRS)}
  var ATTR_KEYS = ${JSON.stringify(ATTR_KEYS)}

  var MAX_DEPTH = 64
  var MAX_TEXT = 300
  var MAX_ATTR = 300
  var MAX_IDENT = 200

  var BASE_STYLE =
    'position:fixed;top:0;left:0;width:0;height:0;margin:0;padding:0;' +
    'box-sizing:border-box;pointer-events:none;display:none;' +
    'z-index:2147483647;border:2px solid ${HIGHLIGHT_BORDER};border-radius:2px;' +
    'background:${HIGHLIGHT_FILL};'
  var FILL = ${JSON.stringify(HIGHLIGHT_FILL)}
  var FILL_CAPTURED = ${JSON.stringify(CAPTURED_FILL)}

  var active = false
  var overlay = null
  var hovered = null
  var savedCursor = null

  function flatten(value, max) {
    if (typeof value !== 'string') return ''
    // Cut first, collapse second. textContent on a big page is megabytes — and
    // clicking <body> while inspecting asks for exactly that — so an unbounded
    // collapse would hang the page on the click it is meant to capture.
    var raw = value.length > max * 8 ? value.slice(0, max * 8) : value
    var flat = raw.replace(/\\s+/g, ' ').trim()
    return flat.length > max ? flat.slice(0, max) : flat
  }

  function printable(value) {
    return !/[\\u0000-\\u001f\\u007f]/.test(value)
  }

  function ensureOverlay() {
    // isConnected, not a null check: a single-page app can wipe the DOM out
    // from under us, and a detached box would silently stop appearing.
    if (overlay && overlay.isConnected) return overlay
    var box = document.createElement('div')
    box.setAttribute('data-terminaldeck-inspector', '')
    box.style.cssText = BASE_STYLE
    document.documentElement.appendChild(box)
    overlay = box
    return box
  }

  function place(el, captured) {
    var box = ensureOverlay()
    var rect = el.getBoundingClientRect()
    box.style.transform = 'translate(' + Math.round(rect.left) + 'px,' + Math.round(rect.top) + 'px)'
    box.style.width = Math.max(0, Math.round(rect.width)) + 'px'
    box.style.height = Math.max(0, Math.round(rect.height)) + 'px'
    box.style.background = captured ? FILL_CAPTURED : FILL
    box.style.display = 'block'
  }

  function hideOverlay() {
    if (overlay) overlay.style.display = 'none'
  }

  function removeOverlay() {
    if (overlay && overlay.parentNode) overlay.parentNode.removeChild(overlay)
    overlay = null
  }

  function isUnique(selector) {
    try {
      return document.querySelectorAll(selector).length === 1
    } catch (err) {
      return false
    }
  }

  function cssStringOf(value) {
    return '"' + value.replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"') + '"'
  }

  function describe(el) {
    var d = { tag: typeof el.localName === 'string' ? el.localName : '' }

    var id = el.getAttribute('id')
    if (typeof id === 'string' && id !== '' && id.length <= MAX_IDENT && printable(id)) {
      d.id = id
      d.idUnique = isUnique('#' + CSS.escape(id))
    }

    for (var i = 0; i < TEST_ATTRS.length; i++) {
      var name = TEST_ATTRS[i]
      var value = el.getAttribute(name)
      if (typeof value === 'string' && value !== '' && value.length <= MAX_IDENT && printable(value)) {
        d.testAttr = name
        d.testValue = value
        d.testUnique = isUnique('[' + name + '=' + cssStringOf(value) + ']')
        break
      }
    }

    var count = 1
    var index = 1
    var parent = el.parentElement
    if (parent) {
      var kids = parent.children
      count = 0
      for (var j = 0; j < kids.length; j++) {
        var kid = kids[j]
        // :nth-of-type counts by element type, which is local name plus
        // namespace — an <a> in SVG is not the same type as an <a> in HTML.
        if (kid.localName === el.localName && kid.namespaceURI === el.namespaceURI) {
          count++
          if (kid === el) index = count
        }
      }
      if (count < 1) count = 1
    }
    d.ofTypeCount = count
    d.nthOfType = index
    return d
  }

  function pathFrom(el) {
    var path = []
    var node = el
    var depth = 0
    while (node && node.nodeType === 1 && depth < MAX_DEPTH) {
      path.push(describe(node))
      node = node.parentElement
      depth++
    }
    return path
  }

  function isSecretField(el) {
    // The property wins where it exists — a page can set input.type without
    // touching the attribute — and the attribute covers the fake-DOM case.
    var type = typeof el.type === 'string' && el.type !== '' ? el.type : el.getAttribute('type')
    return typeof type === 'string' && type.toLowerCase() === 'password'
  }

  function attributesOf(el) {
    var out = {}
    for (var i = 0; i < ATTR_KEYS.length; i++) {
      var name = ATTR_KEYS[i]
      var value = el.getAttribute(name)
      if (typeof value === 'string' && value !== '') out[name] = flatten(value, MAX_ATTR)
    }
    // What a form control currently holds, which its attribute does not track.
    // Never for a password field: that value would be shown in the capture
    // panel and pasted into the agent's prompt, which is written to disk.
    if (typeof el.value === 'string' && el.value !== '' && !isSecretField(el)) {
      out.value = flatten(el.value, MAX_ATTR)
    }
    return out
  }

  function elementFrom(event) {
    var target = event.target
    if (!target || target.nodeType !== 1) return null
    if (overlay !== null && target === overlay) return null
    return target
  }

  function onOver(event) {
    var el = elementFrom(event)
    if (!el) return
    hovered = el
    place(el, false)
  }

  function onOut() {
    hovered = null
    hideOverlay()
  }

  function reposition() {
    if (hovered && hovered.isConnected) place(hovered, false)
    else hideOverlay()
  }

  function swallow(event) {
    // Inspecting must not also drive the page: a click on a nav link would
    // navigate away from the thing being inspected.
    event.preventDefault()
    event.stopPropagation()
    if (typeof event.stopImmediatePropagation === 'function') event.stopImmediatePropagation()
  }

  function onClick(event) {
    var el = elementFrom(event)
    swallow(event)
    if (!el) return
    place(el, true)
    ipc.send(CH_ELEMENT, {
      v: 1,
      path: pathFrom(el),
      text: flatten(el.textContent, MAX_TEXT),
      attributes: attributesOf(el)
    })
  }

  function onKeyDown(event) {
    if (event.key !== 'Escape') return
    event.preventDefault()
    event.stopPropagation()
    disable()
    ipc.send(CH_CANCEL)
  }

  // Capture phase everywhere, so page handlers never see these first.
  var DOC_EVENTS = [
    ['mouseover', onOver],
    ['mouseout', onOut],
    ['click', onClick],
    ['mousedown', swallow],
    ['mouseup', swallow],
    ['dblclick', swallow],
    ['contextmenu', swallow],
    ['keydown', onKeyDown]
  ]
  var WIN_EVENTS = [
    ['scroll', reposition],
    ['resize', reposition]
  ]

  function enable() {
    if (active) return
    active = true
    for (var i = 0; i < DOC_EVENTS.length; i++) {
      document.addEventListener(DOC_EVENTS[i][0], DOC_EVENTS[i][1], true)
    }
    for (var j = 0; j < WIN_EVENTS.length; j++) {
      window.addEventListener(WIN_EVENTS[j][0], WIN_EVENTS[j][1], true)
    }
    var root = document.documentElement
    // Remember what the page had rather than blanking it, so turning
    // inspection off cannot destroy a cursor the page set itself.
    savedCursor = root.style.cursor
    root.style.cursor = 'crosshair'
    ensureOverlay()
  }

  function disable() {
    if (!active) return
    active = false
    hovered = null
    for (var i = 0; i < DOC_EVENTS.length; i++) {
      document.removeEventListener(DOC_EVENTS[i][0], DOC_EVENTS[i][1], true)
    }
    for (var j = 0; j < WIN_EVENTS.length; j++) {
      window.removeEventListener(WIN_EVENTS[j][0], WIN_EVENTS[j][1], true)
    }
    if (savedCursor !== null) {
      document.documentElement.style.cursor = savedCursor
      savedCursor = null
    }
    removeOverlay()
  }

  ipc.on(CH_INSPECT, function (event, enabled) {
    if (enabled === true) enable()
    else disable()
  })
})()
`

/**
 * Write the guest preload next to the app's other user data and return its
 * absolute path.
 *
 * Rewritten every launch rather than cached: a file left behind by an older
 * version would otherwise keep running against a newer main process.
 *
 * The unlink-then-create dance is not ceremony. `writeFileSync` has two
 * behaviours that matter for a file the app *executes*:
 *
 * - `mode` is ignored when the file already exists, so writing 0o600 over a
 *   file someone else created 0o666 leaves it world-writable — and then we load
 *   it into a preload;
 * - it follows symlinks, so a link planted at this path would send the write
 *   somewhere else entirely and keep the link in place for next time.
 *
 * Removing the path first drops a symlink rather than following it, and `wx`
 * refuses to write anything that reappeared in between rather than writing
 * through it.
 */
export function writeGuestPreload(userDataDir: string): string {
  mkdirSync(userDataDir, { recursive: true })
  const target = join(userDataDir, GUEST_PRELOAD_FILENAME)
  rmSync(target, { force: true })
  // Owner-only: this file is executed by the app, so nothing else should be
  // able to rewrite what it executes.
  writeFileSync(target, GUEST_PRELOAD_SOURCE, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
  // Belt and braces, and honestly so: after the unlink above the create always
  // applies `mode`, so this only matters under a umask strict enough to strip
  // the owner's own bits — which would leave the app unable to read the file it
  // is about to load. Not covered by a test, because setting the umask inside a
  // vitest worker is not something a test should be doing.
  chmodSync(target, 0o600)
  return target
}
