import { chmodSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * The half of a session lift that a cookie jar cannot carry.
 *
 * ## Why this exists at all
 *
 * A lot of sites keep their token in `localStorage` rather than in a cookie,
 * and `session.fromPartition(x)` has no method that writes it. The storage
 * lives inside a renderer, per origin, and the only way in is from a page on
 * that origin. A worker profile that nobody has opened has no such page.
 *
 * The route this repository will **not** take is the obvious one: open a hidden
 * window on the origin, write the keys, close it. A hidden window is the first
 * step of headless, and headless is the single behaviour every target this
 * feature exists for answers with a 403 — so a convenience that quietly creates
 * one is a capability regression, not a shortcut. `browser-workers.ts` says the
 * same thing from the other end and `browser-workers.test.ts` pins it.
 *
 * So the keys **wait**, and they are written by the person's own next page
 * load, in the visible tab strip, by this preload.
 *
 * ## How it gets in
 *
 * `session.registerPreloadScript({ type: 'frame' })`, the same door
 * `browser-record-preload.ts` documents and the same door that attaches the
 * recorder to every profile partition. Two registrations on one session both
 * run; the recorder's is unaffected.
 *
 * ## Why the value is not in this file
 *
 * A preload is a file on disk. Writing a live session token into one would put
 * a credential in `<userData>` — the exact thing `browser-session-lift.ts`
 * keeps out of a store, a log and an IPC reply. So this script carries **no
 * secret at all**: it asks the main process whether the frame it is in has a
 * seed waiting, and the main process answers from memory, once.
 *
 * ## And why the main process does not believe the origin it is told
 *
 * The script sends nothing to identify itself. `browser-workers-ipc.ts` reads
 * the origin off `event.senderFrame` and the partition off `event.sender`, both
 * of which are Chromium's facts about the frame rather than the frame's claims
 * about itself. A page cannot reach `ipcRenderer` — it is in the isolated world
 * — but a design where the *only* protection is that fact is one bad Electron
 * release away from handing a token to a site that asked for it politely.
 */

/** Guest → main, `invoke`. No arguments: the frame is identified by Chromium. */
export const GUEST_SEED_CHANNEL = 'terminaldeck-browser:seed'

export const GUEST_SEED_FILENAME = 'browser-seed-preload.js'

/**
 * The script.
 *
 * Deliberately tiny and deliberately silent. Every failure path returns rather
 * than reporting: this runs in every frame of every worker page, including
 * `about:blank` and cross-origin iframes, and the overwhelmingly common answer
 * is "no seed for you". A log line per frame would be noise, and a throw would
 * be a page that fails to load because a feature nobody used is wired up.
 *
 * It runs at document start, before the page's own scripts, which is what makes
 * it useful: a site that reads its token during boot finds it already there.
 */
export const GUEST_SEED_SOURCE = `'use strict'
/* Generated by Deck from src/main/browser-seed-preload.ts. Do not edit — it is overwritten on launch. */
;(function () {
  var ipc = require('electron').ipcRenderer
  var CH = ${JSON.stringify(GUEST_SEED_CHANNEL)}

  function put(store, entries) {
    if (!store || !entries || !entries.length) return
    for (var i = 0; i < entries.length; i++) {
      var pair = entries[i]
      if (!pair || typeof pair[0] !== 'string' || typeof pair[1] !== 'string') continue
      try {
        store.setItem(pair[0], pair[1])
      } catch (e) {
        /* Quota, or storage disabled for this origin. The other keys still go. */
      }
    }
  }

  try {
    ipc.invoke(CH).then(function (seed) {
      if (!seed) return
      try {
        put(window.localStorage, seed.local)
      } catch (e) {
        /* Some origins have no localStorage at all — a sandboxed frame, a
           data: URL. sessionStorage is asked separately for that reason. */
      }
      try {
        put(window.sessionStorage, seed.session)
      } catch (e) {}
    }, function () {})
  } catch (e) {
    /* No ipcRenderer: nothing to do, and nothing worth breaking a page over. */
  }
})()
`

/**
 * Write the script into `<userData>` and hand back its path.
 *
 * The same shape, mode and `wx`-then-`chmod` dance as `writeRecordPreload`, for
 * the same reasons: 0600 because it is a file this app executes, and a delete
 * first because `wx` refuses an existing path and the file must be replaced on
 * every launch rather than left at whatever an older build wrote.
 */
export function writeSeedPreload(userDataDir: string): string {
  mkdirSync(userDataDir, { recursive: true })
  const target = join(userDataDir, GUEST_SEED_FILENAME)
  rmSync(target, { force: true })
  writeFileSync(target, GUEST_SEED_SOURCE, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
  chmodSync(target, 0o600)
  return target
}

/**
 * The origin of a frame, as Chromium reports it, or `''`.
 *
 * Pure so the one rule that matters can be tested without a renderer: an origin
 * is derived from the frame's **own** URL and from nothing the frame said. A
 * frame on `about:blank`, a `data:` URL or a `file:` URL has no origin worth
 * seeding and gets `''`, which no seed key can ever match.
 */
export function frameOrigin(url: unknown): string {
  if (typeof url !== 'string' || url === '') return ''
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    return ''
  }
  if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return ''
  return parsed.origin
}
