import { chmodSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { GUEST_DOM_HELPERS_SOURCE } from './browser-guest-dom'

/**
 * The flow recorder's guest script: the half that lives inside the untrusted
 * page and watches what the user does to it.
 *
 * ## How it gets in without touching browser-tab.ts
 *
 * `browser-tab.ts` sets one preload through `webPreferences`, and that file is
 * not mine to change. Electron 41 has a second route — `session.registerPreload
 * Script({ type: 'frame' })` — which attaches a preload to every frame using a
 * *session*. Since the guest views all share the `persist:pawl-browser`
 * partition, registering there covers every browser tab, present and future,
 * with no change to how tabs are created.
 *
 * Verified on Electron 41.10.5 rather than assumed, because "both preloads run"
 * is the entire premise: a session-registered preload does run alongside the
 * `webPreferences` one, it runs *first*, and `require('electron').ipcRenderer`
 * is available to it even with `sandbox: true`.
 *
 * ## Recording observes, it does not intervene
 *
 * The inspector swallows the events it sees — a click on a link must not
 * navigate away from the element being inspected. The recorder is the opposite:
 * the user is *using* the page, and a recorder that ate its own clicks would
 * record a flow the page never performed. Every listener here is capture-phase
 * and passive, and re-dispatches nothing.
 *
 * ## Explicit, and visible from inside the page
 *
 * A recorder that can be running without the user knowing is a surveillance
 * bug, not a feature. Recording starts only on an explicit message from the main
 * process, and while it runs the page carries a badge of its own — the app's
 * own chrome is easy to stop looking at once you are absorbed in the page.
 */

/** Main → guest: `{ on: boolean, accent: string }`. */
export const GUEST_RECORD_CHANNEL = 'pawl-browser:set-record'
/** Guest → main: one observed interaction. Validated by `browser-steps.ts`. */
export const GUEST_STEP_CHANNEL = 'pawl-browser:step'

export const GUEST_RECORD_FILENAME = 'browser-record-preload.js'

/**
 * Keys worth a step of their own. Everything else a user types arrives as the
 * field's value on `change`, so logging each keystroke would bury the flow.
 * Escape and Tab are here because they are how a form is *dismissed* or moved
 * through, which a replay has to reproduce.
 */
const NOTABLE_KEYS = ['Enter', 'Escape', 'Tab']

export const GUEST_RECORD_SOURCE = `'use strict'
/* Generated by Pawl from src/main/browser-record-preload.ts. Do not edit — it is overwritten on launch. */
;(function () {
  var ipc = require('electron').ipcRenderer

  var CH_RECORD = ${JSON.stringify(GUEST_RECORD_CHANNEL)}
  var CH_STEP = ${JSON.stringify(GUEST_STEP_CHANNEL)}
  var NOTABLE_KEYS = ${JSON.stringify(NOTABLE_KEYS)}
  var MAX_VALUE = 200
${GUEST_DOM_HELPERS_SOURCE}

  var active = false
  var badge = null
  var accent = ''

  /*
   * System colours, not literals. The guest is a different document and cannot
   * read tokens.css, so the badge is drawn in CSS's own \`Canvas\`/\`CanvasText\`
   * — which follow the page's colour scheme — and only takes a real colour when
   * the renderer hands one over, having read it from tokens.css itself.
   *
   * That goes for the shadow too. A literal black one was here first, and it is
   * exactly the bug this comment warns about one line up: invisible against a
   * dark page, which is where the badge most needs its edge. \`color-mix\` keeps
   * it on the system colour, so it inverts with the page.
   */
  var BADGE_STYLE =
    'position:fixed;right:12px;bottom:12px;z-index:2147483647;pointer-events:none;' +
    'display:flex;align-items:center;gap:6px;padding:5px 9px;border-radius:6px;' +
    'font:600 11px/1.2 -apple-system,BlinkMacSystemFont,Segoe UI,system-ui,sans-serif;' +
    'letter-spacing:0.06em;background:Canvas;color:CanvasText;' +
    'border:1px solid CanvasText;' +
    'box-shadow:0 1px 4px color-mix(in srgb, CanvasText 25%, transparent);'

  function ensureBadge() {
    // isConnected, not a null check: a single-page app can replace the whole
    // document, and a detached badge would silently stop being shown while
    // recording carried on.
    if (badge && badge.isConnected) return badge
    var box = document.createElement('div')
    box.setAttribute('data-pawl-recording', '')
    box.setAttribute('aria-hidden', 'true')
    box.style.cssText = BADGE_STYLE
    var dot = document.createElement('span')
    dot.style.cssText =
      'width:8px;height:8px;border-radius:50%;background:' + (accent || 'CanvasText') + ';'
    var text = document.createTextNode('RECORDING')
    box.appendChild(dot)
    box.appendChild(text)
    if (document.documentElement) document.documentElement.appendChild(box)
    badge = box
    return box
  }

  function removeBadge() {
    if (badge && badge.parentNode) badge.parentNode.removeChild(badge)
    badge = null
  }

  function ours(el) {
    // Our own badge, and the inspector's overlay, are not part of the page.
    return !!(el.closest && el.closest('[data-pawl-recording],[data-pawl-inspector]'))
  }

  function inspecting() {
    // The inspector swallows clicks so the user can point at an element without
    // driving the page. Those clicks are not part of any flow, and this overlay
    // is the one signal both scripts can see, sharing a DOM but not a scope.
    return document.querySelector('[data-pawl-inspector]') !== null
  }

  function targetOf(event) {
    var el = event.target
    if (!el || el.nodeType !== 1) return null
    if (ours(el)) return null
    return el
  }

  function send(kind, el, extra) {
    // Re-assert the badge on every step rather than only when recording starts.
    // \`ensureBadge\` checks isConnected, but nothing was calling it again, so a
    // page that removed our node — a framework reconciling documentElement, or a
    // site doing it on purpose — got a recorder with no visible sign of itself.
    // The check is a cheap identity test on a node we already hold.
    ensureBadge()
    var payload = { v: 1, kind: kind, target: pawlDescribeElement(el) }
    if (extra) {
      for (var key in extra) {
        if (Object.prototype.hasOwnProperty.call(extra, key)) payload[key] = extra[key]
      }
    }
    ipc.send(CH_STEP, payload)
  }

  function onClick(event) {
    if (inspecting()) return
    var el = targetOf(event)
    if (!el) return
    send('click', el)
  }

  function onChange(event) {
    if (inspecting()) return
    var el = targetOf(event)
    if (!el) return
    var tag = typeof el.localName === 'string' ? el.localName : ''
    if (tag !== 'input' && tag !== 'textarea' && tag !== 'select') return

    var type = typeof el.type === 'string' ? el.type.toLowerCase() : ''
    if (type === 'password') {
      // The step still exists — a replay has to know a password was entered —
      // but the value never leaves the page.
      send('type', el, { secret: true })
      return
    }
    if (type === 'checkbox' || type === 'radio') {
      send('check', el, { checked: el.checked === true })
      return
    }
    if (type === 'file') {
      // File pickers cannot be replayed and the path is the user's disk.
      send('type', el, { secret: true })
      return
    }
    if (tag === 'select') {
      var option = el.options && el.selectedIndex >= 0 ? el.options[el.selectedIndex] : null
      send('select', el, {
        value: pawlFlatten(option ? option.textContent : el.value, MAX_VALUE)
      })
      return
    }
    send('type', el, { value: pawlFlatten(el.value, MAX_VALUE) })
  }

  function onKeyDown(event) {
    if (inspecting()) return
    if (NOTABLE_KEYS.indexOf(event.key) === -1) return
    var el = targetOf(event)
    if (!el) return
    send('press', el, { key: event.key })
  }

  function onSubmit(event) {
    if (inspecting()) return
    var el = targetOf(event)
    if (!el) return
    send('submit', el)
  }

  // Capture phase so a page that stops propagation on its own handlers cannot
  // hide what the user did; passive so the recorder can never delay or cancel
  // the interaction it is watching.
  var EVENTS = [
    ['click', onClick],
    ['change', onChange],
    ['keydown', onKeyDown],
    ['submit', onSubmit]
  ]
  var OPTIONS = { capture: true, passive: true }

  function enable(nextAccent) {
    accent = typeof nextAccent === 'string' ? nextAccent : ''
    if (active) {
      ensureBadge()
      return
    }
    active = true
    for (var i = 0; i < EVENTS.length; i++) {
      document.addEventListener(EVENTS[i][0], EVENTS[i][1], OPTIONS)
    }
    ensureBadge()
  }

  function disable() {
    if (!active) return
    active = false
    for (var i = 0; i < EVENTS.length; i++) {
      document.removeEventListener(EVENTS[i][0], EVENTS[i][1], OPTIONS)
    }
    removeBadge()
  }

  ipc.on(CH_RECORD, function (event, options) {
    var on = options !== null && typeof options === 'object' ? options.on === true : options === true
    var nextAccent =
      options !== null && typeof options === 'object' && typeof options.accent === 'string'
        ? options.accent
        : ''
    if (on) enable(nextAccent)
    else disable()
  })
})()
`

/**
 * Write the recorder preload beside the app's other user data and return its
 * absolute path.
 *
 * Same unlink-then-`wx` dance as `writeGuestPreload`, for the same two reasons:
 * `writeFileSync` ignores `mode` when the file already exists (so a
 * world-writable file left by someone else would stay world-writable, and then
 * we execute it), and it follows symlinks (so a link planted at this path would
 * redirect the write and survive to redirect the next one).
 */
export function writeRecordPreload(userDataDir: string): string {
  mkdirSync(userDataDir, { recursive: true })
  const target = join(userDataDir, GUEST_RECORD_FILENAME)
  rmSync(target, { force: true })
  writeFileSync(target, GUEST_RECORD_SOURCE, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
  chmodSync(target, 0o600)
  return target
}

/**
 * Colours accepted from the renderer for the in-page badge.
 *
 * The value is read out of `tokens.css` by the renderer and then spliced into a
 * style string inside an untrusted page, so it is checked rather than trusted:
 * anything that is not plainly a colour is dropped and the badge falls back to
 * the page's own system colours. `rgb()`/`rgba()` are allowed because that is
 * how a computed custom property usually comes back.
 */
const COLOUR = /^(#[0-9a-fA-F]{3,8}|rgba?\([0-9.,\s%/]{3,64}\))$/

export function safeAccent(value: unknown): string {
  if (typeof value !== 'string') return ''
  const trimmed = value.trim()
  return COLOUR.test(trimmed) ? trimmed : ''
}
