/**
 * The pill draws nothing when the connection is fine — and is still there when
 * something asks.
 *
 * `ConnectionGraceTests` proves the rule. This proves the two halves of what the
 * rule does to a screen, and both of them are the kind of claim that is easy to
 * write in a comment and wrong in the build:
 *
 *  1. **Nothing is drawn.** Asad's whole complaint was a yellow thing appearing
 *     on launch and a "Connected" badge sitting there forever. A `showing` flag
 *     that the view quietly ignores would satisfy every test in
 *     `ConnectionGraceTests` and change nothing on the phone.
 *  2. **The element survives anyway.** The connection state is still true when it
 *     is not being shouted about, and VoiceOver asking for it is a person asking
 *     a question the screen has stopped answering out loud. Nine cases in the UI
 *     suite also read this label to know a real desktop is answering, so an
 *     element that vanished would take the whole live-desktop suite with it.
 *
 * ## How each half is checked, and why by two different means
 *
 * "Nothing is drawn" is measured: the real view is hosted in a real window and
 * asked what width it wants. A pill with a dot and a word in it is about ninety
 * points; what stands in for it while hidden is one. That answer comes from the
 * layout engine and goes nowhere near accessibility.
 *
 * "The element is still there" is a walk of the view hierarchy, and it only works
 * because the element is a `UIView` this app makes rather than one SwiftUI
 * synthesises. That was not the first design and the reason for the change is
 * recorded on `accessibleViews` below — briefly: SwiftUI's accessibility tree is
 * empty inside a unit test, for the visible pill as well as the invisible one, so
 * the original version failed while saying nothing at all about the app.
 */

import SwiftUI
import UIKit
import XCTest
@testable import TerminalDeck

@MainActor
final class ConnectionPillTests: XCTestCase {

    private var window: UIWindow?

    override func tearDown() {
        window?.isHidden = true
        window = nil
        super.tearDown()
    }

    /// Put a view on screen for real, and hand back the controller so its own
    /// measurement can be asked for as well as its tree. A hosting controller
    /// that is not in a window is not laid out, and an accessibility tree of a
    /// view that was never laid out is empty for reasons that have nothing to do
    /// with this feature.
    private func host<V: View>(_ view: V) -> UIHostingController<V> {
        let controller = UIHostingController(rootView: view)
        let window = UIWindow(frame: CGRect(x: 0, y: 0, width: 390, height: 200))
        window.rootViewController = controller
        window.makeKeyAndVisible()
        controller.view.layoutIfNeeded()
        // One turn of the run loop, so SwiftUI has hosted its representables.
        // `layoutIfNeeded` lays out the views that already exist; a `UIView` a
        // `UIViewRepresentable` is about to make is not one of them yet.
        RunLoop.current.run(until: Date().addingTimeInterval(0.1))
        self.window = window
        return controller
    }

    /**
     * Every accessible view under a root.
     *
     * A plain walk of `subviews`, and that is only enough because the element
     * being looked for is a real `UIView` — `ConnectionAccessibility`. It was
     * originally a SwiftUI `.accessibilityElement(children: .ignore)`, and that
     * is why this walk is not a walk of `accessibilityElements`: measured on iOS
     * 26.5, a hosted SwiftUI view reports an **empty** accessibility tree through
     * both the array and `accessibilityElementCount()`, for the visible pill as
     * well as the invisible one, because those elements are generated by a render
     * pass an accessibility client drives and there is no client in a unit test.
     * The failure said nothing about the app; making the element a `UIView` is
     * what turned the claim into something a test can hold.
     */
    private func accessibleViews(under root: UIView) -> [UIView] {
        var found: [UIView] = []

        func walk(_ view: UIView) {
            if view.isAccessibilityElement { found.append(view) }
            for sub in view.subviews { walk(sub) }
        }

        walk(root)
        return found
    }

    private func pill(identifier: String, under root: UIView) -> UIView? {
        accessibleViews(under: root).first(where: { $0.accessibilityIdentifier == identifier })
    }

    private var connected: ConnectionState {
        ConnectionState(phase: .online, detail: "Connected.", retryAt: nil, attempts: 0)
    }

    private var reconnecting: ConnectionState {
        ConnectionState(phase: .waiting, detail: "Connection lost.", retryAt: nil, attempts: 3)
    }

    /// What the view asks for on screen. Independent of accessibility entirely:
    /// this is the number the layout engine hands back for the view as written,
    /// so it answers "is anything drawn" without going near the tree.
    private func drawnWidth<V: View>(_ view: V) -> CGFloat {
        let controller = host(view)
        return controller.sizeThatFits(in: CGSize(width: 400, height: 200)).width
    }

    // MARK: - Nothing is drawn

    /**
     * Connected, and the pill is not on the screen.
     *
     * The width is the test. A pill with a dot and the word *Connected* in it is
     * about ninety points wide; what stands in for it while hidden is a single
     * point. Any threshold between the two would do; four is chosen so that a
     * change of font, of padding or of screen scale cannot make this fail for a
     * reason that is not the one it is about.
     */
    func testAConnectedPhoneDrawsNoPill() {
        XCTAssertLessThan(drawnWidth(ConnectionPill(state: connected, showing: false)), 4,
                          "nothing may be drawn while the connection is fine")
    }

    /// The same while a drop is inside its five seconds — which is the case the
    /// whole rule exists for.
    func testABriefDropDrawsNothing() {
        XCTAssertLessThan(drawnWidth(ConnectionPill(state: reconnecting, showing: false)), 4)
    }

    /// Past the five seconds it is a real pill, wide enough to read.
    func testALongDropDrawsAPill() {
        XCTAssertGreaterThan(drawnWidth(ConnectionPill(state: reconnecting, showing: true)), 20,
                             "this is the case the indicator exists for — it has to be visible")
    }

    // MARK: - The element survives being invisible

    /**
     * Nothing is drawn, and the connection can still be asked for.
     *
     * Two readers depend on this and neither of them looks at the screen:
     * VoiceOver, for somebody asking a question the screen has deliberately
     * stopped answering out loud; and nine cases in the live-desktop UI suite,
     * which wait on this label to know a real machine is answering. An element
     * that disappeared along with the ink would take both with it.
     */
    func testTheElementSurvivesBeingInvisibleAndStillTellsTheTruth() throws {
        let controller = host(ConnectionPill(state: connected, showing: false))
        let element = try XCTUnwrap(pill(identifier: "connection.pill", under: controller.view),
                                    "the element must survive being invisible")
        XCTAssertTrue(element.accessibilityLabel?.contains("Connected") == true,
                      "the label still has to be true: \(element.accessibilityLabel ?? "nil")")
        XCTAssertFalse(element.accessibilityTraits.contains(.button),
                       "a connection is a fact, not a control")
    }

    /// And it is there when the pill is drawn too — one element in both states,
    /// rather than two that could disagree about what the connection is.
    func testThereIsExactlyOneSuchElementWhetherOrNotThePillIsDrawn() {
        for showing in [true, false] {
            let controller = host(ConnectionPill(state: reconnecting, showing: showing))
            let matches = accessibleViews(under: controller.view)
                .filter { $0.accessibilityIdentifier == "connection.pill" }
            XCTAssertEqual(matches.count, 1,
                           "showing: \(showing) — VoiceOver must not read the connection twice")
        }
    }

    /// Invisible is not the same as claiming to be fine: while a drop is inside
    /// its five seconds the label says what is really happening.
    func testTheInvisibleElementDoesNotClaimToBeConnected() throws {
        let controller = host(ConnectionPill(state: reconnecting, showing: false))
        let element = try XCTUnwrap(pill(identifier: "connection.pill", under: controller.view))
        XCTAssertTrue(element.accessibilityLabel?.contains("Reconnecting") == true,
                      "invisible is not the same as lying: \(element.accessibilityLabel ?? "nil")")
    }

    // MARK: - The wiring

    /// A transport whose state this test drives.
    private final class ScriptedTransport: Transport {
        var state: ConnectionState = .offline
        var capabilities: Set<String> = []
        var onEvent: ((TransportEvent) -> Void)?
        func start() {}
        func stop() {}
        func resume() {}
        @discardableResult func send(_ message: ClientMessage) -> Bool { true }

        func say(_ state: ConnectionState) {
            self.state = state
            onEvent?(.state(state))
        }
    }

    private final class MemoryStore: CredentialStore {
        private var records: [String: StoredCredential] = [:]
        private let keys = StaticKeyPair.generate()
        func all() -> [StoredCredential] { Array(records.values) }
        func load(_ hostId: String) -> StoredCredential? { records[hostId] }
        func save(_ credential: StoredCredential) { records[credential.hostId] = credential }
        func remove(_ hostId: String) { records.removeValue(forKey: hostId) }
        func clearAll() { records = [:] }
        func deviceKeys() -> StaticKeyPair { keys }
    }

    @MainActor
    private final class ManualScheduler: NoticeScheduler {
        private var body: (() -> Void)?
        private(set) var delay: TimeInterval?

        func schedule(after delay: TimeInterval, _ body: @escaping () -> Void) {
            self.delay = delay
            self.body = body
        }

        func cancel() {
            delay = nil
            body = nil
        }

        func fire() {
            let pending = body
            cancel()
            pending?()
        }
    }

    /**
     * A machine's connection reaches its own notice, and every state does.
     *
     * The rule is a function of the whole sequence rather than of the interesting
     * parts of it — see `ConnectionGrace.unsettledSince` — so a `HostLink` that
     * only forwarded the transitions it thought were important would produce a
     * grace period that restarts on every retry and therefore never expires.
     */
    func testAMachinesStatesReachItsOwnNotice() {
        let clock = Box(Date(timeIntervalSince1970: 1_700_000_000))
        let scheduler = ManualScheduler()
        let notice = ConnectionNotice(now: { clock.value }, scheduler: scheduler)
        let transport = ScriptedTransport()

        let link = HostLink(credential: credential(),
                            credentials: MemoryStore(),
                            device: DeviceDescriptor(name: "iPhone", platform: "iOS 26"),
                            makeTransport: { _, _, _ in transport },
                            notice: notice)
        link.start()
        XCTAssertFalse(notice.isShowing, "a launch is quiet")

        transport.say(ConnectionState(phase: .connecting, detail: "Connecting…",
                                      retryAt: nil, attempts: 0))
        clock.value = clock.value.addingTimeInterval(2)
        transport.say(ConnectionState(phase: .waiting, detail: "Connection lost.",
                                      retryAt: nil, attempts: 1))
        XCTAssertFalse(notice.isShowing, "two seconds in, still nothing")

        clock.value = clock.value.addingTimeInterval(3)
        scheduler.fire()
        XCTAssertTrue(notice.isShowing, "five seconds of trying is worth saying")
        XCTAssertTrue(link.notice === notice, "the machine reads the same object the screens do")

        transport.say(ConnectionState(phase: .online, detail: "Connected.", retryAt: nil, attempts: 0))
        XCTAssertFalse(notice.isShowing, "and it goes quiet again the moment it is back")
    }

    /// A mutable cell, so the clock closure above can be advanced from the test
    /// without capturing a `var` it is not allowed to.
    private final class Box<T> {
        var value: T
        init(_ value: T) { self.value = value }
    }

    private func credential() -> StoredCredential {
        StoredCredential(endpoint: .relay(url: URL(string: "wss://relay.example")!,
                                          hostId: "M9G95TNJT64Q928VW3HVRYDR8J",
                                          hostKey: Data(repeating: 5, count: 32)),
                         token: "t",
                         kind: .device,
                         deviceId: "d",
                         deviceName: "iPhone",
                         pairedAt: Date(timeIntervalSince1970: 1),
                         nickname: "MacBook")
    }
}
