/**
 * The one byte this client used to leave off, pinned against the desktop's own
 * numbers.
 *
 * ## Why this file exists separately from `SealedChannelTests`
 *
 * Because the bug it guards against was invisible to that suite and always would
 * have been. `SealedChannelTests` asserts the Swift port of `sealed.ts` against
 * vectors generated by running `sealed.ts`, and it passed — the Noise handshake
 * was correct to the byte. What was missing was the layer *above* it:
 * `src/shared/relay-wire.ts` puts a version byte in front of each handshake
 * message, so a relay carries 81 bytes out and 49 back, and this app was sending
 * 80 and expecting 48.
 *
 * A real Mac answers a first payload of the wrong length by closing the channel
 * and saying nothing — deliberately, so that a hostile relay learns nothing from
 * a refusal — so the failure reached the user as "that Mac is not connected to
 * the relay right now" and nothing anywhere said otherwise. Both stand-in hosts
 * skipped the byte too, so every test in the repository agreed with every other
 * test and all of them disagreed with the product.
 *
 * ## What makes these assertions non-circular
 *
 * The numbers below are not transcribed from the TypeScript by hand; they are
 * read out of `Tests/Fixtures/sealed-vectors.json`, which `ios/Harness/run.sh
 * vectors` writes by *calling* `withSealedVersion` in the real module. The
 * fixture also carries each handshake message twice — unframed and framed — so a
 * port cannot satisfy one assertion by breaking the other. Change the contract in
 * `relay-wire.ts`, regenerate, and this file fails until the Swift side is moved
 * with it.
 *
 * The literal 81 and 49 appear once each, in `testTheWireIsEightyOneOutAndFortyNineBack`,
 * and that is on purpose: a test whose every number comes from the same file it
 * is checking cannot notice the file changing.
 */

import XCTest
@testable import TerminalDeck

final class RelayWireTests: XCTestCase {

    // MARK: - Fixtures

    private struct Vectors: Decodable {
        struct Wire: Decodable {
            let sealedVersion: Int
            let noiseMessageBytes: Int
            let noiseReplyBytes: Int
            let handshakeOpenBytes: Int
            let handshakeReplyBytes: Int
        }
        struct Session: Decodable {
            let label: String
            let handshakeMessage: String
            let reply: String
            let framedHandshakeMessage: String
            let framedReply: String
        }
        let relayWire: Wire
        let sessions: [Session]
    }

    private static let vectors: Vectors = {
        guard let url = Bundle(for: RelayWireTests.self)
            .url(forResource: "sealed-vectors", withExtension: "json") else {
            fatalError("sealed-vectors.json is not in the test bundle. "
                       + "Regenerate it with ios/Harness/run.sh vectors.")
        }
        return try! JSONDecoder().decode(Vectors.self, from: try! Data(contentsOf: url))
    }()

    private func hex(_ value: String) -> Data {
        var out = Data(capacity: value.count / 2)
        var index = value.startIndex
        while index < value.endIndex {
            let next = value.index(index, offsetBy: 2)
            out.append(UInt8(value[index ..< next], radix: 16)!)
            index = next
        }
        return out
    }

    private func hex(_ value: Data) -> String {
        value.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - The byte counts, said out loud

    /**
     * The whole bug, as four numbers.
     *
     * Written as literals rather than derived from anything, so that this case
     * fails if the constants move for any reason at all — including someone
     * "fixing" `Sealed.noiseMessageBytes` to 81 to make a connection work, which
     * is the shortcut that would put the version byte inside the transcript hash
     * and break the handshake in a much harder way.
     */
    func testTheWireIsEightyOneOutAndFortyNineBack() {
        XCTAssertEqual(Sealed.noiseMessageBytes, 80, "the Noise IK message is 80 bytes")
        XCTAssertEqual(Sealed.noiseReplyBytes, 48, "the Noise IK reply is 48 bytes")
        XCTAssertEqual(RelayWire.handshakeOpenBytes, 81, "the wire carries 81 bytes out")
        XCTAssertEqual(RelayWire.handshakeReplyBytes, 49, "the wire carries 49 bytes back")
        XCTAssertEqual(RelayWire.sealedVersion, 1, "the version byte is 0x01")
    }

    /// And the same numbers as the desktop produced them, so the two cannot part
    /// company without a regeneration making it obvious.
    func testTheConstantsMatchTheDesktopsOwn() {
        let wire = Self.vectors.relayWire
        XCTAssertEqual(Int(RelayWire.sealedVersion), wire.sealedVersion)
        XCTAssertEqual(Sealed.noiseMessageBytes, wire.noiseMessageBytes)
        XCTAssertEqual(Sealed.noiseReplyBytes, wire.noiseReplyBytes)
        XCTAssertEqual(RelayWire.handshakeOpenBytes, wire.handshakeOpenBytes)
        XCTAssertEqual(RelayWire.handshakeReplyBytes, wire.handshakeReplyBytes)
    }

    // MARK: - Framing, against bytes the desktop framed

    func testFramesAHandshakeExactlyAsTheDesktopDoes() {
        for session in Self.vectors.sessions {
            let framed = RelayWire.withSealedVersion(hex(session.handshakeMessage))
            XCTAssertEqual(hex(framed), session.framedHandshakeMessage, session.label)
            XCTAssertEqual(framed.count, RelayWire.handshakeOpenBytes, session.label)
            XCTAssertEqual(framed.first, RelayWire.sealedVersion, session.label)
        }
    }

    func testAWholeHandshakeGoesOutAtEightyOneBytes() throws {
        // Not the fixture's recorded message but a fresh one, because production
        // frames whatever `SealedHandshake.start` just produced and a constant
        // that only lines up with a stored vector is not a constant.
        let device = StaticKeyPair.generate()
        let mac = StaticKeyPair.generate()
        let started = try SealedHandshake.start(deviceStatic: device, responderStaticPublic: mac.publicKey)

        XCTAssertEqual(started.message.count, 80, "sealed.ts's half is unchanged")
        let onTheWire = RelayWire.withSealedVersion(started.message)
        XCTAssertEqual(onTheWire.count, 81, "and the wire adds exactly one byte")
        XCTAssertEqual(onTheWire.first, 0x01)
        XCTAssertEqual(Data(onTheWire.dropFirst()), started.message, "the byte is a prefix, not a replacement")
    }

    // MARK: - Reading a reply

    func testReadsTheDesktopsFramedReply() {
        for session in Self.vectors.sessions {
            let framed = hex(session.framedReply)
            XCTAssertEqual(framed.count, 49, session.label)

            let opened = RelayWire.readSealedHandshake(framed, expected: RelayWire.handshakeReplyBytes)
            guard case let .ok(reply) = opened else {
                return XCTFail("the desktop's own reply was refused (\(session.label))")
            }
            XCTAssertEqual(hex(reply), session.reply, session.label)
            XCTAssertEqual(reply.count, Sealed.noiseReplyBytes, session.label)
        }
    }

    /**
     * The exact shape of the old bug: 48 bytes where 49 belong.
     *
     * It must be refused rather than misparsed. A 48-byte reply read as if it
     * were framed would take the responder's first key byte as a version and
     * hand `finish` 47 bytes, which fails as a length error — a sentence about
     * cryptography for what is really a client one version behind.
     */
    func testRefusesAnUnframedReply() {
        let unframed = hex(Self.vectors.sessions[0].reply)
        XCTAssertEqual(unframed.count, 48)
        XCTAssertEqual(RelayWire.readSealedHandshake(unframed, expected: RelayWire.handshakeReplyBytes),
                       .refused(.malformed(count: 48, expected: 49)))
    }

    func testRefusesAVersionThisBuildDoesNotSpeak() {
        var framed = hex(Self.vectors.sessions[0].framedReply)
        framed[framed.startIndex] = 0x02
        let opened = RelayWire.readSealedHandshake(framed, expected: RelayWire.handshakeReplyBytes)
        XCTAssertEqual(opened, .refused(.wrongVersion(0x02)))

        guard case let .refused(reason) = opened else { return XCTFail("expected a refusal") }
        // The distinction exists so the phone can say which of the two ends is
        // out of date. If the sentence stops naming a version, it has stopped
        // being worth distinguishing.
        XCTAssertTrue(reason.sentence.contains("version"), reason.sentence)
        XCTAssertFalse(reason.sentence.isEmpty)
    }

    func testRefusesAReplyOfAnyOtherLength() {
        let framed = hex(Self.vectors.sessions[0].framedReply)
        for count in [0, 1, 47, 48, 50, 81] {
            let payload = count <= framed.count
                ? Data(framed.prefix(count))
                : framed + Data(repeating: 0, count: count - framed.count)
            XCTAssertEqual(RelayWire.readSealedHandshake(payload, expected: RelayWire.handshakeReplyBytes),
                           .refused(.malformed(count: count, expected: 49)),
                           "\(count) bytes must not be read as a reply")
        }
    }

    /// A slice whose indices do not start at zero — what `Data` hands back from
    /// a `dropFirst` upstream. Reading `payload[0]` instead of
    /// `payload[startIndex]` would crash or read the wrong byte.
    func testReadsARebasedSlice() {
        let framed = hex(Self.vectors.sessions[0].framedReply)
        let slice = (Data([0xff]) + framed).dropFirst()
        XCTAssertNotEqual(slice.startIndex, 0, "the slice must actually be rebased for this to test anything")
        guard case let .ok(reply) = RelayWire.readSealedHandshake(slice, expected: 49) else {
            return XCTFail("a rebased slice was refused")
        }
        XCTAssertEqual(hex(reply), Self.vectors.sessions[0].reply)
    }

    // MARK: - End to end, framed

    /**
     * Frame, unframe, and complete a handshake against the fixture's recorded
     * reply.
     *
     * This is the case that would have caught the original bug: it goes through
     * the same two functions the carrier calls, in the same order, on bytes the
     * desktop produced.
     */
    func testAFramedRoundTripCompletesAHandshake() throws {
        for session in Self.vectors.sessions {
            let framedOut = RelayWire.withSealedVersion(hex(session.handshakeMessage))
            XCTAssertEqual(framedOut.count, RelayWire.handshakeOpenBytes, session.label)

            // The responder's side of the same check: what the Mac does with
            // what this app sends.
            guard case let .ok(message) = RelayWire.readSealedHandshake(framedOut, expected: RelayWire.handshakeOpenBytes) else {
                return XCTFail("the desktop would have refused this app's handshake (\(session.label))")
            }
            XCTAssertEqual(hex(message), session.handshakeMessage, session.label)
        }
    }
}
