/**
 * The derivation every client has to agree on, and the channel it opens.
 *
 * ## Why the vectors are the point of this file
 *
 * `Rendezvous.identity` here and `rendezvousIdentity` in
 * `src/main/remote/machines/rendezvous.ts` must produce the **same** host id and
 * the **same** responder key from the same six digits, or a person types a code
 * correctly and is told no machine is showing it. There is no shared module that
 * could make that true by construction — one is Swift and the other imports
 * `node:crypto` — so it is made true by something that fails on the drift
 * instead.
 *
 * The vectors below were generated by running the desktop's function. If
 * somebody changes the salt, a cost parameter, the seed length or the split
 * between the slot secret and the responder key on either side, one of these
 * stops matching. `pwa/src/rendezvous.test.ts` and
 * `android/…/pairing/RendezvousTest.kt` hold the same line from their sides.
 *
 * ## What is *not* tested here, and where it is
 *
 * That the sealed channel itself is byte-compatible with the desktop's:
 * `SealedChannelTests` and `SealedInteropTest` already replay real vectors from
 * `sealed.ts`. This file is about the identity the channel is keyed with.
 */

import XCTest
@testable import TerminalDeck

/**
 * Generated by `rendezvousIdentity` in `src/main/remote/machines/rendezvous.ts`.
 *
 * To regenerate: call that function with the code and print `hostId` and
 * `keys.publicKey.toString('base64')`. Do not regenerate to make a failing test
 * pass — a change to these values is a change every already-shipped client
 * disagrees with.
 */
private let vectors: [(code: String, hostId: String, publicKey: String)] = [
    ("482913", "PNN7FEFPVPEPG8J6JD5LTK22CW", "PluJUUCYOIi9dWOnMK0Sq8NrO635DqyD0yTLIyeLlAU="),
    // The leading-zero case, pinned on purpose. A code is six *digits*, not a
    // number, and anything that parses `000000` as an integer on the way to the
    // derivation lands on `0` and derives a slot nobody else is sitting in.
    ("000000", "ESVP7D6GDHN28MLNU5AEGRGGC7", "AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc="),
    ("999999", "UAFTGU2WS5MN5GYUKF48KJG5SK", "bleS0Mpc5kqiW5FJ7wNs6uardUbhJgcrjUN583t7Zx4="),
]

final class RendezvousTests: XCTestCase {

    func testTheSaltIsTheDesktops() {
        // One line, and it is the line that turns a silent disagreement into a
        // red test. The desktop asserts the same literal from its side.
        XCTAssertEqual(Rendezvous.salt, "terminaldeck-machine-pairing-v1")
        XCTAssertEqual(Rendezvous.scryptN, 16384)
        XCTAssertEqual(Rendezvous.scryptR, 8)
        XCTAssertEqual(Rendezvous.scryptP, 1)
        XCTAssertEqual(Rendezvous.seedBytes, 64)
    }

    func testTheCostParametersAreNotNegotiable() {
        /*
         * Asserted as values rather than merely used, because this is the whole
         * reason six digits is defensible.
         *
         * There are 10^6 codes and a slot lookup is an unlimited oracle for
         * "is this the live one". At a hash, an attacker sweeps the million in
         * seconds, learns the code exactly, and the five-guess budget the desktop
         * enforces buys nothing. At N = 16384, r = 8 a guess costs 16 MiB and
         * tens of milliseconds — ten CPU-hours for the space, inside a
         * sixty-second window. Lowering N "because it is slow on a phone" is the
         * change this assertion exists to stop.
         */
        XCTAssertEqual(128 * Rendezvous.scryptR * Rendezvous.scryptN, 16 * 1024 * 1024)
    }

    func testMatchesTheDesktopHostIdAndResponderKey() async {
        for vector in vectors {
            let identity = await Rendezvous.identity(for: vector.code)
            XCTAssertEqual(identity?.hostId, vector.hostId, "slot for \(vector.code)")
            XCTAssertEqual(identity?.keys.publicKey.base64EncodedString(), vector.publicKey,
                           "responder key for \(vector.code)")
        }
    }

    func testLandsOnOneIdentityHoweverTheCodeWasTyped() async {
        // Both ends derive from the *normalised* string, or pairing depends on
        // what somebody's keyboard put between the digits on the way here.
        let canonical = await Rendezvous.identity(for: "482913")
        for typed in ["482-913", " 482 913 ", "482\u{2013}913"] {
            let other = await Rendezvous.identity(for: typed)
            XCTAssertEqual(other?.hostId, canonical?.hostId, "\(typed) should be the same slot")
        }
    }

    func testRefusesAStringThatIsNotACodeInsteadOfHashingItAnyway() async {
        for typed in ["", "48291", "4829131", "O82913", "H4K9-2FQT", "not a code at all"] {
            let identity = await Rendezvous.identity(for: typed)
            XCTAssertNil(identity, "\(typed) is not a code and must not derive a slot")
        }
    }

    func testTheSlotNameIsTheRelaysAlphabet() {
        // `hostIdFor` in `src/shared/relay-wire.ts`: 26 characters of base32 with
        // no `0`/`O` or `1`/`I`, because a host id gets printed on screens.
        let name = Rendezvous.slotName(for: Data(repeating: 4, count: 32))
        XCTAssertEqual(name.count, 26)
        XCTAssertTrue(PairingCodeParser.isHostId(name))
    }

    // MARK: - The offer

    private let offer = """
    {"t":"machine","relayUrl":"wss://relay.terminaldeck.dev",\
    "hostId":"PNN7FEFPVPEPG8J6JD5LTK22CW",\
    "publicKey":"AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=",\
    "name":"Asad’s MacBook Pro","platform":"darwin"}
    """

    func testReadsTheThreeFactsThatMakeAnEndpoint() throws {
        let parsed = try XCTUnwrap(Rendezvous.parseOffer(offer))
        XCTAssertEqual(parsed.relayURL.absoluteString, "wss://relay.terminaldeck.dev")
        XCTAssertEqual(parsed.hostId, "PNN7FEFPVPEPG8J6JD5LTK22CW")
        XCTAssertEqual(parsed.hostKey.count, 32)
        XCTAssertTrue(parsed.endpoint.isSealed)
    }

    func testAcceptsAKeyInStandardBase64WhichIsWhatTheDesktopSends() throws {
        /*
         * The regression this exists for. An offer carries 32 bytes as
         * **standard** base64, because `machines/ipc.ts` re-encodes them that
         * way, and standard base64 of 32 random bytes contains a `+` or a `/`
         * most of the time — the vector above contains a `+`. A validator written
         * for the base64url form the old pairing link carried would refuse most
         * real machines, intermittently, in a way that reads on screen as a code
         * that had expired.
         */
        XCTAssertTrue(offer.contains("+"))
        XCTAssertNotNil(Rendezvous.parseOffer(offer))
    }

    func testRefusesAnythingThatIsNotAnOffer() {
        XCTAssertNil(Rendezvous.parseOffer("not json"))
        XCTAssertNil(Rendezvous.parseOffer(offer.replacingOccurrences(of: "\"machine\"", with: "\"other\"")))
        // A host id in the wrong alphabet would otherwise become a relay dial
        // that 404s, described to the user as their Mac being offline.
        XCTAssertNil(Rendezvous.parseOffer(offer.replacingOccurrences(
            of: "PNN7FEFPVPEPG8J6JD5LTK22CW", with: "lower-case-and-short")))
        XCTAssertNil(Rendezvous.parseOffer(offer.replacingOccurrences(
            of: "wss://relay.terminaldeck.dev", with: "https://relay.terminaldeck.dev")))
        XCTAssertNil(Rendezvous.parseOffer(offer.replacingOccurrences(
            of: "AFF3srTJviOR9zEbStt+iPZuTjl1Gp595oLklTIfLgc=", with: "AAAA")))
    }

    func testWillNotHoldAnUnboundedStringOnAHostileAnswer() {
        XCTAssertNil(Rendezvous.parseOffer("\"" + String(repeating: "x", count: 8192) + "\""))
    }
}
