/**
 * scrypt, against somebody else's numbers.
 *
 * `Scrypt.swift` is hand-written because Apple ships no scrypt at any deployment
 * target this app supports, and a hand-written KDF is worth exactly as much as
 * the vectors it is checked against. So it is checked against two sets that this
 * repository did not invent:
 *
 *  1. **RFC 7914 §12** — the specification's own published test vectors. Three
 *     of the four are here; the fourth (N = 1048576) allocates a gigabyte and
 *     takes minutes, which is not a thing to put in a unit suite on a phone.
 *  2. **`node:crypto`** — the desktop's own scrypt, at the product's real
 *     parameters and salt, for real six-digit codes. Generated by running
 *     `scryptSync(code, RENDEZVOUS_SALT, 64, { N: 16384, r: 8, p: 1 })` and
 *     pasted here. This is the one that matters in practice: the RFC vectors say
 *     the algorithm is right, and these say this app and that desktop will land
 *     on the same rendezvous slot.
 *
 * A vector here is never regenerated to make a failing test pass. A change to
 * these bytes is a change every already-shipped client disagrees with, which is
 * every pairing failing with "no machine is showing that code".
 */

import XCTest
@testable import TerminalDeck

final class ScryptTests: XCTestCase {

    private func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - RFC 7914 §12

    func testTheEmptyVector() throws {
        let out = try Scrypt.derive(password: Data(), salt: Data(), n: 16, r: 1, p: 1, length: 64)
        XCTAssertEqual(hex(out),
            "77d6576238657b203b19ca42c18a0497f16b4844e3074ae8dfdffa3fede21442" +
            "fcd0069ded0948f8326a753a0fc81f17e8d3e0fb2e0d3628cf35e20c38d18906")
    }

    func testTheVectorWithRAndPBothAboveOne() throws {
        /*
         * The load-bearing one, and the reason the first vector is not enough.
         *
         * With r = 1 the BlockMix shuffle — even-indexed outputs first, then the
         * odd ones — is the identity, so a port that dropped it entirely still
         * passes the empty vector. This one has r = 8 and p = 16, so it exercises
         * the shuffle and the per-lane loop together.
         */
        let out = try Scrypt.derive(
            password: Data("password".utf8), salt: Data("NaCl".utf8), n: 1024, r: 8, p: 16, length: 64)
        XCTAssertEqual(hex(out),
            "fdbabe1c9d3472007856e7190d01e9fe7c6ad7cbc8237830e77376634b373162" +
            "2eaf30d92e22a3886ff109279d9830dac727afb94a83ee6d8360cbdfa2cc0640")
    }

    func testTheVectorAtTheParametersThisAppActuallyUses() throws {
        // N = 16384, r = 8, p = 1 — the rendezvous parameters, with the RFC's
        // password and salt so the answer is somebody else's number.
        let out = try Scrypt.derive(
            password: Data("pleaseletmein".utf8), salt: Data("SodiumChloride".utf8),
            n: 16384, r: 8, p: 1, length: 64)
        XCTAssertEqual(hex(out),
            "7023bdcb3afd7348461c06cd81fd38ebfda8fbba904f8e3ea9b543f6545da1f2" +
            "d5432955613f0fcf62d49705242a9af9e61e85dc0d651e40dfcf017b45575887")
    }

    // MARK: - The desktop's own scrypt, on real codes

    func testMatchesNodeForTheProductsOwnSeeds() throws {
        let vectors = [
            ("482913",
             "646639452580485e5bedb2a94a33340c6c00e6408ad91636c9144a00552f202b" +
             "8a9cbc26a0a81dbe81811217934593f968d4378c98b57bdd8589b8b0bec8cd89"),
            // The leading-zero code, which is the one a port that treats a code
            // as a number gets wrong.
            ("000000",
             "3e8b1acd8b25acff38a710d28c4359d58d3218702af3c1c3cc60debae372635f" +
             "76399aa751f774187b7de853bd346231b1d74c20b6dc15c9192a891e69a421f9"),
            ("999999",
             "d3399bce6b1316cf2992f0db0cf2f208168244d02d29f985230b98440796ac84" +
             "39c372d86dcba1ee45fe4bc3d50f5b3f2a20ef02323cea8368e0d0fd72cc2033"),
        ]
        for (code, expected) in vectors {
            let out = try Scrypt.derive(
                password: Data(code.utf8),
                salt: Data(Rendezvous.salt.utf8),
                n: Rendezvous.scryptN, r: Rendezvous.scryptR, p: Rendezvous.scryptP,
                length: Rendezvous.seedBytes)
            XCTAssertEqual(hex(out), expected, "the seed for \(code) is not the desktop's")
        }
    }

    // MARK: - Refusals

    func testRefusesParametersThatWouldSilentlyChangeTheFunction() {
        // `mod N` in ROMix is done as a mask, so a non-power-of-two N would be a
        // different function rather than a slower one. It is refused rather than
        // rounded, because rounding would produce bytes nothing else derives.
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 1000, r: 8, p: 1, length: 32))
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 1, r: 8, p: 1, length: 32))
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 16, r: 0, p: 1, length: 32))
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 16, r: 1, p: 1, length: 0))
    }

    func testRefusesParametersThatWouldAllocateThePhoneOutOfMemory() {
        // 128 * r * N bytes of scratch. Bounded so a typo is an error rather than
        // a process the OS kills with no message anybody can read.
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 1 << 24, r: 8, p: 1, length: 32))
        XCTAssertThrowsError(try Scrypt.derive(password: Data(), salt: Data(), n: 16, r: 64, p: 1, length: 32))
    }
}
