#!/usr/bin/env node
/**
 * Fetch every store logo once, and write them into the app as bytes.
 *
 * ## Why the logos are fetched here and not in the store
 *
 * A store row is a claim about somebody else's project, and the mark on it is
 * the fastest way a person recognises which project. The obvious way to get one
 * on screen is `<img src="https://vendor.example/logo.svg">`, and it is the one
 * thing this file exists to prevent: an `<img>` pointed at a third-party host is
 * a request to that host **every time the store opens**, carrying an IP address
 * and a referrer to eighteen companies at once, and it draws nothing at all on a
 * laptop with no network. Neither is acceptable in a store whose whole argument
 * is that the bytes it offers were pinned in advance.
 *
 * So each mark is fetched **once, here, by hand**, and what the app ships is the
 * result. `src/renderer/store/logo-data.ts` is generated by this script and is
 * the only place those bytes live. At runtime the store reads a data URI out of
 * its own bundle; it opens the same offline as online and asks nobody anything.
 *
 * ## Why a generated module rather than files in a folder
 *
 * Because there is no other image in this renderer — not one `.png`, not one
 * `.svg`, checked before choosing — so files on disk would mean a new packaging
 * path (Vite emits some assets and inlines others under its 4 KB limit, and
 * `electron-builder.yml` would then be shipping two kinds of thing) invented for
 * a feature whose whole content is 42 small pictures. A module of data URIs is
 * one path: it is code, it is inside `out/**` like every other line of code, it
 * works identically in the app, in `vitest`, and in `.harness/stores.html`, and
 * there is nothing to forget to copy.
 *
 * The cost is a large generated file, and it is capped rather than hoped about:
 * {@link MAX_BYTES} refuses any single mark over 24 KB encoded, and the script
 * prints the total so the budget is a number somebody looked at.
 *
 * ## What is recorded, so this is auditable and refreshable
 *
 * Every row of {@link LOGOS} names the exact URL it was fetched from, and the
 * generated file carries that URL back with the sha256 of the bytes that came
 * back and the date they came back. That is what makes a refresh checkable:
 *
 * ```
 *   node scripts/store-logos.mjs --check   # re-fetch, compare, write nothing
 *   node scripts/store-logos.mjs           # re-fetch and rewrite the module
 * ```
 *
 * `--check` reports every mark whose upstream bytes have changed and exits
 * non-zero if any did. It is not in CI: it is a network call to twenty hosts,
 * and a red build because a vendor re-exported their SVG is a gate nobody would
 * keep. Run it when a logo looks wrong.
 *
 * GitHub sources are pinned to a **commit sha**, not a branch, so the URL in the
 * generated file resolves to the same bytes forever. Vendor sites cannot be
 * pinned that way, and for those the sha256 is the pin — which is the same
 * arrangement `browser-extension-catalogue.ts` makes for the release archives it
 * downloads, for the same reason.
 *
 * ## Trademarks
 *
 * These are third-party marks, used to identify the products the rows are
 * about. Nothing here is restyled, recoloured or redrawn — a mark is fetched
 * from its own project and scaled, and that is all. See the header of the
 * generated module, which says the same thing where somebody reading the app
 * will see it, including that a vendor asking for removal is honoured.
 *
 * ## Running it
 *
 * `node scripts/store-logos.mjs [--check] [--only <key>]`. It needs the network
 * and `sips`, which is macOS's own, for the raster half. It is not a test and
 * nothing in CI runs it.
 */
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

/** The widest a mark is ever drawn, times two for a retina panel. */
const RASTER_PX = 96

/** The fallback size, used only for a mark that is heavy at {@link RASTER_PX}. */
const SMALL_PX = 64

/** A vendor's own file is kept unscaled only up to here. */
const KEEP_PX = 160

/** Past this encoded, a mark is allowed to drop to {@link SMALL_PX}. */
const SOFT_CAP = 12_000

/** No single mark may exceed this encoded. A store is not a photo album. */
const MAX_BYTES = 24_000

/**
 * Where each mark comes from.
 *
 * `plate` marks the ones whose vendor drew them in a single dark ink on nothing,
 * for a light page — GitHub's Invertocat, SQLite's wordmark, Puppeteer's line
 * drawing. Rendered straight onto this app's dark surface those are a dark shape
 * on a dark shape, which is a row with no logo dressed up as a row with one. They
 * get the light tile their own brand guidelines assume. It is the background that
 * changes; the mark is never touched.
 *
 * Set by looking, not by guessing: every one of these was rendered on both
 * surfaces at 40px and 96px before the flag was decided. Marks that carry their
 * own background — Notion's white square, Context7's black one, the MCP
 * favicon — do **not** get a plate, because a plate behind a plate is a border
 * nobody drew.
 *
 * Six MCP reference servers share one mark, and that is not laziness: they are
 * one project's servers, published together, and the Model Context Protocol
 * mark is the true answer to "whose is this" for all six.
 */
const LOGOS = [
  /* --------------------------------------------- browser extensions -- */
  { key: 'dark-reader', url: 'https://raw.githubusercontent.com/darkreader/darkreader/2aa54873769577631695aa01206d05eacc952ce9/src/icons/dr_128.png' },
  { key: 'clearurls', url: 'https://raw.githubusercontent.com/ClearURLs/Addon/6d904144eca14f71789180da4fe43f3c402be153/img/clearurls.svg' },
  { key: 'stylus', url: 'https://raw.githubusercontent.com/openstyles/stylus/559949b267191067b73319752c910b407c5091c2/src/icon/128.png' },
  { key: 'violentmonkey', url: 'https://raw.githubusercontent.com/violentmonkey/violentmonkey/b072d6ab52148a38eb6b39ab02d17c12b85de5da/src/resources/icon.svg' },
  { key: 'ublock-origin', url: 'https://raw.githubusercontent.com/gorhill/uBlock/fe277a4ea6d18a0a62757826bb665a92c04a0745/src/img/ublock.svg' },
  { key: 'ublock-origin-lite', url: 'https://raw.githubusercontent.com/uBlockOrigin/uBOL-home/c4c5127c0b69c1576b0f8a923c0f3dacaa0997d4/chromium/img/icon_128.png' },
  { key: 'sponsorblock', url: 'https://raw.githubusercontent.com/ajayyy/SponsorBlock/6a306a09622170d0f7f733faa3172a58346650bd/public/icons/IconSponsorBlocker128px.png' },
  { key: 'return-youtube-dislike', url: 'https://raw.githubusercontent.com/Anarios/return-youtube-dislike/4e6dfd1977fcf2d160142bf5c2e303d5cda2c685/Extensions/combined/icons/icon128.png' },
  { key: 'isdcac', url: 'https://raw.githubusercontent.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/d4728187136f973c9fd59266b7f629a8228ea144/src/icons/128.png' },
  { key: 'adguard', url: 'https://raw.githubusercontent.com/AdguardTeam/AdguardBrowserExtension/496161c602ee787d23ee87f6ad3e681f8a0a7a4b/Extension/assets/images/logo-shield.svg' },
  { key: 'ghostery', url: 'https://raw.githubusercontent.com/ghostery/ghostery-extension/ace6af39b02dcd16ce39566f0de292e3cda0d739/src/icons/icon.svg' },
  { key: 'consent-o-matic', url: 'https://raw.githubusercontent.com/cavi-au/Consent-O-Matic/8ca8500d26434c586039e126ad091e1bfccd205d/Extension/logo.svg' },
  { key: 'libredirect', url: 'https://raw.githubusercontent.com/libredirect/browser_extension/90729f5282502fd19ee8075dac2d6d9d2059ef60/src/assets/images/libredirect.svg' },
  { key: 'cookie-autodelete', url: 'https://raw.githubusercontent.com/Cookie-AutoDelete/Cookie-AutoDelete/d9e01ba4acfeee7d49ef8edcc9a64b53d3fa568e/extension/icons/icon_128.png' },
  { key: 'video-speed-controller', url: 'https://raw.githubusercontent.com/igrigorik/videospeed/8f9bc13cd1d8bad549795da265735159d9e9fad1/src/assets/icons/icon128.png' },
  { key: 'bitwarden', url: 'https://raw.githubusercontent.com/bitwarden/clients/cce8a341c88790387fab9c5c6eb6dd3aa7e6491d/apps/browser/src/images/icon128.png' },
  { key: 'keepassxc-browser', url: 'https://raw.githubusercontent.com/keepassxreboot/keepassxc-browser/5dc3a3622ee043da4718748a2821f81ad8d28748/keepassxc-browser/icons/keepassxc.svg' },
  { key: 'search-by-image', url: 'https://raw.githubusercontent.com/dessant/search-by-image/d5d20a64be2fc0fccdedbf52becb0a5f80a83848/src/assets/icons/app/icon.svg' },
  { key: 'web-archives', url: 'https://raw.githubusercontent.com/dessant/web-archives/3cc1989d4d714ccecef4914895f9255bcddcd36e/src/assets/icons/app/icon.svg' },
  { key: 'privacy-badger', url: 'https://raw.githubusercontent.com/EFForg/privacybadger/dd1e9f75041a4ce2b08e4b224a4e200f38a9821f/src/icons/badger-128.png' },
  { key: 'singlefile', url: 'https://raw.githubusercontent.com/gildas-lormeau/SingleFile/32931059bc6c125899068b9517d422008380488a/src/ui/resources/icon_128.png' },
  { key: 'vimium', url: 'https://raw.githubusercontent.com/philc/vimium/5aa29614bf1dce05e0d316f8c38722e17f9b38c3/icons/icon128.png' },
  { key: 'wappalyzer', url: 'https://www.wappalyzer.com/apple-touch-icon.png' },
  { key: 'json-formatter', url: 'https://raw.githubusercontent.com/callumlocke/json-formatter/bfd63560efe2c91c899a68c49bc8eedf5a43a101/ext/icons/128.png' },

  /* -------------------------------------------------- MCP servers -- */
  { key: 'modelcontextprotocol', url: 'https://raw.githubusercontent.com/modelcontextprotocol/modelcontextprotocol/5b38eb170281b43f4683c764c0bb2d3ed7d95cd9/docs/favicon.svg' },
  { key: 'git', url: 'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.svg' },
  { key: 'playwright', url: 'https://playwright.dev/img/playwright-logo.svg' },
  { key: 'github', url: 'https://raw.githubusercontent.com/primer/octicons/0e21a4c2d8449102f10e533d241f04797af0914c/icons/mark-github-24.svg', plate: true },
  { key: 'notion', url: 'https://www.notion.so/images/logo-ios.png' },
  { key: 'context7', url: 'https://raw.githubusercontent.com/upstash/context7/c3248289c2ad431a9f34849a3f3d047fc4400373/public/context7-icon.svg' },
  { key: 'tavily', url: 'https://tavily.com/icon.svg' },
  { key: 'firecrawl', url: 'https://raw.githubusercontent.com/firecrawl/firecrawl-mcp-server/678c92a430849b8be90e70f3c0607ac1c8b0bee8/img/firecrawl-logo.png' },
  { key: 'sqlite', url: 'https://upload.wikimedia.org/wikipedia/commons/3/38/SQLite370.svg', plate: true },
  { key: 'postgres', url: 'https://wiki.postgresql.org/images/a/a4/PostgreSQL_logo.3colors.svg' },
  { key: 'slack', url: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png' },
  { key: 'brave', url: 'https://brave.com/static-assets/images/brave-logo-sans-text.svg' },
  { key: 'puppeteer', url: 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png', plate: true },
]

/* ------------------------------------------------------------ fetching -- */

/**
 * A named agent, because two of these hosts refuse an unnamed one.
 *
 * Not a browser's string. A fetch that says what it is and where to complain is
 * the honest version of this, and it is the only header sent.
 */
const AGENT = 'terminaldeck-store-logos (+https://terminaldeck.dev)'

async function get(url) {
  const answer = await fetch(url, { redirect: 'follow', headers: { 'user-agent': AGENT } })
  if (!answer.ok) throw new Error(`${answer.status} ${answer.statusText}`)
  return Buffer.from(await answer.arrayBuffer())
}

/* ------------------------------------------------------------- shaping -- */

/**
 * An SVG, shrunk and made safe to embed.
 *
 * An `<img>` is already a sandbox — an SVG loaded through one cannot run script
 * and cannot fetch anything — but a store that pasted somebody else's
 * `<script>` into its own bundle would be shipping code it never read, so the
 * script tags and the `on*` handlers come out, and a mark that reaches for an
 * external URL is refused outright rather than shipped half-drawn.
 */
function shapeSvg(bytes) {
  let text = bytes.toString('utf8')
  text = text.replace(/<\?xml[\s\S]*?\?>/g, '')
  text = text.replace(/<!DOCTYPE[\s\S]*?>/gi, '')
  text = text.replace(/<!--[\s\S]*?-->/g, '')
  text = text.replace(/<script[\s\S]*?<\/script>/gi, '')
  text = text.replace(/\son[a-z]+\s*=\s*"[^"]*"/gi, '')
  text = text.replace(/>\s+</g, '><').trim()
  if (/(?:href|src)\s*=\s*["']https?:/i.test(text)) {
    throw new Error('this SVG loads something from the network; find another source')
  }
  if (!text.startsWith('<svg') && !/<svg[\s>]/.test(text)) throw new Error('not an SVG')
  return { mime: 'image/svg+xml', bytes: Buffer.from(text, 'utf8') }
}

/**
 * A raster mark at the smallest it can be drawn without looking it.
 *
 * Three candidates, and the smallest file wins: the vendor's own bytes (only if
 * they are already store-sized — nobody needs a 512px picture in a 40px tile),
 * and `sips` re-encodes at {@link RASTER_PX} and, for the stubborn ones,
 * {@link SMALL_PX}.
 *
 * The vendor's own file is in the running because `sips` frequently loses to
 * it: it writes full 8-bit RGBA, and a mark that shipped as a 16-colour palette
 * comes back **three times bigger** after being made smaller. Privacy Badger is
 * 4,907 bytes at 128px and 11 KB after a scale to 96. Re-encoding everything on
 * principle would have cost more than it saved on a third of this list.
 */
function shapeRaster(bytes, extension) {
  const scratch = mkdtempSync(join(tmpdir(), 'td-logo-'))
  try {
    const from = join(scratch, `in.${extension}`)
    writeFileSync(from, bytes)
    const measured = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', from], {
      encoding: 'utf8',
    })
    const side = Math.max(...[...measured.matchAll(/pixel(?:Width|Height): (\d+)/g)].map((m) => Number(m[1])))
    const candidates = []
    if (side > 0 && side <= KEEP_PX && extension === 'png') candidates.push(bytes)
    for (const px of [RASTER_PX, SMALL_PX]) {
      if (side > 0 && px >= side) continue
      const to = join(scratch, `out-${px}.png`)
      execFileSync('sips', ['-Z', String(px), '-s', 'format', 'png', from, '--out', to], {
        stdio: 'pipe',
      })
      candidates.push(readFileSync(to))
    }
    if (candidates.length === 0) candidates.push(bytes)
    /* Smallest wins, but only among the ones that are not absurd: a 64px
       re-encode is allowed to win only when the 96px one is genuinely heavy,
       so an ordinary mark keeps its resolution. */
    const best = candidates.reduce((a, b) => {
      const heavy = a.length * 1.37 > SOFT_CAP
      return heavy && b.length < a.length ? b : a.length <= b.length ? a : b
    })
    return { mime: 'image/png', bytes: best }
  } finally {
    rmSync(scratch, { recursive: true, force: true })
  }
}

function shape(bytes, url) {
  if (bytes.subarray(0, 400).toString('utf8').includes('<svg') || url.endsWith('.svg')) {
    return shapeSvg(bytes)
  }
  const extension = url.endsWith('.png') || bytes.subarray(1, 4).toString() === 'PNG' ? 'png' : 'img'
  return shapeRaster(bytes, extension)
}

/* -------------------------------------------------------------- writing -- */

const HEADER = `/**
 * Every store logo, as bytes this app already has.
 *
 * **Generated by \`scripts/store-logos.mjs\`. Do not edit by hand** — run the
 * script, which re-fetches from the URLs recorded on each entry.
 *
 * ## Why the marks are in here rather than at the end of a URL
 *
 * Because \`<img src="https://vendor.example/logo.svg">\` is a request to a third
 * party every single time the store is opened — an IP address and a referrer
 * handed to twenty companies for the privilege of drawing a picture — and
 * because it draws nothing on an aeroplane. Neither belongs in a store whose
 * whole argument is that what it offers was pinned in advance. Each mark was
 * fetched once, by hand, and what ships is the result: the store reads these out
 * of its own bundle and asks nobody anything.
 *
 * ## What each entry can be checked against
 *
 * \`source\` is exactly where the bytes came from, \`sha256\` is what came back,
 * and \`fetched\` is when. GitHub sources are pinned to a commit sha, so the URL
 * resolves to the same bytes forever; for a vendor's own site the sha256 is the
 * pin. \`node scripts/store-logos.mjs --check\` re-fetches every one and names
 * any whose upstream bytes have moved.
 *
 * ## Trademarks
 *
 * **These are third-party trademarks, reproduced to identify the products the
 * store's rows are about.** Terminal Deck claims no rights in any of them and is
 * not endorsed by, affiliated with, or a partner of any of these projects or
 * companies. Every mark is the vendor's own file, scaled and nothing else — none
 * is recoloured, redrawn, cropped or combined with anything. A vendor who would
 * rather their mark were not shown here only has to say so: open an issue and it
 * comes out, and the row falls back to the generated monogram in
 * \`StoreLogo.tsx\`, which is this app's own drawing and identifies nobody's
 * brand but its own.
 */

/** One mark: the bytes, and the provenance that makes them checkable. */
export interface StoreLogoAsset {
  /** The mark itself, inline. Never a network address. */
  readonly src: string
  /** Exactly where it was fetched from. */
  readonly source: string
  /** sha256 of what came back from {@link source}, before scaling. */
  readonly sha256: string
  /** The day it came back, ISO. */
  readonly fetched: string
  /**
   * Whether this mark needs a light tile behind it.
   *
   * True only for a mark its vendor drew in one dark ink for a light page —
   * GitHub's Invertocat, Context7's wordmark. Without it they are invisible in
   * the dark theme. The tile is a background; the mark itself is untouched.
   */
  readonly plate: boolean
}
`

async function main() {
  const argv = process.argv.slice(2)
  const check = argv.includes('--check')
  const onlyAt = argv.indexOf('--only')
  const only = onlyAt === -1 ? '' : argv[onlyAt + 1]
  const today = new Date().toISOString().slice(0, 10)
  const wanted = only === '' ? LOGOS : LOGOS.filter((one) => one.key === only)

  const out = []
  const problems = []
  let total = 0
  for (const logo of wanted) {
    try {
      const raw = await get(logo.url)
      const sha256 = createHash('sha256').update(raw).digest('hex')
      const shaped = shape(raw, logo.url)
      const src = `data:${shaped.mime};base64,${shaped.bytes.toString('base64')}`
      if (src.length > MAX_BYTES) {
        throw new Error(`${src.length} bytes encoded, over the ${MAX_BYTES} cap`)
      }
      total += src.length
      out.push({ key: logo.key, src, source: logo.url, sha256, fetched: today, plate: logo.plate === true })
      console.log(`  ok  ${logo.key.padEnd(24)} ${String(raw.length).padStart(7)} → ${String(src.length).padStart(6)}  ${sha256.slice(0, 12)}`)
    } catch (error) {
      problems.push(`${logo.key}: ${error instanceof Error ? error.message : String(error)}`)
      console.log(`  FAIL ${logo.key}: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  console.log(`\n  ${out.length}/${wanted.length} marks, ${total.toLocaleString('en-US')} bytes encoded in total`)

  if (check) {
    const current = new URL('../src/renderer/store/logo-data.ts', import.meta.url)
    const text = readFileSync(current, 'utf8')
    let moved = 0
    for (const one of out) {
      if (!text.includes(one.sha256)) {
        console.log(`  MOVED ${one.key} — upstream is now ${one.sha256}`)
        moved += 1
      }
    }
    console.log(moved === 0 ? '  nothing has moved' : `  ${moved} moved`)
    process.exit(moved === 0 && problems.length === 0 ? 0 : 1)
  }

  if (problems.length > 0) {
    console.error('\nrefusing to write: ' + problems.join('; '))
    process.exit(1)
  }
  if (only !== '') {
    console.error('\n--only is for looking, not for writing; run without it to regenerate')
    process.exit(1)
  }

  const body = out
    .map(
      (one) =>
        `  '${one.key}': {\n` +
        `    src: '${one.src}',\n` +
        `    source: '${one.source}',\n` +
        `    sha256: '${one.sha256}',\n` +
        `    fetched: '${one.fetched}',\n` +
        `    plate: ${one.plate},\n` +
        `  },`,
    )
    .join('\n')
  const file =
    HEADER +
    '\n/** Every mark, by the key a catalogue row names in its `logo` field. */\n' +
    'export const STORE_LOGO_ASSETS: Readonly<Record<string, StoreLogoAsset>> = {\n' +
    body +
    '\n}\n'
  writeFileSync(new URL('../src/renderer/store/logo-data.ts', import.meta.url), file)
  console.log('  wrote src/renderer/store/logo-data.ts')
}

await main()
