package dev.terminaldeck.android.protocol

import dev.terminaldeck.android.crypto.HandshakeInitiator
import dev.terminaldeck.android.crypto.Sealed
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The one byte this client used to leave off, pinned against the desktop's own numbers.
 *
 * ## Why this is separate from `SealedInteropTest`
 *
 * Because the bug it guards against was invisible to that suite and always would have been.
 * `SealedInteropTest` checks the Kotlin port of `sealed.ts` against vectors generated by running
 * `sealed.ts`, and it passed — the Noise handshake was correct to the byte. What was missing was
 * the layer *above* it: `src/shared/relay-wire.ts` puts a version byte in front of each handshake
 * message, so a relay carries **81 bytes out and 49 back**, and this app was sending 80 and
 * expecting 48.
 *
 * A real Mac answers a first payload of the wrong length by closing the channel and saying nothing
 * — deliberately, so a hostile relay learns nothing from a refusal — so the failure reached the
 * user as "could not reach that Mac" and nothing anywhere said otherwise. `android/tools/dev-host.cjs`
 * skipped the byte too, so the rig and the client agreed with each other and both disagreed with
 * the product.
 *
 * ## What makes these assertions non-circular
 *
 * The numbers below are read out of `sealed-fixtures.json`, which `gen-sealed-fixtures.cjs` writes
 * by *calling* `withSealedVersion` in the real module rather than by transcribing the spec. The
 * fixture carries the handshake twice — unframed and framed — so a port cannot satisfy one
 * assertion by breaking the other. Change the contract in `relay-wire.ts`, regenerate, and this
 * file fails until the Kotlin side is moved with it.
 *
 * The literals 81 and 49 appear once, in the first case, and that is on purpose: a test whose every
 * number comes from the file it is checking cannot notice that file changing.
 *
 * Regenerate after any change to `relay-wire.ts`:
 *
 *     node android/tools/gen-sealed-fixtures.cjs
 */
class RelayWireTest {

    private val fixtures: JsonObject = Json.parseToJsonElement(
        checkNotNull(javaClass.classLoader?.getResourceAsStream("sealed-fixtures.json")) {
            "sealed-fixtures.json is missing; run node android/tools/gen-sealed-fixtures.cjs"
        }.readBytes().decodeToString(),
    ).jsonObject

    private val wire: JsonObject = checkNotNull(fixtures["relayWire"]) {
        "the fixture predates the relay-wire block; regenerate it"
    }.jsonObject

    private val handshake: JsonObject = checkNotNull(fixtures["handshake"]).jsonObject

    /* -------------------------------------------------------------- the numbers -- */

    /**
     * The whole bug, as four numbers.
     *
     * Literals rather than anything derived, so this fails if the constants move for any reason —
     * including someone "fixing" [Sealed.NOISE_MESSAGE_BYTES] to 81 to make a connection work,
     * which is the shortcut that would put the version byte inside the transcript hash and break
     * the handshake in a much harder way.
     */
    @Test
    fun `the wire is eighty-one bytes out and forty-nine back`() {
        assertEquals("the Noise IK message is 80 bytes", 80, Sealed.NOISE_MESSAGE_BYTES)
        assertEquals("the Noise IK reply is 48 bytes", 48, Sealed.NOISE_REPLY_BYTES)
        assertEquals("the wire carries 81 bytes out", 81, RelayWire.HANDSHAKE_OPEN_BYTES)
        assertEquals("the wire carries 49 bytes back", 49, RelayWire.HANDSHAKE_REPLY_BYTES)
        assertEquals("the version byte is 0x01", 1, RelayWire.SEALED_VERSION.toInt())
    }

    @Test
    fun `the constants match the desktop's own`() {
        assertEquals(wire.int("sealedVersion"), RelayWire.SEALED_VERSION.toInt())
        assertEquals(wire.int("noiseMessageBytes"), Sealed.NOISE_MESSAGE_BYTES)
        assertEquals(wire.int("noiseReplyBytes"), Sealed.NOISE_REPLY_BYTES)
        assertEquals(wire.int("handshakeOpenBytes"), RelayWire.HANDSHAKE_OPEN_BYTES)
        assertEquals(wire.int("handshakeReplyBytes"), RelayWire.HANDSHAKE_REPLY_BYTES)
    }

    /* ------------------------------------------------------------------ framing -- */

    @Test
    fun `framing a handshake produces exactly the bytes the desktop framed`() {
        val framed = RelayWire.withSealedVersion(handshake.hex("message"))
        assertArrayEquals(wire.hex("framedMessage"), framed)
        assertEquals(RelayWire.HANDSHAKE_OPEN_BYTES, framed.size)
        assertEquals(RelayWire.SEALED_VERSION, framed[0])
    }

    @Test
    fun `a whole handshake goes out at eighty-one bytes`() {
        // A fresh handshake rather than the fixture's recorded one, because production frames
        // whatever `HandshakeInitiator` just produced and a constant that only lines up with a
        // stored vector is not a constant.
        val mac = Sealed.generateStatic()
        val device = Sealed.generateStatic()
        val initiator = HandshakeInitiator(device, mac.publicKey)

        assertEquals("sealed.ts's half is unchanged", 80, initiator.message.size)
        val onTheWire = RelayWire.withSealedVersion(initiator.message)
        assertEquals("and the wire adds exactly one byte", 81, onTheWire.size)
        assertEquals(1, onTheWire[0].toInt())
        assertArrayEquals(
            "the byte is a prefix, not a replacement",
            initiator.message,
            onTheWire.copyOfRange(1, onTheWire.size),
        )
    }

    /* --------------------------------------------------------------- reading it -- */

    @Test
    fun `the desktop's framed reply reads back to the Noise reply`() {
        val framed = wire.hex("framedReply")
        assertEquals(49, framed.size)

        val opened = RelayWire.readSealedHandshake(framed, RelayWire.HANDSHAKE_REPLY_BYTES)
        assertTrue("the desktop's own reply was refused: $opened", opened is RelayWire.SealedOpen.Ok)
        val message = (opened as RelayWire.SealedOpen.Ok).message
        assertArrayEquals(handshake.hex("reply"), message)
        assertEquals(Sealed.NOISE_REPLY_BYTES, message.size)
    }

    /**
     * The exact shape of the old bug: 48 bytes where 49 belong.
     *
     * It has to be refused rather than misparsed. A 48-byte reply read as though it were framed
     * would take the responder's first key byte as a version and hand `finish` 47 bytes — a length
     * error, reported to the user as "this Mac could not prove who it is", which is a sentence
     * about cryptography for what is really a client one version behind.
     */
    @Test
    fun `an unframed reply is refused rather than misparsed`() {
        val unframed = handshake.hex("reply")
        assertEquals(48, unframed.size)
        assertEquals(
            RelayWire.SealedOpen.Refused(RelayWire.Refusal.Malformed(48, 49)),
            RelayWire.readSealedHandshake(unframed, RelayWire.HANDSHAKE_REPLY_BYTES),
        )
    }

    @Test
    fun `a version this build does not speak is refused and named`() {
        val framed = wire.hex("framedReply")
        framed[0] = 0x02
        val opened = RelayWire.readSealedHandshake(framed, RelayWire.HANDSHAKE_REPLY_BYTES)
        assertEquals(
            RelayWire.SealedOpen.Refused(RelayWire.Refusal.WrongVersion(2)),
            opened,
        )
        // The distinction exists so the phone can say which of the two ends is out of date. If the
        // sentence stops naming a version it has stopped being worth distinguishing from a
        // malformed frame.
        val sentence = (opened as RelayWire.SealedOpen.Refused).reason.sentence
        assertTrue(sentence, sentence.contains("version"))
        assertNotEquals("", sentence)
    }

    @Test
    fun `no other length is read as a reply`() {
        val framed = wire.hex("framedReply")
        for (size in intArrayOf(0, 1, 47, 48, 50, 81)) {
            val payload = if (size <= framed.size) framed.copyOfRange(0, size) else framed + ByteArray(size - framed.size)
            assertEquals(
                "$size bytes must not be read as a reply",
                RelayWire.SealedOpen.Refused(RelayWire.Refusal.Malformed(size, 49)),
                RelayWire.readSealedHandshake(payload, RelayWire.HANDSHAKE_REPLY_BYTES),
            )
        }
    }

    /* ---------------------------------------------------------------- both ways -- */

    /**
     * Frame, then read, through the same two functions the transport calls.
     *
     * This is the case that would have caught the original bug: it puts this client's handshake
     * through the check a real Mac performs on it.
     */
    @Test
    fun `what this client sends is what a Mac accepts`() {
        val message = handshake.hex("message")
        val framedOut = RelayWire.withSealedVersion(message)
        assertEquals(RelayWire.HANDSHAKE_OPEN_BYTES, framedOut.size)

        val opened = RelayWire.readSealedHandshake(framedOut, RelayWire.HANDSHAKE_OPEN_BYTES)
        assertTrue("a Mac would have refused this app's handshake: $opened", opened is RelayWire.SealedOpen.Ok)
        assertArrayEquals(message, (opened as RelayWire.SealedOpen.Ok).message)
    }

    @Test
    fun `the eighty-byte handshake this client used to send would be refused`() {
        // The regression, stated as a test: an unframed message must not be accepted by the same
        // check the desktop runs, or nothing above stops the byte being dropped again.
        val message = handshake.hex("message")
        assertEquals(80, message.size)
        assertEquals(
            RelayWire.SealedOpen.Refused(RelayWire.Refusal.Malformed(80, 81)),
            RelayWire.readSealedHandshake(message, RelayWire.HANDSHAKE_OPEN_BYTES),
        )
    }

    /* ------------------------------------------------------------------ helpers -- */

    private fun JsonObject.int(name: String) =
        checkNotNull(this[name]) { "the fixture has no $name; regenerate it" }.jsonPrimitive.int

    private fun JsonObject.hex(name: String) =
        checkNotNull(this[name]) { "the fixture has no $name; regenerate it" }.jsonPrimitive.content.fromHex()

    private fun String.fromHex(): ByteArray {
        val out = ByteArray(length / 2)
        for (i in out.indices) {
            out[i] = ((digit(this[i * 2]) shl 4) or digit(this[i * 2 + 1])).toByte()
        }
        return out
    }

    private fun digit(char: Char): Int = Character.digit(char, 16).also { require(it >= 0) { "not hex" } }
}
